### ISSUE TITLE
How can I give Scribe a token in multi-tenancy context?

### ISSUE THREAD

**Issue by rachids** [knuckleswtf/scribe#100]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

Hello, so I am working on an API with multiple databases (one per tenant). I am using my `.env.testing` to generate the documentation but I struggle to fill the `SCRIBE_AUTH_KEY`.

Have you an idea how can I provide a token so I can have responses to my authenticated routes?
I am using [spatie/laravel-multitenancy](https://github.com/spatie/laravel-multitenancy)

**Comment by shalvah** [comment]
I'm not sure exactly what you mean. Do you mean authenticating for a specific tenant? How about running `php artisan tinker` and calling the code to get a token (maybe something like `Auth::getToken()`), then copy that and put in your env? It's a manual process you'd need to do each time, but we're working on a better solution down the road.

**Comment by rachids** [comment]
Yes I'd like to authenticate for a specific tenant and I wanted to know if there was solutions implemented by people who already went through this.

Maybe I should create a tenant specifically for the documentation since the test DB is generated each time I run phpunit.
Thanks for your input and for this package!

**Comment by shalvah** [comment]
Closing this. Adding an authentication step in Scribe is a bit tricky. We'd use closures normally, but Laravel's config doesn't support closures. But this is a problem I plan to address in the future.

**Comment by pageantry** [comment]
You can save auth token to the tenant table for example and use it in `Scribe::class::bootstrap`.
Fill `SCRIBE_AUTH_KEY` with `config(['scribe.auth.use_value' => $tenant->api_token])`
or do the same with `Spatie\Multitenancy\Tasks\SwitchTenantTask` ([documentation](https://spatie.be/docs/laravel-multitenancy/v4/advanced-usage/using-tenant-specific-facades))

```php
// app/Providers/AppServiceProvider.php
public function boot(): void
{
    if (class_exists(\Knuckles\Scribe\Scribe::class)) {
        // step 1: make needed tenant current
        \Knuckles\Scribe\Scribe::class::bootstrap(
            static function (\Knuckles\Scribe\Commands\GenerateDocumentation $command) {
                $domain = \str_replace(['https://', 'http://'], '', config('scribe.base_url'));
                $tenantModel = config('multitenancy.tenant_model');
                $tenant = $tenantModel::query()->where(['domain' => $domain])->first();
                $tenant->makeCurrent();
            }
        );

        //step 2: set domian to the route
        \Knuckles\Scribe\Scribe::class::instantiateFormRequestUsing(static function (string $formRequestClassName, Route $route, ReflectionFunctionAbstract $method) {
            $tenant = \Spatie\Multitenancy\Models\Tenant::current();
            $route->domain($tenant->domain);

            return new $formRequestClassName();
        }
    }
}
```
