### ISSUE TITLE
getting error  "These credentials do not match our records."

### ISSUE THREAD

**Issue by rockers007** [knuckleswtf/scribe#103]
getting error  "These credentials do not match our records." when we run "php artisan scribe:generate" command

**Comment by shalvah** [comment]
This is an extremely lazy way to report an issue. Please do the right thing.

**Comment by shalvah** [comment]
The right thing = use the proper issue template, provide details about your setup and scenario, etc. This sounds like a case of you missing something, rather than a problem with the package, so I'm helping you out of my goodwill. Don't make it hard to help.
