### ISSUE TITLE
Order of the @group 

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#107]
Hi, by default the doc is ordering the groups made by `@group ABC` by an alphabetic order.
It's possible to define a custom order ?

**Comment by shalvah** [comment]
That would be one of the benefits of #105

**Comment by shalvah** [comment]
Update: This is done in v3. You'll be able to sort endpoints and groups as you wish.

How it works: Scribe generates an intermediate YAML file that you can modify, and your changes will be preserved as much as possibl

**Comment by shalvah** [comment]
🎉[v3 is out now](https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3), and you can sort groups as you wish!
