### ISSUE TITLE
Pretty example-languages - render added languages pretty format.

### ISSUE THREAD

**Issue by Nzambu** [knuckleswtf/scribe#108]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

I have added swift as one of the example languages and; added a blade view (swift.blade.php) in the partials folder. The documentation example work well with the swift examples.

The issues is, it renders all in white. How do I get it to render pretty like the javascript or php examples?

Thank you so much.

**Comment by shalvah** [comment]
The highlighting is powered by highlight.js. When installing, you go to their site and pick the languages you want. Swift isn't included in the bundle I use for Pastel/Scribe, in order not to have a very large CSS file size.

I think you can manually download a bundle that includes Swift from their site and include it in the docs CSS folder. That might work.

**Comment by Nzambu** [comment]
By default, they include Bash and JavaScript, though PHP and Python are supported. Am looking for a way to highlight the examples in swift and haven't seen that in the documentation or  anywhere to get the resource. I really appreciate your suggestion and will look into it. Warmest regards @shalvah .

**Comment by shalvah** [comment]
> By default, they include Bash and JavaScript, though PHP and Python are supported

Lol, I know. I'm the person that built it.

I don't think you understood my comment. The highlighting comes from the CSS we include in Scribe. We got the CSS from https://highlightjs.org/. When downloading, I had to pick which languages I wanted included in the CSS, so I only picked a couple of the most popular ones, to reduce the download size for end users. I don't think I included Swift.

You can go on that site and download a new CSS bundle yourself, and include Swift. Then locate the highlightjs CSS file that Scribe outputs for you after generation, and replace that with the one you downloaded. Clearer?

**Comment by Nzambu** [comment]
You did such a wonderful job and it deserves all accolades.

I have downloaded the highlight.zip for Swift and it's is only 264 kbs. Am going to fix it. I got you very clear, you response was very quick. Was anticipating may be later today. I read the documentation on how to contribute and the rules were simple and clear as well hahahahaha
Once again, thank you so much @shalvah

**Comment by Nzambu** [comment]
It is working perfectly, 

Kindly, the documentation adding example-languages can benefit with how to highlight examples.

I will close the issue at this point.

**Comment by shalvah** [comment]
Yeah, I'll add it. Thanks.
