### ISSUE TITLE
Example Faker

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#109]
Hi, 
Where i can modify the faker for the example fields. I know i could create custom example text, but for some reason the faker, when i create a parameter without example, creates strange text.

`@bodyParam invoice.name string required The Client Name for the invoice`

In the example create something like this : `"name": "facere",` , i think it's some random string.

It's possible to map the name of the parameter to faker type content (ex:`$faker->name()`)?

**Comment by shalvah** [comment]
No, I don't know of any such way. The only option available for customising the faker is the seed, which just makes it generate consistent values. You can check Faker's docs to see if anything else you can do.

If it's really a big deal for you, I guess you can create a custom strategy that extends the main strategy you want (query parameters or body parameters) and implement the getDummyValue method to return what you want. Then replaced the original strategy in the config with the new one.

**Comment by pirex360** [comment]
Thanks , once more a great solution. It's not a game changer for me, but i will see what to do for this feature.
Maybe adding other atribute on defining the bodyParam like `Faker: name`or 'Faker: lastName` , so :
`@bodyParam invoice.name string required The Client Name for the invoice. Faker : name`

**Comment by shalvah** [comment]
Err, it's not something I'm interested in doing right now. It feels like it would add unnecessary complexity. Maybe I'll consider that later. And if you're going to write that, why not just hardcode an example at once? 🙂
