### ISSUE TITLE
How to remove css/highlight-darcula.css permanently

### ISSUE THREAD

**Issue by ajcastro** [knuckleswtf/scribe#113]
I prefer the text color like in mpociot where the code looks better.
I tried to remove the `<link rel="stylesheet" href="css/highlight-darcula.css" media="" />` in `index.html` and it solves it, but when I ran `scribe:generate` it regenerates again the `index.html` with the `highlight-dracula.css`

**Comment by shalvah** [comment]
This proposal for v3 will bring support for themes (and without needing to go through Pastel). #105 

In the meantime, probably write a little script that does a find-and-replace on the output. Shouldn't be hard.
