### ISSUE TITLE
Multiple example for array using bodyParamaters()

### ISSUE THREAD

**Issue by Duvy2** [knuckleswtf/scribe#117]
Could someone help out with an example how shall I do an example request for an array?

In the example I'm expecting ID's of users, like: user[0], user[1]... etc:
```
public function rules()
    {
      return [
          'users' => 'required|array',
          'users.*' => 'required|integer|exists:users,id',
      ];
    }
```

What's the proper way to include at least two values in the request on the documentation using bodyParameters()?

btw: also using the annotation way I couldn't find a way how to populate the example values.

**Comment by shalvah** [comment]
You're doing it correctly. For the example with two items in the array via bodyParameters(), have you tried setting it for `users`, not `users.*`?

The annotation version would be:

`@bodyParam users integer[] required`. 

By default, there will be two values in the generated example array, but you can also set an example: `Example: [4, 7]`.

**Comment by Duvy2** [comment]
For the annotation way I happened to miss, the array bracket on the **Example**, now it's working great, thanks.

But for the bodyParameters() function I can't figure out how the array should be structured, I tried something like this:

```
public function bodyParameters()
    {
        return [
            "users" =>
            [
                "example" => 6
            ],
            [
                "example" => 2
            ]
        ];
    }
```

or this:


```
public function bodyParameters()
    {
        return [
            "users" =>
            [
                "example" => [6, 2]
            ]
        ];
    }
```


These seem not to work.

**Comment by shalvah** [comment]
The second way is the right one. What do you get with that?

**Comment by Duvy2** [comment]
If I comment the second validation rule, scribe generates the given example values, so this works well:
```
public function rules()
    {
      return [
          'users' => 'required|array',
          //'users.*' => 'required|integer|exists:users,id',
      ];
    }

    public function bodyParameters()
    {
        return [
            "users" =>
                [
                    "example" => [4, 7]
                ]
        ];
    }
```
When I uncomment, it generates not two, but only one random integer, and also not in an array.
The javascript example how it calls the API:
```
let body = {
    "users": 10
}
```

**Comment by shalvah** [comment]
Try removing the first validation rule. I don't think it's necessary. `users.*` already tells Laravel it's an array.

**Comment by shalvah** [comment]
Thanks for this. I think this should be fixed in the latest v2 (no release, just the branch 2.x-dev)

**Comment by shalvah** [comment]
Tried it out?

**Comment by Duvy2** [comment]
Works as expected now :) 👍
