### ISSUE TITLE
Postman sub-folder

### ISSUE THREAD

**Issue by SamadiPour** [knuckleswtf/scribe#12]
Hi there,

Is there any way to create this with group?
![image](https://user-images.githubusercontent.com/24422125/82106537-ed17a780-9736-11ea-877f-1bd5c2b5c25c.png)

**Comment by shalvah** [comment]
Um...yes, your APIs are put in folders already in the Postman Collection, based on the `@group`.

![image](https://user-images.githubusercontent.com/14361073/82121676-c2553f80-9786-11ea-835b-1407fcb4bcf0.png)

If you're asking for sub-folders, no, we don't support that. And I don't think Postman even does. https://schema.getpostman.com/json/collection/v2.0.0/docs/index.html
