### ISSUE TITLE
How to Add Postman Pre-request Scripts

### ISSUE THREAD

**Issue by tsndp** [knuckleswtf/scribe#121]
Hi,

Thank you for wonderful tool, everything is working with Laravel Sanctum APIs except, POST/PUT methods as laravel is expecting csrf token X-XSRF-TOKEN in header.

Do you have workaround for this?

-----

I have added below two in headers and scribe.php config file

                'headers' => [
                    'Content-Type' => 'application/json',
                    'Accept' => 'application/json',
                    'Referer' => env('APP_URL'),
                    'X-XSRF-TOKEN' => '@{{xsrf-cookie}}',   <- postman environment variable
                ],

and wrote prescript in postman, but this is manual work, how to include "postman event" into scribe postman export?

----
postman collection json example: 

	"event": [
		{
			"listen": "prerequest",
			"script": {
				"id": "cd4eaacf-09f2-414b-acf0-f5d4094bc987",
				"type": "text/javascript",
				"exec": [
					"pm.sendRequest({",
					"    url: 'https://abcd.com/backend/csrf-cookie',",
					"    method: 'GET'",
					"}, function(error,response, {cookies}){",
					"    if(!error) {",
					"        pm.environment.set('xsrf-cookie', cookies.get('XSRF-TOKEN'))",
					"    }",
					"})"
				]
			}
		}
]

**Comment by shalvah** [comment]
I think [postman.overrides](https://scribe.readthedocs.io/en/latest/config.html?highlight=Overrides#postman) is what you need.

**Comment by tsndp** [comment]
thank you shalvah, it worked. 

----
How i did, postman prescripts

```
	'event.0.listen' => 'prerequest',
        'event.0.script.id' => 'f0622cf2-2aa1-4c96-b956-00d6f53105af',
        'event.0.script.type' => 'text/javascript',
	'event.0.script.exec' => 'pm.sendRequest({url: \'https://abc.com/backend/csrf-cookie\',method: \'GET\'}, function(error,response, {cookies}){if(!error) { pm.environment.set(\'xsrf-cookie\', cookies.get(\'XSRF-TOKEN\'))    }})',

**Comment by james2doyle** [comment]
Here is what I did to add the token as a variable while using laravel sanctum:

```
/*
 * Manually override some generated content in the spec. Dot notation is supported.
 */
'overrides' => [
    'info.name' => env('APP_SERVICE', env('APP_NAME')),
    'info.description' => 'This documentation aims to provide all the information you need to work with our API.',
    'auth.bearer.0' => [
        'key' => 'token',
        'value' => 'some-token-or-whatever',
        'type' => 'string',
    ],
    'event.0' => [
        'listen' => 'prerequest',
        'script' => [
            'type' => 'text/javascript',
            'exec' => [
                // adds the CSRF token to each request
                "pm.sendRequest({",
                "    url: ['http://', pm.collectionVariables.get(\"baseUrl\"), '/sanctum/csrf-cookie'].join(''),",
                "    method: 'GET'",
                "}, function (error, response, { cookies }) {",
                "    if (!error && cookies) {",
                "        pm.environment.set('xsrfToken', cookies.get('XSRF-TOKEN'))",
                "    }",
                "})",
                "",
            ],
        ],
    ],
    'variable.0' => [
        'id' => 'baseUrl',
        'key' => 'baseUrl',
        'type' => 'string',
        'name' => 'string',
        'value' => config('app.url'),
    ],
    // add the variable to all the requests
    'item.*.item.*.request.header.2' => [
        'key' => 'X-XSRF-TOKEN',
        'value' => '{{xsrfToken}}',
        'type' => 'text'
    ],
    // add the referrer to all the requests
    'item.*.item.*.request.header.3' => [
        'key' => 'Referer',
        'value' => '{{baseUrl}}',
        'type' => 'text'
    ],
],
```
