### ISSUE TITLE
Sort navigation items

### ISSUE THREAD

**Issue by tsndr** [knuckleswtf/scribe#122]
Is it possible to specify an order of the items in the sidebar?

I tried naming the groups like this:
```
1. Group
2. Another group
...
10. Yet another group
11. The last group
```

But when generating the the docs it does this:
```
1. Group
10. Yet another group
11. The last group
2. Another group
...
```

What can I do to fix this?

Maybe something like
```
/**
 * @group 1. Group
 * @sort 0
 */
```
```
/**
 * @group 2. Another group
 * @sort 1
 */
```

- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

**Comment by shalvah** [comment]
It isn't possible right now. Your best option would be to use letters? 

```
A. Group A
B. ,,,
```

**Comment by shalvah** [comment]
#105 should address this. Closing this in the meantime, since it's same as #107
