### ISSUE TITLE
New array doc syntax is broken

### ISSUE THREAD

**Issue by tomcoonen** [knuckleswtf/scribe#124]
**What happened?**
1. Upgraded to version 2.0
2. Then I ran `php artisan scribe:generate`
3. I get this error:
`Undefined index: name (View: /xxx/vendor/knuckleswtf/scribe/resources/views/partials/body-parameters.blade.php)

  at vendor/knuckleswtf/scribe/src/../resources/views//partials/body-parameters.blade.php:8
  >  8|   'name' => $parameter['name'],`

**My environment:**
 - PHP version (from `php -v`): 7.4.10
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show lumen/framework`): 7 latest
 - Scribe version (from `composer show knuckleswtf/scribe`): 2.0

**My Scribe config (minus the comments):**
- type: laravel

**Additional info:**
The docblock line it is failing on: 
`* @bodyParam products[].id int required Product ID`

**Comment by shalvah** [comment]
Are you using any custom strategies?

Did you add something like this present before the offending line?

```
@bodyParam products object[]
```

**Comment by robtesch** [comment]
> Are you using any custom strategies?
> 
> Did you add something like this present before the offending line?
> 
> ```
> @bodyParam products object[]
> ```

This was the fix for me, it's right there in the upgrade guide but I had to go through all my doc blocks again just to double check. Managed to find and fix them.

The only issue in this particular case is that the error message isn't too helpful in helping track down which block is causing the issue, but I imagine adding one might be quite tricky.

**Comment by shalvah** [comment]
Yeah, adding a better error message will be an unnecessary amount of work. I'll just add bigger notices in the docs.

**Comment by tomcoonen** [comment]
I did read the docs and saw this notice, but since it's an array, an object reference didn't make sense here..
Works now, thanks!

**Comment by shalvah** [comment]
I've reworked the docs so it's clearer.

![Screenshot_20201027-140653](https://user-images.githubusercontent.com/14361073/97305667-b73a2b80-185d-11eb-996e-3187b4c07846.jpg)
