### ISSUE TITLE
Use of undefined constant baseUrl - assumed 'baseUrl'

### ISSUE THREAD

**Issue by AgustinV08** [knuckleswtf/scribe#126]
I am using Scribe for my API documentation and after doing php artisan scribe:generate and php artisan serve i get this error when i enter the docs Use of undefined constant baseUrl - assumed 'baseUrl' (this will throw an Error in a future version of PHP) (View: /Users/agustinvillanueva/Documents/api-auth/resources/views/scribe/index.blade.php)

![Captura de Pantalla 2020-10-28 a la(s) 11 45 39](https://user-images.githubusercontent.com/32682024/97475653-2160d800-1913-11eb-911b-d0660590a02c.png)

**Comment by shalvah** [comment]
It looks like your Postman collection is within your Blade files for some reason???


THIS IS WHY THERE'S A BUG TEMPLATE. TELL ME ABOUT YOUR ENVIRONMENT SO I CAN TRY TO FIGURE OUT WHAT IS GOING ON. JEEEEZ.

**Comment by Nordok** [comment]
Faced the same issue.

@AgustinV08 Add `'docs.*'` to the `routes.exclude` in the `config/scribe.php`. It seems like scribe tries to generate documentation for file with the postman collection

**Comment by shalvah** [comment]
Thanks for the info @Nordok . Tagged v2.0.2 that should fix this.
