### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by 4unkur** [knuckleswtf/scribe#127]
I am using `laravel` type of docs. The path is `/docs`  
On local there is no errors or something, but on the real website the docs page is taking too long to load and sometimes it crashes. I have opened the console and found this:  

![Velocorner_Documentation](https://user-images.githubusercontent.com/7892851/97524088-0010f200-19ce-11eb-8209-955a5275f407.png)

I tried to navigate to the error and formatted the sources in Chrome:  

![image](https://user-images.githubusercontent.com/7892851/97524325-934a2780-19ce-11eb-9d4a-71aa6faccc51.png)

On the local installation, there is no such errors.  
If it's related: I have added `/resources/views/scribe` and `/resources/docs` folders to .gitignore, because I have API generation step in the CI.  

Any ideas on how to fix this?

**My environment:**
 - PHP version (from `php -v`): 7.4
 - Framework (Laravel/Lumen): Laravel 8.11.2
 - Scribe version (from `composer show knuckleswtf/scribe`): 2.0.1

**Comment by shalvah** [comment]
> If it's related: I have added /resources/views/scribe and /resources/docs folders to .gitignore, because I have API generation step in the CI.

Thank you for sharing. This is an important distinction. It may be possible that what is being generated on your server and locally are different.

Do you have a lot of endpoints? From what I see, I'd say it's failing when trying to initialise the sidebar containing headings. Not sure why.

**Comment by 4unkur** [comment]
@shalvah 

I have only 20 endpoints. As I mentioned earlier it loads perfectly fast on the local, but on the staging server it takes up to few minutes.  
Another information I could provide is that the staging server is protected via basic HTTP authentication.

**Comment by 4unkur** [comment]
@shalvah I have reduced the amount of the returning records from endpoints and it's fixed the problem. So the problem was just in the big amount of json to format, I guess.  

Thanks.
