### ISSUE TITLE
Dingo router implementation not working

### ISSUE THREAD

**Issue by evy0311** [knuckleswtf/scribe#129]
I have been trying to use the 'router' => 'dingo' feature for a few days now and have been running into issues. As is, when I run the generation command I get the following error:

`evan@ubuntu:~/somedirectory$ php artisan scribe:generate

   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 2 passed to App\Providers\PassportDingoProvider::authenticate() must be an instance of Dingo\Api\Routing\Route, null given, called in /home/evan/somedirectory/api/vendor/dingo/api/src/Auth/Auth.php on line 82

  at /home/evan/somedirectory/api/app/Providers/PassportDingoProvider.php:44
    40|      * @param \Dingo\Api\Routing\Route $route
    41|      *
    42|      * @return mixed
    43|      */
  > 44|     public function authenticate(Request $request, Route $route)
    45|     {
    46|
    47|         if (! $user = $this->auth->user()) {
    48|             throw new UnauthorizedHttpException(

  Exception trace:

  1   App\Providers\PassportDingoProvider::authenticate()
      /home/evan/somedirectory/api/vendor/dingo/api/src/Auth/Auth.php:82

  2   Dingo\Api\Auth\Auth::authenticate()
      /home/evan/somedirectory/api/vendor/dingo/api/src/Auth/Auth.php:151

  Please use the argument -v to see more details.`

Note: The information above has been modified as to not release sensitive info.

When I modify the Scribe RouteMatcher class, specifically the getAllRoutes() method, i can change line 52 to be as follows:
`$allRouteCollections = app(\Dingo\Api\Routing\Router::class)->getRoutes('v2'); ` where getRoutes() now takes in a version number (as the getRoutes() method in Dingo wants one unless specified). 

After changing that line to specify a version, I get the following error:
` Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Knuckles\Scribe\Matching\RouteMatcher::Knuckles\Scribe\Matching\{closure}() must be an instance of Dingo\Api\Routing\RouteCollection, instance of Dingo\Api\Routing\Route given

  at /home/evan/somedirectory/api/vendor/knuckleswtf/scribe/src/Matching/RouteMatcher.php:61
    57|
    58|
    59|         //I believe this method is broken
    60|         return collect($allRouteCollections)
  > 61|             ->flatMap(function (RouteCollection $collection) {
    62|                 return $collection->getRoutes();
    63|             })->toArray();
    64|     }
    65|

  Exception trace:

  1   Knuckles\Scribe\Matching\RouteMatcher::Knuckles\Scribe\Matching\{closure}()
      [internal]:0

  2   array_map()
      /home/evan/somedirectory/api/vendor/laravel/framework/src/Illuminate/Support/Collection.php:638

  Please use the argument -v to see more details.`

It seems that the getRoutes() method on line 62 of that error is actually returning a route and not a RouteCollection. Anyone have any ideas why this is behaving this way? I believe Scribe might need to be modified to work properly here, but I wanted to see if anyone else had any thoughts. Thanks so much to everyone for such an awesome package and all of the hard work. All the best. Evan

**Comment by evy0311** [comment]
It seems that within a matter of minutes I have fixed my own issue. I believe that on my end that this is actually an issue with the Scribe package itself an not with my own code. Here's how I fixed it, and maybe someone can chime in and see if this is something I should do a pull request for or if this is just a one off fix for my situation:

The method I have changed in the RouteMatcher class now looks like this:
`php
private function getAllRoutes(bool $usingDingoRouter) //todo change this to take in version
    {
        if (! $usingDingoRouter) {
            return RouteFacade::getRoutes();
        }

        $allRouteCollections = app(\Dingo\Api\Routing\Router::class)->getRoutes('v2'); //Changed this to include a version
        
        //Return this instead since this is already an array of routes
        return $allRouteCollections->getRoutes();


        //I believe this method is broken
        return collect($allRouteCollections)
            ->flatMap(function (RouteCollection $collection) {
                return $collection->getRoutes();
            })->toArray();
    }`

As you can see, I specified a version in the getRoutes() call to the Dingo router class (this will need to be modified to take a version from the config file in scribe). I have also changed the return statement to return the route array from the original call to the router class and this has fixed all errors I am having, and all of the routes, etc are there in the docs file. I believe the original return statement is broken because collect brings together a collection, and then flatMap iterates through that collection and passes in each value to the closure function. This won't work because the closure function wants a RouteCollection passed into itself and it is instead getting a Route. We can simply return the $allRouteCollection->getRoutes() as it is already an array of all routes. I am more than happy to build out a pull request for this here soon, let me know your input and again thanks for such a great package!

**Comment by shalvah** [comment]
Hmm. Nice work (although I haven't looked at it in depth). Sure, send in a PR if you think you have a fix. Make sure to read the contribution guidelines.

**Comment by shalvah** [comment]
Took a stab at your issue and everything seems to work fine. The RouteMatcher picks up Dingo routes correctly. 

> I believe the original return statement is broken because collect brings together a collection, and then flatMap iterates through that collection and passes in each value to the closure function. 

Nope, I believe the existing implementation is correct. If you take a look at the source code for the Dingo Router class, you'll see that it returns either an array or a RouteCollection, depending on if that version parameter is passed. So of course, your `allRouteCollections ` is a collection while the existing one is an array.

> This won't work because the closure function wants a RouteCollection passed into itself and it is instead getting a Route.

Nope, the Closure in flatMap has a typehint, so if a value of a different type is passed in, it would throw an exception.


I don't know, I think your issue was down to something else. Gonna close this now.
