### ISSUE TITLE
Call to undefined method Illuminate\Support\Reflector::isCallable()

### ISSUE THREAD

**Issue by hannahe-lizabet** [knuckleswtf/scribe#130]
Hi, I get this error when running `php artisan scribe:generate` command.

Error message:

```
In RouteAction.php line 32:

Call to undefined method Illuminate\Support\Reflector::isCallable()
```

Enviroument:
- Ubuntu 20.10
-  PHP 7.4.3
-  Lumen 8.0.1

I have register the service provider in `bootstrap/app.php` and add `$app->configure('scribe');` to `bootstrap/app.php`.

**Comment by shalvah** [comment]
We're gonna need a more complete stack trace...

**Comment by shalvah** [comment]
@hannahe-lizabet Still waiting for a stack trace. If you've followed the troubleshooting guide, you should know what to do to get it.

**Comment by danus12** [comment]
@hannahe-lizabet i got also the same error...
@shalvah this is the only stack trace we got

And when i went to the RouteAction class, i really did not see the isCallable() method, so went back to my RouteAction and i removed, just for trial, all the section (if statement) depending on that isCallable method.

And every went well...

**Comment by danus12** [comment]
Sorry guys i'm not working on "scribe", but on "laravel-apidoc-generator"

**Comment by danus12** [comment]
@hannahe-lizabet 
You have to make a `composer update`
It works for me

**Comment by shalvah** [comment]
> Sorry guys i'm not working on "scribe", but on "laravel-apidoc-generator"

😐
