### ISSUE TITLE
$authDescription needs double quotes on line 375 in Writer.php

### ISSUE THREAD

**Issue by oskirkon** [knuckleswtf/scribe#134]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
Noticed that \n\n is included in string on line 375 of Writer.php, php requires double quotes to prevent \n from being interpreted literally.

https://www.php.net/manual/en/language.types.string.php

**Comment by shalvah** [comment]
Thank you. PRs welcome.
