### ISSUE TITLE
Object in array of objects causes error

### ISSUE THREAD

**Issue by mixdd** [knuckleswtf/scribe#139]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. Created a blank Lumen project with ```composer create-project --prefer-dist laravel/lumen scribe_test```
2. Ran ```composer require --dev knuckleswtf/scribe ```
3. Set up Lumen as per https://scribe.readthedocs.io/en/latest/
4. Updated generated controller.php to look as follows:
```
<?php

namespace App\Http\Controllers;

use Laravel\Lumen\Http\Request;
use Laravel\Lumen\Routing\Controller as BaseController;

class Controller extends BaseController
{
    /**
     * Test object within array of objects
     *
     * @bodyParam test object required Object to create.
     * @bodyParam test.items object[] required Object items. No-example.
     * @bodyParam test.items[].more object required Another object. No-example.
     * @bodyParam test.items[].more.info boolean required A property on more. Example: true
     *
     */

    public function test_post(Request $request)
    {
        return response()->json('{}', 200);
    }
}
```
5. Updated routes/web.php by adding the following line: ```$router->post('/test', 'Controller@test_post');```
6. Ran ```php artisan scribe:generate```
7. Saw the following:
![ss_error](https://user-images.githubusercontent.com/637754/98543454-3175a180-229b-11eb-8293-101d1bc88f10.png)
8. Added ```@dd($parameter);``` after  line 2 on body-parameters.blade.php (```@foreach($parameters as $name => $parameter)```)
9. Saw the following:
![ss_error2](https://user-images.githubusercontent.com/637754/98544389-9e3d6b80-229c-11eb-95a4-a590323997ef.png)
10. The above told me the object used to generate the documentation was not being generated correctly. Basically the last ```fields``` object should have been included in the ```fields``` property of the ```more``` object.
11. I figured out that the above issue was due to ```$normalisedBaseName``` on line 414 of Knuckles\Scribe\Extracting\Generator looking as follows: ```test.fields.items.fields.fields.more```
12. To fix this I added the following code under line 414 in Knuckles\Scribe\Extracting\Generator (```$normalisedBaseName = str_replace('[]', '.fields', $baseName);```):

```
if (strpos($normalisedBaseName, 'fields.fields') !== false) {
    $normalisedBaseName = str_replace('fields.fields', 'fields', $normalisedBaseName);
    if(!substr_compare( $normalisedBaseName, '.fields', -strlen( '.fields' ) ) === 0)
        $normalisedBaseName = $normalisedBaseName.'.fields';
}
```

Screenshot of what code looked like after change:
![Knuckles_Scribe_Extracting_Generator_change](https://user-images.githubusercontent.com/637754/98545199-cbd6e480-229d-11eb-9fda-2c7b57dbba85.png)
13. That fixed some of the error but I also needed to add the following code in Knuckles\Scribe\Writing\OpenAPISpecWriter under line 479(```'properties' => collect($field['fields'])->mapWithKeys(function ($subfield) use ($field) {```):

```
$subfield['name'] = str_replace('[]', '', $subfield['name']);
$field['name'] = str_replace('[]', '', $field['name']);
```
Screenshot of what code looked like after change:
![Knuckles_Scribe_Writing_OpenAPISpecWriter_change](https://user-images.githubusercontent.com/637754/98545564-5881a280-229e-11eb-8bb9-25116a879dc5.png)
14. The above changes fixed the issue for me but I know it's quite a hack. Apologies for addressing the symptom and not the cause.
15. Hopefully the above error and hack show the problem and goes some way to creating a fix (or helps someone with the same issue).

**Screenshots and stack traces:**

**My environment:**
 - PHP version (from `php -v`): 7.4.3
 - Framework (Laravel/Lumen): Lumen
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show lumen/framework`): v8.2.0
 - Scribe version (from `composer show knuckleswtf/scribe`): * 2.0.2

**My Scribe config (minus the comments):**

Completely standard

**Additional info:**

**Comment by shalvah** [comment]
This will be fixed in 2.2.1
