### ISSUE TITLE
Laravel type doesn't work

### ISSUE THREAD

**Issue by tomcoonen** [knuckleswtf/scribe#14]
When using the 'laravel' type, there are some issues;
- Writer paths have errors in them, so generating doesn't work
- Config `laravel.url` should be `laravel.docs_url`

I'm going for the static type for now, as soon as I have some extra time I can make a PR.

**Comment by shalvah** [comment]
> Writer paths have errors in them, so generating doesn't work
> Config laravel.url should be laravel.docs_url

You definitely need to share more details about these. Also, did you follow the migration guide?

**Comment by tomcoonen** [comment]
I know this is minimal, but I lack the time now. I fixed the issues locally to see what the problem was.

It just misses files at locations in the Writer.

**Comment by shalvah** [comment]
Have you tried switching to dev-master?

**Comment by b0rt** [comment]
I can confirm for 'dev-master'

Be mindful, dear reader.. this is just an invastigative report.. not a hotfix ;)

```
/var/www$ php artisan scribe:generate --no-extraction
🔊 info Generating API HTML code

   ErrorException

  file_get_contents(resources/views/scribe/index.blade.php): failed to open stream: No such file or directory

  at vendor/knuckleswtf/scribe/src/Writing/Writer.php:198
    194|         // We need to do this delete first, otherwise move won't work if folder exists
    195|         Utils::deleteDirectoryAndContents("public/vendor/scribe/", getcwd());
    196|         rename("{$this->outputPath}/", "public/vendor/scribe/");
    197|
  > 198|         $contents = file_get_contents("$this->outputPath/index.blade.php");
    199|
    200|         // Rewrite links to go through Laravel
    201|         $contents = preg_replace('#href="css/(.+?)"#', 'href="{{ asset("vendor/scribe/css/$1") }}"', $contents);
    202|         $contents = preg_replace('#src="(js|images)/(.+?)"#', 'src="{{ asset("vendor/scribe/$1/$2") }}"', $contents);

      +18 vendor frames
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

removing / commenting L195 and L196 in [Writer.php](https://github.com/knuckleswtf/scribe/blob/master/src/Writing/Writer.php#L195)
```
   protected function performFinalTasksForLaravelType(): void
    {
        // Make output a Blade view
        if (!is_dir($this->outputPath)) {
            mkdir($this->outputPath);
        }

        rename("{$this->outputPath}/index.html", "$this->outputPath/index.blade.php");
        // Move assets from public/docs to public/vendor/scribe
        // We need to do this delete first, otherwise move won't work if folder exists
        // Utils::deleteDirectoryAndContents("public/vendor/scribe/", getcwd());
        // rename("{$this->outputPath}/", "public/vendor/scribe/");

```

the generation proceeds 
```
/var/www$ php artisan scribe:generate --no-extraction
🔊 info Generating API HTML code
👍 success Wrote HTML documentation to: resources/views/scribe
```

**Comment by ErnestStaug** [comment]
Can confirm :) this issue is happening to me as well... 
Blade is being generated in the same folder and then is `moved` to public `dir` and then it's trying to access old dir before it was moved.
Please merge the pull request

**Comment by shalvah** [comment]
Thanks for the detailed report! I was able to recognise and fix the actual issue. This means I won't be merging your PR, as the complete fix was more involved than that. You can view it [here](https://github.com/knuckleswtf/scribe/commit/ee7efd4efb1a55b9b245277a9fef53cc33d04130). Please confirm by switching to version 1.0.0-beta2 and see if it works well.

**Comment by shalvah** [comment]
Make that 1.0.0-beta3. 🤦‍♂️

**Comment by b0rt** [comment]
Hey @shalvah I can confirm that 1.0.0-beta3 resolves the issue for the file saving.
Thank you for the fast response!
And thank you for taking the time to explain the closing of the PR.🙏
I suspected the PR would be a sloppy solution and that I was probably missing some complexity.

**Comment by tomcoonen** [comment]
Thanks for fixing!
