### ISSUE TITLE
Failure to generate api documentation for nested objects

### ISSUE THREAD

**Issue by tommica** [knuckleswtf/scribe#142]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. I set my configuration to:

```
/**
 * @bodyParam foo object[] required No-example
 * @bodyParam foo[].bazBar object[] required No-example
 * @bodyParam foo[].bazBar[].value number required Example: 1180
 * @bodyParam foo[].bazBar[].forced boolean required  Example: true
 */
```

and rules to:
```
return [
  'foo' => 'array|required',
  'foo.bazBar' => 'array|required',
  'foo.barBar.value' => 'numeric|required',
  'foo.bazBar.forced' => 'required|boolean',
];
```

2. Then I ran `php artisan scribe:generate`
3. But I saw...
```
Undefined index: name (View: /home/vagrant/code/xxx/vendor/knuckleswtf/scribe/resources/views/partials/body-parameters.blade.php)
```

![Screenshots and stack traces](https://user-images.githubusercontent.com/1391027/100062416-cd70e280-2e2f-11eb-8c9c-91dae3bedb82.png)

**My environment:**
 - PHP version (from `php -v`): 7.4.11
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 8.15.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 2.0.2

**Additional info:**
I've looked at both of these issues:
https://github.com/knuckleswtf/scribe/issues/135
https://github.com/knuckleswtf/scribe/issues/124

I've also tried this config with the same issue as the result:

```
/**
 * @bodyParam foo object required No-example
 * @bodyParam foo.bazBar object required No-example
 * @bodyParam foo.bazBar.value number required Example: 1180
 * @bodyParam foo.bazBar.forced boolean required  Example: true
 */
```

**Comment by shalvah** [comment]
Update your Scribe version.

> I confirm that I have read and attempted the tips in the Troubleshooting Guide.

That's literally the first thing in the Troubleshooting Guide. There's a reason it exists—I spent time putting it together to help you and save everyone's time. Please respect it.

**Comment by tommica** [comment]
Sorry, that was my bad - I did not take a good look at my composer file, and assumed I was running the latest version after running composer update - thanks for the heads up :)

**Comment by shalvah** [comment]
Cool.
