### ISSUE TITLE
how to generate only 1 model with @apiResourceCollection?

### ISSUE THREAD

**Issue by denyudin** [knuckleswtf/scribe#143]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

here is my piece of code:
 - controller
```
     /**
     * @apiResourceCollection App\Http\Resources\ConnectionResource
     * @apiResourceModel App\PlatformConnection
     */
     public function connections()
     {
         return ConnectionResource::collection($connections)->resolve();
     }
```
 - scribe docs Example response:
```
{  
   "data": [
        {
            "id": 1
        },
        {
            "id": 2
        },
        {
            "id": 2
        },
        etc...
   ]
}
```
in the generated documentation, I get a selection of all entities from the database, but I want to get only one entity, like this:
```
{  
   "data": [
        {
            "id": 1
        }
   ]
}
```
@apiResourceCollection and @apiResource work the same in this case

**Comment by Lovro1107** [comment]
I have the same annotations as you and I get only the first model **but twice**.
My example response looks like this:
```
{
    "data": [
        {
            "id": 1,
            "name": "John",
        },
        {
            "id": 1,
            "name": "John",
        }
    ]
}
```

The only difference I see is that I don't call `resolve()` on the collection but I don't think this affects anything.

**Comment by denyudin** [comment]
@Lovro1107 resolve() in this case does not affect the current problem in any way

@apiResourceCollection and @apiResource pull all entities from the base and the documentation is huge

Unfortunately so far I have not been able to solve this problem, using @responseFile, slower, manually, but the result is what I expect

**Comment by shalvah** [comment]
Hmmm.

> in the generated documentation, I get a selection of all entities from the database

This shouldn't happen.

https://github.com/knuckleswtf/scribe/blob/master/src/Extracting/Strategies/Responses/UseApiResourceTags.php#L98

You can see that two models are explicitly generated here. I suspect this response is coming from the response call, not the API resource strategy. That should only happen if the API resource strategy failed. Try adding some logging within that strategy to see what it returned.
