### ISSUE TITLE
Undefined index: name 

### ISSUE THREAD

**Issue by tonycodes** [knuckleswtf/scribe#144]
**What happened?**
I ran `php artisan scribe:generate` and saw

   Facade\Ignition\Exceptions\ViewException 

  Undefined index: name (View: /app/resources/views/vendor/scribe/partials/body-parameters.blade.php)

  at resources/views/vendor/scribe/partials/body-parameters.blade.php:8
      4▕ <p>
      5▕ <details>
      6▕ <summary>
      7▕ @component('scribe::components.field-details', [
  ➜   8▕   'name' => $parameter['name'],
      9▕   'type' => $parameter['type'] ?? 'string',
     10▕   'required' => $parameter['required'] ?? false,
     11▕   'description' => $parameter['description'] ?? '',
     12▕   'endpointId' => $endpointId,

instead of success message

**My environment:**
 - PHP version (from `php -v`): 7.4.9
 - Framework (Laravel/Lumen): Laravel 8
 - Laravel/Lumen version (from `composer show laravel/framework`:  * v8.14.0 
 - Scribe version (from `composer show knuckleswtf/scribe`): * 2.3.0

**Comment by shalvah** [comment]
Take a look at #124. It's likely that you have the same problem (you're trying to document a nested array or object without adding the parent field).

If that isn't your problem, you'll need to debug this some more on your own. What endpoint is failing? (Hint: it's going to be one that has nested objects or arrays). Try excluding other routes to verify which it is, then we can look at what you're doing in that route.

**Comment by shalvah** [comment]
Should be fixed in 2.4.1
