### ISSUE TITLE
Laravel Validation Rules Error Message non-English language replace bug

### ISSUE THREAD

**Issue by victorioustr** [knuckleswtf/scribe#145]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. I set my configuration to...
2. Then I ran `php artisan scribe:generate` ...
3. But I saw...

For use with Laravel Request Validation Rules, if a non-English language is used, the word "The: attribute" is replaced with str_replace in the description field at the beginning of the Validation Error message. Str_replace does not work because there is no word "The" in our language. Because of that

vendor/knuckleswtf/scribe/src/Extracting/ValidationRuleDescriptionParser.php:50

str_replace should be changed to ":attribute" instead of "The :attribute".

**My environment:**
 - PHP version 7.4.3
 - Framework (Laravel/Lumen): 8
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 8.15.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 2.3.0

**Comment by shalvah** [comment]
I wouldn't change it, because it reads weird stuff the "The" left in. Maybe add it as a fallback. PR welcome.

**Comment by shalvah** [comment]
Should be fixed in 2.4.1
