### ISSUE TITLE
How to use post parameter in request ?

### ISSUE THREAD

**Issue by victorioustr** [knuckleswtf/scribe#146]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

Hello,
I am trying to prepare api documentation with Laravel. I have read the user manual and Issues complete. Either I missed it or I couldn't find what I wanted.

I want to send form-data as Post Parameter to POST request. Whatever I did he always does it as json. If only "file" is added in the documentation, "multipart / form-data" header is added and parameters are sent as form-data.

I would like your help on the subject.

Good work.

**Comment by shalvah** [comment]
Have you tried changing the Content-Type header in `apply.headers` in your config?

**Comment by victorioustr** [comment]
All requests are requested with json, but only the login request is sent via form-data. What should I do in this situation?

**Comment by victorioustr** [comment]
I don't know what I'm doing but it works right now. We can close.
