### ISSUE TITLE
apiResource Database Transactions not working

### ISSUE THREAD

**Issue by victorioustr** [knuckleswtf/scribe#147]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. I set my configuration to...
2. Then I ran `php artisan scribe:generate` ...
3. But I saw...

After a response (default User Model and Factory) generate as apiResource in my database, which is defined as Mysql Innodb, the record stays in the database permanently. Transaction does not work.

The continue_without_database_transactions setting is an empty array.

I made it work by manually making the following changes in the code.

vendor/knuckleswtf/scribe/src/Extracting/DatabaseTransactionHelpers.php:16

    private function startDbTransaction()
    {

        // my codes...
        $connections = array_keys(config('database.connections', []));
        $driver = app('db')->connection($connections[1]);
        $driver->beginTransaction();

        return;
        // my codes ended...

        $connections = array_keys(config('database.connections', []));

        wait(parallelMap($connections, function ($connection) {
            try {
                $driver = app('db')->connection($connection);

                if (self::driverSupportsTransactions($driver)) {
                    $driver->beginTransaction();

                    return;
                }

                $driverClassName = get_class($driver);

                if ($this->shouldAllowDatabasePersistence($driverClassName)) {
                    throw DatabaseTransactionsNotSupported::create($connection, $driverClassName);
                }

                c::warn("Database driver [$driverClassName] for the connection [{$connection}] does not support transactions. Any changes made to your database will persist.");
            } catch (ScribeException $e) {
                throw $e;
            } catch (Exception $e) {
            }
        }));
    }
$connections[1] is my MySQL connection.

**My environment:**
 - PHP version 7.4.3
 - Framework (Laravel/Lumen): 8
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 8.15.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 2.3.0

**Comment by milosh012** [comment]
👍 
I have the same problem (same env like @victorioustr ) I will create a PR for this today

**Comment by shalvah** [comment]
https://github.com/knuckleswtf/scribe/issues/141#issuecomment-735222861

**Comment by milosh012** [comment]
@shalvah here is PR related to this issue...

**Comment by shalvah** [comment]
This should be fixed in 2.4.0, but might be a breaking change if you use more than one transaction. See https://github.com/knuckleswtf/scribe/blob/master/CHANGELOG.md#240-monday-30-november-2020
