### ISSUE TITLE
League/flysystem v2.0 support

### ISSUE THREAD

**Issue by sangnguyenplus** [knuckleswtf/scribe#148]
Hello @shalvah @mpociot,

I just want to notify you that league/flysystem 2.0 was released 2 days ago.

Can you update Scribe to support league/flysystem 2.0? 

Thanks for a great package!

**Comment by shalvah** [comment]
Thanks. I actually used Flysystem 2 initially in Scribe, but it was still in alpha that I had to revert it, so upgrading shouldn't be difficult. However, I can't make that change until Laravel upgrades to Flysystem v2 (which I'm guessing would be Laravel 9). I want to avoid causing any package conflicts..
