### ISSUE TITLE
Can't generate docs

### ISSUE THREAD

**Issue by tsonevpetyo** [knuckleswtf/scribe#15]
## Expected Behavior
Running ```  php artisan scribe:generate ``` should generate docs folder in public/

## Actual Behavior
The output of the command is 
![image](https://user-images.githubusercontent.com/62121640/82305966-13537680-99c7-11ea-9dea-a9a45f041f10.png)
And no docs folder is generated. I migrated from [Laravel API Documentation Generator](https://github.com/mpociot/laravel-apidoc-generator) The config file contains the same as apidoc.php. Using  [Laravel API Documentation Generator](https://github.com/mpociot/laravel-apidoc-generator) cause no problems at all with the same anotations. I found it strange that returning the array of parsed routes in ``` GenerateDocumentation@processRoutes ``` at the third iteration (in my case ) generates the docs successfully. Also what are those numbers 368, 276 ?

## Code
```
/**
 * Class RefreshTokenController
 * @package App\Http\Controllers\V1\Auth
 * @group Authentication
 */
class RefreshTokenController extends Controller

/**
     * Refresh token.
     *
     * @header Authorization Bearer {token}
     * @param  \Illuminate\Http\Request  $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
```

```
/**
 * Class LogoutController
 * @package App\Http\Controllers\V1\Auth
 * @group Authentication
 */
class LogoutController extends Controller

/**
     * Log out and blacklist token
     *
     * @authenticated
     * @header Authorization Bearer {token}
     * @param  \Illuminate\Http\Request  $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function __invoke(Request $request)
```

```
/**
 * Class LoginController
 * @package App\Http\Controllers\V1\Auth
 * @group Authentication
 */
class LoginController extends Controller
{
    /**
     * Get Authentication Token
     *
     *
     * @bodyParam code_login string Scanned login code. * Not required if email and password are present
     * @bodyParam email string The email of the user. * Required if code_login is not passed
     * @bodyParam password string The password for the user. * Required if code_login is not passed
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
```
## Specifications
  - PHP: 7.4 
  - Laravel version: 7.11
  - Scribe: ^1.0@beta
  - Platform: MacOS 10.15.4

**Comment by shalvah** [comment]
Umm... Did you follow the migration guide? Have you tried the troubleshooting tips?

**Comment by tsonevpetyo** [comment]
> Umm... Did you follow the migration guide? Have you tried the troubleshooting tips?

Yes, and the output has been run with verbose mode

**Comment by shalvah** [comment]
> Yes, and the command has been run with verbose mode
And this is all you get?

> The config file contains the same as apidoc.php
You're aware that it's not exactly the same contents, right?

Try switching to dev-master

**Comment by tsonevpetyo** [comment]
> > Yes, and the command has been run with verbose mode
> 
> And this is all you get?
> 
> > The config file contains the same as apidoc.php
> 
> You're aware that it's not exactly the same contents, right?
> 
> Try switching to dev-master

Yes, i am aware of that i meant the main things the rest are left untouched :). I will switch the branches and i will let you know. Thanks

**Comment by tsonevpetyo** [comment]
@shalvah Nothing at all only those number as output :) 

![image](https://user-images.githubusercontent.com/62121640/82314174-13a53f00-99d2-11ea-8ccd-9c4f83046db9.png)
![image](https://user-images.githubusercontent.com/62121640/82314206-20299780-99d2-11ea-80fe-aca9f710ccef.png)

Not even info about the routes parsed...

**Comment by shalvah** [comment]
How many routes are you parsing? Have you tried running with a higher
memory limit?

**Comment by tsonevpetyo** [comment]
3 routes only... No difference with higher memory limit

**Comment by shalvah** [comment]
Please share your machine config (PHP/Laravel version) and Scribe config (minus the comments)

**Comment by shalvah** [comment]
Also, please try updating to 1.0.0-beta2

**Comment by shalvah** [comment]
Make that 1.0.0-beta3. 🤦‍♂️

**Comment by shalvah** [comment]
Any luck?

**Comment by tsonevpetyo** [comment]
Hi, sorry for the late answer... Still no joy :(

**Comment by shalvah** [comment]
> I found it strange that returning the array of parsed routes in GenerateDocumentation@processRoutes at the third iteration (in my case ) generates the docs successfully.

What did you mean by this in your initial comment?

**Comment by tsonevpetyo** [comment]
![image](https://user-images.githubusercontent.com/62121640/82662205-1ef8a480-9c36-11ea-9408-2ee731c1c334.png)

![image](https://user-images.githubusercontent.com/62121640/82662232-2a4bd000-9c36-11ea-8719-d605fe58c34f.png)

As you can see returning the parsedRoutes array leads to successful generation of the docs.

**Comment by shalvah** [comment]
I'm assuming `$k` is the index of the routes. Why that condition (`$k == 3`)? If you're generating 3 routes, wouldn't 2 be where you stop? Also, try letting it run all the way and dumping `$k`.

**Comment by tsonevpetyo** [comment]
Hi 
![image](https://user-images.githubusercontent.com/62121640/83011635-e33d5080-a022-11ea-8abc-62b0792c17fe.png)
I find it "strange" that there are 4 matches for 3 routes

**Comment by shalvah** [comment]
Try logging the details of each route before it's processed.

**Comment by tsonevpetyo** [comment]
Hmm, it seems the route parser does not "like" closures but i am shooting in the dark here. I added the prefix 'v1' in the scribe config and it started working. It was catching a route from the web.php which is closure (the default welcome one)

**Comment by shalvah** [comment]
Scribe supports Closure routes, so that's weird... So yeah, maybe some more investigation is needed. Maybe something in the specific closure route is tripping it up.

**Comment by shalvah** [comment]
>  It was catching a route from the web.php 

I think this may be the real problem. Routes in web.php have different middleware applied, which might make them behave weirdly.
