### ISSUE TITLE
php version (8.0.0) does not satisfy that requirement.

### ISSUE THREAD

**Issue by simonproud** [knuckleswtf/scribe#152]
Problem 1
    - knuckleswtf/scribe[2.4.0, ..., 2.4.2] require knuckleswtf/pastel ^1.3.6 -> satisfiable by knuckleswtf/pastel[1.3.6].
    - knuckleswtf/pastel 1.3.6 requires mnapoli/front-yaml ^1.7.0 -> satisfiable by mnapoli/front-yaml[1.7.0].
    - mnapoli/front-yaml 1.7.0 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires knuckleswtf/scribe ^2.4 -> satisfiable by knuckleswtf/scribe[2.4.0, 2.4.1, 2.4.2].

**Comment by shalvah** [comment]
> - mnapoli/front-yaml 1.7.0 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.

**mnapoli/front-yaml**

**Comment by shalvah** [comment]
The problem is obviously a different package; not sure why you're complaining here...? Go open an issue there, otherwise, your best bet is `composer install --ignore-platform-reqs=php`. 

v3 will probably get rid of the need for this package, but that's still a ways off.🤔
