### ISSUE TITLE
Laravel Sanctum SPA authentication.

### ISSUE THREAD

**Issue by gpanos** [knuckleswtf/scribe#154]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

Hey thanks for the awesome package! 
I am building a Laravel API to be consumed by a Nuxt SSR application. I want to use [Laravel Sanctum](https://laravel.com/docs/8.x/sanctum) to add cookie based session authentication. I can't figure out how to setup the authentication to work with scribe. I have been looking for hours but couldn't find any resources on the subject. Can anyone provide an example or point me to the right direction? Is it even possible to be done or should I switch to a token based authentication? 

Thanks a lot :)

**Comment by shalvah** [comment]
Cookie-based auth for an API? Hmm. Scribe is designed to work with stateless APIs. However, there's a `cookies` parameter in the config that you can set for response calls. So perhaps get a cookie manually and set it there to authenticate your calls.

**Comment by gpanos** [comment]
Yep basically following the Laravel docs for SPA authentication https://laravel.com/docs/8.x/sanctum#spa-authentication. Since the API would be consumed only from a first party Nuxt application cookie based auth seems like the simplest approach... I am gonna give `cookies` parameter a try and let you know. Thanks a lot

**Comment by cs02lk1** [comment]
Hi @gpanos,

I am facing a similar issue while trying to use auth:sanctum on the docs endpoint. Did you manage to resolve this?

Thanks

**Comment by nivv** [comment]
Sanctum also include token based auth. I made a simple route for generating a token and then setting `SCRIBE_AUTH_KEY` to this value.

```php
Route::get('get-token', function() {
    $user = \App\Models\User::findOrFail(7);
    return $user->createToken('test')->plainTextToken;
});
```

I better approach would be to make a console command to generate the token though

**Comment by jeanremy** [comment]
I faced the same issue and ended using a custom Command, if it can be useful:
```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class GenerateDocs extends Command
{
    protected $signature = 'generate:docs';

    protected $description = 'Generate documentation';

    public function __construct()
    {
        parent::__construct();
    }

    public function handle()
    {
        $user = \App\Models\User::findOrFail(1);
        config(['scribe.auth.use_value' => $user->createToken('yourstring')->plainTextToken]);
        $this->call('scribe:generate');
        return 0;
    }
}
```

**Comment by shalvah** [comment]
Thanks to @james2doyle, in v3.10.0, Try It Out now supports Sanctum SPA authentication when you set `try_it_out.use_csrf` to true. (Run `php artisan scribe:upgrade` to upgrade your config file.)

Response calls still won't work, I guess, but hopefully someone can come up with something for that.

**Comment by shalvah** [comment]
You can now customize the pre-authentication flow for your response calls (v3.11) [docs](https://scribe.knuckles.wtf/laravel/documenting/responses#authentication-and-customization):

```php
public function boot()
{
    // Be sure to wrap in a `class_exists()`, 
    // so production doesn't break if you installed Scribe as dev-only
    if (class_exists(\Knuckles\Scribe\Scribe::class)) {
        Scribe::beforeResponseCall(function (Request $request, ExtractedEndpointData $endpointData) {
            $token = User::first()->api_token;
            $request->headers->add(["Authorization" => "Bearer $token"]);
        });
    }
    // ...
}
```

**Comment by mansha99** [comment]
Headers does not seem to be added

**Comment by emadbatwa** [comment]
i have same issue even when try this
```php
        if (class_exists(\Knuckles\Scribe\Scribe::class)) {
            Scribe::beforeResponseCall(function (Request $request, ExtractedEndpointData $endpointData) {
                if ($endpointData->route->getName() === 'auth.logout') {
                $doctor_user = User::query()->whereHas('doctor')->latest()->first();
                $token = $doctor_user->createToken('test_token')->plainTextToken;
                $token = explode('|', $token)[1];
                $request->headers->add(["Authorization" => "Bearer $token"]);
                dump($request->header('Authorization'));
                dump($token);
                }
            });
        }

```

the token not added to request when i dump the user request its return someone else


in controller

```php

    public function __construct()
    {
        $this->middleware('guest')->except(['logout', 'me']);
        $this->middleware('auth:sanctum')->only('logout');
    }

```

```php
    /**
     * Logout user
     *
     * This endpoint lets you logout authenticated user for both (customer / doctor) role.
     *
     * @authenticated
     */
    public function logout(Request $request)
    {
        dump(Auth::user());
        $request->user()->currentAccessToken()->delete();
        return response(['message' => __('auth.logout')], 200);
    }

```


and in api.php

```php
    Route::post('/logout', [AuthController::class, 'logout'])->name('auth.logout');

```

**Comment by dac-humi** [comment]
For future devs looking for a [Sanctum SPA](https://laravel.com/docs/10.x/sanctum#spa-authentication) solution:

```php
use Laravel\Sanctum\Sanctum;
// ...snip...
Scribe::beforeResponseCall(function (Request $request, ExtractedEndpointData $endpointData) {
    $user = User::first();
    Sanctum::actingAs($user, ['*']);
});

```

**Comment by shalvah** [comment]
> Headers does not seem to be added

In a Symfony\Request object, you may need to set a header twice for it to work, something like:

```php
$request->headers->add(["Authorization" => "Bearer $token"]);
$request->server->add(["HTTP_AUTHORIZATION" => "Bearer $token"]);
```

Do some debugging, guys. Scribe isn't doing anything special here. The request passed to the hook is the same one we pass to your Laravel app during the response call.
