### ISSUE TITLE
How to describe flat array of objects?

### ISSUE THREAD

**Issue by bmbBAMBUS** [knuckleswtf/scribe#156]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

Hello I can't find out, how to write annotations correctly for flat array of objects.
My current annotations:

```
     /**
     * Title
     *
     * Description line0
     * Description line1
     *
     * @urlParam shortlink integer required Id of shortlink.
     * @bodyParam [] object[] required Array of OgTags
     * @bodyParam [].property string required Each OgTag needs to have property field.
     * @bodyParam [].content string required Each OgTag needs to have value.
     *
     * @example
     */
```
It generates wrong request:
```
curl -X POST \
    "http://mydomain.com/api/shortlinks/19/ogtags" \
    -H "Authorization: Bearer {YOUR_AUTH_KEY}" \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -d '{"[]":[[],[]]}'
```
Generated -d parameter is not accurate, here is correct body for request:
```
[
    {
        "property": "og:url",
        "content": "https://google.com"
    },
    {
        "property": "og:title",
        "content": "Google"
    }
]
``` 
Here are request rules:
```
public function rules()
    {
        return [
            '*.property' => 'required|starts_with:og:',
            '*.content' => 'required',
        ];
    }
```

It's caused by "flat" array of objects in request. Is any way to handle it?
I've tried many ways with no luck:
Fore example to delete: 
     * @bodyParam [] object[] required Array of OgTags

**Comment by shalvah** [comment]
You aren't doing anything wrong. This is a known limitation of Scribe that I plan to address in v3. I mostly hadn't decided on a syntax. I think I'll go with the way you wrote it.

**Comment by shalvah** [comment]
I've implemented this in v3, which should be out in May or June.

However, I think this already works in v2. Just need to omit the outer parameter (ie remove this line👇).

```
* @bodyParam [] object[] required Array of OgTags
```

**Comment by shalvah** [comment]
🎉[v3 is out now](https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3)! Try it out and see if it works for you.

**Comment by bmbBAMBUS** [comment]
Will try in new microservice API docs!
