### ISSUE TITLE
"Match" is a semi-reserved keyword in PHP 8

### ISSUE THREAD

**Issue by Barzin73** [knuckleswtf/scribe#159]
When I'm trying to run `php artisan scribe:generate`
I'm getting an error about the Match is a reserved keyword in php8.0 that you are using it as a class name.
Please change this class name, it's just used in one file and it's easy to change. 

**My environment:**
 - PHP version: 8.0
 - Framework: Laravel

**Comment by ErnestStaug** [comment]
Had to fix few packages myself today, seems like an issue with a lot of packages :D

**Comment by shalvah** [comment]
PHP 8 support now in 2.5.1
