### ISSUE TITLE
Call to undefined method ReflectionUnionType::getName()

### ISSUE THREAD

**Issue by Barzin73** [knuckleswtf/scribe#160]
There are some calls to undefined methods in this files:

src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php:45
src/Extracting/Strategies/Headers/GetFromHeaderTag.php:30
src/Extracting/Strategies/BodyParameters/GetFromBodyParamTag.php:36
src/Extracting/Strategies/UrlParameters/GetFromUrlParamTag.php:31
src/Extracting/Strategies/QueryParameters/GetFromQueryParamTag.php:36

In all of this files, the error is because of this line:
`$parameterClassName = $paramType->getName();`

My solution is change it to
```
if (method_exists($paramType, 'getName'))
    $parameterClassName = $paramType->getName();
else
    continue;
```

**My environment:**
 - PHP version:  8.0
 - Framework: Laravel 8.0

**Comment by shalvah** [comment]
I'll probably get to this by next week, but it's open source—you can send in a PR with these fixes (plus a Travis CI entry for PHP 8).

**Comment by shalvah** [comment]
Eh, went ahead to create a PR: #162

**Comment by shalvah** [comment]
PHP 8 support now in 2.5.1
