### ISSUE TITLE
Bad hostname

### ISSUE THREAD

**Issue by sweebee** [knuckleswtf/scribe#161]
When i've generated the docs I get the following 404 in the example:

```
"message": "Bad hostname provided.",
"exception": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
```

I used https://github.com/mpociot/laravel-apidoc-generator this one before and that one works fine.

I've also tried to add the hostname to the /etc/hosts file but without any success. I'm using Laravel Valet locally.

**Comment by sweebee** [comment]
![Schermafbeelding 2020-12-10 om 11 59 53](https://user-images.githubusercontent.com/10496485/101763557-38344600-3adf-11eb-86cd-1f5c06dedad6.png)

**Comment by shalvah** [comment]
Try dumping the hostname in your app, based on the stacktrace.

**Comment by boywijnmaalen** [comment]
is the APP_URL value correct? it should match the domain you want for your API
