### ISSUE TITLE
Dynamic translation

### ISSUE THREAD

**Issue by fabolousfrances** [knuckleswtf/scribe#163]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

Hello,

we are on a laravel project, with a scribe api doc.
Is there a way to have a multi-language apidoc, with a dynamic translation by a filter like a dropdown with english, french, italian etc... ?
In our laravel project, we use a {{ message.string }} to put a string which is refering to a language file. Is there a way to use the same translate system in Scribe API doc ?

thanks in advance.

**Comment by shalvah** [comment]
Hey. That's not supported, and not on the roadmap for anytime soon, sorry.

**Comment by shalvah** [comment]
It doesn't look like this will ever be on the roadmap for Scribe, sorry. I think you can achieve it with some custom wiring like using `laravel` type, plus a custom controller, and a script that does a find-replace on the Blade view. Or maybe fork Scribe and customise for your setup.

**Comment by scortes1989** [comment]
you have publish the theme and change this manually with: `php artisan vendor:publish --tag=scribe-views
`
