### ISSUE TITLE
urlParam and Form request conflict

### ISSUE THREAD

**Issue by Elshaden** [knuckleswtf/scribe#164]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. I set my configuration to...
2. Then I ran `php artisan scribe:generate` ...
3. But I saw...

``URL Parameters
id  string  

Body Parameters
id  string  
``

instead of...
``URL Parameters
id  string  
``

**Screenshots and stack traces:**
![image](https://user-images.githubusercontent.com/33955172/102393591-dd1bbb00-3fd8-11eb-9f60-d177a0bf47c6.png)

**My environment:**
 - PHP version (from `php -v 7.4`): 
 - Framework (Laravel):
 - Laravel version 8
 - Scribe version

**My Scribe config (minus the comments):**

**Additional info:**

The problem is that I am merging the URL parameters and body parameters if any and using the form request validating for both.
Plus I have other functionalities in the form request like decoding the hashId.

what should I have a way to ignore the Form request rules from the API documentation

Thanks.

**Comment by shalvah** [comment]
Comment out the GetFromFormRequest strategy in your config.

**Comment by Elshaden** [comment]
Thanks 
It is working well now
