### ISSUE TITLE
is Lumen support broken?

### ISSUE THREAD

**Issue by boywijnmaalen** [knuckleswtf/scribe#165]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

Hi, I'm using Laravel lumen but it seems Lumen is not (anymore?) supported out of the box.

routes/laravel.php uses Router methods, which simply don't exist in Lumen' version of the Router.

Maybe I'm doing something wrong but Lumen isn't supported out of the box.

Please advice!

**Comment by shalvah** [comment]
Lumen is supported (with a lot of pain involved).

`routes/laravel.php` provides convenience routes for your API docs when using `laravel` type. Very easy to make your own routes instead.

**Comment by shalvah** [comment]
If the routes file is throwing errors on Lumen, you can disable the auto-addition of routes (look for the appropriate key in your config file).

**Comment by boywijnmaalen** [comment]
Hi @shalvah,

Thanks vor your reply.

I can add the routes myself manually yes.

However the /docs page itself requires the asset() method to load.
This method is not available in Lumen. What do you recommend in order to display the /docs page properly?

**Comment by syphernl** [comment]
These routes seem to work fine with Lumen:
```php
// Documentation
$router->group(['namespace' => '\Knuckles\Scribe\Http'], function() use ($router) {
    $prefix = config('scribe.laravel.docs_url', '/docs');
    $middleware = config('scribe.laravel.middleware', []);

    $router->group(['middleware' => $middleware], function () use ($router, $prefix) {
        $router->get($prefix, ['as' => 'scribe', 'uses' => 'Controller@webpage']);
        $router->get($prefix . '.postman', ['as' => 'scribe.postman', 'uses' => 'Controller@postman']);
        $router->get($prefix . '.openapi', ['as' => 'scribe.openapi', 'uses' => 'Controller@openapi']);
    });
});
```

The only problem is that the views aren't working
