### ISSUE TITLE
Update to league/flysystem ^2.0

### ISSUE THREAD

**Issue by milanbeo** [knuckleswtf/scribe#166]
Problem 1
    - Root composer.json requires knuckleswtf/scribe ^2.5 -> satisfiable by knuckleswtf/scribe[2.5.1].
    - knuckleswtf/scribe 2.5.1 requires league/flysystem ^1.0 -> found league/flysystem[1.0.0-alpha1, ..., 1.x-dev] but it conflicts with your root composer.json require (^2.0).

**Comment by shalvah** [comment]
https://github.com/knuckleswtf/scribe/issues/148

Has Laravel updated its dependency yet?
