### ISSUE TITLE
Nested API resources

### ISSUE THREAD

**Issue by hcphoon01** [knuckleswtf/scribe#168]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. I added `
@apiResourceCollection App\Http\Resources\Flights\RequestResource
@apiResourceModel App\Models\Flights\FlightRequest` to a method comment
2. Then I ran `php artisan scribe:generate` 
3. I then got this error in the console
```
Eloquent model factory failed to instantiate App\Models\Flights\FlightRequest; trying to fetch from database.

   Error

  Call to a member function tokenCan() on null

  at app/Http/Resources/UserResource.php:21
    17|     {
    18|         return [
    19|             'id' => $this->id,
    20|             'username' => $this->username,
  > 21|             'email' => $this->when($request->user()->tokenCan('email') && Auth::id() == $this->id, $this->email),
    22|         ];
    23|     }
    24| }
    25|
```

instead of...

No errors

**My environment:**
 - PHP version (from `php -v`): 7.4.3 
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`):  7
 - Scribe version (from `composer show knuckleswtf/scribe`): 2.5

**Additional info:**

I believe this may be due to the `UserResource` being referenced in my `RequestResource`, I have tried adding the `UserResource`  into the comment block aswell but that hasnt fixed the issue

**Comment by shalvah** [comment]
See https://github.com/knuckleswtf/scribe/issues/155#issuecomment-740970828

The same thing I explained there applies here. Your problem is this:

```php
$request->user()
```
You're trying to retrieve the authenticated user. But the ApiResource strategy doesn't do any authentication, so that will always return null. The strategy basically just creates that class and calls the method. If you want a strategy that can authenticate, use ResponseCalls.

**Comment by Longlv197** [comment]
i still find the way to resolve this problem

**Comment by Longlv197** [comment]
i got the same problem and i still haven't found a way to resolve this problem. Can you help me?

**Comment by UtkuDalmaz** [comment]
I am having the same issue
