### ISSUE TITLE
config/scribe.php exclude doesn't work to passport route

### ISSUE THREAD

**Issue by c2w570063013** [knuckleswtf/scribe#171]
Some passport routes from vender can't be eexcluded even though i have alredy config it on scribe.php.

**Comment by shalvah** [comment]
It definitely works.🙂

How did you exclude it? Always include what you did when asking for help.

**Comment by kingRayhan** [comment]
I have got the same issue, I exclude `/admin` path but it don't work
```php
/*
 * Exclude these routes even if they matched the rules above.
 * The route can be referenced by name or path here. Wildcards are supported.
 */
'exclude' => [
    'admin/'
],
```
When I give command of `php artisan scribe:generate` , it starts generating doc for admin path too.

![image](https://user-images.githubusercontent.com/7611746/112736285-cc85c400-8f7b-11eb-9365-77c47b2431c5.png)

**Comment by shalvah** [comment]
`admin/*`?
