### ISSUE TITLE
Splitting documention based on API version

### ISSUE THREAD

**Issue by siegerhansma** [knuckleswtf/scribe#172]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

Hey, 

First of all, thank you for you package. It has saved me a lot of work in documenting a large API.

In our API we have two versions at the moment. I would like to generate seperate documentation files (maybe /docs/v1 and /docs/v2) for both API versions. Is this possible with the current version of Scribe? And if not, is this something that is on the roadmap for v3?

**Comment by siegerhansma** [comment]
Just saw https://github.com/knuckleswtf/scribe/issues/72 is similar, apologies. Are there any updates on this?

**Comment by shalvah** [comment]
Nope, I doubt there will be more direct support for that. It's too much of a niche feature to justify the added complexity.

**Comment by shalvah** [comment]
You can now do this! https://scribe.knuckles.wtf/laravel/generating#generating-multiple-docs
