### ISSUE TITLE
Excluded routes still showing in documentation

### ISSUE THREAD

**Issue by juliakerschbaummayr1** [knuckleswtf/scribe#175]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
In the scribe.php file at 'routes' => 'match' => 'prefixes' I set the value to ['api/*'] to only show routes from my api in the documentation. But it seems that this value is ignored because all of my routes are showing. 
I also grouped my endpoints. This works and the different groups are showing, but still some of the routes are showing in the created group and also in the default group Endpoints.

So my two questions are:
- why is the setting to only show 'api/*' routes in the documentation ignored and how can I achieve only having these routes in my documentation
- why are some routes showing in two groups although they only exist once and have the @ group value in the comments

**My environment:**
 - PHP version (from `php -v`): PHP 7.3.25
 - Framework (Laravel/Lumen): Laravel 8
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 8.17.2
 - Scribe version (from `composer show knuckleswtf/scribe`): 2.5.1

**My Scribe config (minus the comments):**

```
return [
    'title' => null,
    'description' => '',
    'routes' => [
        [
            'match' => [
                'domains' => ['*'],
                'prefixes' => ['api/*'],
                'versions' => ['v1'],
            ],
            'include' => [
            ],
            'exclude' => [
            ],
            'apply' => [
                'headers' => [
                    'Content-Type' => 'application/json',
                    'Accept' => 'application/json',
                ],
                'response_calls' => [
                    'methods' => ['GET'],
                    'config' => [
                        'app.env' => 'documentation',
                    ],
                    'queryParams' => [
                    ],
                    'bodyParams' => [
                    ],
                    'fileParams' => [
                    ],
                    'cookies' => [
                    ],
                ],
            ],
        ],
    ],
    'type' => 'laravel',
    'static' => [
        'output_path' => 'public/docs',
    ],
    'laravel' => [
        'add_routes' => true,
        'docs_url' => '/docs',
        'middleware' => [],
    ],
    'interactive' => true,
    'auth' => [
        'enabled' => true,
        'default' => false,
        'in' => 'query',
        'name' => 'token',
        'use_value' => env('SCRIBE_AUTH_KEY'),
        'placeholder' => '{YOUR_AUTH_KEY}',
        'extra_info' => 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.',
    ],
    'intro_text' => <<<INTRO
This documentation aims to provide all the information you need to work with our API.
<aside>As you scroll, you'll see code examples for working with the API in different programming languages in the dark area to the right (or as part of the content on mobile).
You can switch the language used with the tabs at the top right (or from the nav menu at the top left on mobile).</aside>
INTRO
    ,
    'example_languages' => [
        'bash',
        'javascript',
    ],
    'base_url' => null,
    'postman' => [
        'enabled' => true,
        'overrides' => [
        ],
    ],
    'openapi' => [
        'enabled' => true,
        'overrides' => [
        ],
    ],
    'default_group' => 'Endpoints',
    'logo' => false,
    'router' => 'laravel',
    'faker_seed' => null,
    'strategies' => [
        'metadata' => [
            \Knuckles\Scribe\Extracting\Strategies\Metadata\GetFromDocBlocks::class,
        ],
        'urlParameters' => [
            \Knuckles\Scribe\Extracting\Strategies\UrlParameters\GetFromLaravelAPI::class,
            \Knuckles\Scribe\Extracting\Strategies\UrlParameters\GetFromLumenAPI::class,
            \Knuckles\Scribe\Extracting\Strategies\UrlParameters\GetFromUrlParamTag::class,
        ],
        'queryParameters' => [
            \Knuckles\Scribe\Extracting\Strategies\QueryParameters\GetFromQueryParamTag::class,
        ],
        'headers' => [
            \Knuckles\Scribe\Extracting\Strategies\Headers\GetFromRouteRules::class,
            \Knuckles\Scribe\Extracting\Strategies\Headers\GetFromHeaderTag::class,
        ],
        'bodyParameters' => [
            \Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromFormRequest::class,
            \Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromBodyParamTag::class,
        ],
        'responses' => [
            \Knuckles\Scribe\Extracting\Strategies\Responses\UseTransformerTags::class,
            \Knuckles\Scribe\Extracting\Strategies\Responses\UseResponseTag::class,
            \Knuckles\Scribe\Extracting\Strategies\Responses\UseResponseFileTag::class,
            \Knuckles\Scribe\Extracting\Strategies\Responses\UseApiResourceTags::class,
            \Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls::class,
        ],
        'responseFields' => [
            \Knuckles\Scribe\Extracting\Strategies\ResponseFields\GetFromResponseFieldTag::class,
        ],
    ],
    'fractal' => [
        'serializer' => null,
    ],
    'routeMatcher' => \Knuckles\Scribe\Matching\RouteMatcher::class,
    'continue_without_database_transactions' => [],
    'database_connections_to_transact' => [config('database.default')]
];
```

**Comment by shalvah** [comment]
That's weird. I couldn't reproduce this. Route rules work fine in both the package tests and my machine. Try debugging this further by adding some

**Comment by juliakerschbaummayr1** [comment]
I am not sure what you mean, but I ran php artisan `scribe:generate --verbose` and copied the output here, hope this helps

As you can see I added `@hideFromAPIDocumentation` to a lot of routes to prevent them from showing in the documentation but some are still showing although they don´t start with api/, for example login, logout, register and so on

The route `api/forums/all/{courseId}` is an example of the routes I have two times, in the Forums group and in the general Endpoints group

php artisan scribe:generate --verbose
🔊 info Processing route: [GET] sanctum/csrf-cookie
👍 success Processed route: [GET] sanctum/csrf-cookie 
🔊 info Processing route: [GET] api/user
👍 success Processed route: [GET] api/user 
🔊 info Processing route: [POST] api/tokens/create
👍 success Processed route: [POST] api/tokens/create 
🔊 info Processing route: [GET] api/courses
👍 success Processed route: [GET] api/courses 
🔊 info Processing route: [PUT] api/courses/follow/{id}
👍 success Processed route: [PUT] api/courses/follow/{id} 
🔊 info Processing route: [GET] api/coaches/all/{courseId}
👍 success Processed route: [GET] api/coaches/all/{courseId} 
🔊 info Processing route: [GET] api/coaches/{id}
👍 success Processed route: [GET] api/coaches/{id} 
🔊 info Processing route: [GET] api/forums/all/{courseId}
**👍 success Processed route: [GET] api/forums/all/{courseId}** 
🔊 info Processing route: [GET] api/forums/{id}
👍 success Processed route: [GET] api/forums/{id} 
🔊 info Processing route: [PUT] api/forums/{courseId}
👍 success Processed route: [PUT] api/forums/{courseId} 
🔊 info Processing route: [GET] api/forums/comments/{id}
👍 success Processed route: [GET] api/forums/comments/{id} 
🔊 info Processing route: [PUT] api/forums/comments/{id}
👍 success Processed route: [PUT] api/forums/comments/{id} 
🔊 info Processing route: [GET] api/videos/all/{courseId}
👍 success Processed route: [GET] api/videos/all/{courseId} 
🔊 info Processing route: [GET] api/videos/{id}
👍 success Processed route: [GET] api/videos/{id} 
🚸 warning Skipping route: [GET] activate/{user}/{token}: @hideFromAPIDocumentation was specified.
🔊 info Processing route: [GET] login
**👍 success Processed route: [GET] login** 
🚸 warning Skipping route: [POST] login: @hideFromAPIDocumentation was specified.
🔊 info Processing route: [POST] logout
**👍 success Processed route: [POST] logout** 
🔊 info Processing route: [GET] register
**👍 success Processed route: [GET] register** 
🔊 info Processing route: [POST] register
👍 success Processed route: [POST] register 
🔊 info Processing route: [GET] password/reset
👍 success Processed route: [GET] password/reset 
🔊 info Processing route: [POST] password/email
👍 success Processed route: [POST] password/email 
🔊 info Processing route: [GET] password/reset/{token}
👍 success Processed route: [GET] password/reset/{token} 
🔊 info Processing route: [POST] password/reset
👍 success Processed route: [POST] password/reset 
🔊 info Processing route: [GET] /
👍 success Processed route: [GET] / 
🚸 warning Skipping route: [GET] home: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [GET] admin/coachings: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [GET] admin/coachings/create: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [POST] admin/coachings: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [GET] admin/coachings/{coaching} - Controller method does not exist.
🚸 warning Skipping route: [GET] admin/coachings/{coaching}/edit: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [PUT,PATCH] admin/coachings/{coaching}: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [DELETE] admin/coachings/{coaching}: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [GET] admin/coaching/signout/{attendee}: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [GET] admin/coaching/cancel/{coaching}: @hideFromAPIDocumentation was specified.
🔊 info Processing route: [POST] admin/notifications/{notification}/read
👍 success Processed route: [POST] admin/notifications/{notification}/read 
🔊 info Processing route: [POST] admin/notifications/read
👍 success Processed route: [POST] admin/notifications/read 
🚸 warning Skipping route: [GET] admin/forums: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [GET] admin/forums/create: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [POST] admin/forums: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [GET] admin/forums/{forum}: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [GET] admin/forums/{forum}/edit: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [PUT,PATCH] admin/forums/{forum}: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [DELETE] admin/forums/{forum}: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [POST] admin/forums/{forum}/add/comment: @hideFromAPIDocumentation was specified.
🔊 info Processing route: [GET] admin/mailable/{id}/{type}
👍 success Processed route: [GET] admin/mailable/{id}/{type} 
🔊 info Processing route: [GET] admin/testnotification/{id}
👍 success Processed route: [GET] admin/testnotification/{id} 
🚸 warning Skipping route: [GET] coaching/coachings: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [GET] coaching/attend/{coaching}: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [GET] coaching/info/{coaching}: @hideFromAPIDocumentation was specified.
🚸 warning Skipping route: [GET] coaching/signout/{coaching}: @hideFromAPIDocumentation was specified.
🔊 info Processing route: [GET] coachings
👍 success Processed route: [GET] coachings 
🔊 info Processing route: [GET] forum
👍 success Processed route: [GET] forum 
🔊 info Processing route: [GET] forum/{forum}
👍 success Processed route: [GET] forum/{forum} 
🔊 info Processing route: [GET] testcrudgenerator
CrudGeneratorServiceProvider: OK👍 success Processed route: [GET] testcrudgenerator 
🔊 info Writing source Markdown files to: resources/docs
🚸 warning Skipping modified file resources/docs/groups/endpoints.md
🚸 warning Skipping modified file resources/docs/index.md
🚸 warning Skipping modified file resources/docs/authentication.md
🔊 info Wrote source Markdown files to: resources/docs
🔊 info Transforming Markdown docs to HTML...
👍 success Wrote HTML documentation to: resources/views/scribe 
🔊 info Generating Postman collection
👍 success Wrote Postman collection to: storage/app/scribe/collection.json 
🔊 info Generating OpenAPI specification
👍 success Wrote OpenAPI specification to: storage/app/scribe/openapi.yaml

**Comment by juliakerschbaummayr1** [comment]
not sure why but it works now
I added Authentication and generated the docs again and now it works, so I´ll close this issue
