### ISSUE TITLE
Why postman collection doesnot have examples for the requests

### ISSUE THREAD

**Issue by hsmfawaz** [knuckleswtf/scribe#177]
When i export the current docs to postman, I cant finds the responses defined for the requests in examples section in postman,
Is this a bug or there is someting i missed

**Comment by shalvah** [comment]
I'm not sure what you mean, but I followed the Postman spec when implementing the collection export. If you think there's something missing, you can send in a PR (and include a link to what we're missing).

**Comment by shalvah** [comment]
Oh, I see you mean the responses aren't included. Hmmm. When I implemented the spec, I didn't notice that. Will probably add it sometime, but, yes, you can send a PR, because my hands are pretty full right now.

**Comment by hsmfawaz** [comment]
I will be happy to help

**Comment by shalvah** [comment]
Implemented in v2.6.0
