### ISSUE TITLE
how set laravel translation in a generated docs?

### ISSUE THREAD

**Issue by simonproud** [knuckleswtf/scribe#179]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

**Comment by shalvah** [comment]
This is a poorly crafted issue. I'm not in your mind. Ask a better question, with examples of what you mean and what you've tried. Otherwise, I'll close it.

**Comment by shalvah** [comment]
Localization support in Scribe is very limited atm.

**Comment by scortes1989** [comment]
you can publish the views and change this in your installation : `php artisan vendor:publish --tag=scribe-views
`

**Comment by shalvah** [comment]
It's taken 3 years, but you can now use Laravel translations to override the Scribe text: `php artisan vendor:publish --tag=scribe-translations` 😅
