### ISSUE TITLE
I'm unable to install: migrating from mpociot/laravel-apidoc-generator 

### ISSUE THREAD

**Issue by MilesHart** [knuckleswtf/scribe#18]
**What happened?**
1. Removed apidoc
2. Composer install of scibe
3. Error

Using version ^1.0@beta for knuckleswtf/scribe
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nunomaduro/collision (locked at v2.1.1, required as ^2.0) -> satisfiable by nunomaduro/collision[v2.1.1].    
    - knuckleswtf/scribe 1.0.0-beta requires nunomaduro/collision ^3.0|^4.0 -> satisfiable by nunomaduro/collision[v4.x-dev].
    - knuckleswtf/scribe 1.0.0-beta2 requires nunomaduro/collision ^3.0|^4.0 -> satisfiable by nunomaduro/collision[v4.x-dev].
    - knuckleswtf/scribe 1.0.0-beta3 requires nunomaduro/collision ^3.0|^4.0 -> satisfiable by nunomaduro/collision[v4.x-dev].
    - Conclusion: don't install nunomaduro/collision v4.x-dev
    - Installation request for knuckleswtf/scribe ^1.0@beta -> satisfiable by knuckleswtf/scribe[1.0.0-beta, 1.0.0-beta2, 1.0.0-beta3].     

Installation failed, reverting ./composer.json to its original content.

**My environment:**
 - PHP version: PHP 7.3.1
 - Laravel version: Laravel Framework 6.18.15
 - Scribe Version: na

This is my composer.json

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "barryvdh/laravel-dompdf": "^0.8.5",
        "facade/ignition": "^1.13",
        "fideloper/proxy": "^4.0",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "~6.0",
        "itsgoingd/clockwork": "^4.0",
        "laravel/framework": "^6.0",
        "laravel/tinker": "^1.0",
        "maatwebsite/excel": "^3.1",
        "mpdf/mpdf": "^8.0",
        "simplesoftwareio/simple-qrcode": "^2.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "krlove/eloquent-model-generator": "^1.3",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}


```

**Comment by shalvah** [comment]
Thanks. There's some weird dependency shit going on. Have you tried adding it to your composer.json and running composer install instead?

**Comment by shalvah** [comment]
Your dependencies are incompatible. Why do you have`"nunomaduro/collision": "^2.0"`? It comes with Laravel, and it's been in version 3 since at least LL5.8 and version 4 since L7. You should remove that.

**Comment by shalvah** [comment]
https://github.com/laravel/laravel/blob/v6.18.8/composer.json#L20

You should be on v3 of Collision.

**Comment by MilesHart** [comment]
Thank you team. This was originally a Laravel 5.4? version and I did upgrade, it must be hole in the update. All good now.
