### ISSUE TITLE
Closure Routes doesn't work! Throws ReflectionException 

### ISSUE THREAD

**Issue by aeadedoyin** [knuckleswtf/scribe#180]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

When I include a closure route e.g:
```php
Route::get('/', function () {
    return view('welcome');
});
```
 and run 
```
php artisan scribe:generate
```
I get
```php
ReflectionException is thrown.
 Class C:32:"Opis\Closure\SerializableClosure":256:{ does not exist
```

but when I remove all closure routes, the generate command works perfectly.

---
Further checks shows its originated from opis/closure (^3.6) 
but after running ` composer why opis/closure` turns out `laravel/framework  v8.22.1  requires  opis/closure (^3.6)`

Scribe Version: "^2.5",
Laravel Version: "v8.22.1"

**Comment by shalvah** [comment]
I don't think this problem is from Closure routes. There are closure routes in the [example docs](https://shalvah.me/TheCensorshipAPI) and they work fine.

On the other hand,

```php
Route::get('/', function () {
    return view('welcome');
});
```

is a web route. (Why are you returning a view?) Try switching to an API route; that should work.

**Comment by shalvah** [comment]
If you don't want to include that route, tweak your config to skip it.

**Comment by aeadedoyin** [comment]
I think you can make scribe ignore web routes out of the box.

**Comment by shalvah** [comment]
No, not really. We match routes based on prefix or name. Web routes don't have any common prefix. API routes might have a prefix (/api), but that doesn't apply to all apps.

The only somewhat reliable way to determine web routes would be to check for the `web` middleware on a route, but I'm not sure if that would be worth it.
