### ISSUE TITLE
More than 2 example fields for arrays?

### ISSUE THREAD

**Issue by JonPurvis** [knuckleswtf/scribe#183]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

I have a `@bodyParam` that's using `string[]` as the type, when I generate my documentation, the execution form only contains 2 fields. Is there any way to customise the amount of fields that show here? I thought it had something to do with specifying examples, so I set 3 examples for this param but still only get 2 fields in the documentation.

Thanks!

**Comment by shalvah** [comment]
For an array of strings, you probably want something like this:

```
     * @bodyParam names string[] The names of the users.  Example: [
     *   "Peter Pan",
     *   "Phil Dunphy"
     * ]
```

For objects, see my comments at https://github.com/knuckleswtf/scribe/issues/66#issuecomment-777390090
