### ISSUE TITLE
Guzzle Multipart header issue

### ISSUE THREAD

**Issue by ErnestStaug** [knuckleswtf/scribe#184]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

In `php` generated docs GuzzleHttp header is set to

`‘Content-Type’  multipart/form-data.`
If there is a file submission.

For some reason when you POST with this header Laravel doesn't see any data/or GuzzleHttp doesn't send it.

It seems like I am [not the first one](https://stackoverflow.com/questions/30645996/guzzle-6-0-multipart-and-form-params) who have this issue and we have clients who report that our endpoint is not working because of this issue. 

I would suggest not adding this header at all, to prevent this issue from happening.

**My environment:**
 - PHP version (from `php -v`):  7.4
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 7.29
 - Scribe version (from `composer show knuckleswtf/scribe`):  2.4.2
 - guzzlehttp/guzzle: 6.5.5

**Comment by shalvah** [comment]
Hmmm, so what you're saying is to NOT include the `Content-Type` header in the Guzzle example if the request is multipart?

**Comment by shalvah** [comment]
I think I'd probably just remove the Content-Type header from Guzzle, since Guzzle sets it automatically when you use `json` or `multipart`.
