### ISSUE TITLE
'Try it out' bug

### ISSUE THREAD

**Issue by dvlpr91** [knuckleswtf/scribe#186]
Hi, thanks for reading.

**version: 2.5.2**

1. Write the sample response value. (@ response ...)

2. Generate. (php artisan scribe:generate)

3. Do `Try it out`. (on my scribe page)

4. Click the'Cancel' button.

5. You cannot see the sample response values.

Thanks!

**Comment by shalvah** [comment]
Yep, I'm aware the Try Out feature is a bit buggy. I'll fix it in the next major version, but you can send in a PR instead.

**Comment by dvlpr91** [comment]
Also, when transferring a file, all body parameters are not transferred.

**Comment by shalvah** [comment]
This should be fixed later today (3.3.2).
