### ISSUE TITLE
"Try it out" Bug for Navigation

### ISSUE THREAD

**Issue by darken-innovation** [knuckleswtf/scribe#187]
**What happened?**

1. I run `Try it out` and `Send Request`
2. Then when I click the below navigation gets mess up. 

**My environment:**

PHP version (from php -v): 7.4.14
Framework: Laravel 8.12
Scribe version (from composer show knuckleswtf/scribe): 2.5

**Comment by shalvah** [comment]
Yep, I'm aware the Try Out feature is a bit buggy. I'll fix it in the next major version, but you can send in a PR instead.

**Comment by shalvah** [comment]
This should be fixed later today (v3.3.2).
