### ISSUE TITLE
FormRequest Dependency Injection

### ISSUE THREAD

**Issue by eac0n** [knuckleswtf/scribe#189]
According to the [Laravel docs](https://laravel.com/docs/8.x/validation#creating-form-requests) you can inject dependencies to the` rules` method of a `FormRequest`.
> You may type-hint any dependencies you require within the rules method's signature. They will automatically be resolved via the Laravel service container.

However, scribe seems to have trouble with this since the `GetFromFormRequest` strategy always calls the `rules` method without parameters. I managed to workaround the Problem by overwriting `GetFromFormReques::getRouteValidationRules` in a custom strategy like this:

```php
namespace App\Docs\Strategies\BodyParameters;


use Illuminate\Contracts\Validation\Factory as ValidationFactory;
use Illuminate\Support\Facades\App;

class GetFromFormRequest extends \Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromFormRequest {

    protected function getRouteValidationRules($formRequest)
    {
        if (method_exists($formRequest, 'validator')) {
            $validationFactory = app(ValidationFactory::class);

            return call_user_func_array([$formRequest, 'validator'], [$validationFactory])
                ->getRules();
        } else {
            $params = [];
            $reflectionMethod = new \ReflectionMethod(get_class( $formRequest ), 'rules');
            $reflectionParameters = $reflectionMethod->getParameters();
            foreach($reflectionParameters as $reflectionParameter) {
                $params[] = App::make($reflectionParameter->getClass()->getName());
            }
            return call_user_func_array([$formRequest, 'rules'], $params);
        }
    }

}
```
I don't know if this will work for every dependency but in my case, a custom rule, it works fine. Also I don't know if other strategies may face the same problem.

Nevertheless, I think scripe should take dependency injection into account of its own accord.

**Comment by shalvah** [comment]
Yes, the form request strategy always instantiates the form request directly, not through the service container.

The FormRequest behaviour is complicated. We could change it to use the service container, but that won't fix every thing. 🤔

**Comment by tbordinat** [comment]
Hi!
Thank you for your awesome work on this project !
I'm confronted to something similar, do you know if there is a solution ? I looked for one but I can't find anything... :/ 

Here is my request.

```
class AnalyticsRequest extends FormRequest
{
    public function __construct(
        UserService $userService
    ) {
        $this->userService = $userService;
    }
    /** ... */
}
```

And I got this error when I try to `scribe:generate` on my project : 

```
  Too few arguments to function App\Domains\Analytics\Http\Requests\AnalyticsRequest::__construct(), 0 passed in /var/www/html/vendor/knuckleswtf/scribe/src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php on line 69 and exactly 1 expected
```

**Comment by shalvah** [comment]
A workaround would be to instantiate the service yourself.

```php
public function __construct() {
        $this->userService = app(UserService::class);
    }
```

It will also work for your regular app too.

**Comment by tbordinat** [comment]
Thank you for your fast answer ! 
Is there a way to prevent Request from being instanciate, and only look at the @bodyParam instead ?
It could be a solution, I would be ok to add @bodyParam when things can't be automatic :) 

I don't wanna change the entire codebase to add this workaround only for doc generation.

**Comment by shalvah** [comment]
> I don't wanna change the entire codebase to add this workaround only for doc generation.

It will work for the rest of your app, too, so you can leave it in. But I understand if you don't want to change it.

> Is there a way to prevent Request from being instanciate, and only look at the @bodyParam instead ?

You can remove it from your config. `strategies.bodyParameters`.

**Comment by shalvah** [comment]
There's now an [`instantiateFormRequestUsing()`](https://scribe.knuckles.wtf/laravel/hooks#instantiateformrequestusing) hook that you can use to customise how your requests are created.

**Comment by salvationarinze** [comment]
@shalvah I'm having the same issue as above and this is what I have:
```
if (class_exists (Scribe::class)) {
            Scribe::instantiateFormRequestUsing(function (string $className,  Route  $route,
                                                          ReflectionFunctionAbstract $method) {
                ray($className, $route, $method)->green();
                return app()->make($className);
            });
        }
```
Its still not calling the function for some reason

**Comment by shalvah** [comment]
Where does the error come from? What code is trying to instantiate the IncotermService? Can you paste a fuller stack trace? I have a few suspects, but want to be sure. Depending on the location, we should probably switch to instantiating via `app()`, or catching any exceptions when using `new`.
