### ISSUE TITLE
Unable to disable postman queries

### ISSUE THREAD

**Issue by MilesHart** [knuckleswtf/scribe#19]
I've set the 

`'enabled' => false,`

In the scribe.php and reg'd, however its still producing postman examples. Any way to turn this off?

**Comment by shalvah** [comment]
Nope, this is a false flag. Looks like you generated with Postman collection before and then disabled that. Scribe won't delete the Postman collection if it already exists.🤷‍♂️ You have to delete that manually. 

For confirmation, when you run `scribe:generate` with Postman collection disabled, you'll notice that:
- the console output does not mention generating a collection, unlike when you have it enabled
- there's no "Get Postman collection" link in the sidebar.

(For future purposes, please include more info when reporting an issue, like described in the template. It saved everyone's time so I won't have to later ask for details of your environment.)

**Comment by MilesHart** [comment]
PHP version: 7.3.1
Laravel version: Laravel Framework 6.18.15

Render type : static

I think you might be right, but I'm not seeing that in my instance.

Its not outputting what your saying however it is generating the postman markup files in the 

\resources\docs\groups\asset-managerment.md

And also generating the postman request reponses in the public/docs/index.html

I have hard deleted these between each change and also use the --force switch....

Also to note, when it does generate the page, and I render this, more often than not the chrome page will time out, with a wait or kill.. When it does render it takes about 3 minutes.

I've also attempted to kill the examples by removing all types.

```
'example_languages' => [
        //'bash',
        //'javascript',
    ],
```

**Comment by shalvah** [comment]
> Its not outputting what your saying however it is generating the postman markup files in the
>
> \resources\docs\groups\asset-managerment.md

Now I'm confused. Are you talking about the Postman collection? Because that has nothing to do with Markdown.

**Comment by shalvah** [comment]
> Also to note, when it does generate the page, and I render this, more often than not the chrome page will time out, with a wait or kill.. When it does render it takes about 3 minutes.

Hmm. How many routes are you documenting?

**Comment by MilesHart** [comment]
Good question, this is the console output.

```
php artisan scribe:generate
�🔊 info Processed route: [GET] api/us
�🔊 info Processed route: [POST] api/updatetick
�🔊 info Processed route: [POST] api/getvatra
�🔊 info Processed route: [POST] api/getohvatcode
�🔊 info Processed route: [POST] api/updateticketl
�🔊 info Processed route: [POST] api/genSiteInfo
�🔊 info Processed route: [POST] api/regenSiteInfo
�🔊 info Processed route: [GET] api/jobtracker/search/{strSearc
�🔊 info Processed route: [GET] api/jobtracker/id/{strI
�🔊 info Processed route: [GET] api/qboa
�🔊 info Processed route: [GET] api/qboard/qtrs/{unrestrict
�🔊 info Processed route: [POST] api/qboard/card/mo
�🔊 info Processed route: [POST] api/qboard/card/a
�🔊 info Processed route: [POST] api/qboard/card/remo
�🔊 info Processed route: [POST] api/report/{reportType}
�🔊 info Processed route: [POST] api/l
�🔊 info Processed route: [GET] api/getAssets/{useri
�🔊 info Processed route: [GET] api/assets/{toast_i
�🔊 info Processed route: [GET] api/asset/mode
�🔊 info Processed route: [GET] api/asset/statuslab
�🔊 warning Skipping route: [POST] api/asset/add - Exception encountere
�🔊 warning ErrorException in C:\XXXXXXX
\vendor\knuckleswtf\scribe\src\Extracting\Strategies\BodyParameters\GetFromBodyParamTag.php at l
e 78: Undefined offset: 1
�🔊 warning Run again with --verbose for a full stacktrace
�🔊 info Processed route: [GET] api/asset/{asseti
�🔊 info Processed route: [POST] api/asset/{assetid}/assign/{toasti
�🔊 info Processed route: [POST] api/asset/{assetid}/unassign
�🔊 info Processed route: [GET] api/users/{search
�🔊 info Processed route: [POST] api/use
�🔊 info Processed route: [GET] api/users/fromtoast/{i
�🔊 info Processed route: [POST] api/customercare/n
�🔊 info Processed route: [POST] api/customercare/reop
�🔊 info Processed route: [POST] api/customercare/requestupda
�🔊 info Processed route: [GET] api/findUser/{search}/{all
�🔊 info Processed route: [GET] api/getUser/{i
�🔊 info Processed route: [GET]
�🔊 info Processed route: [GET] reg
�🔊 info Processed route: [POST] reg
�🔊 info Processed route: [GET] report/{projid}/{periodMonth}/{periodYear}/{reportType}/{cutOffDay}
�🔊 info Processed route: [GET] file
�🔊 info Processed route: [GET] file/{uid}/{download?}
�🔊 info Processed route: [POST] file
�🔊 info Processed route: [GET] dropdown/{startMonth}/{startYear}/{dayOfTheMonth}
�🔊 info Processed route: [GET] image
�🔊 info Processed route: [GET] login
�🔊 info Processed route: [POST] login
�🔊 info Processed route: [POST] logout
�🔊 info Processed route: [GET] home
�🔊 info Processed route: [GET] qrcode
�🔊 info Processed route: [GET] trackerHistory
�🔊 info Processed route: [GET] encrypt/{string}
�🔊 info Processed route: [GET] decrypt/{string}
�🔊 info Processed route: [GET] fitteractivity/{date}/{ResourceId?}
�🔊 info Processed route: [GET] papi
�🔊 info Writing source Markdown files to: resources/docs
�🔊 info Wrote source Markdown files to: resources/docs
�🔊 info Generating API HTML code
�🔊 success Wrote HTML documentation to: public/docs
```
50 ish...

**Comment by shalvah** [comment]
And my other question?

**Comment by MilesHart** [comment]
Ok, just to circle round with my issue....

resources/docs/groups/endpoints.md

contains about 150k lines of responses which is causing alot of payload to the rendering, so I want to disable this. I was assuming this was firing off (via guzzle or curl) and recording the responses to document the bash and javascript examples. 

Just so we reading from the same page... I do appreciate any help here. Thank you.

**Comment by shalvah** [comment]
Are you new to using this package? Because it seems your understanding of its workings is pretty inaccurate. I'll try to help, but you should take some time to read through the docs (https://scribe.rtfd.io).

First off, this has nothing to do with Postman. Postman collections are a single JSON file generated by the package and are not generated when you disable them. They don't have anything to do with what shows up on the HTML page (except the extra link "Get Postman Collection" when you have it enabled).

Secondly, 

> resources/docs/groups/endpoints.md
>
> contains about 150k lines of responses which is causing alot of payload to the rendering, so I want to disable this.

First off, endpoints are organised by groups. See [here](https://scribe.readthedocs.io/en/latest/documenting/documenting-endpoint-metadata.html#grouping-endpoints). If you don't group your endpoints, Scribe will put all of them in a single group, `Endpoints`. Since routes are split into Markdown files based on groups, yes, you get a single Markdown file. 

...But this shouldn't be a problem! Scribe uses [Pastel](https://githubcom/knuckleswtf/pastel) to convert the Markdown to a single HTML file, so you shouldn't bother with the Markdown, but rather the output HTML.

>  I was assuming this was firing off (via guzzle or curl) and recording the responses to document the bash and javascript examples.

Not really. Again, you should [read the docs](https://scribe.readthedocs.io/en/latest/documenting/documenting-endpoint-responses.html). By default, for GET endpoints **only**, Scribe makes an internal call to the endpoint if you haven't specified a response using any of the other methods described in the linked article.  For other endpoints, you'll simply get `null` responses.

It seems like what you want to do is disable the example requests and responses shown in the output? Hmmm. Setting `example_languages` to an empty array should work. I'll test that out.

**Comment by shalvah** [comment]
Tested it out, and yes, when you empty the `example_languages` array, no example requests are shown. Example responses are shown, though.
![image](https://user-images.githubusercontent.com/14361073/82695949-f5ec0a00-9c5d-11ea-981d-fbe733167b27.png)

**Comment by kodunmi** [comment]
Please how can I remove the example response altogether @shalvah

**Comment by shalvah** [comment]
Make a custom template (search the docs for this)
