### ISSUE TITLE
can i create sub folders to separate system modules?

### ISSUE THREAD

**Issue by maiconmva** [knuckleswtf/scribe#190]
can i create sub folders to separate system modules?

**Comment by shalvah** [comment]
Can you clarify what you mean?

**Comment by maiconmva** [comment]
structure requests into folders and subfolders

![image](https://user-images.githubusercontent.com/5194641/110264270-ba75be80-7f97-11eb-84a4-7eadd48c7ee3.png)

**Comment by shalvah** [comment]
Er, the Postman collection is already structured into folders by default (`@group` tag). If you're asking about subfolders, no, those aren't supported, and there aren't any plans for that.
