### ISSUE TITLE
Documentation search missing results

### ISSUE THREAD

**Issue by maguilar92** [knuckleswtf/scribe#191]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. When I search endpoint in the doc only first coincidence returned when name is reused instead of return both.

**Screenshots and stack traces:**

<img width="234" alt="Screenshot 2021-03-10 at 09 52 30" src="https://user-images.githubusercontent.com/25102127/110602532-641aa280-8186-11eb-8877-23aec36c3610.png">
<img width="230" alt="Screenshot 2021-03-10 at 09 52 39" src="https://user-images.githubusercontent.com/25102127/110602538-64b33900-8186-11eb-884f-a9c074b10bd9.png">
<img width="229" alt="Screenshot 2021-03-10 at 09 52 46" src="https://user-images.githubusercontent.com/25102127/110602541-654bcf80-8186-11eb-90c5-2e7ecd969808.png">

**My environment:**
 - PHP version (from `php -v`): 7.3.27-1+ubuntu18.04.1+deb.sury.org+1
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): v8.31.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 2.5.3

**Comment by shalvah** [comment]
I'm sorry, I don't understand your question. Is the problem the extra result ("Get Payments Paginated")?

**Comment by maguilar92** [comment]
Hi @shalvah. I want to say that if I have for example:

- Collective (Group)
  - Process Payment (endpoint)
- User (Group)
  - Process Payment (endpoint)

When use the searcher typing Process Payment only one result is found. I think if could be interesting if searcher could show:
- Process Payment [Collective]
- Process Payment [User]

**Comment by shalvah** [comment]
I see. I honestly have no idea how the search even works, but my guess is that it uses the h3 IDs on the page. And those two have the same ID (`process-payment`), so the HTML probably picks the last. The fix would probably be to set the ID of each endpoint to include the group name, if any. So the two IDs would be "user-process-payment" and "collective-process-payment". I'm kinda busy at the moment, so feel free to give this a go.

**Comment by shalvah** [comment]
Done this in v3 (coming out next week or the week after).

**Comment by shalvah** [comment]
🎉[v3 is out now](https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3)!
