### ISSUE TITLE
Make the base domain dynamic acording to the app.url for the generated doc

### ISSUE THREAD

**Issue by meyer59** [knuckleswtf/scribe#192]
- [V] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

Hello
I have been wondering if there is any way to make the base domain dynamic according to the .env once the doc is generated. 
So for example, if i run `scribe:generate` on my local machine it will show `http://localhost` but if i push the same doc to the production (without running `scribe:generate`) it will show `http://prod-url`.
The need is to generate the docs in a safe environement and check that everything is ok and then push the file to git. 
Also it facilitate the integration with CI/pipeline since everything is in the git repos, no need to run the `scribe:generate` command on prod.
Since in your doc you suggest to install with the `--dev` flag `composer require --dev knuckleswtf/scribe`, i presume that we don't need to install it on prod env. So is there any way to make the domain stick to the `app.url` ?
Thank you

**Comment by tommica** [comment]
I think the issue is that the files that are generated are static files - What I've done is have a middleware that handles auth access to the docs, and also does a search-replace for the http://testapi.test url to config('app.url'), but the problem is that I've not found a way to modify the content of the binaries that is being served by laravel (for example the generated openapi json file)

**Comment by meyer59** [comment]
This is a bit of a hack.. Also, by editing files on the fly like that you will have conflit with git when you re-pull next time. I don't it is a proper way to handle it

**Comment by shalvah** [comment]
Yep, right now Scribe doesn't support this use case well. I'll spend some time thinking of a better way to support this in v3.

**Comment by lk77** [comment]
It's not working at all, when i'm doint scribe:generate is does not take the app.url in the .env, it will always default to http://localhost not mater what

**Comment by shalvah** [comment]
What docs type?

**Comment by lk77** [comment]
Sorry, it was not working because i was not using --force

**Comment by shalvah** [comment]
So here's what I'm thinking @tommica @meyer59:

- the current app URL (`config('app.url'), which == `env(APP_URL)`) will be used as the domain for response calls
- the `scribe.base_url` will be used as the display URL in the docs
- there will be a new option to set the URL for Try It Out functionality.

This way, you can generate docs on your local machine, and Scribe will hit localhost:8000 to get responses, display your production server in the examples, and use your staging server for the API tester.

**Comment by shalvah** [comment]
The Postman collection and OpenAPI spec will also use the provided `base_url`.

As for displaying per-environment URLs, I don't think I can get that to work in `static` type (unless I add some JavaScript, but I don't want to go there atm). For `laravel` type, I think we can make it dynamic to the current URL.

**Comment by tommica** [comment]
Sounds good to me - at least in postman it is easy to swap the base url variable to something else after importing the collection, so that is ok.

Thanks for doing this 😊

26 May 2021 23.20.53 Shalvah ***@***.***>:

**Comment by meyer59** [comment]
Sounds Ok too 👍

**Comment by shalvah** [comment]
🎉[v3 is out now](https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3)!
