### ISSUE TITLE
fakerphp/faker

### ISSUE THREAD

**Issue by Dysha96** [knuckleswtf/scribe#194]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

- knuckleswtf/scribe[2.5.1, ..., 2.5.3] require fakerphp/faker ^1.9.1 -> satisfiable by fakerphp/faker[v1.9.1, ..., v1.14.1]
- fakerphp/faker[v1.9.1, ..., v1.9.2] require php ^5.3.3 || ^7.0 -> your php version (8.0.3) does not satisfy that requirement.
- Hi, are there any plans to update the fakerphp/faker version?

**Comment by shalvah** [comment]
This isn't a problem from this package. Something in your project is locking your Faker version to 1.9.1 or 1.9.2, which doesn't support your PHP version.

This should fix it:
1. Ensure your `fakerphp/faker` version in `composer.json` is set to `^1.9.1` (NOT `~1.9.1`).
2. Run `composer update fakerphp/faker`.
