### ISSUE TITLE
Testing Routes from Localhost vs explicit domain

### ISSUE THREAD

**Issue by santiagazo** [knuckleswtf/scribe#197]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

My dev environment is a live server, so I don't develop locally. Our system is a multi-tenant site. Each tenant is recognized by its subdomain. When the system tests against my routes, it's testing with localhost. This results in the following error:

```
{
    "message": "Tenant could not be identified on domain localhost",
}
```

The `$base_url` is great for displaying the URL my API consumers can test against but how can I set the testing URL so that it has a subdomain, allowing my system to pull up the correct tenant. ie: demo.domain.com or _maybe_ demo.localhost (I don't know if this would work - I'd rather use my full subdomain.domain.com).

Any help would be appreciated!

**Comment by santiagazo** [comment]
Yes, sorry, I mean response calls I believe...
![Tenant-not-ided-localhost](https://user-images.githubusercontent.com/15197623/114100703-ed0a2400-9881-11eb-9c75-940f6bc3f8b9.jpg)

**Comment by santiagazo** [comment]
Thx for the quick reply btw - please let me know if I can answer anything else I haven't explained well enough!

**Comment by shalvah** [comment]
Response calls will use your current `app.url` config value. Have you tried setting this in your `response_calls.config` key?

https://scribe.readthedocs.io/en/latest/documenting/documenting-endpoint-responses.html#generating-responses-automatically-via-response-calls

**Comment by santiagazo** [comment]
Ah! I missed/misunderstood this part of the documentation. I created a `.env.docs` file and populated it with data just for my demo account. See below:

![scribe-env-docs-file](https://user-images.githubusercontent.com/15197623/114109543-b7216b80-9892-11eb-8739-16b45eaea902.jpg)

And here's the actual file (.env.docs) :
![env-docs-example-file](https://user-images.githubusercontent.com/15197623/114109741-1f704d00-9893-11eb-884b-4b0db824fd07.jpg)

It's the central database because when the request comes in from demo.suitelion.com it hits the central database, identifies the tenant based on the subdomain and then loads the correct tenant (demo) and changes the database automatically. This part appears to be working 100% correctly from my testing... it's just failing still because it's still calling from localhost instead of demo.suitelion.com (even with the `APP_URL` set to `demo.suitelion.com`). It seems the response calls are not using the app.url config value - neither in the config scribe file under `routes.apply.response_calls.config.app.url` nor in my `.env.docs` `APP_URL`.
See Below:
![still-failing-on-auto-response-calls](https://user-images.githubusercontent.com/15197623/114110140-0b791b00-9894-11eb-8b6a-3118d0ad003e.jpg)


That said - manually testing using the "Try it Out" button now works! 
![testing-works](https://user-images.githubusercontent.com/15197623/114110193-2c417080-9894-11eb-9754-2fa09ba838e0.jpg)

What am I missing? Maybe I'm still not putting the URL in the right place?

**Comment by shalvah** [comment]
Hmmm. Can you try adding some dump statements to verify the URL being called?

**Comment by santiagazo** [comment]
ok, after an hour or more of digging through code... I found it :) 

![responseCalls](https://user-images.githubusercontent.com/15197623/114443974-92c3d880-9b8b-11eb-84f7-e779a99c721c.jpg)

The dump was done in the ResponseCalls.php file, line 75 (dumping line 73).

Here is what was dumped:
```
Illuminate\Http\Request^ {#3226
  #json: null
  #convertedFiles: null
  #userResolver: null
  #routeResolver: null
  +attributes: Symfony\Component\HttpFoundation\ParameterBag^ {#3227
    #parameters: []
  }
  +request: Symfony\Component\HttpFoundation\ParameterBag^ {#3225
    #parameters: []
  }
  +query: Symfony\Component\HttpFoundation\InputBag^ {#3067
    #parameters: array:1 [
      "id" => 2
    ]
  }
  +server: Symfony\Component\HttpFoundation\ServerBag^ {#3230
    #parameters: array:19 [
      "SERVER_NAME" => "localhost"
      "SERVER_PORT" => 80
      "HTTP_HOST" => "localhost"
      "HTTP_USER_AGENT" => "Symfony"
      "HTTP_ACCEPT" => "application/json"
      "HTTP_ACCEPT_LANGUAGE" => "en-us,en;q=0.5"
      "HTTP_ACCEPT_CHARSET" => "ISO-8859-1,utf-8;q=0.7,*;q=0.7"
      "REMOTE_ADDR" => "127.0.0.1"
      "SCRIPT_NAME" => ""
      "SCRIPT_FILENAME" => ""
      "SERVER_PROTOCOL" => "HTTP/1.1"
      "REQUEST_TIME" => 1618252325
      "REQUEST_TIME_FLOAT" => 1618252325.8225
      "HTTP_AUTHORIZATION" => "Bearer 1|7CPIZOfRTh4UAFa2Ou1H4QM8rIehOG5uxf0efbuw"
      "CONTENT_TYPE" => "application/json"
      "PATH_INFO" => ""
      "REQUEST_METHOD" => "GET"
      "REQUEST_URI" => "/"
      "QUERY_STRING" => "id=2"
    ]
  }
  +files: Symfony\Component\HttpFoundation\FileBag^ {#3229
    #parameters: []
  }
  +cookies: Symfony\Component\HttpFoundation\InputBag^ {#3228
    #parameters: []
  }
  +headers: Symfony\Component\HttpFoundation\HeaderBag^ {#3231
    #headers: array:7 [
      "host" => array:1 [
        0 => "localhost"
      ]
      "user-agent" => array:1 [
        0 => "Symfony"
      ]
      "accept" => array:1 [
        0 => "application/json"
      ]
      "accept-language" => array:1 [
        0 => "en-us,en;q=0.5"
      ]
      "accept-charset" => array:1 [
        0 => "ISO-8859-1,utf-8;q=0.7,*;q=0.7"
      ]
      "authorization" => array:1 [
        0 => "Bearer 1|7CPIZOfRTh4UAFa2Ou1H4QM8rIehOG5uxf0efbuw"
      ]
      "content-type" => array:1 [
        0 => "application/json"
      ]
    ]
    #cacheControl: []
  }
  #content: "[]"
  #languages: null
  #charsets: null
  #encodings: null
  #acceptableContentTypes: null
  #pathInfo: null
  #requestUri: null
  #baseUrl: null
  #basePath: null
  #method: null
  #format: "json"
  #session: null
  #locale: null
  #defaultLocale: "en"
  -preferredFormat: null
  -isHostValid: true
  -isForwardedValid: true
  -isSafeContentPreferred: null
  pathInfo: "/"
  requestUri: "/"
  baseUrl: ""
  basePath: ""
  method: "GET"
}
```

That HTTP_HOST seems to be the problem - any ideas on what we'd need to do to change that to an actual URI (_demo.suitelion.com_) instead? I attempted hard coding it as the `$uri = 'https://demo.suitelion.com'.Utils::getUrlWithBoundParameters($route, $urlParams);` and a few other variations (including hardcoding the 'api' prefix in  - _https://demo.suitelion.com/api_) but even that doesn't seem to quite get it. It's hitting the domain and even triggering the correct tenant but then fails to connect to the right route or something. I keep getting a 404 NotFoundException. See below:

```
{
    "message": "",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
    "file": "\/var\/www\/suitelion.com\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/AbstractRouteCollection.php",
    "line": 43,
    "trace": [
        {
            "file": "\/var\/www\/suitelion.com\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/RouteCollection.php",
            "line": 162,
            "function": "handleMatchedRoute",
            "class": "Illuminate\\Routing\\AbstractRouteCollection",
            "type": "->"
        },
        {
            "file": "\/var\/www\/suitelion.com\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
            "line": 647,
            "function": "match",
            "class": "Illuminate\\Routing\\RouteCollection",
            "type": "->"
        },
        {
            "file": "\/var\/www\/suitelion.com\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
            "line": 636,
            "function": "findRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "\/var\/www\/suitelion.com\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
            "line": 625,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "\/var\/www\/suitelion.com\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php",
            "line": 166,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        }....
```

**Comment by santiagazo** [comment]
OK! Good news, I played around with it more and by replacing line 122 in ResponseCalls.php with:
`$uri = 'https://demo.suitelion.com/'.Utils::getUrlWithBoundParameters($route, $urlParams);`

I was able to get it to pull the correct data. I might have had this right before, but I had failed to list correctly formatted `@urlParam`s so they weren't rendering correctly. Is there way we can make a variable in the scribe.php file or extend the `$base_url` to this file with a toggle to use the `$base_url` as the "response_call_url" or just make a `$response_call_url` variable and add it to the scribe.php file - lastly maybe we use the `app.url` from the `apply.config array`? I think your original thought that the `app.url` should already be affecting this area of the code would be great. 

Please let me know if you believe this is a viable solution for this problem.

**Comment by shalvah** [comment]
Hmmm...I mean, if that works for you, sure. I'll need to make some time to investigate it later.

**Comment by santiagazo** [comment]
Yeah, it works perfectly. It seems this would be the appropriate code to add to the file:

ResponseCalls.php
Line 122
```
$app_url = isset($rulesToApply['config']) && isset($rulesToApply['config']['app.url']) ? $rulesToApply['config']['app.url'] : null;
$uri = $app_url.Utils::getUrlWithBoundParameters($route, $urlParams);
```

This doesn't handle if they put the URL in an env file (like .env.docs). I wasn't sure how you're loading that info and couldn't find any code that is loading from that file in ResponseCalls.php

**Comment by shalvah** [comment]
> This doesn't handle if they put the URL in an env file (like .env.docs). I wasn't sure how you're loading that info and couldn't find any code that is loading from that file

It's loaded by Laravel. When you run any artisan command with `--env xxx`, it loads the `.env.xxx` file.

**Comment by santiagazo** [comment]
RIGHT! When I was debugging everything I didn't add my `--env docs` argument on there and thus didn't see the loaded env file. 
:facepalm: :facepalm: :facepalm:

So I would amend the code above like so:

```
$app_url = null;
if(isset($rulesToApply['config']) && isset($rulesToApply['config']['app.url'])){
    $app_url = $rulesToApply['config']['app.url'].'/';
}elseif(isset($rulesToApply['config']) && isset($rulesToApply['config']['app.env']) && !empty(env('APP_URL')){
    $app_url = env('APP_URL').'/';
}
        
$uri = $app_url.Utils::getUrlWithBoundParameters($route, $urlParams);
```

Do you feel the if statement should set priority to the .env.docs file or to any lines in the scribe.php file first? I lean more towards the scribe.php file because it's more in-your-face explicit. If they're specifying a .env.docs file they shouldn't be adding an `app.url` to the `config` array also. But if they do, I would want the scribe file to take precedence personally. To me scribe.php should be the end-all-be-all config file, superseding any env files.

**Comment by santiagazo** [comment]
Thanks for your time and attention.

**Comment by santiagazo** [comment]
> That HTTP_HOST seems to be the problem - any ideas on what we'd need to do to change that to an actual URI (_demo.suitelion.com_) instead? I attempted hard coding it in the `prepareRequest` method as the `$uri = 'https://demo.suitelion.com'.Utils::getUrlWithBoundParameters($route, $urlParams);` 

Just wanted to point out, in some of my initial tests I had tried hard coding the URL in and it didn't work. Closer examination shows why - I didn't place a `/` between the end of the URL and the `Utils::getUrlWithBoundParameters($route, $urlParams);` so it created an improper URL. I added it however to the end of my URLs in the if statements as it shouldn't be written in to an `APP_URL` normally.

**Comment by shalvah** [comment]
I think, by default in v3, the current `config('app.url')` in use will be used as the domain for response calls. Then the `scribe.app.url` will be used as the display URL in the docs.

**Comment by santiagazo** [comment]
If I'm understanding you correctly, we are in agreement. Thanks for the incredible package. 

All the best,
Jay
