### ISSUE TITLE
Incorrect examples generated for array of files

### ISSUE THREAD

**Issue by dnwjn** [knuckleswtf/scribe#200]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
I have some file fields that allow multiple files. I have set up validation rules using FormRequest files. One of the file rules is configured as follows:

```
'imagery' => ['nullable', 'array'],
'imagery.*' => ['file', 'mimes:png,jpg,jpeg'],
```

However, when generating the docs, examples for this field are generated in the following way:

```
"imagery[]=ex"
```

I've tried configuring this rule in a different way:

```
'imagery.*' => ['nullable', 'file', 'mimes:png,jpg,jpeg'],
```

But then no example is generated at all.

**My environment:**
 - PHP version (from `php -v`): 7.4.16
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 8.37.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 2.6.0

**Comment by shalvah** [comment]
I'll take a look at this.

**Comment by shalvah** [comment]
This seems to be working on v3. I get

![image](https://user-images.githubusercontent.com/14361073/119488923-ffb5bb00-bd52-11eb-8afb-33526939326f.png)


Seems like I might have fixed the bug somewhere along the way.😀 v3 will be released next month.
