### ISSUE TITLE
Grouping of endpoints

### ISSUE THREAD

**Issue by borcherds-ralph** [knuckleswtf/scribe#201]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.
We are wanting to group our endpoints using a hierarchical format.
Something like this
CRUD
    all crud related endpoints with each class group by another category
Workflow
      All endpoints that relate to workflow processes group by another category

Something like using @group CRUD/Users to get the top level and second level category or 
@group CRUD
@subgroup Users

Anything like this possible?

**Comment by shalvah** [comment]
Nope, subgroups are not supported. It'll be a bit more complexity than I'm ready to deal with now. If you really want them, you can send in a PR after v3 is released in a few months, and then we'll talk about it.
