### ISSUE TITLE
Generating multiple HTML files for dispaly

### ISSUE THREAD

**Issue by borcherds-ralph** [knuckleswtf/scribe#205]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

Is there a way to tell scribe to generate different HTML files for each of the group end points? The one HTML file it generates for us is over 2 MB in size and we know it will grow as we build out the features of the application we are working on.

**Comment by shalvah** [comment]
Err, no, that isn't supported now (and probably not in the near future). I've thought about it, but the only way I could see would just increase the complexity for everyone. v3 is coming out soon with some changes to the theming/output system, and that might make it easier, but we'll see.
