### ISSUE TITLE
Call to undefined method Laravel\Lumen\Routing\Router::namespace();

### ISSUE THREAD

**Issue by mkamranmalik72** [knuckleswtf/scribe#206]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. I set my configuration documentation output type='laravel'
2. Then I ran `php artisan scribe:generate` 
3. But I saw Call to undefined method Laravel\Lumen\Routing\Router::namespace();

instead of success

I debug code and find solution 
you are using laravel type route registrations in this file vendor\knuckleswtf\scribe\routes\laravel.php as

`Route::namespace('\Knuckles\Scribe\Http')
    ->middleware($middleware)
    ->group(function () use ($prefix) {
        Route::get($prefix, 'Controller@webpage')->name('scribe');
        Route::get("$prefix.postman", 'Controller@postman')->name('scribe.postman');
        Route::get("$prefix.openapi", 'Controller@openapi')->name('scribe.openapi');
    });` 

    in lumen namespace not using like this so I replaced above with

    `$router = app()->router;
$router->group(['namespace' => '\Knuckles\Scribe\Http'], function() use ($router, $prefix) {
    $router->get($prefix, ['as' => 'scribe', 'uses' => 'Controller@webpage']);
    $router->get("$prefix.postman", ['as' => 'scribe.postman', 'uses' => 'Controller@postman']);
    $router->get("$prefix.openapi", ['as' => 'scribe.openapi', 'uses' => 'Controller@openapi']);
});` 

and now it worked so please update your code which will work for both laravel and lumen thanks.
**Screenshots and stack traces:**
![image](https://user-images.githubusercontent.com/27995556/116764801-bcaa4580-aa3b-11eb-83bb-b1c5885e9f07.png)

**My environment:**
 - PHP version 7.4: 
 - Framework Lumen:
 - Laravel/Lumen version 6.0: 
 - Scribe version v2:

**Comment by shalvah** [comment]
Thanks👍

**Comment by shalvah** [comment]
Fixed in v3 and v2.7.9
