### ISSUE TITLE
document alway send request to localhost while host ip http://13.229.104.89/

### ISSUE THREAD

**Issue by duong120798** [knuckleswtf/scribe#209]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.
- [ ] document alway send request to localhost while host ip http://13.229.104.89/
![image](https://user-images.githubusercontent.com/44045389/117291337-0f9b5700-ae99-11eb-80b5-c0137714d697.png)

**Comment by duong120798** [comment]
![image](https://user-images.githubusercontent.com/44045389/117291828-abc55e00-ae99-11eb-9f69-f4b99cd5bc76.png)

**Comment by HungThinh0710** [comment]
@duong120798 Make sure `APP_URL` in your `.env` is `http://13.229.104.89`.
Example: `APP_URL=http://13.229.104.89`
Then go to the root of your application in server and run: `php artisan scribe:generate --force`
If it's still not effect, try clear cache, restart PHP, Nginx/Apache Server.

**Comment by shalvah** [comment]
Yes, @HungThinh0710 is right. The `APP_URL` is what's used.

What value is used in the examples? @duong120798

**Comment by fcolecumberri** [comment]
Same problem here, we have already set our `APP_URL` and the `base_url` on the `config/scribe.php`to point to the correct url, but still is getting sent to `localhost:8000`

**Comment by shalvah** [comment]
Also: in v3 (releasing in a week or two), you'll be able to specify the URL for the Try It Out feature.

That way, you can have a different URL displayed in the docs and a different one where the requests actually go to.

**Comment by shalvah** [comment]
🎉[v3 is out now](https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3)! Try it out and see if the changes work for you.
