### ISSUE TITLE
How to describe endpoints provided by vendor package?

### ISSUE THREAD

**Issue by mortenscheel** [knuckleswtf/scribe#21]
Is it possible to customize the description of endpoints provided by a third party package?

I would like to add my own metadata to routes provided by packages such as `laravel/passport` or `laravel/sanctum`, without editing the actual files in the `vendor/` folder.

**Comment by shalvah** [comment]
No, there isn't a direct way. Right now your best bet is editing the generated Markdown file containing those routes. To make things easier, you should make sure all your routes have an `@group` set, so only the vendor ones end up in the default group Markdown file. How's that?

We're open to considering ways to add.improve this functionality, so any suggestions are welcome.

**Comment by Chris-Pratt-Clystnet** [comment]
This is best handled by the package developers rather then scribe.

For example with Passport I have not implemented there default routes and instead created a class to extend there AccessTokenController that overrides the issueToken function. This then allowed me to add the doc block required for scribe and then I created the routes I needed myself.

```php
/**
 * Class AccessTokenController
 *
 * @group Auth
 *
 * APIs for accessing the access tokens
 */
class AccessTokenController extends \Laravel\Passport\Http\Controllers\AccessTokenController
{
    /**
     * Issue Token
     *
     * Issue Oauth Token
     *
     * @param ServerRequestInterface $request
     * @return \Illuminate\Http\Response
     * @bodyParam grant_type string required Grant Type. Example client_credentials
     * @bodyParam client_id string required Client ID
     * @bodyParam client_secret string required Client Secret
     * @bodyParam refresh_token string Refresh Token
     * @bodyParam redirect_uri string Redirect URI
     * @bodyParam code string Code
     * @bodyParam scope string Scope
     *
     * @response {
     *   "token_type": "Bearer",
     *   "expires_in": 1,
     *   "access_token": "token"
     * }
     */
    public function issueToken(ServerRequestInterface $request)
    {
        return parent::issueToken($request);
    }
}
```

```php
Route::post('/token', [
    'uses' => 'App\Http\Controllers\API\Auth\AccessTokenController@issueToken',
    'as' => 'passport.token',
    'middleware' => 'throttle',
]);
```

Unfortunately not all packages give this level of control so if you come across a package that doesn't I would suggest talking to the developer of that package to see what they can do.

**Comment by ajcastro** [comment]
maybe create a fork of the package, and add docblocks there..  and iirc in composer json, I think you can alias the package into your fork

**Comment by shalvah** [comment]
The best approach I can think of for this:

- Generate your docs as normal. Make sure the vendor routes are captured by the `prefixes` setting
- Make sure all your routes are tagged with an `@group`. This means only the vendor endpoints will be untagged and go into the `resources/docs/groups/endpoints.md` file. 
- You can then copy the contents of that file into a file of your choice and edit as you please. Then include that file in the YAML section of `resources/docs/index.md`. 
- You can then exclude the vendor endpoints in your config and generate docs again. The new docs will be combined with the old.

**Comment by shalvah** [comment]
See the RFC that would help with this: #105

**Comment by shalvah** [comment]
With this, you could add a vendor endpoint by simply copying any of the endpoints in the YAMl files and editing it. No need to mess with Markdown.

**Comment by shalvah** [comment]
Update: This is done in v3. You'll be able to add extra endpoints.

How it works: Scribe generates an intermediate YAML file that you can modify, and your changes will be preserved as much as possible. It's in a simple format, so you can easily add more endpoints or edit existing ones.

**Comment by shalvah** [comment]
🎉[v3 is out now](https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3), and you can add endpoints not in your code!
