### ISSUE TITLE
FormRequests rules that are from queryParam treated like bodyParam

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#210]
Hi, once again thanks for your great software.

I am using an endpoint that uses queryParam, this endpoint was a laravel FormRequests to validate the data.

`* @queryParam filter string Parameter can have one of two values: <b>{ all | web }</b>. Defaults to 'all'. Example: web`

So, when I generate the docs, two params appear...the correct one and now the bodyParam, is there any flag to ignore get data from FormRequest for this endpoint?

![2021-05-08_17-06](https://user-images.githubusercontent.com/17271768/117545996-1f917300-b020-11eb-9f12-3b8c4abde938.png)

I want only the queryParam information.

As a temporary solution, in scribe.php config file, I comment the :

```

        'bodyParameters' => [
            // \Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromFormRequest::class,
            // \Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromBodyParamTag::class,
        ],
```

**Comment by pirex360** [comment]
Yes, you are right.

**Comment by shalvah** [comment]
> No need to comment out both strategies, only the GetFromFormRequest, but still, this doesn't solve the actual problem.
> 

What's the problem that it doesn't solve?🤔 Comment out FormRequests if you aren't using it in `bodyParameters`. Or you can move it to `queryParameters` if you want to use it for that.

**Comment by hadjistasi** [comment]
> I'm confused. If you're using the form request for your query parameters, then put it in the `query Parameters` section, then put `GetFromQueryParamTag` after it, so the docblock can overwrite it. Do you mean if you're mixing both query and body parameters in one form request?

Some requests have body parameters, some others query parameters. All types of requests go through FormRequest validation. Thus, the only "elegant" way of dealing with this is having a default way of translating those variables (as of right now all are translated to @bodyParams) but also have the power to overwrite some to @queryParams.

**Comment by shalvah** [comment]
Oh, I see. That's a pain, but I can't think of an elegant solution for that right now. `@overwrite` feels clunky to me.

**Comment by pirex360** [comment]
Also, we need some @endParameters tag, because in some query or other parameters with an example, if we put a piece of HTML after to describe some context... it thinks that's related to the example parameter and put all the HTML in the example.
I can think in some sort of tag to enable after parameter some additional text before writing the @response. If we use No-example, this behavior doesn't occour.

**Comment by shalvah** [comment]
That...will probably not happen. The "Example: " needs to be at the end of the parameter description. Anything that comes after it is, by definition, part of the example.

If you want to add extra context, write it _before_ you start describing parameters. If it relates to a specific parameter, just put it in the description and put the example at the end.

**Comment by ErnestStaug** [comment]
Just noticed this issue too. All of my get request uses query params ant post/put request uses body params as REST API should do. Would like to disable body params at all on GET requests...

**Comment by ErnestStaug** [comment]
As well example request of languages (php/js/python) should include query params examples too, so far just bash has it.

**Comment by shalvah** [comment]
It's complicated.🤷‍♀️ 

I personally hate when frameworks allow you to treat query and body params interchangeably, because it leads to situations like these. Is there any internal identifier in your code that can be used to distinguish when a FormRequest is for query or body params? Or are they written exactly the same, and Laravel just checks if there's a query or body parameter matching the name?

**Comment by ErnestStaug** [comment]
Correct me if I am wrong. I think it's laravel specific thing as HTTP "get" requests validation only applies to query, body is discarded. 

As well as I understand GET requests are meant to query data, so thats why you have query params, you not sending data you querying. Which makes sense to me. Never seen api's who have body params on GET requests.

**Comment by shalvah** [comment]
I have😅. Elasticsearch's GET API takes a body, but I agree yes a rare case.

Either way, my question is more about for endpoints that have both body and query parameters. It's easier to deal with only GETs.

**Comment by ErnestStaug** [comment]
I understand, but could we at least disable body params on GET? As it goes
against standards and now I have manualy delete generated content.

**Comment by shalvah** [comment]
So, from v3:
1. `bodyParameters` stage will be skipped for GET requests
2. If you wish to use a form request for query parameters, you'll need to do two things:
  - add `GetFromFormRequest` to `queryParameters` in your config. This tells Scribe that you also use form requests for query parameters
  - mark the FormRequest as `@useAsQueryParams` (or add a `queryParameters()` method to it instead of [`bodyParameters()`](https://scribe.readthedocs.io/en/latest/documenting/documenting-endpoint-body-parameters.html#using-formrequests)). This lets Scribe know that this form request applies to query parameters.

How's that?

I'm currently focused on v3, so I can't say when I'll be able to backport these changes to v2. PRs are welcome.

**Comment by shalvah** [comment]
On second thought, there will be a new QueryParameters\GetFromFormRequest class included in v3 config, so you'll only need to do the second part—add the annotation to your FormRequest class.

**Comment by shalvah** [comment]
Oh, I forgot to mention—v3 is out now with support for this. 

release post - https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3

query params + validation rules - https://scribe.knuckles.wtf/laravel/documenting/query-body-parameters#using-validation-rules-for-query-parameters
