### ISSUE TITLE
Required array of objects example generated twice

### ISSUE THREAD

**Issue by KDSaltyPony** [knuckleswtf/scribe#211]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**My environment**
I'm working on a Lumen 8 API with a type of documentation output set to "laravel" and routes made on my own :
```php
$prefix = config('scribe.laravel.docs_url', '/docs');
$middleware = config('scribe.laravel.middleware', []);

$router->group(
    [
        'namespace'  => '\Knuckles\Scribe\Http',
        'middleware' => $middleware
    ],
    function () use ($router, $prefix) {
        $router->get($prefix, [
            'as'   => 'scribe',
            'uses' => 'Controller@webpage'
        ]);
        $router->get("{$prefix}/postman", [
            'as'   => 'scribe.postman',
            'uses' => 'Controller@postman'
        ]);
        $router->get("{$prefix}/openapi", [
            'as'   => 'scribe.openapi',
            'uses' => 'Controller@openapi'
        ]);
    }
);
```

I also added the following helpers methods to allow assets calls in blade :
```php
if (!function_exists('urlGenerator')) {
    function urlGenerator() {
        return new \Laravel\Lumen\Routing\UrlGenerator(app());
    }
}

if (!function_exists('asset')) {
    function asset($path, $secured = false) {
        return urlGenerator()->asset($path, $secured);
    }
}
```

Outside of this, there is nothing pecular with my config.

**What happened?**
I have the following enpoint input description :
```php
    /**
     * [...]
     * @bodyParam parametres object[] required Les paramètres de l'entité.
     * @bodyParam parametres[].uid string required Un identifiant de paramétrage unique existant. Example: id_unique_universel2
     * @bodyParam parametres[].valeur string requiredLa valeur à associer au paramétrage de l'entité. Example: whatever2
     * [...]
     */
```

So in the right panel of my documentation, I'm expecting something like that :
- Javascript :
```javascript
let body = {
    "parametres": [
        {
            "uid": "id_unique_universel2",
            "valeur": "whatever2"
        }
    ]
}
```
- Bash :
```bash
    -d '{"parametres":[{"uid":"id_unique_universel2","valeur":"whatever2"}]}'
```
- PHP
```php
        'json' => [
            'parametres' => [
                [
                    'uid' => 'id_unique_universel2',
                    'valeur' => 'whatever2',
                ]
            ],
        ],
```

But here is what I got :
```javascript
let body = {
    "parametres": [
        {
            "uid": "id_unique_universel2",
            "valeur": "whatever2"
        },
        {
            "uid": "id_unique_universel2"
        }
    ]
}
```
- Bash :
```bash
    -d '{"parametres":[{"uid":"id_unique_universel2","valeur":"whatever2"},{"uid":"id_unique_universel2"}]}'
```
- PHP
```php
        'json' => [
            'parametres' => [
                [
                    'uid' => 'id_unique_universel2',
                    'valeur' => 'whatever2',
                ],
                [
                    'uid' => 'id_unique_universel2',
                ],
            ],
        ],
```

I've tried to remove generated files and redo a ```php artisan scribe:generate``` but nothing to  do about it.

**Comment by shalvah** [comment]
That's by design. For an array, Scribe tries to generate two items (the rationale is so that it's more obvious to the end user that this is an array and can have multiple items). Since `valeur` is not marked as `"required"`, the second item doesn't include it.

**Comment by KDSaltyPony** [comment]
Thanks for the quick answer !
OK, is there a way to design the second item ? Having twice the same UID when one of the constraint is for it to be unique looks a bit weird...

**Comment by shalvah** [comment]
Unfortunately, I don't think so. But you could try adding an example at the top-level too.

    /**
     * [...]
     * @bodyParam parametres object[] required Les paramètres de l'entité. Example: [{"uid": "...", "valeur": ""}]
     * @bodyParam parametres[].uid string required Un identifiant de paramétrage unique existant. Example: id_unique_universel2
     * @bodyParam parametres[].valeur string requiredLa valeur à associer au paramétrage de l'entité. Example: whatever2
     * [...]
     */

**Comment by KDSaltyPony** [comment]
OK, thanks a lot !
