### ISSUE TITLE
Advanced Form Request rules crash the documentation 

### ISSUE THREAD

**Issue by andronikigr** [knuckleswtf/scribe#212]
Hello! Thanks for the amazing material!

I want to ask if is there any way to overcome some obstacles:
I have written some advanced rules in an UpdateSomehtingRequest for nested objects.

I also have registered some custom validation rules.

One rule is something like this:

'data.*.results'            => ['required', 'array', ['results.requiredGroupIds', $this->thing]],

So in this rule, scribe crashes out. 
I want to ask if is there a way to get around that manually.
I tried to specify the bodyparameter for that rule but I get the same error:

🚫 error ErrorException in /var/www/html/vendor/knuckleswtf/scribe/src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php at line 408: strpos() expects parameter 1 to be string, array given.

The thing is that we have many custom rules! 
So we will be more than thankful if is there a solution!

**Comment by andronikigr** [comment]
@shalvah 
Thank you for your response!
This is something that we've used many times and it has worked fine!
It is an alternative way when you want to pass something that is not scalar variable.

But we have this exception while trying to generate documentation through scribe, 
so I ask  if there is any solution to avoid the problem in some way.

Thanks a lot in advance!

**Comment by shalvah** [comment]
Obviously, this is a bug in Scribe that should be fixed. At worst, the extra rules should be ignored. Just need to be sure that that is valid Laravel syntax. I'm not aware of array rules. Any links?

**Comment by shalvah** [comment]
I'll just add a defensive check that checks the type of the valuation rule first. I'm busy now, so you can send in a PR for that; it's easy.

Just add an if-condition to this foreach https://github.com/knuckleswtf/scribe/blob/cf9d9765ac4fd48e4bc02d18df22411ca2cee1de/src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php#L197 that does a `continue` if the type of `$rule` is not string or `Rule` object.

**Comment by andronikigr** [comment]
@shalvah 
Thanks again!

I've sent a PR , as you asked:
https://github.com/knuckleswtf/scribe/pull/219

**Comment by WesleyGoncalves** [comment]
> Obviously, this is a bug in Scribe that should be fixed. At worst, the extra rules should be ignored. Just need to be sure that that is valid Laravel syntax. I'm not aware of array rules. Any links?

It can be found on the following section of the documentation [Validating Arrays](https://laravel.com/docs/8.x/validation#validating-arrays)

**Comment by shalvah** [comment]
Should be fixed in 2.7.7 (and in v3, [which is out](https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3))
