### ISSUE TITLE
Arrow from object/array is not display in Parameters

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#213]
When we describe our parameters, objects and arrays don't have the black arrow indicate to click on the parameter and expand/collapse for digging inside the object/array.

![2021-05-20_11-45](https://user-images.githubusercontent.com/17271768/118966088-42495300-b961-11eb-9fe8-45571ff3f7e7.png)

**Comment by shalvah** [comment]
Hmm. Was it there before?

Please include details about your environment. Scribe version? Browser and operating system?

**Comment by pirex360** [comment]
Hi, never seen the arrow.

Scribe "knuckleswtf/scribe": "^2.6.0",
Browser: Chrome | Opera | Firefox ...
Operation System: PopOS

**Comment by shalvah** [comment]
Oh thanks. Just noticed this too. Not sure if I broke something in a recent update, or Chrome changed some display behaviour. I'll take a look.

**Comment by shalvah** [comment]
Hey, have you tried updating? Does this still happen?

**Comment by pirex360** [comment]
Yes, sorry for the delay (vacations) ...I just updated it...all work fine now. 

Thanks for all the hard work.
