### ISSUE TITLE
Config key mismatch in laravel routes

### ISSUE THREAD

**Issue by ncatanchin** [knuckleswtf/scribe#22]
The route configuration is looking for config key `scribe.laravel.docs_url` 

https://github.com/knuckleswtf/scribe/blob/d8a1e1713bbf10295063d47981566f2df746d5bb/routes/laravel.php#L5

However, the default configuration file defines it as `scribe.laravel.url`

https://github.com/knuckleswtf/scribe/blob/d8a1e1713bbf10295063d47981566f2df746d5bb/config/scribe.php#L36

I did not submit a PR as unsure of which option you would prefer to go ahead with!

---

Thanks for all the hard work on the new package! :) After some initial hurdles, I just got my docs building this morning and ❤️ the design improvements. Jumping in to take advantage of the feature enhancements now. 🥳

**Comment by shalvah** [comment]
Nice catch, thanks! Should be `docs_url`, so it's explicit. Sure, you can send in a PR.

> After some initial hurdles

Anything that should be in the migration guide? Feel free to mention or send in a PR.

**Comment by ncatanchin** [comment]
PR linked above, thanks @shalvah 

Regarding hurdles - I think most were self-imposed, I've made some substantial changes to strategies and linked classes, most of which I should be able to get rid of now. 

Overall, migrating has been very smooth, I started a few weeks ago where it was perhaps not quite ready. I'll let you know any other feedback, and perhaps some suggestions or PRs to come.
