### ISSUE TITLE
Is there a way to ignore a bodyParameter when generating responses?

### ISSUE THREAD

**Issue by carestad** [knuckleswtf/scribe#222]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

I have certain endpoints where it would just be easier if I could tell Scribe to ignore a body parameter when it tries to generate a response, but I have not found a way to do this with `bodyParameters()` or docblocks. What if `bodyParameters()` could support a `'ignore' => true` or something?

Something like this:

```php
public function bodyParameters()
{
	return [
		'ignoreMe' => ['ignored' => true],
	];
}
```

And perhaps docblock support would be good as well, something like:

```php
/**
  * @bodyParam ignoreMe ignored=true
  */
public function updateSomething()
{}
```

**Comment by shalvah** [comment]
Did you try using `No-example`?

**Comment by carestad** [comment]
> Did you try using `No-example`?

Does it work for body parameters too, or just URL parameters?

**Comment by shalvah** [comment]
It works for all parameters. It's in the docs. Did you try it?

**Comment by carestad** [comment]
> It works for all parameters. It's in the docs. Did you try it?

Yes, it did work. Not sure how I missed it and only thought it would work for `@urlParam` :roll_eyes: 

Thanks!

**Comment by Nicolas-Mousten-WeCode** [comment]
Have i misunderstood how it works? Like above i don't want to have the body parameters but this code dosen't seem to work:

 /**
     * @bodyParam uuid int This won't be added to the examples. No-example
     * @bodyParam status String This won't be added to the examples. No-example
**/
