### ISSUE TITLE
Nullable responseField

### ISSUE THREAD

**Issue by rogier-dev** [knuckleswtf/scribe#226]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

I have some laravel resources which return a string or null.

Ive read the docs but cant seem to find if I can change the @responseField type string to string|null or ?string for example. How do you guys deal with this?

Extended the class for checking types and added ?string and string|null so its working now but im wondering how you guys handle use cases such as this.

Kind regards,

Rogier

**Comment by shalvah** [comment]
Hmm... We don't really support that right now. Did you try just including the type? `@responseField fieldName ?type Description`? That didn't work?

**Comment by rogier-dev** [comment]
I did but it does not show up as a type value but as comment.

Anyway it can be closed as Ive changed all my return resources to empty strings etc.

**Comment by shalvah** [comment]
Ah, yes. The `responseField` tag is currently fairly restrictive. You can try using the description to indicate that "This value may be empty". In a future version, we may add support for nullable types.

**Comment by shalvah** [comment]
Will release 3.1.0 later this week that allows you to write `?string` or `string|string[]`, if you like, and they'll be displayed as-is.
