### ISSUE TITLE
Call to a member function {functionName}() on null

### ISSUE THREAD

**Issue by williamxsp** [knuckleswtf/scribe#227]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. I have a custom User class, where Ive created a method called isAdmin to check if the current user is an Admin.
I use like this
```php
auth()->user()->isAdmin()
```
2. Then I ran `php artisan scribe:generate` ...
And get this error
```
 class CreateUserRequest extends FormRequest
      9▕ {
     10▕     public function rules()
     11▕     {
  ➜  12▕         if (auth()->user()->isAdmin()) {
...
```
3. But I saw...
Call to a member function isAdmin() on null
instead of...
generating the documentation

**Screenshots and stack traces:**

**My environment:**
 - PHP version (from `php -v`):  7.4.19
 - Framework (Laravel/Lumen):Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): v8.36.2
 - Scribe version (from `composer show knuckleswtf/scribe`): 2.7.6

**My Scribe config (minus the comments):**
Default. Its a fresh install.

**Additional info:**
I only got this error at a FormRequest Class. Works fine on a Controller.

**Comment by shalvah** [comment]
This happens because the FormRequest strategy does not evaluate your code in the context of a request. Basically, it does:

```php
$f = new FormRequest;
$rules = $f->rules();
```

So there's no authentication or user object set at the time.

Obviously, it shouldn't crash, but in the meantime, you can comment that line out.

**Comment by shalvah** [comment]
("That line" = the line in your FormRequest that calls the auth() method.)
