### ISSUE TITLE
support PHP 8

### ISSUE THREAD

**Issue by Ahmed4969** [knuckleswtf/scribe#229]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. I set my configuration to...
2. Then I ran `composer install`
instead of...
    - knuckleswtf/scribe[2.4.0, ..., 2.7.6] require fakerphp/faker ^1.9.1 -> satisfiable by fakerphp/faker[v1.9.1, ..., 1.15.x-dev (alias of dev-main)].

**Screenshots and stack traces:**

**My environment:**
 - PHP version 8: 
 - Framework (Laravel):
 - Laravel/8
 - Scribe version versions : * 2.7.3

**My Scribe config (minus the comments):**

**Additional info:**

**Comment by Ahmed4969** [comment]
@khuongvancong @nerijunior @MarkVaughn @MrMage

**Comment by shalvah** [comment]
Your problem isn't PHP 8. I'm not sure what your problem is, because you didn't post a complete bug report. But it looks like a minor issue which is not caused by this package. My guess is that you need to upgrade your fakerphp/faker version.

**Comment by Aqitaniya** [comment]
I have the same issue

**Comment by shalvah** [comment]
Guys.

> Root composer.json requires fzaninotto/faker ^1.9.1


That's your problem, not this package. You're using an abandoned package that does not support PHP 8. Switch to fakerphp/faker.
https://laravel-news.com/changes-coming-to-php-faker

**Comment by Aqitaniya** [comment]
That's helped. Thanks
