### ISSUE TITLE
<b>Warning</b>:  Missing boundary in multipart/form-data POST data in <b>Unknown</b> on line <b>0</b><br />

### ISSUE THREAD

**Issue by tahasethwala** [knuckleswtf/scribe#231]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. API uses the file input
2. Framework: Lumen

**Comment by shalvah** [comment]
Please post a complete issue report. I mean, you don't even say where this error message is reported. The least you can do after the maintainer's hard work is described your issues properly.
