### ISSUE TITLE
Can file input be tested on the docs?

### ISSUE THREAD

**Issue by tahasethwala** [knuckleswtf/scribe#232]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

I am working on a project, and an API's request has a parameter for type file. Can that be possible with scribe?

As, I am testing it I am getting an error:
![scribe-bug](https://user-images.githubusercontent.com/85347409/120799671-af153d80-c55c-11eb-9944-1d54b2f47403.PNG)

I understand that this is a warning message from the API saying that the Boundary is missing in the headers
Error: Missing boundary in multipart/form-data POST data

So, as the request of the API has the File input, it changes the content type to Form Data, but it is not sending the boundary with it.

Can this be fixed?

**Comment by shalvah** [comment]
It can be fixed, and it should be fixed, but when it _will_ be fixed is a different story...

There are a bunch of bugs reported on the Try It Out feature that I haven't been able to get to. After v3 is released in the next week or two, I'll make some time to tackle those bugs. But, in the meantime, anyone can send in a PR. The code is in tryitout.js and isn't _too_ complicated.
