### ISSUE TITLE
is there any way to place all scribe elements outside of controller

### ISSUE THREAD

**Issue by tameemahmad** [knuckleswtf/scribe#239]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

Writing annotation in controller make code very dirty is there any better approach to make a service  class or util to make code clean..?

**Comment by shalvah** [comment]
Yes, but.

Scribe uses strategies. A number of the default strategies make use of annotations on your controller method, but with some variations:
- For metadata, you can place them on the controller class instead.
- For body or query parameters, you can place them on a Form Request instead.
- For headers, you can place them in your config file instead.

If these aren't enough, you can write your own strategies that pull data from elsewhere. You don't even have to use annotations. See [the docs](https://scribe.knuckles.wtf/laravel/advanced/plugins). You could even just extend some of the default strategies and overwrite the relevant parts.

If that's still not acceptable, then Scribe might not be the tool for you. There are lots of other alternative approaches to generating API documentation.
