### ISSUE TITLE
Compatible with spatie/dto ^3

### ISSUE THREAD

**Issue by smadrom** [knuckleswtf/scribe#241]
Hello! Is it possible to implement compatibility with the ^3 version?

```
  Problem 1
    - knuckleswtf/scribe[3.0.0, ..., 3.0.2] require spatie/data-transfer-object ^2.6 -> found spatie/data-transfer-object[2.6.0, ..., v2.x-dev] but it conflicts with your root composer.json require (^3.3).
    - Root composer.json requires knuckleswtf/scribe ^3.0 -> satisfiable by knuckleswtf/scribe[3.0.0, 3.0.1, 3.0.2].

```

**Comment by shalvah** [comment]
Hmm, that would be a bit of work that I can't commit to any time soon, as I'm not on PHP 8. You can give it a shot, though.

**Comment by punyflash** [comment]
```
Problem 1
    - knuckleswtf/scribe[3.5.0, ..., 3.5.2] require spatie/data-transfer-object ^2.6 -> found spatie/data-transfer-object[2.6.0, ..., v2.x-dev] but the package is fixed to 
3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires knuckleswtf/scribe ^3.5 -> satisfiable by knuckleswtf/scribe[3.5.0, 3.5.1, 3.5.2].
```
Can this be fixed by updating package?

**Comment by shalvah** [comment]
No, our composer.json would need to be changed to use ^2.0|^3.0, but that is not a small task, because this package relies heavily on spatie/dto, and there may be breaking changes that affect us. Even worse, I don't currently have PHP 8, so I have no way of testing it locally. 

It would be nice if one of you made the attempt.

**Comment by shalvah** [comment]
This should be supported now in 3.7.0. Thanks @punyflash
