### ISSUE TITLE
Error when generating documentation: Public properties `value` not found on Knuckles\Camel\Output\Parameter

### ISSUE THREAD

**Issue by nlsnightmare** [knuckleswtf/scribe#246]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I set my configuration to the default configuration
2. Then I ran `php artisan scribe:generate`
3. But I saw the provided screenshot

The autogenerated documentation seems to kinda work still, althouth there are a few extra backticks in the end of the bash commands (screenshots bellow).  
Also, a few requests seem to return exceptions such as "invalid signature", or "xxx not found". These are not too much of a big deal however, since I can manually override them

**Screenshots and stack traces:**
![image](https://user-images.githubusercontent.com/19950169/122540668-864b7880-d031-11eb-9106-6840be79c72a.png)

![image](https://user-images.githubusercontent.com/19950169/122541040-e4785b80-d031-11eb-9240-8e607df2112b.png)

**My environment:**
 - PHP version (from `php -v`): PHP 8.0.6 (cli)
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 8.47.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.0.2

**My Scribe config (minus the comments):**

**Additional info:**

**Comment by shalvah** [comment]
Do you have any custom strategies? Seems like a case of old code (v2, 'value') instead of new (v3, 'example').

**Comment by nlsnightmare** [comment]
No, it it's a vanilla, freshly installed version. I have however modified a
few Laravel things, and some exceptions are thrown while generating the
documentation.

As a sidenote, after disabling postman and openapi generation it works fine
for me. I can of course keep providing feedback if you'd like to, but for
me the problem is solved, and I'd be ok with closing this issue.

Στις Παρ, 18 Ιουν 2021, 2:27 μ.μ. ο χρήστης Shalvah <
***@***.***> έγραψε:

**Comment by shalvah** [comment]
Thank you, that was helpful. If you can update to 3.1.0, it should be fixed now.

**Comment by nlsnightmare** [comment]
I  can indeed confirm that it works like a charm! Thanks a lot!
