### ISSUE TITLE
Hi! How to attach Middleware to document endpoint?

### ISSUE THREAD

**Issue by binotby** [knuckleswtf/scribe#248]
![image](https://user-images.githubusercontent.com/32414473/122654040-dbdb6e80-d172-11eb-815d-c886a651bb5f.png)

- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

**Comment by shalvah** [comment]
You'll need to add more details to your question. Not sure what you're asking.

Also, did you really search the documentation? Because [this](https://scribe.knuckles.wtf/laravel/reference/config#laravel) is the first search result for "middleware".
