### ISSUE TITLE
Input from PUT requests sent as multipart/form-data to Laravel backend is unavailable

### ISSUE THREAD

**Issue by urbsny** [knuckleswtf/scribe#250]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I'm using Laravel for the api backend.
2. I sent PUT request as multipart/form-data.
3. In the backend, the requested data will be empty.

**My environment:**
 - PHP version (from `php -v`): 8.0.3
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): v8.47.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.0.3

**My Scribe config (minus the comments):**

**Additional info:**
This problem is related to https://github.com/laravel/framework/issues/13457 .
The solution is to change the HTTP request from PUT to POST and set PUT as the "_method" attribute.
I can solve this problem with fixing `tryitout.js`.
But I'm not sure if it will work well with using Lumen.

I'm sorry for my poor English.

**Comment by shalvah** [comment]
Right. I see you've made a commit for this. Do you want to send in a PR?
