### ISSUE TITLE
Dynamic description or example data in Controllers

### ISSUE THREAD

**Issue by MrHaroldA** [knuckleswtf/scribe#252]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

We added a Scribe user to our database which has a set of generated example data. The autonumber ids are different per environment, so to prevent 404 responses in the API docs, it would be nice if the example data could be queried instead of a fixed value in the doc block.

In the request we are using the `bodyParameters()` method for dynamic/queried parameter example data, is there a equivalent for Controllers (@urlParam/@queryParam) available too?

**Comment by shalvah** [comment]
I don't really understand your question. COuld you add an example of what you mean?

**Comment by MrHaroldA** [comment]
Sure!

We seed our tables with data owned by the Scribe user. The id's are autonumbered, so depending on the environment (dev, test, staging, production) the id's will be different.

```
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $company = Company::where('name', getenv('SCRIBE_COMPANY_NAME'))->first();
        Product::factory()->count(100)->create(['company_id' => $company->getKey()]);
    }
}
```

The first inserted id will be different across installations, so with this (company) example:

```
    /**
     * Get company information
     *
     * @urlParam company required The id of the company Example: 494895689
     *
     * @param Company $company
     * @return Company
     */
    public function show(Company $company): Company
    {
        return $company->encodeIDs();
    }
```

... the `494895689` is valid for the test environment, but not for the other ones. On top of that, we also encode our IDs with Optimus, so 14 will be 494895689 on one environment, and 429049394 on an other environment.

To prevent 404 examples in the generated request responses, the id needs to be valid for the Scribe company/user.

I could do some trickery with a middleware to rewrite the id to always be valid for the Scribe company as well?

**Comment by shalvah** [comment]
You can override the data sent in response calls by using the `bodyParams` key in the config, under `response_calls`. Have you tried that? You could maybe specify the ID as an env then retrieve it in there.

**Comment by MrHaroldA** [comment]
I don't think the bodyParams in the config will suffice, but overriding `vendor/knuckleswtf/scribe/src/Extracting/Strategies/UrlParameters/GetFromLaravelAPI.php` with our own logic just might!

I'll try to test that within the coming week or so ...

**Comment by shalvah** [comment]
Oh, the issue is the URL parameter. Well, yes, you can create your own class that extends that and add it to the strategies in your config.
