### ISSUE TITLE
Is OpenApi "3.0.0" supported to generate ?

### ISSUE THREAD

**Issue by EddiePikulya** [knuckleswtf/scribe#259]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hey, im sorry, I haven't find the answer for that. Am I able to generate openapi version 3.0.0 ? Or only version 2.0.0 is supported?

**Comment by shalvah** [comment]
https://github.com/knuckleswtf/scribe/blob/8b9325270e728858973ac49ec6393e6be970129b/src/Writing/OpenAPISpecWriter.php#L21
