### ISSUE TITLE
Please support customizing the route key.

### ISSUE THREAD

**Issue by urbsny** [knuckleswtf/scribe#262]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I have the Eloquent model which [customized route key](https://laravel.com/docs/8.x/routing#customizing-the-default-key-name).
2. The model key type is integer and route key type is string.
3. But GetFromLaravelAPI::class only use key type.

**Screenshots and stack traces:**

**My environment:**
 - PHP version (from `php -v`): 8.0.3
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): v8.49.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.3.2

**Additional info:**
In my case, I changed GetFromLaravelAPI.php to the following and it worked fine.

https://github.com/knuckleswtf/scribe/blob/4b59fb99a770a479c1a16ddbaaab932f1f4b5912/src/Extracting/Strategies/UrlParameters/GetFromLaravelAPI.php#L69

```php
                    $typeName = $argumentInstance->getKeyName() === $argumentInstance->getRouteKeyName()
                        ? $argumentInstance->getKeyType() : 'string';
                    $type = $this->normalizeTypeName($typeName);
```

**Comment by shalvah** [comment]
Sure, send in a PR. But what does the route key method return for people who haven't defined it for their model?

**Comment by urbsny** [comment]
Thank you for your quick response. I'll send PR.

> what does the route key method return for people who haven't defined it for their model?

Base model return key name. So I don't think it will affect the people who haven't defined it.

https://github.com/laravel/framework/blob/6a3ddf21096b1801d9e7f221f72ae78d90eb3622/src/Illuminate/Database/Eloquent/Model.php#L1786

```php
    public function getRouteKeyName()
    {
        return $this->getKeyName();
    }
```

**Comment by shalvah** [comment]
Cool, should be easy to send in a PR then.
