### ISSUE TITLE
Rules 'numeric' from laravel's FormRequest's rules add '!!float' to openapi example

### ISSUE THREAD

**Issue by EddiePikulya** [knuckleswtf/scribe#264]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

**Comment by EddiePikulya** [comment]
Hi, if im using 'numeric' rule from laravel form request like - 
            `'orderId'    => 'required|numeric|digits_between:1,8',`
the generated openapi.yml will contain !!float string before example
`-
          in: query
          name: orderId
          description: 'Order ID. Must be between 1 and 8 digits.'
          example: !!float 12345678
          required: true
          schema:
            type: number
            description: 'Order ID. Must be between 1 and 8 digits.'
            example: !!float 12345678`

**Comment by shalvah** [comment]
That is valid YAML, even though I don't like it. Disabling that would be a bit complicated. Most YAML parsers should handle it fine. What's the problem?

**Comment by EddiePikulya** [comment]
thanks for clarification, no problem then
