### ISSUE TITLE
bodyParam in Requests

### ISSUE THREAD

**Issue by piotranon** [knuckleswtf/scribe#266]
Hi, 
Why there is no feature like loading additional info about body params from Requests?
Exactly to what is done in validators [example in validator](https://github.com/knuckleswtf/TheSideProjectAPI/blob/0b8dc1a8a61d59303ec35d6bbc8a17169393c13e/app/Http/Controllers/SideProjectController.php#L42) but allowing the same thing in requests.   

Example code in Request
```php
     /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            // Name of user. Example: John Doe
            'name' => 'required|string|min:3',
            // Email of user. Example: john@gmail.com
            'email' => 'required|email|unique:users,email'
        ];
     }
```

**Comment by shalvah** [comment]
Hmm, how did you come to that conclusion? 🤨https://scribe.knuckles.wtf/laravel/documenting/query-body-parameters#validation-rules

The issue template (which you deleted for some reason) asks you to first check the docs, and the docs literally mention FormRequests on the [home page](https://scribe.knuckles.wtf/laravel). Don't know how you missed that.

You could as well have done a quick search for it in the Issues tab, and see how many places it's referenced. There's even an open issue right there when you click on Issues.

Please do a little more research and don't cause maintainers extra stress.😕

**Comment by shalvah** [comment]
Oh, and on top of all that, there's an example of such, in the same codebase you referenced.

https://github.com/knuckleswtf/TheSideProjectAPI/blob/0b8dc1a8a61d59303ec35d6bbc8a17169393c13e/app/Http/Requests/CreateUserRequest.php#L25-L29

**Comment by shalvah** [comment]
Ohhh, I see you're talking about "additional information". Well, the comments approach is not supported in FormRequests, but the `bodyParameters()` method has been supported for long. The docs link I shared has an example.
