### ISSUE TITLE
How can I use schema references

### ISSUE THREAD

**Issue by nazar-linkup** [knuckleswtf/scribe#269]
Is there an option to have a single description of schema and use references to it on multiple endpoints description?

For example, if I have PostController with Show and Store actions and my action returns the same type of response as the PostResource. I user @apiResource and @apiResourceModel annotations, but in generated openapi.yaml responses described as a schema of type object separately for each route. But I need to have a single schema for Post response and those two routes just use references to it.

Thanks

**Comment by shalvah** [comment]
Nah, there isn't. That would introduce a lot more complexity internally, as we'd have to add extra logic to determine when two pieces of data are identical. The other alternative would be allowing you to specify a schema name, but that would still be a bunch of OAS-specific logic. Not worth it for me.
