### ISSUE TITLE
Is it possible to generate only openapi spec for laravel

### ISSUE THREAD

**Issue by EddiePikulya** [knuckleswtf/scribe#270]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hey, docs says 
`If you're using laravel type:
the Blade view will be at resources/views/scribe/index.blade.php
the CSS and JS assets will be in public/vendor/scribe
the Postman collection and OpenAPI spec will be in storage/app/scribe/.`

Is it possible to generate only openapi spec without blade view and css/js assets ?

**Comment by shalvah** [comment]
Err, no. Primary reason is that the main goal of this project is generating that docs webpage. If an OpenAPI spec is that important, I'd recommend doing spec-driven docs, where you build your API based on the spec. Otherwise, you can just delete the docs you don't want.
