### ISSUE TITLE
OpenAPI output

### ISSUE THREAD

**Issue by BartFijneman** [knuckleswtf/scribe#271]
Group descriptions are not added to the OpenAPI output. The 'tags' need to be included in the OpenAPI file.

**Comment by BartFijneman** [comment]
Some other enhancements for OpenAPI:
- The response status code should not be included in the response description
- Responses without content should not be included als 'String'

**Comment by shalvah** [comment]
> The response status code should not be included in the response description

Why?

**Comment by BartFijneman** [comment]
> > The response status code should not be included in the response description
> 
> Why?

The output responses for OpenAPI already contain the status code this way:
404:
  description: 'Not found'

Currently it's:
404:
  description: '404, Not found'

Readers will now show something like: '404 - 404, Not found' which is not clean.

**Comment by kressaty** [comment]
Can confirm that removing the redundant status code would be nice. For a visual example, putting the OpenAPI spec into Redoc generates a response item that looks like this: 

![image](https://user-images.githubusercontent.com/289165/128212718-39e4870d-546b-48ca-9118-ecd14f14e48e.png)

**Comment by shalvah** [comment]
> Responses without content should not be included als 'String'

I don't understand this. 204 responses are currently included without a `content`, as per the spec.

**Comment by shalvah** [comment]
Implemented the rest of the suggestions in 3.9.0 👍
