### ISSUE TITLE
Sorting of groups filename should be using natural sort

### ISSUE THREAD

**Issue by ajcastro** [knuckleswtf/scribe#273]
![image](https://user-images.githubusercontent.com/4918318/125398548-0c18d480-e3e2-11eb-9894-6298bf907002.png)

![image](https://user-images.githubusercontent.com/4918318/125398678-34083800-e3e2-11eb-8b6c-77f5c6ab3ac4.png)

I expect that the sorting is alphabetical. Then I checked the generated yaml files and it seems the sorting of filename is not using natural sort. 

The sorting should be 0,1,2,3...10 but it seems it was 0,1,10,2,3...9

**Comment by ajcastro** [comment]
I resolved it by adding `--force` option, running `php artisan scribe:generate --force`.

**Comment by ajcastro** [comment]
@shalvah maybe you need to increase the digits to hundreds or thousands just in case?

**Comment by shalvah** [comment]
I don't think it's likely that people will have 100 endpoint groups. I mean, at that point, Scribe is probably not for you, because it'll take you'll have a big-ass page, and it'll take quite a while to generate.
