### ISSUE TITLE
Download links for Postman and OpenApi do not use the output_path

### ISSUE THREAD

**Issue by ajcastro** [knuckleswtf/scribe#274]
![image](https://user-images.githubusercontent.com/4918318/125592404-f709bb92-86d8-40e7-a705-8ebd1e8c6d68.png)

I set the config `'output_path' => 'public/docs.next'` and the link for my docs is `docs.next`. 
But the download links is still using `docs` but it should be `docs.next`

I also tried setting `'docs_url' => '/docs.next'`  but still the same.

**Comment by shalvah** [comment]
Fixed in 3.6.1
