### ISSUE TITLE
CSP Nonce support

### ISSUE THREAD

**Issue by robtesch** [knuckleswtf/scribe#28]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

Is there any way we could introduce CSP nonce support? I'm specifically referring to the inline scripts in the head and at the end of body,

Of course for now i can simply add them to the generated index.blade.php file, but i have a feeling i will forget to do this at some point.

**Comment by shalvah** [comment]
I'm not very familiar with CSP nonces. But a simple fix that should work:
- create a prepend.md file in the docs Markdown output folder (resources/docs/) containing just the html you need:

```html
<head>
...
</head>
```

It's probably an extra head tag, but the browser should parse and handle it correctly.

You can use append.md to achieve similar functionality too.

https://scribe.readthedocs.io/en/latest/customization.html#specifying-content-to-be-added-to-the-beginning-or-end-of-the-documentation

**Comment by robtesch** [comment]
Many thanks @shalvah , unfortunetely that doesn't quite solve the issue, as the problem is the built in script tags. I don't need to add anything new really, i just have to change what's already there. 

The following two script tags:

```
<script>hljs.initHighlightingOnLoad();</script>
```
and
```
<script>
  $(function() {
    var languages = ["bash", "javascript"];
    setupLanguages(languages);
  });
</script>
```

Would change to something like the following:

```
<script nonce="{{ csp_nonce() }}">hljs.initHighlightingOnLoad();</script>
```
and
```
<script nonce="{{ csp_nonce() }}">
  $(function() {
    var languages = ["bash", "javascript"];
    setupLanguages(languages);
  });
</script>
```

**Comment by shalvah** [comment]
Ah, no easy way to achieve that. Your best bet is writing maybe a shell script to inject it into the generated Blade file.

**Comment by robtesch** [comment]
Understood. Many thanks for your help.
