### ISSUE TITLE
try it out not working

### ISSUE THREAD

**Issue by hooman-mirghasemi** [knuckleswtf/scribe#280]
Uncaught (in promise) ReferenceError: _ is not defined
    executeTryOut file:///home/hooman/dev/php/test/laravel/src/public/docs/js/tryitout-3.6.2.js:180
    executeTryOut file:///home/hooman/dev/php/test/laravel/src/public/docs/js/tryitout-3.6.2.js:180
    onsubmit file:///home/hooman/dev/php/test/laravel/src/public/docs/index.html#

when it set  @queryParam or @bodyParam try it out dont work and I see top error in console.

**Comment by shalvah** [comment]
That seems like a problem with your internet. Looks like the lodash script failed to download. You should investigate that some more.
