### ISSUE TITLE
Endpoints menu generated even with @group included

### ISSUE THREAD

**Issue by kisbovan** [knuckleswtf/scribe#283]
I have this issue I've been trying to solve for a while now and it's driving me crazy. I went through the documentation, which says that only those routes will be included in the "Endpoints" menu which do NOT have a @group tag. 

I have a class called AccessTokenController which extends Laravel's Passport AccessTokenController. I genuinely think that I have documented everything properly, but Scribe still generates the documentation from the parent 'issueToken' method, and not from my child method. 

Could anyone give me some pointers on how to fix this?

![Screenshot from 2021-07-21 10-58-32](https://user-images.githubusercontent.com/9549853/126461615-2e286dc1-bb7f-452f-95d9-eb0d2f1da693.png)

Only this is generated:
![Screenshot from 2021-07-21 11-00-33](https://user-images.githubusercontent.com/9549853/126461858-b30bf8e4-bdb1-463d-b72e-9dfe4a8e4189.png)

**Comment by shalvah** [comment]
It looks like Scribe is finding the passport controller, not your controller, as the handler for the route. How is the route defined?

**Comment by kisbovan** [comment]
I have the following defined in my routes/api.php file:

![Screenshot from 2021-07-21 11-05-53](https://user-images.githubusercontent.com/9549853/126462721-0613d9fb-4562-4a2a-90a8-730124213607.png)

**Comment by shalvah** [comment]
@kisbovan what was the solution?
