### ISSUE TITLE
Getting a Facade\Ignition\Exceptions\ViewException while migrating from v2 to v3

### ISSUE THREAD

**Issue by kisbovan** [knuckleswtf/scribe#286]
I am trying to migrate our docs from v2 to v3, however I am getting this error when running scribe:generate. I tried to put @hideFromAPIDocumentation to all my endpoints to debug it, then the command ran through fine (without generating a single endpoint documentation). Then I removed @hideFromAPIDocumentation from a single one, and I got the error again, meaning that I cannot generate documentation for a single endpoint. 

Does anyone know what's wrong?

![Screenshot from 2021-07-23 10-03-26](https://user-images.githubusercontent.com/9549853/126753741-7b6bf991-595f-4bcc-a7b1-5f9cb9f1a777.png)

**Comment by shalvah** [comment]
What was the cause?👀
