### ISSUE TITLE
Disable/enable "Try It Out" for specific endpoints

### ISSUE THREAD

**Issue by SquareBeard** [knuckleswtf/scribe#289]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I don't think there is an annotation to disable or enable the "Try It Out" feature for specific endpoints.
But is there a workaround ?
Is there any plan for this feature ?

Thank you

**Comment by shalvah** [comment]
No, no plans for that. Why do you want that feature? There's also no easy way to implement that without adding another config item or docblock tag, two things I wish to avoid.

Your best bet would be to write a custom JS script that removes the button from some endpoints and add that to your docs.

**Comment by SquareBeard** [comment]
We'd like to connect the documentation to the real data but disable that feature for destruction actions.
I did not think about doing it in JS, that might work, thank you.
