### ISSUE TITLE
How to join @apiResource and @responseFile?

### ISSUE THREAD

**Issue by Dimrak** [knuckleswtf/scribe#29]
Hi,
I would like to join both answers together in one unique example response, any suggestions on how to achieve this result?

Here screenshot on how it looks like, when generating a response from @responseFile .json and from factory with @apiResource

![example-response](https://user-images.githubusercontent.com/29204770/82991698-bed37b00-a006-11ea-8f24-70b79957f982.png)

Thanks for this great tool.

**Comment by shalvah** [comment]
Not sure what you mean. What's your desired output?

**Comment by Dimrak** [comment]
The desired output would be ;

Example response(200)

-json file data
-resource data

Without creating two - Example response(200)

**Comment by shalvah** [comment]
Why though? Are those two possible responses from the endpoint, or two parts of a single response?

**Comment by Dimrak** [comment]
They are part of a single JsonResponse which looks like this from the endpoint:

```
$data = [
            'success' => true,
            'message' => $message ?? 'Success',
            'data' => $resource
        ];
```

**Comment by shalvah** [comment]
Hmmm.. There isn't a direct way to do that. You can merge a response file with custom JSON, but there are no plans to add this particular functionality to Scribe. But you can write a strategy to do this!

Some pointers:
- Extend the default ApiResource strategy
- Figure out how to throw in the response file there. I'd recommend adding it as an attribute (see [this line](https://github.com/knuckleswtf/scribe/blob/master/src/Extracting/Strategies/Responses/UseApiResourceTags.php#L150)), which means you'll be able to write something like `@apiResourceModel YourResource mergeFile=your/file`.
- Then write the code to fetch the file contents and merge the responses. You can see how it's done in `@responseFile` [here](https://github.com/knuckleswtf/scribe/blob/master/src/Extracting/Strategies/Responses/UseResponseFileTag.php#L68).  Cheers.
