### ISSUE TITLE
Image validation causes docs generation to fail

### ISSUE THREAD

**Issue by duncan-c** [knuckleswtf/scribe#290]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. One of my routes uses image validation (https://laravel.com/docs/8.x/validation#rule-image)
   `'uploadFile' => 'nullable|image|mimes:jpeg|max:2048'`
2. Then I ran `php artisan scribe:generate` ...
3. But I saw the following error:
   `Object of class stdClass could not be converted to string`

It generates the `.scribe` files, but then fails to generate the static docs. It appears to be this code which is causing the problem `<?php echo "$key=".$actualValue; ?>`, where `$actualValue` should be a string, but is actually a stdClass. This is in the bash request example generation, for the `--form` parameter contents.

**My environment:**
 - PHP version (from `php -v`): 7.4.13
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`):  8.49
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.3.1

**My Scribe config (minus the comments):**

```
<?php

use Knuckles\Scribe\Extracting\Strategies;

return [

    'theme' => 'default',

    'title' => null,

    'description' => '',

    'base_url' => '...',

    'routes' => [[
        'match' => [
            'domains' => ['*'],
            'prefixes' => ['api/*'],
            'versions' => ['v1'],
        ],
        'include' => [],
        'exclude' => [
        ],
        'apply' => [
            'headers' => ['Content-Type' => 'application/json', 'Accept' => 'application/json'],
            'response_calls' => [
                'methods' => [],
                'config' => ['app.env' => 'staging'],
                'queryParams' => [
                    'api_key' => '1234',
                ],
                'bodyParams' => [],
                'fileParams' => [],
                'cookies' => [],
            ],
        ],
    ]],

    'type' => 'static',

    'static' => [
        'output_path' => 'public/docs',
    ],

    'laravel' => [
        'add_routes' => true,
        'docs_url' => '/docs',
        'middleware' => [],
    ],

    'try_it_out' => [
        'enabled' => false,
        'base_url' => null,
    ],

    'auth' => [
        'enabled' => true,

        'default' => true,

        'in' => 'bearer',

        'name' => 'Authorization',

        'use_value' => env('SCRIBE_AUTH_KEY'),

        'placeholder' => '{YOUR_AUTH_KEY}',

        'extra_info' => <<<INFO
...
INFO
,
    ],

    'intro_text' => <<<INTRO
...
INTRO

    ,


    'example_languages' => [
        'bash',
        'javascript',
        'php',
    ],

    'postman' => [
        'enabled' => true,
        'overrides' => [
        ],
    ],

    'openapi' => [
        'enabled' => true,
        'overrides' => [
        ],
    ],

    'default_group' => 'Endpoints',

    'logo' => '',

    'faker_seed' => null,

    'strategies' => [
        'metadata' => [
            Strategies\Metadata\GetFromDocBlocks::class,
        ],
        'urlParameters' => [
            Strategies\UrlParameters\GetFromLaravelAPI::class,
            Strategies\UrlParameters\GetFromLumenAPI::class,
            Strategies\UrlParameters\GetFromUrlParamTag::class,
        ],
        'queryParameters' => [
            Strategies\QueryParameters\GetFromFormRequest::class,
            Strategies\QueryParameters\GetFromInlineValidator::class,
            Strategies\QueryParameters\GetFromQueryParamTag::class,
        ],
        'headers' => [
            Strategies\Headers\GetFromRouteRules::class,
            Strategies\Headers\GetFromHeaderTag::class,
        ],
        'bodyParameters' => [
            Strategies\BodyParameters\GetFromFormRequest::class,
            Strategies\BodyParameters\GetFromInlineValidator::class,
            Strategies\BodyParameters\GetFromBodyParamTag::class,
        ],
        'responses' => [
            Strategies\Responses\UseTransformerTags::class,
            Strategies\Responses\UseResponseTag::class,
            Strategies\Responses\UseResponseFileTag::class,
            Strategies\Responses\UseApiResourceTags::class,
            Strategies\Responses\ResponseCalls::class,
        ],
        'responseFields' => [
            Strategies\ResponseFields\GetFromResponseFieldTag::class,
        ],
    ],

    'fractal' => [
        'serializer' => null,
    ],

    'routeMatcher' => \Knuckles\Scribe\Matching\RouteMatcher::class,

    'database_connections_to_transact' => [config('database.default'), config('database.default')]
];

```

**Additional info:**

Perhaps, as a fallback, there should be the ability to disable the auto-validation interpretation on a route-by-route basis with a meta parameter?

**Comment by duncan-c** [comment]
The plot thickens...

The validation in question also contains another input which is just defined as `nullable`:
```
'members' => 'nullable',
'uploadFile' => 'nullable|image|mimes:jpeg|max:2048'
```

Commenting out either of these fixes the generation of the docs.

Also, in the corresponding .yaml file, this route has the following definition for body parameters:
```
bodyParameters:
  members:
    name: members
    description: ''
    required: false
    example: {  }
    type: string
  uploadFile:
    name: uploadFile
    description: 'Must be an image. Must not be greater than 2048 kilobytes.'
    required: false
    example: null
    type: file
```

So the `{  }` example value for the `members` parameter appears to be what is causing the problem.

Obviously, I can just remove the 'members' parameter as it's not actually validating anything (in my case it can be a string or an array so there's not a useful validator to use). But it's a bit strange that removing the image parameter fixed it?

**Comment by shalvah** [comment]
Someone else reported this issue a few days ago. The fix is adding a type validation for `members` eg string/number. Cause the default right now is to generate an object if no type is specified. Not yet sure if I should change that.

**Comment by shalvah** [comment]
Removing the image parameter fixed it because that changes the content type was from multipart to JSON, and the crash only happens in multipart.

**Comment by duncan-c** [comment]
Ah yeah, makes sense. I've removed `members` for now as I couldn't easily validate it with Laravel, which has fixed it. I'd say the ideal behaviour though is for Scribe to handle validators without types by ignoring them, or maybe assuming string?
I'm happy to close though as it's edge case?

**Comment by shalvah** [comment]
In v3.8.0, parameters without any type information or examples will default to null, so I think this should be fixed.
