### ISSUE TITLE
Issue with Laravel 8 when no factories present

### ISSUE THREAD

**Issue by chris-ware** [knuckleswtf/scribe#292]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
Attempting to run `php artisan scribe:generate` has a fatal error.

**Screenshots and stack traces:**
```
Call to undefined function Knuckles\Scribe\Tools\factory()

  at vendor/knuckleswtf/scribe/src/Tools/Utils.php:156
    152▕                     $factory = $factory->$state();
    153▕                 }
    154▕             }
    155▕         } else {
  ➜ 156▕             $factory = factory($modelName);
    157▕             if (count($states)) {
    158▕                 $factory = $factory->states($states);
    159▕             }
    160▕         }
```

**My environment:**
 - PHP version (from `php -v`): 7.4
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 8.28.1
 - Scribe version (from `composer show knuckleswtf/scribe`): 2.5.2, though also tried upgrading to v3

**My Scribe config (minus the comments):**

all default aside from:
```php
'routes' => [
        [
            'match' => [
                'prefixes' => ['api/*'],

```

**Additional info:**

I'm aware this issue has been raised before [here](https://github.com/knuckleswtf/scribe/issues/169) and apparently solved. However, the way the code works causes it to break on Laravel 8 when no factories have been declared on the model, meaning it doesn't fallback to the database as it should. The detection looks for the factory method on the model, which gets added by the HasFactory trait. However, adding that trait with no factory defined causes a fatal error in that the factory cannot be found. If the model doesn't have a factory method, it then attempts the Laravel 7 factory() helper, which doesn't exist on Laravel 8, hence the error above. Realistically, it should just gracefully fall over if nether factory method on model, or factory helper exist, yet it does not. 

If you'd like, I can do a PR to solve this, but basically, just adding a detection for the factory helper and a fallback return should suffice in fixing it. It appears to have done so in my testing anyway.

**Comment by aradhell** [comment]
Hello,

 I am also having issue with laravel 8 

` Class "Database\Factories\ProductFactory" not found`

if I remove HasFactory trait from model then,

`Call to undefined function Knuckles\Scribe\Tools\factory() {"exception":"[object] (Error(code: 0): Call to undefined function Knuckles\\Scribe\\Tools\\factory() at /app/vendor/knuckleswtf/scribe/src/Tools/Utils.php:201)
`

**Comment by shalvah** [comment]
Hmm. 

I have no idea how that's happening.

https://github.com/knuckleswtf/scribe/blob/3b9645478139e8c58a2f1fd1329b6851379eed0d/src/Extracting/Strategies/Responses/UseApiResourceTags.php#L184-L195


https://github.com/knuckleswtf/scribe/blob/badae4778defc98252e047013b71afed6be785fa/src/Extracting/Strategies/Responses/UseTransformerTags.php#L154-L166



Those `factory()` calls (via `getModelFactory()`) are wrapped in a try/catch that logs the error and then tries the database. You shouldn't be getting unhandled exceptions. Can you paste the full output?

**Comment by shalvah** [comment]
On second thought, I think I know the problem. "Call to undefined function" is an `Error` instance, which inherits from `Throwable`, not `Exception`. Should be fixed in the next patch release, in a few hours or so.
