### ISSUE TITLE
Unsupported rules

### ISSUE THREAD

**Issue by rodolfosaraiva** [knuckleswtf/scribe#293]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I created a Laravel Request with rule `'recurring_days.*'   => 'integer',`
2. Then I ran `php artisan scribe:generate` ...
3. But I saw `ParsesValidationRules.php at line 521: Undefined index: setter`

**Screenshots and stack traces:**
![image](https://user-images.githubusercontent.com/8200848/127231427-9cc1653b-5d45-41bd-a6fb-1b92bc2575d8.png)
![image](https://user-images.githubusercontent.com/8200848/127231463-c40eb828-cf50-4a5b-982e-a204841f18f9.png)

**My environment:**
 - PHP version (from `php -v`): 7.4
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): v8.49.1
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.6.3

**My Scribe config (minus the comments):**
Default config.

**Additional info:**
When i config my rule with `'recurring_days.*.id'   => 'integer'`, the error does not appear.

**Comment by shalvah** [comment]
This should be fixed in v3.8.0. Try upgrading and let me know.
