### ISSUE TITLE
Menu not showing

### ISSUE THREAD

**Issue by kisbovan** [knuckleswtf/scribe#295]
I've just upgraded from v2 to v3. The docs are generating fine, however the menu from the left side is completely missing.

![Screenshot 2021-08-02 at 11 06 59](https://user-images.githubusercontent.com/9549853/127835520-4011fcdf-dddc-4b57-9a8c-327d53708654.png)

Anyone experienced this before?

**Comment by kisbovan** [comment]
`toc` list not generating

![Screenshot 2021-08-02 at 11 33 35](https://user-images.githubusercontent.com/9549853/127839403-637cf40e-497f-4eb5-a04a-e4e08af2be76.png)

**Comment by shalvah** [comment]
Should probably check your console for any JS errors?

**Comment by kisbovan** [comment]
It was due to a JS error... 🤦
