### ISSUE TITLE
Response Code 201 instead of 200

### ISSUE THREAD

**Issue by hendrikbl** [knuckleswtf/scribe#3]
When generating a response with a factory using `@apiResource, @apiResourceCollection, and @apiResourceModel` the response code shown in the documentation is `201 Created` even if it's clearly a `GET` method and nothing is beeing created.

From the example page:
![image](https://user-images.githubusercontent.com/9558391/81061531-cce51e80-8ed4-11ea-9dcb-78bd70183994.png)

I'm guessing it has something to do with the factory creating the object, so `201 Created` kinda makes sense. But in the end it's still not correct.

**Comment by shalvah** [comment]
Nice catch. Yep, Laravel sets status code to 201 if the model was recently created. Should be fixed now.
