### ISSUE TITLE
syntax error, unexpected 'static' (T_STATIC)

### ISSUE THREAD

**Issue by alighasemzadeh** [knuckleswtf/scribe#301]
````
    /**
     * Remove Address
     *
     * @queryParam network string Network Of Symbol
     * @queryParam address string Address of Network
     * @queryParam server_url string Server URL
     */
    public function removeAddress(Request $request)
    {
        WatchAddress::where('address', $request->address)->where('network', $request->network)->where('server_url', $request->server_url)->delete();
        return response()->json(['status'=> true, 'address' => $request->adddress], 200);
    }
````

Error:

  at C:\xampp\htdocs\nr\vendor\spatie\data-transfer-object\src\DataTransferObject.php:67
    63| 
    64|         return $data;
    65|     }
    66| 
  > 67|     public function only(string ...$keys): static
    68|     {
    69|         $dataTransferObject = clone $this;
    70| 
    71|         $dataTransferObject->onlyKeys = [...$this->onlyKeys, ...$keys];

  1   C:\xampp\htdocs\node-server\vendor\composer\ClassLoader.php:346
      Composer\Autoload\includeFile("C:\xampp\htdocs\nr\vendor\composer/../spatie/data-transfer-object/src/DataTransferObject.php")

  2   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("Spatie\DataTransferObject\DataTransferObject")

And Route:
`Route::post('/address/check-address', 'API\AddressController@checkAddress');`

How can I fix this problem

**Comment by shalvah** [comment]
1. PHP is complaining because it does not recognise `static` as a return type.
2. The `static` return type was added in PHP 8, that means you're probably on PHP 7.4?
3. spatie/data-transfer-object v3 requires PHP 8, while v2 requires 7.4.
4. This package depends on spatie/data-transfer-object, and supports both versions. If you're on PHP 7.4, Composer should have installed spatie/data-transfer-object v2.

The question for you to solve now is "why do I have spatie/data-transfer-object v3 installed?" Maybe you installed it yourself? Maybe you passed `--ignore-platform-reqs` to Composer?

**Comment by alighasemzadeh** [comment]
@shalvah 
Now I get:

  Class 'Knuckles\Scribe\Extracting\Strategies\QueryParameters\GetFromFormRequest' not found

  at C:\xampp\htdocs\node-server\vendor\knuckleswtf\scribe\src\Extracting\Generator.php:233
    229|         $strategies = $this->config->get("strategies.$stage", $defaultStrategies[$stage]);
    230|         $extractedData[$stage] = $extractedData[$stage] ?? [];
    231|         foreach ($strategies as $strategyClass) {
    232|             /** @var Strategy $strategy */
  > 233|             $strategy = new $strategyClass($this->config);
    234|             $strategyArgs = $arguments;
    235|             $strategyArgs[] = $extractedData;
    236|             $results = $strategy(...$strategyArgs);
    237|             if (!is_null($results)) {

  1   C:\xampp\htdocs\node-server\vendor\knuckleswtf\scribe\src\Extracting\Generator.php:162
      Knuckles\Scribe\Extracting\Generator::iterateThroughStrategies("queryParameters")

  2   C:\xampp\htdocs\node-server\vendor\knuckleswtf\scribe\src\Extracting\Generator.php:102
      Knuckles\Scribe\Extracting\Generator::fetchQueryParameters(Object(ReflectionClass), Object(ReflectionMethod), Object(Illuminate\Routing\Route), [])
