### ISSUE TITLE
Can´t sort custom endpoints

### ISSUE THREAD

**Issue by marcelpreparatodos** [knuckleswtf/scribe#303]
I'm using Laravel Passport to authenticate the API. To document the `/login` endpoint i edited `custom.00.yml` file, it worked but the custom endpoint group appear after normal endpoint group. Tryied sort by editing endpoint file names:  `01.yml`, `custom.00.yml` but always had same result. 

Is there something i doing wrong?

**Comment by rickdubiel** [comment]
If there could be some sort of "groupPosition" set for groups then the final $groupedEndpoints array could be ordered here maybe?

https://github.com/knuckleswtf/scribe/blob/17bd5a9f0449642a85ccbd46011c6f9afe4ff572/src/Commands/GenerateDocumentation.php#L49

Something like so perhaps?
`
$groupedEndpoints = collect($groupedEndpoints)->sortBy('groupPosition')->toArray();`

Just a thought, but I'm looking for this feature as well!

**Comment by shalvah** [comment]
Implemented in 3.14.0.

https://scribe.knuckles.wtf/laravel/documenting/custom-endpoints#extra-sorting-groups-in-custom-endpoint-files

**Comment by rickdubiel** [comment]
Just tested it out.. Works great! Thank you very much!!
