### ISSUE TITLE
Can I make multiple openapi files?

### ISSUE THREAD

**Issue by alexnen** [knuckleswtf/scribe#309]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I have 400+ endpoints and i need to make multiple swagger pages for different integrations. Is there a config way for "routes", to split openapi.yaml ?

**Comment by shalvah** [comment]
Only OpenAPI specs? not multiple documentation pages?

**Comment by shalvah** [comment]
But, no, `routes` wasn't designed for that. Your best bet is probably to follow the approach I recommended to this guy who wanted multiple docs: https://github.com/knuckleswtf/scribe/issues/302#issuecomment-904535934
