### ISSUE TITLE
Static urls

### ISSUE THREAD

**Issue by ilic993** [knuckleswtf/scribe#314]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Is there a way to make links static?
Example:
instead of `https://publitio.test/docs/#introduction` -> `https://publitio.test/docs/introduction`

Regards

**Comment by shalvah** [comment]
Nope. It's a single documentation page that uses HTML anchors.

If you want to achieve that, I'll recommend you set up your own routing. You could add a route for /docs/{whatever} and reroute to /docs#whatever server- or client-side.
