### ISSUE TITLE
Should the example params/body be used in the try-it-out fields?

### ISSUE THREAD

**Issue by james2doyle** [knuckleswtf/scribe#322]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I was wondering why the fields in the try-it-out aren't using the same values that are used in the example requests. It is actually really to add these examples into the field by just passing the example field to `scribe::components.field-details` and setting it as the `value` for the corresponding inputs.

You can see I did that as a test checking if it worked:

![Screen Recording 2021-09-14 at 09 25 33 AM](https://user-images.githubusercontent.com/1425304/133296835-a1ec9e68-d423-41dd-a090-a7d818d8457a.gif)

Thoughts on this?

**Comment by shalvah** [comment]
I guess there isn't any harm in that
Considered it in the past, but I guess I was worried about users having to go through the work of deleting each value, but now I think it might actually help.

If we're doing this though, I think boolean values should be left unselected. It's easy for a user to miss that a radio button was filled in.
