### ISSUE TITLE
Can't get example to display for object array

### ISSUE THREAD

**Issue by wyfiwyfi** [knuckleswtf/scribe#323]
Hi - I'm using Scribe 3.10.2/Lumen 6.3.3/PHP 7.14/Ubuntu 20 on Homestead.

This should be straightforward, but after combing through the documentation and other issues, I can't get the example for an array of objects to work. 

What I want to produce in the (PHP json) documentation example is something like this:
```
...
'json' => [
            'geopoints' => [
                [
                    'latitude' => 23.61721882,
                    'longitude' => 67.43423423,
                ],
                [
                    'latitude' => 66.12345432,
                    'longitude' => 90.98762342,
                ],
            ],
        ],
...

```
That is, an array of objects with two (preferably three) examples of objects using 8-decimal place numbers that I provide.

Here is what I think should work:
```
* @bodyParam geopoints object[] List of latitude and longitude pairs Example: [{"latitude": 23.61721882, "longitude": 67.43423423}, {"latitude": 66.12345432, "longitude": 90.98762342}]
* @bodyParam geopoints[].latitude number required Number between -90 and 90 and up to 8 decimals. Must have corresponding longitude.
* @bodyParam geopoints[].longitude number required Number between -180 and 180 with up to 8 decimals. Must have corresponding latitude.
```

But any example I include in the top level object is ignored and replaced by an auto-generated example. The above produces this (correct format, but not the numbers given):
```
...
'json' => [
            'geopoints' => [
               [
                    'latitude' => 1394.7993,
                    'longitude' => 34.90597,
                ],
                [
                    'latitude' => 1394.7993,
                    'longitude' => 34.90597,
                ],
            ],
        ],
...

```
If I instead place the examples on the item lines, like this:
```
* @bodyParam geopoints object[] List of latitude and longitude pairs
* @bodyParam geopoints[].latitude number required Number between -90 and 90 and up to 8 decimals. Must have corresponding longitude. Example: 23.61721882
* @bodyParam geopoints[].longitude number required Number between -180 and 180 with up to 8 decimals. Must have corresponding latitude. Example: 67.43423423
```

the result is:
```
...
'json' => [
            'geopoints' => [
                [
                    'latitude' => 23.61721882,
                    'longitude' => 67.43423423,
                ],
                [
                    'latitude' => 23.61721882,
                    'longitude' => 67.43423423,
                ],
            ],
        ],
...
```
This is better, since the structure is correct and the one set of numbers I entered as example are used, but I can't figure out a way to produce multiple geopoints (three or more would be optimal) with numbers that I provide. 

Even though it's not documented, I've tried arrays on the item lines, like the following, but with poor results (the examples generated in the documentation are all zeroes):

```
* @bodyParam geopoints object[] List of latitude and longitude pairs
* @bodyParam geopoints[].latitude number required Number between -90 and 90 and up to 8 decimals. Must have corresponding longitude. Example: [{23.61721882, 66.12345432}]
* @bodyParam geopoints[].longitude number required Number between -180 and 180 with up to 8 decimals. Must have corresponding latitude. Example: [{67.43423423, 90.98762342}]
```

I've experimented with some other ideas, but can't seem to get the result I'm after. Can someone spot what I'm missing?  Thanks.

**Comment by shalvah** [comment]
I don't think you're doing anything wrong. Your first scenario should have worked, I guess. It seems to be a bug.

**Comment by wyfiwyfi** [comment]
Closing this issue because it was created in an incorrect format. It is restated in the new issue is [#328 ](https://github.com/knuckleswtf/scribe/issues/328)
