### ISSUE TITLE
Try It out always sending value 0 for boolean true set in queryParam

### ISSUE THREAD

**Issue by baneetsharma** [knuckleswtf/scribe#325]
Try It out always sending value **0** for **boolean true** set in queryParam from the controller.

This is how I have set queryParam in my controller : 

`@queryParam show_beta bool Show/Hide Beta users`

On sending the request you can see although I have selected true, but value sent is 0

![image](https://user-images.githubusercontent.com/12934454/133637998-90fcfa33-83c7-4fdd-8b1c-8edd0138ce3c.png)

Also in you can see in the Example request that the value for show_beta which is a boolean type is empty. Checked with php, curl, javascript. All have the same issue. 

![image](https://user-images.githubusercontent.com/12934454/133637689-58b15321-5e3a-4f7c-be22-24c2ed186408.png)

**My environment:**
 - PHP version : 7.4.18
 - Framework (Laravel): 8.51.0
 - Scribe version : 3.10.2

**Comment by shalvah** [comment]
Hmm, I couldn't reproduce this.

**Comment by shalvah** [comment]
Does it still happen for you on the latest version? (3.11.2)

**Comment by baneetsharma** [comment]
> Does it still happen for you on the latest version? (3.11.1)

I haven't tried with this version will check over the weekend and update you. Sorry bit busy these days.

**Comment by shalvah** [comment]
Let me know if this is still happening.
