### ISSUE TITLE
Unable to locate the api  where the name is a Chinese character!

### ISSUE THREAD

**Issue by Oranzh** [knuckleswtf/scribe#326]
## Unable to locate the api  where the name is a Chinese character, and can't search with Chinese character!

**Locate result** 

![image](https://user-images.githubusercontent.com/21193565/133755068-a9a1d778-2893-43f1-9fd8-fdd4ca1cc0fc.png)

**My environment:**
 - PHP version (from `php -v`):   7.4.3
 - Framework (Laravel/Lumen):  Lumen
 - Laravel/Lumen version : v8.2.4 
 - Scribe version: * 3.6.3 

**My Scribe config (minus the comments):**   Default config.

**Comment by shalvah** [comment]
Hmmm, I'm open to a PR if you can think of a fix. As far as I can tell, the headings are generated by the tocify library.

**Comment by Oranzh** [comment]
Thank you for your advice! I will try my best to solve it!

**Comment by Oranzh** [comment]
Thank you for your advice! I will try my best to solve it!

**Comment by james2doyle** [comment]
Should be closed with https://github.com/knuckleswtf/scribe/pull/354
