### ISSUE TITLE
Error in Upgrader

### ISSUE THREAD

**Issue by dnwjn** [knuckleswtf/scribe#327]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I upgraded the package to its latest version
2. I ran `php artisan scribe:generate`
3. I received an error

**Screenshots and stack traces:**

```
ⓘ Generating OpenAPI specification
✔ Wrote OpenAPI specification to: storage/app/scribe/openapi.yaml

   ErrorException 

  Attempt to read property "value" on null

  at vendor/shalvah/upgrader/src/Upgrader.php:163
    159▕         // Loop over the old config
    160▕         // TODO handle cases of mixed assoc- and list array
    161▕         foreach ($userCurrentConfig as $arrayItem) {
    162▕             // @phpstan-ignore-next-line Not yet sure how to handle mixed
  ➜ 163▕             $key = $arrayItem->key->value;
    164▕             $value = $arrayItem->value;
    165▕ 
    166▕             $fullKey = $this->getFullKey($key, $rootKey);
    167▕ 

      +20 vendor frames 
  21  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**My environment:**
 - PHP version (from `php -v`): 8.0.10
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 8.61.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.10.2

**Debugging results:**

I went into `vendor/shalvah/upgrader/src/Upgrader.php` and added a dump to see in which case there was no value:

```
foreach ($userCurrentConfig as $arrayItem) {
    dump($arrayItem);
    ...
}
```

I noticed that the command fails at the `'middleware' => ['nova']` part:

```
'laravel' => [
    'add_routes' => true,

    'docs_url' => '/docs/scribe',

    'middleware' => ['nova'],
],
```

It seems that the upgrader cannot handle items without index key (probably also why the author of that package added `// TODO handle cases of mixed assoc- and list array` above it.

**Suggested solution:**

Do not use this version of `shalvah/upgrader` yet **OR** change the way the middleware is defined.

**Comment by shalvah** [comment]
Thanks. The middleware key should actually be ignored, since it's for user-specified values. Should be fixed now.
