### ISSUE TITLE
Problem with T_DOUBLE_ERROR

### ISSUE THREAD

**Issue by dmalmeida** [knuckleswtf/scribe#329]
Hi
I'm having a problem with T_DOUBLE_ERROR. On my local server everything is ok, and on my live server everything was ok until I upgrade to scribe v3.0.
I dind't notice that until now when I copied changed files from local server to live server.

It gives this error: ParseError: syntax error, unexpected '=&gt;' (T_DOUBLE_ARROW), expecting ',' or ')' in file /home/dbgep/dbgep-api/vendor/knuckleswtf/scribe/src/ScribeServiceProvider.php on line 25

I presume that it needs php 7.4. 
I already changed the version to 7.4 on cpanel, but after that it gives an error 500 with Interface 'JsonSerializable' not found. Even I see that extension json is installed.

Before I upgrade scribe to v3, I had all working, but now I can't even run my api on live server.

I have to present this api on a final work to university until 30th september and now that I even wrote my report, I can't run my api.
I don't mind to have version 2.10 of scribe or even don't have scribe working. Since API can run.

Please help.... is there a way to downgrade scribe, or make the API don't run scribe code when I call an endpoint?

Thanks

**Comment by shalvah** [comment]
> is there a way to downgrade scribe

Yes, just change the Scribe version in your composer.json back to an older one and run `composer update`

> or make the API don't run scribe code when I call an endpoint?

I'm pretty sure that Scribe does not run when you call your endpoints. But if you think you're having issues from Scribe, then, on your server, you should install your dependencies without dev dependencies (I'm assuming you have Scribe in the `require-dev` section): `composer install --no-dev`.
This will skip dependencies in the `require-dev` section, leaving you Scribe-free.

Finally, as to your actual issue:

> ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')' i

That code is an arrow function, introduced in PHP 7.4. https://github.com/knuckleswtf/scribe/blob/093a1f24435d44e82aac33e9e2d8fee3a54fdcce/src/ScribeServiceProvider.php#L25

I doubt your server is running PHP 7.4. You should double-check. And remember that the CLI PHP version can be different from the web PHP version.

**Comment by dmalmeida** [comment]
Thanks. I could downgrade scribe but the composer update has upgraded some other dependencies I it asked for php 7.3.
I changed it to 7.3 and after php artisan cache:clear and config:clear I am able to run my API again.

For now an until presentation I will not try any other change. After that I will try again to put php 7.4 and scribe 3.

Thanks shalvah.... you are a lifesaver
