### ISSUE TITLE
Postman collection namings

### ISSUE THREAD

**Issue by Dzale** [knuckleswtf/scribe#33]
Hey guys,

first of all, awesome package, works great. 

I have a question about naming function in Postman collection that is generated. 

Let's have a look at example below: 

```   
/**
     * Index
     * Get paginated list of items.
     * @param Request $request
     * @return JsonResponse
     * @authenticated
     * @apiResourceCollection App\Http\Resources\Actor\ActorCollection
     * @apiResourceModel App\Models\Actor paginate=10
     */
```

In this example name should be "Index" and description should be "Get paginated list of items.". 

In generated documentation this is properly shown, but in Postman, i get name like this: "IndexGet paginated list of items."

Did you intend to make it like that or i am doing something wrong ?

Thanks in advance,
Nikola Dzakovic

**Comment by shalvah** [comment]
(Please always put code snippets in triple backticks so they're easier to read. I've added them in your post.)

Try putting a blank space after the first line. Does that work?

**Comment by Dzale** [comment]
Hey @shalvah, 

thanks for quick answer. Yes, when i leave empty line, it is parsed correctly. 

I'm noticing other thing in HTML docs now. 

When i have blank line between name and desc, "requires authentication" is placed below endpoint name. Checkout image below. 

![image](https://user-images.githubusercontent.com/9077950/83329453-e38b5500-a289-11ea-9615-f4a2f70395a7.png)

And earlier it was like this:

![image](https://user-images.githubusercontent.com/9077950/83329498-336a1c00-a28a-11ea-8aa3-23944a609251.png)

To me personally it's all the same, i like it either way, just though you should know. 

Best regards and thanks again for the help,
Nikola Dzakovic

**Comment by shalvah** [comment]
When you leave a blank line, it's sort correctly into title and description. Without that line, everything is considered part of the title. Not sure that's how it should be. I'll look into it.

**Comment by shalvah** [comment]
Came across this in the source of the package we're using to parse the docblocks (mpociot/reflection-docblock):

```
The short description is started from the first character until a dot is encountered followed by a
         *   newline OR two consecutive newlines (horizontal whitespace is taken into account to consider spacing
         *   errors). This is optional.
```

So apparently, this is by design. If you end the first line with a period and then continue on the next line, they are split into title and description. If you don't end with a period, you have to leave a blank line in betwee.
