### ISSUE TITLE
There are no commands defined in the "scribe" namespace. 

### ISSUE THREAD

**Issue by ebonertz** [knuckleswtf/scribe#334]
I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I set my configuration to laravel
2. Then I ran `php artisan scribe:generate` 
3. But I saw "There are no commands defined in the "scribe" namespace.

This is a Lumen API implementation. I verified that that scribe is update to the latest 

How do I add scribe to the namespace?

**My environment:**
 - PHP version (from `php -v`): PHP 7.4.24
 - Framework (Laravel/Lumen): Lumen
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): v8.2.7
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.11.1

**Comment by shalvah** [comment]
You didn't follow the complete installation instructions for Lumen. 
The part where you're meant to add the service provider to your bootstrap/app.php. https://scribe.knuckles.wtf/laravel/

**Comment by steveerg** [comment]
Hi, great package. I got the same error in Laravel (not Lumen)
"laravel/framework": "^v10.1.5"
"knuckleswtf/scribe": "^4.18"
