### ISSUE TITLE
How to ignore ID field in put/patch based URLs?

### ISSUE THREAD

**Issue by diegomagikal** [knuckleswtf/scribe#336]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hello, 
My docs are showing instructions for "id" fields even when they are not present in my code. 

```
// api.php
Route::resources(
	[
                'negotiations'  => 'NegotiationController',
                ...
	]
);
```

```
// NegotiationController.php
/**
     * Atualiza uma negociação
     *
     * @urlParam uuid string required Código UUID da negociação em questão
     */
    public function update(NegotiationRequest $request, $uuid)
    {
       ....
    }

```

And the result:
![image](https://user-images.githubusercontent.com/16082344/136616763-77716c4c-cf33-474d-aaab-1a1fad0d859b.png)

Why does it happen? How should I put an instruction to the route show UUID instead of ID? Thanks

**Comment by diegomagikal** [comment]
So, all my code is that... 

The `Route::resources()` automatically points the route to the `update` method and expects a parameter (`$uuid`). The $uuid integrity is validated by request `NegotiationRequest`.

The primary key in my table is `id`. I didn't declare `uuid` as pk because I'm using uuid as binary internally (from `spatie/laravel-binary-uuid`). But all my routes use `uuid` to their operations.

I thought the params in controller methods were enough to instruct Scribe, but by the look of it, no...

**Comment by shalvah** [comment]
You know, you can get rid of it by removing the `GetFromLaravelAPI` strategy in your config. Then you'll always have to declare your URL parameters manually.

**Comment by syofyanzuhad** [comment]
> You know, you can get rid of it by removing the `GetFromLaravelAPI` strategy in your config. Then you'll always have to declare your URL parameters manually.

it was disappear the URL param input, but the route still use the `{id}` param
![Screenshot from 2021-11-26 15-28-40](https://user-images.githubusercontent.com/52684582/143550576-330564c7-e20a-4d68-8a2a-ffdf0f6ac43f.png)
