### ISSUE TITLE
Can't generate documentation

### ISSUE THREAD

**Issue by kalemakk** [knuckleswtf/scribe#337]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.
  ErrorException 

  Undefined array key 1

  at vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php:230
    226▕ 
    227▕     private function isValidRoute(array $routeControllerAndMethod = null): bool
    228▕     {
    229▕         if (is_array($routeControllerAndMethod)) {
  ➜ 230▕             [$classOrObject, $method] = $routeControllerAndMethod;
    231▕             if (u::isInvokableObject($classOrObject)) {
    232▕                 return true;
    233▕             }
    234▕             $routeControllerAndMethod = $classOrObject . '@' . $method;

      +18 vendor frames 
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by shalvah** [comment]
Posting a stack trace is not how you report an issue. I guess you expect me to magically know what your setup is like and what caused the issue. There's a bug report template; please follow it.

**Comment by kalemakk** [comment]
my bad, i solved it.

**Comment by AchrafBardan** [comment]
> my bad, i solved it.

HOW

**Comment by k2288** [comment]
clearing route cache solved my problem

**Comment by syofyanzuhad** [comment]
solved my problem with clear the route run:
```
php artisan route:clear
```
