### ISSUE TITLE
add authentication button to all apis 

### ISSUE THREAD

**Issue by khaled-mohamed2021** [knuckleswtf/scribe#340]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

hi , i was wondering is there an option to add bearer token in the documentation page and it be used in all apis that requires authentication ?

**Comment by shalvah** [comment]
I don't understand this question. You'll need to clarify with an example.

**Comment by khaled-mohamed2021** [comment]
@shalvah  as u can see in this screenshot 
![image](https://user-images.githubusercontent.com/92052784/137630233-08188f8f-cf8c-4aac-8991-cd38710184dd.png)

there is a button called authorize the top right section of the apis , when i enter the bearer value or the authorization value in this field . it will use it automatically with all the apis that requires authorization instead of writing it every time i test a api

**Comment by shalvah** [comment]
Well, I wouldn't call that a "problem", just a convenience issue.

We're not going to add such a button, cause that would introduce an extra click + scroll to test an endpoint. Instead when you enter an auth token in one endpoint, we can save it and populate any other endpoints when you click "Try It Out".

**Comment by syofyanzuhad** [comment]
> Well, I wouldn't call that a "problem", just a convenience issue.
> 
> We're not going to add such a button, cause that would introduce an extra click + scroll to test an endpoint. Instead when you enter an auth token in one endpoint, we can save it and populate any other endpoints when you click "Try It Out".
the meaning of our brother is when we click the Authorize button, it will appear an input for the bearer token or something else..
so if we put the token, it will authorize all the entire api's

**Comment by shalvah** [comment]
I'm not going to add a modal. It's extra UI work, plus I don't think it fits the current design. But as I mentioned earlier, when you set the auth header value in one endpoint, it will automatically be set for all the endpoints, so you don't have to enter it again. Available now (3.15.0).

**Comment by syofyanzuhad** [comment]
> I'm not going to add a modal. It's extra UI work, plus I don't think it fits the current design. But as I mentioned earlier, when you set the auth header value in one endpoint, it will automatically be set for all the endpoints, so you don't have to enter it again. Available now (3.15.0).

btw, the modal is just an example...
maybe you can put an input that will appear used to save the token once, so if it is enabled it will authorize all the endpoints, and it can be disabled (as you see the padlock in the screenshot)
*its just a suggestion ✌️😅
