### ISSUE TITLE
bodyParams for multiple fields 

### ISSUE THREAD

**Issue by Kristories** [knuckleswtf/scribe#341]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hey, I really love response calls feature. Is there a way to use `bodyParams` for multiple fields having the same key? For example: field `name` for `/customers` endpoint and field `name` for `/category` endpoint. 

Yes, I know if it can be done by creating a custom strategy. But it would be better if it was available in the default configuration. Is this a good way to create PR?

```
'bodyParams' => [

    'customers' => [
        'name' => 'Customer Name',
        'email' => 'customer@email.tld'
    ],
    'categories' => [
        'name' => 'Category Name',
        'identifier' => 'ID-123',
    ]

    ...
],
```

**Comment by shalvah** [comment]
No, there isn't. And while that would be a really good feature, I can't introduce that anytime soon. But one way to achieve this yourself with `Scribe::beforeResponseCall()`.

https://scribe.knuckles.wtf/laravel/documenting/responses#authentication-and-customization

It's meant for authentication, but you can use it to change anything in the request. So you could add this config yourself, then inside that hook, check the request URL and match against your custom config and set the body parameters.
