### ISSUE TITLE
Extract validation information in lumen

### ISSUE THREAD

**Issue by eschricker** [knuckleswtf/scribe#344]
The extraction of validation information in laravel is supported. It would be great if the validation rules from lumen would also be supported. The difference in my opinion is that you validate against `$this->validate($request, [...])` instead of `$request->validate([...])`.

[Lumen Doc - Validation](https://lumen.laravel.com/docs/8.x/validation)

**Comment by shalvah** [comment]
`$this->validate($request, ...)` is now supported (3.30.1).

https://github.com/knuckleswtf/scribe/blob/29940c2e05c8035a1ab85d9482c2335e1747ab41/src/Extracting/Strategies/GetFromInlineValidatorBase.php#L139-L144
