### ISSUE TITLE
Beautify json body parameters

### ISSUE THREAD

**Issue by kevinklinegargar** [knuckleswtf/scribe#353]
It's possible to generate a beautify format of json body parameters in collection.json for postman same in the  previous version 2 ?

Currently looks like this when we import collection.json:
![image](https://user-images.githubusercontent.com/7617185/139022613-36636801-b7cb-47f8-a731-8fe09945e1db.png)

It's better if in beautify once imported:
![image](https://user-images.githubusercontent.com/7617185/139022737-3f403a38-12f3-4db5-ac20-9024e14eda87.png)

**Comment by shalvah** [comment]
Sorry, I decided to stick with this.

The reason I removed it was because the pretty-fied output looks like this in the collection file:

```
"{\n    \"user_id\": 9,\n    \"room_id\": \"consequatur\",\n    \"forever\": false,\n    \"another_one\": 11613.31890586,\n    \"yet_another_param\": {\n        \"name\": \"consequatur\"\n    },\n    \"even_more_param\": [\n        11613.31890586,\n        11613.31890586\n    ],\n    \"book\": {\n        \"name\": \"consequatur\",\n        \"author_id\": 17,\n        \"pages_count\": 17\n    },\n    \"ids\": [\n        17,\n        17\n    ],\n    \"users\": [\n        {\n            \"first_name\": \"John\",\n            \"last_name\": \"Doe\"\n        },\n        {\n            \"first_name\": \"John\",\n            \"last_name\": \"Doe\"\n        }\n    ]\n}"
```

which is much harder to see when inspecting the collection file (which I often need to do). It also bloats the size of the file.
