### ISSUE TITLE
optional required auth

### ISSUE THREAD

**Issue by ibrahem-kamal** [knuckleswtf/scribe#355]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

sometimes we have a public api like list all posts but it may optionally have a bearer token to return if the auth user liked the post or not , but with the current approach its either authenticated which require the token or unauthenticated with doesnt require the token , so i`d suggest adding another tag like @sometimesauthenticated  to indicate that the token is optionally required and show the token input accordantly

**Comment by shalvah** [comment]
3.14.0 removes `required` parameter validation from Try It Out.
