### ISSUE TITLE
No-example for bodyParameters()

### ISSUE THREAD

**Issue by swarley** [knuckleswtf/scribe#356]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I've been playing around trying to get things working but I haven't found a good way to exclude a field in a FormRequest using `bodyParameters`. Setting the `'example'` key to `null` doesn't achieve it, and I can't find anything in the docs.

Using `@bodyParam foo string desc. No-example` works, but it also removes the description created using the validation rules.

Currently using `3.13.0`.

**Comment by swarley** [comment]
Update, using `@bodyParam` on the controller method rather than the FormRequest class works, but I'd still like to know if this could be achieved in `bodyParameters()`

**Comment by shalvah** [comment]
Hmm, that's an oversight. Setting it to `null` should work. You're sure the parameter is not required?

**Comment by vrgblzs** [comment]
Same here! My field is 'nullable', 'numeric' - and I can not exclude it from the examples generated if I use formRequests.
Tried 'example' => null and 'example' => ''
using v3.15.0

Thank you for this fantastic package!

**Comment by shalvah** [comment]
I think this should have been fixed by https://github.com/knuckleswtf/scribe/pull/511
