### ISSUE TITLE
Can make sub group? like on postman

### ISSUE THREAD

**Issue by retry19** [knuckleswtf/scribe#357]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

**Comment by shalvah** [comment]
https://github.com/knuckleswtf/scribe/issues/35

**Comment by shalvah** [comment]
Implemented and coming in the next major. https://github.com/knuckleswtf/scribe/issues/484#issuecomment-1179599066
