### ISSUE TITLE
Query param annotation not respected when using custom rule

### ISSUE THREAD

**Issue by LiamNorman** [knuckleswtf/scribe#359]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hi, I am currently trying to set example query parameters in an example Request that extends Illuminate\Support\FormRequest.php 

I have a custom rule which gets instantiated and I think Scribe might not be sending through a default even though I am trying to set a default using annotations, for example:

```

/**
 * @queryParam interval string Interval. Example: 12
 */
class UpdateRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = [
            'interval' => ['required_with:frequency', new PolicyIntervalRule],
            'interval_frequency' => [
                'required_with:interval',
                'enum:'.PolicyIntervalFrequency::class,
                Rule::when($this->has('interval'), [new PolicyIntervalFrequencyRule(interval: $this->input('interval'))]),
            ],
```

When I try to run `php artisan scribe:generate` against that request, I get the following:

```
  TypeError 

  App\Rules\PolicyIntervalFrequencyRule::__construct(): Argument #1 ($interval) must be of type string, null given, called in 
  UpdateRequest.php on line 52
  ```
  
  So I am guessing that it is not passing my default when it's instantiating the custom rule PolicyIntervalFrequencyRule **however** if I instead of the annotations, use the queryParameters() function then it works as expected:
  
  ```
      public function queryParameters(): array
    {
        return [
            'interval' => [
                'description' => 'Interval',
                'example' => '12'
            ],
        ];
    }
   ```

I think the issue is when it's instantiating the custom rule below:

```
                Rule::when($this->has('interval'), [new PolicyIntervalFrequencyRule(interval: $this->input('interval'))]),
```               
               
 Is there anything I am doing incorrectly with my queryParam annotation as I would expect either the annotation or the function to achieve the same thing with my FormRequest when generating docs?
   
 Thanks for the awesome library! 🎉

**Comment by shalvah** [comment]
The problem isn't the annotation, but this:

```php
new PolicyIntervalFrequencyRule(interval: $this->input('interval'))]),
```

The FormRequest rule just instantiates the FormRequest directly. It doesn't create a HTTP request (it doesn't know your parameters yet!) or call your app. So there is not request input, and `$this->input()` always returns null.

**Comment by LiamNorman** [comment]
Hi @shalvah, thanks! Would it be best to either do the following: 

1. Use queryParam function which seems to work as expected? 
2. Change type checking to allow for null?

Interesting that it works for the function but not the annotation 🤔 Will try see if there is a reason behind that. 

Thanks!

**Comment by shalvah** [comment]
Of course, I'd recommend (1) (but it's strange that it works for the function, since the  `rules()` method is executed anyway). (2) and (3) involve modifying your code's runtime behaviour, which is less than ideal, so I'd be against those.

Okay...I think the reason it works for `queryParameters()` is because that function is run before executing `rules()`, as part of the same FormRequest strategy. So by the time `rules()` runs, it doesn't really need the extra information about `interval`. However, the exception should still be thrown, but maybe there's some logic that catches it in this case.
