### ISSUE TITLE
Ok so you basically have stolen this package...?

### ISSUE THREAD

**Issue by PovilasKorop** [knuckleswtf/scribe#36]
At first I was surprised that Marcel has abandoned his original package. But now see his comment: https://twitter.com/PovilasKorop/status/1270590112217399297

Just curious, was that your plan from the beginning? Contribute to his package and then declare that as your own, taking over?

I'm very confused by such behavior in open-source community.

I've tried Scribe and it works well, but abandoning the original package without asking the owner? Seriously?

**Comment by shalvah** [comment]
https://twitter.com/theshalvah/status/1270600159425171459?s=19

I appreciate you asking. Beyond that tweet, there really isn't much else I can say. Mistakes happen.

"Stolen" is a strong word considering I've maintained the package alone for almost two years, and gotten no rewards from it. Not sure how long you've been around, but the package was effectively abandoned when I volunteered to manage it, and I've done a great job, if I may say so myself. Make your own judgement, at the end.

**Comment by PovilasKorop** [comment]
@shalvah I appreciate the answer, and indeed you did a great job, it was just a "bad tone" of taking over without discussing with Marcel. 

Scribe works well, good luck with it!

**Comment by shalvah** [comment]
And if you didn't follow the change, you could do a little digging and see that I documented it in the open as it was happening: https://github.com/mpociot/laravel-apidoc-generator/issues/723#issuecomment-622995973

Please do a bit more due diligence next time before throwing around the s-word. It's painful to hear someone accuse you of stealing when you've put in (and still plan to put in) hours of your life into this. Maybe it's Marcel's package, but at this point, I have more code in it than he does—[nearly 10x as much](https://github.com/mpociot/laravel-apidoc-generator/graphs/contributors).

**Comment by PovilasKorop** [comment]
@shalvah yes I apologize, overreacted trying to defend a "victim" friend. Sorry.

**Comment by shalvah** [comment]
Fair enough.
