### ISSUE TITLE
is there any way to custom the "Try" button only for an endpoint?

### ISSUE THREAD

**Issue by syofyanzuhad** [knuckleswtf/scribe#361]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I'll hide the "Try" button only for an endpoint, is there any tag like `@hideTryButton` maybe..

**Comment by shalvah** [comment]
No. I'm not yet sure if we want to have that feature (although it likely won't be via annotation). You can [customise the theme](https://scribe.knuckles.wtf/laravel/advanced/theming) and add some logic yourself to hide/show the button.
