### ISSUE TITLE
Several different Docs in one app

### ISSUE THREAD

**Issue by andreypopov** [knuckleswtf/scribe#363]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I use laravel8 and I need to have two different docs for user's API and for admin's API . Users should not have access to admin's API docs.
How to divide docs to be generated into different blade files?

**Comment by andreypopov** [comment]
A expect smth like:

`   
    'routes' => [
        'default' => [
            'match' => [...]
        ],
        'v2' => [
            'match' => [...]
        ],

   'laravel' => [
        'default' => [
            'add_routes' => false,
            'docs_url' => '/en/docs',
            'middleware' => [App\Http\Middleware\Api\DocsAuth::class],
            'routes'=> ['default'],
        ],
        'v2' => [
            'add_routes' => false,
            'docs_url' => '/en/docs_v2/',
            'middleware' => [App\Http\Middleware\Api\DocsV2Auth::class],
            'routes'=> ['v2'],
        ],

php artisan scribe:generate --endpoint=v2
`

**Comment by shalvah** [comment]
I'm sorry, but it's unlikely we'll do this. It will add too much complexity to the project for developers and most users.

However, Scribe is open enough that you can implement this yourself. You can write your own custom command that calls Scribe. SOmething similar to this:


```php
class GenerateYourMultipleDocs
{
  protected $signature = "docs:generate --endpoint=
    ";
  public function handle() 
  {
    $endpoint = $this->getArg("endpoint");
    Config::set('scribe', $this->getConfigFor($endpoint));
    Artisan::call('scribe:generate');
  }
}
```

Basically, you can store the different configs somewhere (maybe separate config files, or just as a variable or method in the class) and load the appropriate one before calling Scribe. That way you could have them generate to different locations, for instance. You can even use the [`afterGenerating()` hook](https://scribe.knuckles.wtf/laravel/hooks) to do some more cleanup.

**Comment by andreypopov** [comment]
Thanks. you helped me so much!) Works fine

**Comment by Mina-R-Meshriky** [comment]
@shalvah Hi,
I have tried that approach but every time I run a different config file it overrides the previous run which I suppose is the normal behaviour. 
but, as a continue for the above question, what if I need 2 routes always available.
1- /backend-docs
2- /docs    --> which will be shown to authorized clients
is there a way to instruct scribe to produce another docs from another config with a specific url

**Comment by shalvah** [comment]
You should probably ask @andreypopov , who said the approach worked fine for him.

Beyond that, I don't have much else to suggest. I don't see why the above approach shouldn't work. Calling `Config::set('scribe', $someNewConfig)` should change the Scribe config to a new set of values, so when you call Scribe again, it will use those values. Of course, if both of your configs use the same values (eg output to the same path), then one will overwrite the other, so you should use different paths.

**Comment by shalvah** [comment]
It seems "multiple APIs" is a more popular request these days. I personally don't want to add native support for that because I can't (yet) think of a good way that doesn't make things unnecessarily complex and meets most expectations. But I'm open to well-thought-out suggestions.

**Comment by andreypopov** [comment]
```
if (class_exists(\Knuckles\Scribe\Scribe::class)) {
            \Knuckles\Scribe\Scribe::afterGenerating(function (array $paths) {
                $endpoint = config('scribe.endpoint', null);
                if ($endpoint) {
                    $defaultDir = dirname($paths['blade']);
                    File::deleteDirectory($defaultDir.'-'.$endpoint);
                    rename($defaultDir, $defaultDir.'-'.$endpoint);
                }
            });
        }
```
```

<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Config;

class DocsGenerateCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'docs:generate {endpoint}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Scribe custom generation.';

    public function handle()
    {
        $endpoint = $this->argument('endpoint');

        $config = Config::get('scribe-'.$endpoint);
        $config['endpoint'] = $endpoint;
        if (is_null($config)) {
            $this->error('Configuration was not found: /config/scribe-'.$endpoint.'.php');
            return false;
        }

        Config::set('scribe', $config);

        Artisan::call('scribe:generate');
        $this->info(Artisan::output());
    }
}

```

**Comment by Mina-R-Meshriky** [comment]
the above worked very good,
but I also was enabling postman and the openapi so the following changes are required:
```php
 if (class_exists(\Knuckles\Scribe\Scribe::class)) {
            \Knuckles\Scribe\Scribe::afterGenerating(function (array $paths) {
                $endpoint = config('scribe.endpoint', null);
                if ($endpoint) {
                    $bladeDir = dirname($paths['blade']);
                    $openapiDir = dirname($paths['openapi']);
                    if($openapiDir) {
                        $contents = file_get_contents("$bladeDir/index.blade.php");
                        // Rewrite asset links to go through Laravel
                        $contents = str_replace('href="{{ route("scribe.postman") }}"', "href=\"{{ route(\"scribe-$endpoint.postman\") }}\"", $contents);
                        $contents = str_replace('href="{{ route("scribe.openapi") }}"', "href=\"{{ route(\"scribe-$endpoint.openapi\") }}\"", $contents);

                        file_put_contents("$bladeDir/index.blade.php", $contents);
                        
                        File::deleteDirectory($openapiDir . '-' . $endpoint);
                        rename($openapiDir, $openapiDir . '-' . $endpoint);
                    }

                    File::deleteDirectory($bladeDir . '-' . $endpoint);
                    rename($bladeDir, $bladeDir . '-' . $endpoint);
                }
            });
        }
```

and in the routes:
```php
$prefix = config('scribe-admin.laravel.docs_url', '/admin/docs');
$middleware = config('scribe-admin.laravel.middleware', []);
Route::namespace('\Knuckles\Scribe\Http')
    ->middleware($middleware)
    ->group(function () use ($prefix) {
        Route::get($prefix, function () {
            return View::make('scribe-admin.index');
        })->name('scribe-admin');
        Route::get($prefix.".postman", function () {
            return  response()->file(storage_path('app/scribe-admin/collection.json'));
        })->name('scribe-admin.postman');
        Route::get($prefix.".openapi", function () {
            return  response()->file(storage_path('app/scribe-admin/openapi.yaml'));
        })->name('scribe-admin.openapi');
    });
```

**Comment by Mina-R-Meshriky** [comment]
but still @shalvah if it is natively supported it would be better than this workaround.
because we should expect to see .scribe and .scribe-admin folders, but there is only one .scribe folder

**Comment by andreypopov** [comment]
Also I need different permissions for different sections of docs. So I have to create several APIs...

**Comment by shalvah** [comment]
> but still @shalvah if it is natively supported it would be better than this workaround.

Well, I'm only one man...🤷‍♀️

**Comment by shalvah** [comment]
You can now do this! https://scribe.knuckles.wtf/laravel/generating#generating-multiple-docs
