### ISSUE TITLE
Routing doesn't work in lumen

### ISSUE THREAD

**Issue by alibokiev** [knuckleswtf/scribe#365]
$router->group([
    'middleware' => $middleware
], function () use ($router, $prefix) {
    $router->get($prefix, ['uses' => [Controller::class, 'webpage'], 'as' => 'scribe']);
    $router->get("$prefix.postman", ['uses' => [Controller::class, 'postman'], 'as' => 'scribe.postman']);
    $router->get("$prefix.openapi", ['uses' => [Controller::class, 'openapi'], 'as' => 'scribe.openapi']);
});

Routing doesn't work in lumen. 

![image](https://user-images.githubusercontent.com/77080870/141415665-d916e68e-1e21-4e2d-815f-716b11cc296c.png)

in lumen is not accepted in uses array to pass as in laravel. Or maybe I missed something. I would be grateful if you correct me )

**Comment by alibokiev** [comment]
I fixed it this way

**Comment by shalvah** [comment]
Wow. Lumen really is terrible. Fixed in 3.16.0

**Comment by alibokiev** [comment]
yeah, partially agree :)
thanks !

**Comment by alibokiev** [comment]
@shalvah , sorry, I had a question off topic. Why can't I create another issue?
