### ISSUE TITLE
BodyParam's example is ignored when example array is empty

### ISSUE THREAD

**Issue by hetzner** [knuckleswtf/scribe#366]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I set my configuration to
```
@bodyParam myStatus object Description
@bodyParam myStatus.listOfValues string[] Description. Example: []
```
2. Then I ran `php artisan scribe:generate`
3. But I saw...

 The parameter is not visible at all:
```
'myStatus' => [
],
```

instead of...

  The example should show the empty array (because it's a valid value for that param)

```
'myStatus' => [
                'listOfValues' => [],
],
```

**My environment:**
 - PHP version (from `php -v`): 8.0.8
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): v8.70.2
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.15.0

**Comment by shalvah** [comment]
Fixed in 3.16.0
