### ISSUE TITLE
Type format specification?

### ISSUE THREAD

**Issue by mikebronner** [knuckleswtf/scribe#368]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Is there a way for specify the format of a field type? For example, I would like to specify the formats of `date` and `datetime` fields, as well as some string fields.

Thanks! :)

**Comment by shalvah** [comment]
There's no structured way to do that. You can just include it in each parameter's description, or put it somewhere general, like your Introduction section.
