### ISSUE TITLE
Errors in index.blade in Lumen

### ISSUE THREAD

**Issue by alibokiev** [knuckleswtf/scribe#369]
Hi !
Two problems after generation in index.blade.php:
1. After generating the documentation (when the type is laravel), css and js files are injected into index.blade using the asset method, and Lumen does not support this method.
2. The path to the files is specified as follows: "vendor/scribe/js/theme-default-3.16.0.js". There are two more problems, the first is that the file is actually in "vendor/knuckleswtf/scribe/resources/js/theme-default.js", the second is not indicated in the files, but in the script they are.
![image](https://user-images.githubusercontent.com/77080870/142396929-d2a9b571-1103-420f-b730-1795483b5b84.png)

If this is not a bug, and I missed something, I would be grateful for your help :)

**Comment by alibokiev** [comment]
I fixed it this way:
![image](https://user-images.githubusercontent.com/77080870/142397838-6aa49638-fd8b-4a56-b74e-127bd693028e.png)
 - replacing the asset method with url and manually specified the paths to the files. 
 I would be glad to know your opinion on how much this is correct. Thanks )

**Comment by victorioustr** [comment]
I made an asset helper as below.

`
if (!function_exists('urlGenerator')) {
    /**
     * @return \Laravel\Lumen\Routing\UrlGenerator
     */
    function urlGenerator() {
        return new \Laravel\Lumen\Routing\UrlGenerator(app());
    }
}

if (!function_exists('asset')) {
    /**
     * @param $path
     * @param bool $secured
     *
     * @return string
     */
    function asset($path, $secured = false) {
        return urlGenerator()->asset($path, $secured);
    }
}
`

**Comment by victorioustr** [comment]
I made an asset helper as below.

```php
if (!function_exists('urlGenerator')) {
    /**
     * @return \Laravel\Lumen\Routing\UrlGenerator
     */
    function urlGenerator() {
        return new \Laravel\Lumen\Routing\UrlGenerator(app());
    }
}

if (!function_exists('asset')) {
    /**
     * @param $path
     * @param bool $secured
     *
     * @return string
     */
    function asset($path, $secured = false) {
        return urlGenerator()->asset($path, $secured);
    }
}
```

**Comment by shalvah** [comment]
Good move @victorioustr . 

@alibokiev I'm not sure those hardcoded paths are meant to be so. The try-it-out JS should gave been copied to a location in your public path and named with the version. I doubt you can/should link directly to a file not in your public/ path; it's a security jole..

**Comment by shalvah** [comment]
Unfortunately, I don't know what's up with Lumen in this regard. If anyone can PR a good fix, that'd be good.

**Comment by alibokiev** [comment]
Yes you are right.  I then noticed that there are these files in the public folder.  but since the asset method is not supported importing does not work.

I created the asset method and connected it to the project.  I think this is a solution)
