### ISSUE TITLE
Multiple authentication methods

### ISSUE THREAD

**Issue by raccube** [knuckleswtf/scribe#370]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I'm working on an application which exposes two sets of APIs, one user-facing API which uses a bearer token and a backend API which uses an `X-API-Key` header.

Is there any way of configuring Scribe to use the relevant one?

**Comment by shalvah** [comment]
See https://github.com/knuckleswtf/scribe/issues/363 if you're talking about using Scribe to handle multiple APIs. If your question is about authentication _alone_, then maybe turn off Scribe's auth features and add the auth parameters to each endpoint manually. You can use route groups or custom strategies to make it easy, so you don't have to do it for each endpoint.
