### ISSUE TITLE
Suggestion: Scan routes instead of controllers for documentation metadata

### ISSUE THREAD

**Issue by Cogneter** [knuckleswtf/scribe#372]
Hello.

I've read https://scribe.knuckles.wtf/laravel/documenting/custom-endpoints and my case falls under the 3rd scenario - I need to document endpoints which are processed by controllers provided by Fortify.

I understand that the current indended way to document them is to edit the Camel files, however I would really like to keep my code documentation in one place (in the API code) and in one format (Camel files use a different documentation format).

Would it be possible to optionally scan route definitions instead of controllers for documentation?

So, for example, I would have this code in my /routes/api.php:
```
    /**
     * Logout
     *
     * This endpoint allows a user to log out, invalidating their token.
     */
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy']);
```

And Scribe would use the metadata provided above "Route:post", instead of scanning the AuthenticatedSessionController->destroy method for it.

**Comment by shalvah** [comment]
That is probably doable in some way, but I have no real incentive to make time for it, nor do I think it will become the default (for instance, how do you document `Route::resource()`?).

I'd suggest you give this a try yourself and see how it goes. Someone did something similar to extract docs from tests - https://github.com/knuckleswtf/scribe/issues/260.
