### ISSUE TITLE
Protected Documentation

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#378]
Hi there, I'm using scribe v2 because of some customization on the output docs, with some testing I should update soon.

Now I need to protect the docs URL using the user session auth, what is the better approach in laravel ?
Only authenticated users could consume the documentation URL, by default the '.../docs' is a public URL.

Maybe I'm creating a nonissue with this need... or there is a simple solution to this, but I don't get it for now.

Best Regards For All...keep safe.

**Comment by shalvah** [comment]
If you need to add middleware like authentication, use [`laravel` type](https://scribe.knuckles.wtf/laravel/reference/config#type) instead of `static` type.
