### ISSUE TITLE
Exported JSON files in Postman do not support describing this parameter setting

### ISSUE THREAD

**Issue by Zmingjun** [knuckleswtf/scribe#386]
I mean there is no option to set this description
![1638947050(1)](https://user-images.githubusercontent.com/23253933/145163754-be5ad1e1-2eb1-409c-9ffb-7ce391c5777c.png)

**Comment by shalvah** [comment]
PRs welcome. 🙂

**Comment by Zmingjun** [comment]
> 欢迎 PR。 🙂

I would like to ask if this setting is not available or I didn't finish reading the document

**Comment by shalvah** [comment]
It's currently not available for JSON, because we use `raw` for the request body (see the code [here](https://github.com/knuckleswtf/scribe/blob/a81d8785ed3f928f5c6a4dccc7f65968ede4987f/src/Writing/PostmanCollectionWriter.php#L161-L163)).. I don't think Postman supports that.  Are you using JSON?

**Comment by Zmingjun** [comment]
> I submitted in formData format and found that the description is not supported in Postman, but now I have rewritten the plugin, do I need to submit

**Comment by Zmingjun** [comment]
I used formData format to submit, and then FOUND that the description is not supported by Postman, but now I have added it on the original basis, do I need to submit it

**Comment by Zmingjun** [comment]
> 

Let me tidy it up😄

**Comment by shalvah** [comment]
Released in 3.33.0
