### ISSUE TITLE
Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by HAstaShakiba** [knuckleswtf/scribe#387]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I set my configuration to...
2. Then I ran `php artisan scribe:generate` ...
3. But I saw...

docs/js/theme-default-3.19.0.js:6

**Screenshots and stack traces:**

**My environment:**
 - PHP version (from `php -v`): 8.0
 - Framework (Laravel/Lumen): laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 8.75
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.19.0

**My Scribe config (minus the comments):**

**Additional info:**

**Comment by shalvah** [comment]
That sounds like the lodash JS script was not loaded. You should check your internet and check the Network tab of DevTools to confirm.

**Comment by HAstaShakiba** [comment]
please check `index.blade.php`  lodash script cdn.
