### ISSUE TITLE
Wrong alphabetical sort, when having many controllers in one group.

### ISSUE THREAD

**Issue by Mina-R-Meshriky** [knuckleswtf/scribe#389]
https://github.com/knuckleswtf/scribe/blob/30ea2dc97571b4ae675cb7f4ead6c0588d97a0ee/camel/Camel.php#L144

Example of current $e->endpointId()
```
GETapi-v1-industries
GETapi-v1-languages
```

in the above example all the get will be sorted together
Instead it should be $e->uri, so it can be sorted by the route itself. Example
```
api/v1/industries 
api/v1/industries/{industry} 
api/v1/languages
```

**Comment by shalvah** [comment]
Good point.

**Comment by retry19** [comment]
@Mina-R-Meshriky do have any tips? if want to debug to know value from some variable, e.g. `GETapi-v1-industries` or do you using xdebug?

**Comment by 090809** [comment]
@shalvah purpose about it:
1) I think, we can use default laravel sort (by uri), and not use indexes sorts.
2) We also can use all of `'/', '?', '{', '}', ':', '\\', '+', '|'` symbols for url formatting. It works fine.
3) For `tryItOut` we must escape all of this symbols.

If you interested for this, can push PR for it.

**Comment by shalvah** [comment]
Sure, but please include a test case to demonstrate what you mean.

**Comment by shalvah** [comment]
I don't think this is an issue. See https://github.com/knuckleswtf/scribe/pull/423#discussion_r800165816
