### ISSUE TITLE
Should I add .scribe folder to gitignore

### ISSUE THREAD

**Issue by 4unkur** [knuckleswtf/scribe#390]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I've upgraded from v2 to v3 and noticed that .scribe folder appeared in the root of the project. Is it safe to add it to .gitignore? Or is it something like composer.lock file?

**Comment by shalvah** [comment]
https://scribe.knuckles.wtf/laravel/generating#the-scribe-folder
