### ISSUE TITLE
Uncaught TypeError: hljs.highlightAll is not a function

### ISSUE THREAD

**Issue by bjhijmans** [knuckleswtf/scribe#393]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I updated Scribe from 3.16 to 3.19.1
2. Then I ran `php artisan scribe:generate`
3. But when I load the documentation page I got the error `Uncaught TypeError: hljs.highlightAll is not a function`

The error is on line 44 of theme-default-3.19.1.js. It didn't happen in 3.16, and I've been trying to understand why, but I can't figure it out. hljs is set, but it doesn't have the highlightAll function, even though highlight.js v10.7.2 does have that method.

**My environment:**
 - PHP 8.0.12
 - Framework Laravel:
 - Laravel version 8.76.1 
 - Scribe version 3.19.1: 

**My Scribe config (minus the comments):**
```
[
    'theme' => 'default',
    'title' => config('app.name') . ' API Documentation',
    'description' => '',
    'base_url' => null,
    'routes' => [[
        'match' => [
            'domains' => ['*'],
            'prefixes' => ['api/*'],
            'versions' => ['v1'],
        ],
        'include' => [],
        'exclude' => [],
        'apply' => [
            'headers' => ['Content-Type' => 'application/json', 'Accept' => 'application/json'],
            'response_calls' => [
                'methods' => [],
                'config' => ['app.env' => 'documentation'],
                'queryParams' => [],
                'bodyParams' => [],
                'fileParams' => [],
                'cookies' => [],
            ],
        ],
    ]],
    'type' => 'laravel',
    'static' => [
        'output_path' => 'public/docs',
    ],
    'laravel' => [
        'add_routes' => false,
        'docs_url' => '/api-documentation',
        'middleware' => [],
    ],

    'try_it_out' => [
        'enabled' => false,
        'base_url' => null,
        'use_csrf' => false,
        'csrf_url' => '/sanctum/csrf-cookie',
    ],
    'auth' => [
        'enabled' => true,
        'default' => true,
        'in' => 'bearer',
        'name' => 'key',
        'use_value' => env('SCRIBE_AUTH_KEY'),
        'placeholder' => '{API_TOKEN}',
        'extra_info' => '',
    ],
    'intro_text' => '...'
    'example_languages' => [
        'bash',
        'javascript',
        'python',
        'php',
    ],
    'postman' => [
        'enabled' => true,
        'overrides' => [
            // 'info.version' => '2.0.0',
        ],
    ],
    'openapi' => [
        'enabled' => true,
        'overrides' => [
            // 'info.version' => '2.0.0',
        ],
    ],
    'default_group' => 'Endpoints',
    'logo' => false,
    'faker_seed' => null,
    'strategies' => [
        'metadata' => [
            Strategies\Metadata\GetFromDocBlocks::class,
        ],
        'urlParameters' => [
            Strategies\UrlParameters\GetFromLaravelAPI::class,
            Strategies\UrlParameters\GetFromLumenAPI::class,
         //   Strategies\UrlParameters\GetFromUrlParamTag::class,
        ],
        'queryParameters' => [
            Strategies\QueryParameters\GetFromFormRequest::class,
            Strategies\QueryParameters\GetFromInlineValidator::class,
            Strategies\QueryParameters\GetFromQueryParamTag::class,
            \App\Http\Api\Docs\Strategies\AddFilterParam::class,
            \App\Http\Api\Docs\Strategies\AddSortParam::class,
            \App\Http\Api\Docs\Strategies\AddIncludeParam::class,
        ],
        'headers' => [
            Strategies\Headers\GetFromRouteRules::class,
            Strategies\Headers\GetFromHeaderTag::class,
        ],
        'bodyParameters' => [
            Strategies\BodyParameters\GetFromFormRequest::class,
            Strategies\BodyParameters\GetFromInlineValidator::class,
            Strategies\BodyParameters\GetFromBodyParamTag::class,
        ],
        'responses' => [
            Strategies\Responses\UseTransformerTags::class,
            Strategies\Responses\UseResponseTag::class,
            Strategies\Responses\UseResponseFileTag::class,
            Strategies\Responses\UseApiResourceTags::class,
            Strategies\Responses\ResponseCalls::class,
            \App\Http\Api\Docs\Strategies\AddExampleResponses::class,
            \App\Http\Api\Docs\Strategies\AddPaginatedExampleResponses::class,
        ],
        'responseFields' => [
            Strategies\ResponseFields\GetFromResponseFieldTag::class,
        ],
    ],
    'fractal' => [
        'serializer' => null,
    ],
    'routeMatcher' => \Knuckles\Scribe\Matching\RouteMatcher::class,
    'database_connections_to_transact' => [config('database.default'), config('database.default')]
]
```
**Additional info:**

**Comment by shalvah** [comment]
I'm not sure what could cause this....

Try out v3.20 and let me know if it still occurs.

**Comment by rickdubiel** [comment]
I had the same issue. The highlight.js changelog states the following:

> Deprecations / Removals / API Changes:
>     initHighlighting() and initHighlightingOnLoad() deprecated. Use highlightAll().

Which can be found here:

https://highlightjs.org/#news-142

So I tried upgrading the version used in the index.blade.php stub file and regenerating the docs but the error remains. The only way I could get it to work was to adjust this line within the `theme-default.js` file:
```
window.hljs.highlightAll();
```
to this:
```
window.hljs.initHighlighting();
```
This works even when using the latest version of `highlight.js` (currently Version 11.3.1), which according to their changelog it's not supposed to work. Perhaps a bug in the plugin?

**Comment by shalvah** [comment]
That's strange. Did we somehow update the version of h1js included? If we didn't, the changelog shouldn't apply to us. I'll need to check.

**Comment by bjhijmans** [comment]
My problem was the Laravel debugbar. It also loaded highlighjs, but an older version. And then Scribe used that version because it was loaded later. Excluding the api docs routes from the debugbar fixed the issue.

**Comment by shalvah** [comment]
Well then.

Checked and there was no upgrade.

**Comment by mahdi-mh** [comment]
I have same problem with version 3.20, I generate scribe doc as  laravel blade. and i have not Laravel debugbar.
error in chrome console:

document:7972 Uncaught ReferenceError: $ is not defined
    at document:7972
(anonymous) @ document:7972
theme-default-3.20.0.js:26 Uncaught TypeError: window.Jets is not a constructor
    at HTMLDocument.<anonymous> (theme-default-3.20.0.js:26)

**Comment by mahdi-mh** [comment]
I copy old version with `theme-default-3.20.0.js` and `tryitout-3.20.0.js` so worked for me but why newest version have bug !!

**Comment by retry19** [comment]
> My problem was the Laravel debugbar. It also loaded highlighjs, but an older version. And then Scribe used that version because it was loaded later. Excluding the api docs routes from the debugbar fixed the issue.

Yup, it's happen on me too when laravel-debugbar is active

**Comment by marijoo** [comment]
Can confirm this is happening in the latest version of scribe and everything works fine if I disable the Debugbar.

**Comment by shalvah** [comment]
I'm not sure what else we can do about this. DebugBar is loading a different version of highlight.JS, which conflicts. I recommend you exclude the docs route from debug bar, if that's possible.

**Comment by rickdubiel** [comment]
This did the trick for me. Added the following to `config/debugbar.php`:

```
'except' => [
    'docs',
],
```

**Comment by hooman-mirghasemi** [comment]
In last version with laravel 9
I have problem:
document:13662 Uncaught ReferenceError: $ is not defined
    at document:13662:5
(anonymous) @ document:13662
theme-default-3.23.0.js:27 Uncaught TypeError: window.Jets is not a constructor
    at HTMLDocument.<anonymous> (theme-default-3.23.0.js:27:19)

**Comment by stephanesoares** [comment]
> In last version with laravel 9 I have problem: document:13662 Uncaught ReferenceError: $ is not defined at document:13662:5 (anonymous) @ document:13662 theme-default-3.23.0.js:27 Uncaught TypeError: window.Jets is not a constructor at HTMLDocument. (theme-default-3.23.0.js:27:19)

Anyone found solution for this? 
I disable debugbar, switch debug to false, problem continue...

**Comment by hooman-mirghasemi** [comment]
check if you do vendor publish for scribe html,
check : https://scribe.knuckles.wtf/laravel/troubleshooting#delete-old-published-templates
