### ISSUE TITLE
menu <a href ... style changes design

### ISSUE THREAD

**Issue by romanstingler** [knuckleswtf/scribe#396]
in the latest version you have `<a href` .... for the links but the stylesheet is not applied

![Screenshot from 2021-12-20 09-26-21](https://user-images.githubusercontent.com/5576250/146736261-6c66358e-a44b-4016-9bcf-d3aa99ef5650.png)
The old version was displayed correctly.

![Screenshot from 2021-12-20 09-26-31](https://user-images.githubusercontent.com/5576250/146736282-ccb63d3f-6f78-4f66-833d-d1277b2022f7.png)

**Comment by shalvah** [comment]
Umm...I can't reproduce this.

Can you try out the latest v3.20 and let me know?
