### ISSUE TITLE
Custom Endpoint

### ISSUE THREAD

**Issue by romanstingler** [knuckleswtf/scribe#397]
Is there a way to add validators to the custom endpoint file?
Because it seems that I have to append the whole text after the description.

Thanks in advance

**Comment by leandrodiogenes** [comment]
Hi @romanstingler  , i can't understand.
Can you give more details about your question?

**Comment by shalvah** [comment]
Do you mean writing Laravel validation code in an endpoint YAML file? If so, that's not supported and won't be. The clue is in the name... _Laravel_ validators. We're not going to start reimplementing the parsing logic already in Laravel.
