### ISSUE TITLE
Dynamic Documentation by User Access Routes

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#398]
Hi,

I have some endpoints that are only visible to some users.
For now, the documentation is for all endpoints.... I changed the documentation to be "laravel" for blade and route control, so only auth users can access the documentation.

What I need, is dynamic documentation...if user A does not have access to endpoint B, the documentation of endpoint B is hidden/do not show. but if some user has access to endpoint B, if he goes to the documentation then endpoint B information is visible to him.

I want to know if the package support this need or you may point me to the right solution, that suit better with you awesome package.

Best Regards

**Comment by shalvah** [comment]
This package doesn't support that, but by switching to `laravel` as you did, you can implement it yourself, with a bit of work.

You can create a custom theme, so you'll override the default Blade file with yours. In your template, you can then add code that will check for the current user and their permissions, before rendering the endpoint or not.

(Note that the Blade file you provide is not the view that will be rendered for your user, but the template that will be combined with the endpoints data and used to generate that view, so be sure to write the correct code.)

**Comment by pirex360** [comment]
Thank you for the quick advice.

I will try your way... I think that I understand the logic...
It's like a rule only for that view that checks prior if the user has access or not to render.


Thank you, once again.
