### ISSUE TITLE
Adjusting the Test URL?

### ISSUE THREAD

**Issue by WorthLMS** [knuckleswtf/scribe#399]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I am using Spatie Query Builder on Laravel 8.

The url setup requires something along the lines of filter['related.property']=x

My issue, is that the test url generates the following (albeit encoded)... filter[related][property]=xd

Anyway to fix this?

**Comment by shalvah** [comment]
That means you're specifying `filter[related]` add on object, with `property` as a field, so Scribe follows that. We don't know anything about the dot notation. 

Don't think there's anything that can be done there, except maybe a custom strategy or something.

**Comment by WorthLMS** [comment]
I am doing the following

@queryParam filter[x.y] string Example: 1

This should translate in the test url to ?filter[x.y]=1

But the test url is generating it as filter[x][y]=1...

Surely there is somewhere that this can be modified to not break the dot notation

**Comment by shalvah** [comment]
I see. That's tricky, and I doubt it can be overridden anywhere because there's a lot that relies on/assumes dot notation. Try prefixing the dot with a backslash, as in "x\.y".
