### ISSUE TITLE
DB transactions with multiple connections

### ISSUE THREAD

**Issue by hendrikbl** [knuckleswtf/scribe#4]
Strategies that utilize database transactions do not work correctly with multiple database connections configured. It always uses the default connection:

[DatabaseTransactionHelpers.php](https://github.com/knuckleswtf/scribe/blob/master/src/Extracting/DatabaseTransactionHelpers.php)
```
app('db')->beginTransaction();
```

I started adding support for multiple connections in [my fork](https://github.com/hendrikbl/scribe/tree/multi-connection). It simply gets the connection from the model type and passes it to the `startDbTransaction` and `endDbTransaction` function.

I'm not sure though how to do it in [ResponseCalls.php](https://github.com/knuckleswtf/scribe/blob/master/src/Extracting/Strategies/Responses/ResponseCalls.php) since I don't know any way to get the utilized connection from the route itself. One way could be simply iterating over all connections and starting and ending transactions for all connections. But if there is a better method I'd prefer that :D

Let me know what you think and if i missed anything.

**Comment by shalvah** [comment]
Yup, I've wondered about that before.

> One way could be simply iterating over all connections and starting and ending transactions for all connections. 
That's a good idea, and possibly the simplest method. Feel free to go for it.😄

**Comment by shalvah** [comment]
(Also, for future purposes, you shouldn't need a fork. Just extend the ResponseCalls class, override the needed methods and replace it in the `strategies` config. 🙂)
