### ISSUE TITLE
Include raw in request.url?

### ISSUE THREAD

**Issue by chriserikhaugli** [knuckleswtf/scribe#40]
Hi,

I'm using Insomnia, and when I import _collection.json_ the urls to the endpoints are empty.

Importing to Postman, exporting from there and importing again to Insomnia makes be believe that this could be fixed by adding _raw_ to the export:
```
"item": [
{
  "name": "/myendpoint",
  "request": {
    "url": {
      **"raw": "https://example.com/myendpoint",**
      "protocol": "https",
      "host": "example.com",
      "path": "/myendpoint",
      "query": []
    },
}
]
```

Should this be added, to conform to the way Postman exports its endpoints?

**Comment by shalvah** [comment]
Sure.

I see the `raw` property mentioned in the (schema)[https://schema.getpostman.com/collection/json/v2.0.0/draft-04/collection.json], though it would be nice to have specific documentation of which is used in what scenarios.

Seems like a pretty straightforward change. PRs welcome.
