### ISSUE TITLE
Inherited methods in controllers?

### ISSUE THREAD

**Issue by MaRmARk0** [knuckleswtf/scribe#402]
Hi there,
I've just discovered a possible problem with simple inheritance. I have a BaseController which in simplified form looks like this:

```
abstract class BaseCollectorController extends Controller
{
    /**
     * @var string Required CollectorInterface
     */
    protected string $collectorClass;

    /**
     * @param FilterRequest $request
     */
    public function index(FilterRequest $request)
    {
        $response = [];

        $collector = $this->createCollector($this->collectorClass);
        $response = $collector->collect();
        // some additional logic 

        return response()->json($response);
    }
}
```

and then multiple extended controllers like this:
```
/**
 * @group Reports
 */
class KpiController extends BaseCollectorController
{

    /**
     * @inheritdoc
     */
    protected string $collectorClass = KpiCollector::class;
}
```

Then I have a route like this:
```
Route::post('kpi', [\Bla\Bla\KpiController::class, 'index'])->name('bla-bla.kpi.index');
```

Is there any intelligent way to document `KpiController::index()` method except doing this?

```
    /**
     * Title
     *
     * Description
     *
     * @param FilterRequest $request
     *
     * @return \Illuminate\Http\JsonResponse|mixed
     */
    public function index(FilterRequest $request)
    {
        // Just for API docs
        return parent::index($request);
    }
```

Thanks.

- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

**Comment by shalvah** [comment]
Not really, no.

What exactly do you get when you don't reimplement the method? No docs for that endpoint? Or the same for all the overridden endpoints?

**Comment by MaRmARk0** [comment]
If I inherit/override method I'll get all the docs as expected. But you know this way I actually have to add/modify _real code_ just to get the docs generated. Until now I only had to add/modify _PHPdocs_ instead of code.

I'm just thinking loud - maybe I could use PHPdoc above controller (not method)? This way I wouldn't be forced to actually override method(s).

E.g.:

```
/**
 * @group Reports
 * @method index response=200 {"success":true}
 * @method index response=500 {"success":false}
 */
class KpiController extends BaseCollectorController
{

    /**
     * @inheritdoc
     */
    protected string $collectorClass = KpiCollector::class;
}
```

Maybe a other users would too prefer writing one big PHPdoc above class and not above each method. Don't know.

**Comment by shalvah** [comment]
Will give this a shot for the next major.

**Comment by shalvah** [comment]
Done in v4: https://scribe.knuckles.wtf/laravel/tasks/sorting-and-inheritance#overriding-docs-for-inherited-controller-methods
