### ISSUE TITLE
Installation fails with Laravel 9.x

### ISSUE THREAD

**Issue by Rubenpannen** [knuckleswtf/scribe#407]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

Currently trying to install Laravel 9.x, but installation fails because one of the requirements for Laravel 9 is version 6.x of nunomaduro/collision and the latest version of scribe is locked at  version ^3.0|^4.0|^5.0 for nunomaduro/collision.

**My environment:**
 - PHP version (from `php -v`): 

PHP 8.1.1 (cli) (built: Dec 15 2021 10:31:43) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies

 - Framework (Laravel/Lumen): Laravel v8.79.0
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`):

**Comment by shalvah** [comment]
Use `dev-master`. Laravel 9 is supported.
