### ISSUE TITLE
How do i customize colors or put a light theme?

### ISSUE THREAD

**Issue by acgfbr** [knuckleswtf/scribe#41]
Is possible edit this color?

![image](https://user-images.githubusercontent.com/8755427/84842726-41ef5c00-b01c-11ea-9858-353f4f245ea1.png)

**Comment by shalvah** [comment]
Not from here, no. The HTML structure, CSS and JS files are hardcoded in [Pastel] (http://GitHub.com/knuckleswtf/pastel). Custom templates may be supported someday, but not right now. However, you can open a PR to add such a feature to Pastel if you wish.

**Comment by shalvah** [comment]
See the RFC that would help with this: #105

**Comment by shalvah** [comment]
With this, you'd be able to add custom styles, probably in your Laravel config file, or make or pick a different theme (including layout) altogether.

**Comment by Hesesses** [comment]
I would also like to edit just the colors in the first post. The only thing from docs I can see it to publish all files and edit those... Is there any other ways to change just the background color?
