### ISSUE TITLE
Bug with loading (creating) relation of belongsTo relation. (dot notation)

### ISSUE THREAD

**Issue by 090809** [knuckleswtf/scribe#415]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
When using `@apiResourceModel` and `with` parameter, it WILL NOT create relationships of BelongsTo connected model.

Example:
I have an Event, it was created by user:
```php
class Event extends Model
{
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
```

And I have a User model, that having MorphTo relation (spatie lib):
```php
class User extends Model
{
    public function media(): MorphMany
    {
        return $this->morphMany(config('media-library.media_model'), 'model');
    }
}
```

Of all of them I have an Factories. But!
For today, BelongsTo relations using this code:
https://github.com/knuckleswtf/scribe/blob/60e421cdded157864f8757878e23a144b7878169/src/Tools/Utils.php#L248-L256
So when Scribe calls ->create() of factory method, the Laravel will call this code [(link)](https://github.com/laravel/framework/blob/4735b0e287fa0fa35a7a98586497c89500c145a4/src/Illuminate/Database/Eloquent/Factories/Factory.php#L307-L318):

```php
protected function store(Collection $results)
{
    $results->each(function ($model) {
        if (! isset($this->connection)) {
            $model->setConnection($model->newQueryWithoutScopes()->getConnection()->getName());
        }

        $model->save();

        $this->createChildren($model);
    });
}
```

Where createChildren will call `createFor` as Parent instead of Child (there logic reverse), and it will exit from it without creating children of selected model, 'cause it doesn't have scenario for BelongsTo implementations
```php
    public function createFor(Model $parent)
    {
        $relationship = $parent->{$this->relationship}();
        
        if ($relationship instanceof MorphOneOrMany) { // its realizing by MorphOne and MorphMany
            $this->factory->state([
                $relationship->getMorphType() => $relationship->getMorphClass(),
                $relationship->getForeignKeyName() => $relationship->getParentKey(),
            ])->create([], $parent);
        } elseif ($relationship instanceof HasOneOrMany) { // its realizing by MorphOne, MorphMany, HasOne, HasMany
            $this->factory->state([
                $relationship->getForeignKeyName() => $relationship->getParentKey(),
            ])->create([], $parent);
        } elseif ($relationship instanceof BelongsToMany) { // its realizing itself: BelongsToMany.
            $relationship->attach($this->factory->create([], $parent));
        }

        // exit without creating of BelongsTo
    }
```

**My environment:**
 - PHP version (from `php -v`): 8.0
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): v8.80.0
 - Scribe version (from `composer show knuckleswtf/scribe`): dev-master

**Suggestion:**
Add 
```php
} else if ($relationType === BelongsTo::class) {
    $factory = $factory->for($factoryChain);
}
```
To 
https://github.com/knuckleswtf/scribe/blob/60e421cdded157864f8757878e23a144b7878169/src/Tools/Utils.php#L248-L256

### BUT! 
It doesnt normally works with relations with `name != relation class snakecased name`, so it need more research, explain:
Have class Tag and TagGroup, Tag belongsTo TagGroup in function named group(), and when I try to generate docs, it will try to create record with `group_id` instead of `tag_group_id`. IDK why its happens, but it is (And I'm tired for today, will continue research tomorrow).

**Comment by shalvah** [comment]
Thanks for the report. I don't use that area personally, so I don't have the needed context to investigate or fix it. Feel free to send in a PR with a fix (and a test, if possible—ping me if you're stuck).

**Comment by 090809** [comment]
@shalvah, I've test this issue more completly, but now, for complete testing we need to use Laravel 8 extended factory methods and in-memory sqlite. 
Completly it solves by add
```diff
                if ($relationType === BelongsToMany::class) {
                    $pivot = method_exists($factory, 'pivot' . $relationVector)
                        ? $factory->{'pivot' . $relationVector}()
                        : [];

                    $factory = $factory->hasAttached($factoryChain, $pivot, $relationVector);
+               } else if ($relationType === BelongsTo::class) {
+                    $factory = $factory->for($factoryChain, $relationVector);
+               } else {
                    $factory = $factory->has($factoryChain, $relationVector);
                }
```

My Issue was wrong in naming - it's handles by setted right foreign_key in models
And, of course, need to create right configure factory methods for `load` nested relation to create correct docs

I can create a pull request for it, but IDK how to split current tests and test with factory methods (and sqlite with anonymous migration) to not to break all another tests
