### ISSUE TITLE
Uncaught TypeError: event is undefined in js

### ISSUE THREAD

**Issue by bjhijmans** [knuckleswtf/scribe#416]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
Whenever I click a sub-item of a menu item, I get a type error in my console that says `event` is not defined.

The problem occurs in theme-default.js on line 16 in the closeSidebar function. Here is the definition of the function:
```
function closeSidebar(event) {
        event.preventDefault();
        if (menuWrapper) {
            menuWrapper.classList.remove('open');
            navButton.classList.remove('open');
        }
    }
```
And the only place where it's called is on line 82:
```
    closeSidebar();
```
No parameter is passed here, so the `event` parameter is undefined.

My guess is you can simply remove the parameter and the `event.preventDefault()` call, but there might be a reason it's there that I'm not aware of?

**My environment:**
 - PHP version (from `php -v`): 8.0
 - Framework (Laravel/Lumen): Laravel
 - Laravel version 8.76.1: 
 - Scribe version 3.21.0: 

**My Scribe config (minus the comments):**

**Additional info:**

**Comment by shalvah** [comment]
Thanks for the report. Do any other visible bugs happen when you click?
