### ISSUE TITLE
Can't get scribe works with Laravel 8x

### ISSUE THREAD

**Issue by HELMAB** [knuckleswtf/scribe#418]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I set my configuration to...
2. Then I ran `php artisan scribe:generate` ...
3. But I saw... ``` Undefined offset: 1```

instead of...

**Screenshots and stack traces:**
![Screenshot from 2022-01-30 00-25-06](https://user-images.githubusercontent.com/15307857/151670967-54e9eb91-306e-4a62-aeff-75853d6f3d78.png)

**My environment:**
 - PHP version (from `php -v`): 7.4.27
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 8.81.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.22.0

**My Scribe config (minus the comments):**
I didn't change the scribe configuration file.

Does anybody what definely I missing?

**Comment by shalvah** [comment]
You need to do a little debugging. Edit that code and dump the `$routeControllerAndMethod`.

**Comment by HELMAB** [comment]
Hello @shalvah 

I've debugged and found that cause from `api.php` route file. it has only an element.

![Screen Shot 2022-01-30 at 11 50 53 AM](https://user-images.githubusercontent.com/15307857/151687162-4a749ffb-1945-4813-a1e7-cccf33c70d69.png)

And my `api.php' route file
