### ISSUE TITLE
How do I...?

### ISSUE THREAD

**Issue by barsengin** [knuckleswtf/scribe#42]
Is there anyway to customize markdown files(api documentation output) customization setting? or  how can i customize all api endpoint parameters preview on api documentation files as bottom ?

|Parameter       |Type                      |Description                 |
|--------------------|-------------------------|-----------------------------|
|parameter_1	 |integer			| description.....           |
|parameter_2    |string		        | description.....           |

**Comment by shalvah** [comment]
I don't really understand your question. But if you mean customising the output, yes, you can. [See the docs](https://scribe.readthedocs.io/en/latest/customization.html).

**Comment by barsengin** [comment]
> php artisan scribe:generate 
 my output:
![output](https://user-images.githubusercontent.com/33950394/84986604-7f9cd380-b147-11ea-81da-b5bbc9962010.png)

But ı my goal output 
![goal_output](https://user-images.githubusercontent.com/33950394/84986652-93483a00-b147-11ea-87e0-ddc00b78be50.png)

I could customize it manuel, after generated.But can I add any settings to it without customizing the output file manually. Because there are lots of api endpoints

**Comment by shalvah** [comment]
Please see the linked docs. You don't have to customise it manually. What you'll need to do is publish the vendor views (the Blade files where the layout is specified) and adjust the layout in there (should be the partials/route.blade.php file). Then generate as normal.

https://scribe.readthedocs.io/en/latest/customization.html#changing-the-markdown-templates

**Comment by barsengin** [comment]
it was very useful for me. Thank you so much
