### ISSUE TITLE
Collapsable response fields?

### ISSUE THREAD

**Issue by rickdubiel** [knuckleswtf/scribe#420]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Is it possible to set up the "Response Fields" so that they can expand and collapse just like the request "Body Parameters" can?

Body Parameters Collapsed
![image](https://user-images.githubusercontent.com/18044230/151719673-3802a526-7e61-4ae9-8e0f-5d06e3627f5b.png)

Body Parameters Expanded
![image](https://user-images.githubusercontent.com/18044230/151719681-89bdeebf-17dd-490d-bb02-50a547d98b2c.png)

Response Parameters don't Expand/Collapse
![image](https://user-images.githubusercontent.com/18044230/151719698-ee351d60-a688-4f9f-a093-defcde4578ec.png)

**Comment by shalvah** [comment]
I think it can be done. PRs are welcome.

**Comment by shalvah** [comment]
This is now done in v4
