### ISSUE TITLE
Custom docs pages with markdown support without the right side.

### ISSUE THREAD

**Issue by Erth0** [knuckleswtf/scribe#425]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel/documenting/custom-endpoints) and I can't find details on how to achieve this.
I would like to achieve custom doc pages with markdown support where I can add custom navigation so basically I can have on the sidebar.
- Main link
   - Sub link
   - Sub link
All of this without the need of all the methods from custom.x.yaml
Is this possible at the current state otherwise maybe I can make a PR.
Thank you very much!

**Comment by shalvah** [comment]
No, I think that's beyond the capabilities of Scribe right now.
