### ISSUE TITLE
Can I use with the multiple URLs ?

### ISSUE THREAD

**Issue by ysfkaya** [knuckleswtf/scribe#426]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hello, I have a SaaS project. So, I'd like to set central url and tenant url in the documentation.

For example:

Central:

- `https://api.test/tenants`
- `https://api.test/tenants/{id}/domains`

Tenant:

- `https://acme.api.test/users`
- `https://acme.api.test/products`

Is there a way to do this somehow?

**Comment by shalvah** [comment]
Do you mean that some endpoints are for the tenant domain, while some are for the central domain? No, that's not supported. You might have to use another tool for that (or fork Scribe).
