### ISSUE TITLE
How would you create more badges?

### ISSUE THREAD

**Issue by Drillan767** [knuckleswtf/scribe#428]
Hello,

I'm in the process of documenting my company's API, but we use [Spatie Laravel Permission](https://spatie.be/docs/laravel-permission/v4/introduction), and some routes cannot be accessed with the wrong role / permission.

What would be the best way to add badges, like, one that would say "requires role `Owner`", or "Can `read site infos`"?

Thank you in advance, and thank you for this amazing package!

**Comment by shalvah** [comment]
Seen this? https://scribe.knuckles.wtf/laravel/reference/html#badges

You could manually add that to every endpoint's description, or [create a custom strategy](https://scribe.knuckles.wtf/laravel/advanced/plugins) that can handle that.

**Comment by Drillan767** [comment]
I was about close and say that I found what I was looking for, but you're really fast! Thanks for the links!
