### ISSUE TITLE
`@header` should allow supplying values to the `Try It Out` section

### ISSUE THREAD

**Issue by ElvenSpellmaker** [knuckleswtf/scribe#429]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Similar to the other options like `@bodyParam` the `@header` should allow us to supply a header in the Try It Out section. I can't seem to find a way of achieving this currently.

Use case: A Mock API where responses are returned based on headers so tests can pass headers and pass in environments without the real API.

**Comment by shalvah** [comment]
This would be interesting, but it's a bit difficult. Where would this fit in the UI? Also, all headers are treated equally, so we would have to show all the headers.

Best I can think of is to maybe hide the headers behind a `<details>` view that you can expand if you want to customise headers.

**Comment by salvationarinze** [comment]
I really need this. Is there a way to achieve this yet even using the `<details>` view. Can't seem to find the docs

**Comment by shalvah** [comment]
Headers are now displayed in the generated docs in the `default` theme. There's also a new theme, `elements`, that also does this.
