### ISSUE TITLE
How to make scribe work with multiple level url?

### ISSUE THREAD

**Issue by gitstashgithub** [knuckleswtf/scribe#434]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hi guys,

Our url for the doc is `http://localhost:9000/api/v2/docs`, and it's redirected to Laravel `public/docs` folder.
Currently all css, js, images and etc are not loaded correctly
![image](https://user-images.githubusercontent.com/16966392/153687938-8143298b-8fba-49a6-9273-b987aedabb27.png)
As you can see, the css href is `"../docs/css/theme-default.print.css"`, which doesn't work for me because it assumes the upper level is 'v2', which doesn't exist. The correct css href should be `"./docs/css/theme-default.print.css"`, which has one dot.

I found that the href path is set in `vendor/knuckleswtf/scribe/src/Writing/HtmlWriter.php` constructor
![image](https://user-images.githubusercontent.com/16966392/153687682-1eafa73e-911f-4db8-ba4c-fd006fdd2fda.png)
by default the `assetPathPrefix` value is '../docs/' or './', and I cannot find any place to update it. Do you know to make it work?

Thank you,
Gordon

**Comment by shalvah** [comment]
Did you look at the config file? If the [`output_path`](https://scribe.knuckles.wtf/laravel/reference/config) setting does not work for you, then use an [`afterGenerating()`](https://scribe.knuckles.wtf/laravel/hooks#aftergenerating) hook to rewrite the paths.
