### ISSUE TITLE
How to add sections to intro.md permanently?

### ISSUE THREAD

**Issue by gitstashgithub** [knuckleswtf/scribe#437]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hi guys, 

I would like to add some more sections to intro.md, like API rate limit, release notes and etc. I added them in the intro.md file, but after I run `php artisan scribe:generate --force` they are all gone. I added `--force` because `intro_text` was changed after. Do you know how to keep the intro.md change permanently? Or maybe I should save the section in another file?

Thank you,
Gordon

**Comment by shalvah** [comment]
How about `"intro_text" => file_get_contents('some-other-file.md')`?

**Comment by gitstashgithub** [comment]
Thanks @shalvah , I tried it but still have some minor issue. I added `'intro_text' => file_get_contents(resource_path('scribe/intro.md')),` in scribe.php file, and in this file there's only one line: `# Section test`.

The generated .scribe/intro.md file content is:
````
# Introduction

Welcome to the API reference.

# Section test


> Base URL

```yaml
http://localhost
```
````

So the Base URL section is attached to the end of the intro.md file, which is not ideal for my document. I guess my only solution is to use `php artisan vendor:publish --tag=scribe-views` to customise the template?
