### ISSUE TITLE
Incorrect Headers on Response Calls

### ISSUE THREAD

**Issue by th0rn0** [knuckleswtf/scribe#44]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

I've been looking at the ResponseCalls for automated documentation on some projects I'm working on. Mostly, they seem to work but I've come across a weird error where it seems that headers are not getting set? 

Example that's generated:

curl -X POST \
    "http://iam.localhost/api/1/auth/register" \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Authorization: Bearer {token}" \
    -H "asdasd: asdasd" \
    -d '{"first_name":"Joe","last_name":"Bloggs","email":"joeBloggs@example.com","password":"supersecret"}'

When running scribe:generate I dumped the headers on that request

^ Illuminate\Support\Collection^ {#2862
  #items: array:5 [
    "host" => "iam.localhost"
    "user-agent" => "Symfony"
    "accept" => "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    "accept-language" => "en-us,en;q=0.5"
    "accept-charset" => "ISO-8859-1,utf-8;q=0.7,*;q=0.7"
  ]
}

However running the example from the Postman Collection that's generated works due to postman putting in the Content-Length.

^ Illuminate\Support\Collection {#1147
  #items: array:13 [
    "accept-encoding" => "gzip"
    "x-real-ip" => "172.22.0.1"
    "x-forwarded-server" => "1206b265bdde"
    "x-forwarded-proto" => "http"
    "x-forwarded-port" => "80"
    "x-forwarded-host" => "iam.localhost"
    "x-forwarded-for" => "172.22.0.1"
    "content-type" => "application/json"
    "cache-control" => "no-cache"
    "authorization" => "Bearer SOMETOKEN"
    "accept" => "*/*"
    "content-length" => "127"
    "host" => "iam.localhost"
  ]
}

There is no Auth header or Content-Length headers in the request so the request from scribe:generate is failing.

I've set the headers in the scribe config

                'headers' => [
                    'Content-Type' => 'application/json',
                    'Accept' => 'application/json',
                    'Authorization' => 'Bearer {token}',
                ],

Am I missing something fundamental here or is this not the desired behaviour? I've read through the docs and from what I can understand this should work?

**Comment by shalvah** [comment]
I'm a little confused.

> However running the example from the Postman Collection that's generated works due to postman putting in the Content-Length.
> 
> ^ Illuminate\Support\Collection {#1147

1. Where is this being dumped from? File, line?

> When running scribe:generate I dumped the headers on that request
> 
> ^ Illuminate\Support\Collection^ {#2862

2. Same for this^^^

3. What exactly is the problem? You specified headers in your config and they show up in the examples, but not in response calls and the generated Postman collection? Is this for all the headers?

**Comment by th0rn0** [comment]
Sorry lemme try and clear some stuff up :)

I was dumping that from the controller I'm trying to document.

To my understanding the responseCalls actually call the routes? There is no mocking involved for those?

The problem is that in the responseCalls the request is failing on the create route for the controller. But when running it outside of responseCalls (IE Postman) it works fine. The only difference I can see is that Content-Length is not set but I cannot find a way so set this. 

I havent got the code to hand right now but I can get some examples in over the weekend or on monday.

**Comment by th0rn0** [comment]
Sorry for late reply.

Ok so in my config I have the following set in the auth section:

`
    'enabled' => true,
    'in' => 'bearer',
    'name' => 'Authorization',
    'use_value' => 'some token'

`

with my headers set to:

`
'Content-Type' => 'application/json',
'Accept' => 'application/json',
`

If I put a dd() in the controller that's being called and dump the headers out I get something like this:

![image](https://user-images.githubusercontent.com/13924261/85746951-c4ec7280-b6fe-11ea-8be6-69e537bafd49.png)

No Auth token present.

However, if I explicitly set the token in the headers section like this:

`
                    'Content-Type' => 'application/json',
                    'Accept' => 'application/json',
                    'Authorization' => 'Bearer sometoken'
`
It works and the correct headers are present.

![image](https://user-images.githubusercontent.com/13924261/85747343-1bf24780-b6ff-11ea-8733-2c40915a092e.png)


So my question is why are the headers set in the auth section being ignored? Not sure if this is a miss understanding on my part or if this is a bug.

**Comment by shalvah** [comment]
Ah. Does your endpoint have an `@authenticated` tag?

**Comment by shalvah** [comment]
If it doesnt, the headers won't be added. It's mentioned in the docs, but maybe I'll highlight it some more. https://scribe.readthedocs.io/en/latest/documenting/documenting-api-information.html

**Comment by shalvah** [comment]
Made it more prominent in the docs that you need `@authenticated` for the parameters to show up.

**Comment by th0rn0** [comment]
We've found a solution. 

So when we did some digging we found that the Request object did not have any of the parameters or headers. Looking into the lumen code we found that there are two Request Objects. Laravel\Lumen\Http\Request and Illuminate\Http\Request. For some reason it was sending the requests to the wrong one and was stripping the Request Parameters and the Headers out unless we explicity set the content type to form-encoded, however all of our applications talk to this service with json requests.

We ran tests side by side with another service we have running the same lumen & scribe versions and we could not replicate these issues.

We ended up putting this code snippet into the app.php

```
Laravel\Lumen\Http\Request::macro('sync', function ($request) {
    $this->headers = $request->headers;
    $this->attributes = $request->attributes;
    $this->request = $request->request;
    $this->query = $request->query;
    $this->server = $request->server;
    $this->files = $request->files;
    $this->content = $request->content;
    $this->json = $request->json();
});
```
```
Illuminate\Http\Request::macro('sync', function ($request) {
    $this->headers = $request->headers;
    $this->attributes = $request->attributes;
    $this->request = $request->request;
    $this->query = $request->query;
    $this->server = $request->server;
    $this->files = $request->files;
    $this->content = $request->content;
    $this->json = $request->json();
});
```

We are going to do some more research as this isn't a nice fix by any means and we are unsure what is causing the issue. As in why one of our services works fine yet this one does not. We just know that this fixes it.

Hopefully this brings some insight to someone. It's had us stumped for days.

**Comment by shalvah** [comment]
> Ah. Does your endpoint have an `@authenticated` tag?

Did you check this though?

**Comment by shalvah** [comment]
(Also, you should always state your framework. Lumen is weird and has many incompatibilities with Laravel.)

**Comment by th0rn0** [comment]
Yea, I added the authenticated tag. Didnt make a difference. Lumen was still stripping the request data and headers. 

In future I'll mention the stack. Apologies.
