### ISSUE TITLE
same query param for multiple api

### ISSUE THREAD

**Issue by farhad2161** [knuckleswtf/scribe#441]
Hi,
I have to copy the following api doc for multiple api in different controllers.
```
/*
...
* @queryParam limit int
* @queryParam offset int
* @queryParam order string Example: id
* @queryParam direction string Should be `asc` or `desc` Example: asc
...
* /
public function index()
{
...
}
```
How can I prevent this copy and pasting?
Can I save it as a fragment in a file and then reference it?

- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

**Comment by shalvah** [comment]
You have a number of options, but your best bet is probably a custom strategy. The example in the docs matches your use case. https://scribe.knuckles.wtf/laravel/advanced/plugins
