### ISSUE TITLE
How to add JWT Auth before accessing the route docs?

### ISSUE THREAD

**Issue by IrfanRZ44** [knuckleswtf/scribe#443]
- [ ] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.
'auth' => [
        'enabled' => true,
        'default' => false,
        'in' => 'bearer',
        'name' => 'token',
        'use_value' => env('SCRIBE_AUTH_KEY'),
        'placeholder' => '{YOUR_AUTH_KEY}',
        'extra_info' => 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.',
    ],

- [ ] I've already config scribe config like the code in top, 
- [ ] and already php artisan scribe:generate
- [ ] clear cache

but still the route docs can be access, someone can help me?
![image](https://user-images.githubusercontent.com/29773559/156052128-f390f236-d540-4ffa-a5b3-dafac57cbed3.png)

**Comment by shalvah** [comment]
It's stated in the docs:

![image](https://user-images.githubusercontent.com/14361073/156208276-f1211f04-6e9c-4be8-8e4a-21db8ee84c80.png)

ie the `auth` section has nothing to do with authenticating the docs route. What you're looking for is to switch to `laravel` type:

![image](https://user-images.githubusercontent.com/14361073/156208596-0e417dd3-aa25-4722-8bf5-cb0a16b4bfdd.png)

https://scribe.knuckles.wtf/laravel/reference/config#type
