### ISSUE TITLE
Best way to generate two sets of docs, internal and external?

### ISSUE THREAD

**Issue by WordsofDefiance** [knuckleswtf/scribe#444]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hi, I'm exploring Scribe as a way to generate public/private API docs. Is there a way to generate two separate blade templates with different sets of documentation without using a plugin or separate parser?

**Comment by shalvah** [comment]
No, not really. #363 contains some ways to achieve this in userland.

Seems like this is a fairly popular feature request (see also #172, #72), but I don't have the time (or motivation) to implement this at the moment. Additionally, it would need an API that wouldn't break backwards compatibility. Open to PRs.

**Comment by shalvah** [comment]
You can now do this! https://scribe.knuckles.wtf/laravel/generating#generating-multiple-docs

**Comment by WordsofDefiance** [comment]
Fantastic, saved me a future PR! 🤣 Thanks for letting me know.

**Comment by mettad3v** [comment]
> You can now do this! https://scribe.knuckles.wtf/laravel/generating#generating-multiple-docs

for future reference, now moved to - https://scribe.knuckles.wtf/laravel/tasks/generating#generating-multiple-docs
