### ISSUE TITLE
Content section of docs is blank

### ISSUE THREAD

**Issue by mattfletcher** [knuckleswtf/scribe#445]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I set my configuration to laravel
2. Then I ran `php artisan scribe:generate` ...
3. It generated resources/views/scribe/index.blade.php but the content div is totally blank:

    <div class="content">
        

        

        
        
    </div>

If I add/change endpoints the navigation changes to match, so nothing appears to be cached, but the content just does not appear, verified in both inspect element and manually viewing the blade source file.

**My environment:**
 - PHP version (from `php -v`): 
 - PHP 8.1.3 (cli) (built: Feb 18 2022 19:32:26) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies
 - Framework (Laravel/Lumen):
 - Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 
 - v9.2.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 
 - 3.24.0

**My Scribe config (minus the comments):**

return [
    'theme'       => 'default',
    'title'       => null,
    'description' => '',
    'base_url'    => null,
    'routes'      => [
        [
            'match'   => [
                'prefixes' => ['v2/*'],
                'domains'  => ['*'],
                'versions' => ['v1'],
            ],
            'include' => [
            ],
            'exclude' => [
            ],
            'apply'   => [
                'headers'        => [
                    'Content-Type' => 'application/json',
                    'Accept'       => 'application/json',
                ],
                'response_calls' => [
                    'methods'     => ['GET'],
                    'config'      => [
                        'app.env' => 'documentation',
                    ],
                    'queryParams' => [
                    ],
                    'bodyParams'  => [
                    ],
                    'fileParams'  => [
                    ],
                    'cookies'     => [
                    ],
                ],
            ],
        ],
    ],
    'type'        => 'laravel',
    'static'      => [
        'output_path' => 'public/docs',
    ],
    'laravel'     => [
        'add_routes' => true,
        'docs_url'   => '/docs',
        'middleware' => [],
    ],
    'try_it_out'        => [
        'enabled'  => true,
        'base_url' => null,
        'use_csrf' => false,
        'csrf_url' => '/sanctum/csrf-cookie',
    ],
    'auth'              => [
        'enabled'     => true,
        'default'     => true,
        'in'          => 'bearer',
        'name'        => 'key',
        'use_value'   => env('SCRIBE_AUTH_KEY'),
        'placeholder' => '{YOUR_ACCESS_TOKEN}',
        'extra_info'  => 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.',
    ],
    'intro_text'        => <<<INTRO
This documentation aims to provide all the information you need to work with our API.

<aside>As you scroll, you'll see code examples for working with the API in different programming languages in the dark area to the right (or as part of the content on mobile).
You can switch the language used with the tabs at the top right (or from the nav menu at the top left on mobile).</aside>
INTRO
    ,
    'example_languages' => [
        'php',
        'javascript',
        'python',
        'bash',
    ],
    'postman'           => [
        'enabled'   => true,
        'overrides' => [
        ],
    ],
    'openapi'           => [
        'enabled'   => true,
        'overrides' => [
        ],
    ],
    'default_group'     => 'Endpoints',
    'logo'              => false,
    'faker_seed'        => null,
    'strategies'        => [
        'metadata'        => [
            Strategies\Metadata\GetFromDocBlocks::class,
        ],
        'urlParameters'   => [
            Strategies\UrlParameters\GetFromLaravelAPI::class,
            Strategies\UrlParameters\GetFromLumenAPI::class,
            Strategies\UrlParameters\GetFromUrlParamTag::class,
        ],
        'queryParameters' => [
            Strategies\QueryParameters\GetFromFormRequest::class,
            Strategies\QueryParameters\GetFromInlineValidator::class,
            Strategies\QueryParameters\GetFromQueryParamTag::class,
        ],
        'headers'         => [
            Strategies\Headers\GetFromRouteRules::class,
            Strategies\Headers\GetFromHeaderTag::class,
        ],
        'bodyParameters'  => [
            Strategies\BodyParameters\GetFromFormRequest::class,
            Strategies\BodyParameters\GetFromInlineValidator::class,
            Strategies\BodyParameters\GetFromBodyParamTag::class,
        ],
        'responses'       => [
            Strategies\Responses\UseTransformerTags::class,
            Strategies\Responses\UseApiResourceTags::class,
            Strategies\Responses\UseResponseTag::class,
            Strategies\Responses\UseResponseFileTag::class,
            Strategies\Responses\ResponseCalls::class,
        ],
        'responseFields'  => [
            Strategies\ResponseFields\GetFromResponseFieldTag::class,
        ],
    ],
    'fractal'                          => [
        'serializer' => null,
    ],
    'routeMatcher'                     => \Knuckles\Scribe\Matching\RouteMatcher::class,
    'database_connections_to_transact' => [config('database.default')]
];

**Comment by mattfletcher** [comment]
For further info, the output under the generate command appears normal:

ⓘ Processing route: [POST] v2/authentication
✔ Processed route: [POST] v2/authentication
ⓘ Processing route: [GET] v2/airports
✔ Processed route: [GET] v2/airports
ⓘ Processing route: [POST] v2/airports
⚠ No bodyParameters() method found in App\Http\Requests\StoreAirportRequest. Scribe will only be able to extract basic information from the rules() method.
✔ Processed route: [POST] v2/airports
ⓘ Processing route: [GET] v2/airports/{airport}
✔ Processed route: [GET] v2/airports/{airport}
ⓘ Processing route: [PUT,PATCH] v2/airports/{airport}
⚠ No bodyParameters() method found in App\Http\Requests\UpdateAirportRequest. Scribe will only be able to extract basic information from the rules() method.
✔ Processed route: [PUT,PATCH] v2/airports/{airport}
ⓘ Processing route: [DELETE] v2/airports/{airport}
✔ Processed route: [DELETE] v2/airports/{airport}
ⓘ Extracting intro and auth Markdown files to: .scribe
✔ Extracted intro and auth Markdown files to: .scribe
ⓘ Writing HTML docs...
✔ Wrote Blade docs to: resources/views/scribe/
ⓘ Generating Postman collection
✔ Wrote Postman collection to: storage/app/scribe/collection.json
ⓘ Generating OpenAPI specification
✔ Wrote OpenAPI specification to: storage/app/scribe/openapi.yaml

**Comment by mattfletcher** [comment]
In case it's relevant, I also noticed that the OpenAPI and Postman exports are getting updated in line with the changes I make. It's just the the middle panel of the HTML docs themselves that seems to be missed off the output.

**Comment by shalvah** [comment]
Hmm, have you checked the HTML and verified that the content is there? Any JS errors? Are you using any toolbars that pull in some deps? Have you tried using an earlier version?

**Comment by mattfletcher** [comment]
The div with the content "id" is there, but totally empty. There are no JS errors. Not sure what you mean by toolbars, but I've not modified the scribe setup other than the config settings listed. 

I will try an older version and report back. I did delete vendor and rerun composer install, but that didn't help.

**Comment by mattfletcher** [comment]
I found the issue, the input view (vendor/knuckleswtf/scribe/resources/views/themes/default/groups.blade.php) was being cached.

`php artisan view:clear`

fixed it. Submitted a docs PR: https://github.com/knuckleswtf/scribe-docs/pull/13
