### ISSUE TITLE
The try it out feature show the response of 404 (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException)

### ISSUE THREAD

**Issue by vnhunter** [knuckleswtf/scribe#451]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

- The try it out feature show the response of 404 (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException) even though I have checked that the api routes are present.
<img width="1544" alt="Screen Shot 2022-03-21 at 16 42 31" src="https://user-images.githubusercontent.com/102024847/159237250-1b0fc389-1792-4e4d-b65e-262318867a2d.png">
<img width="1064" alt="Screen Shot 2022-03-21 at 16 45 16" src="https://user-images.githubusercontent.com/102024847/159237204-9daeba51-461f-4852-87a0-bd147c0f03bf.png">
- But when i send a request with postman, it shows success
<img width="1358" alt="Screen Shot 2022-03-21 at 16 42 51" src="https://user-images.githubusercontent.com/102024847/159237279-e689617c-7c59-4c25-9d23-41b00d4e2f4c.png">Ω

Can anyone help me with this? Thank you

**Comment by shalvah** [comment]
Debugging tip: You should check your browser's DevTools to see what request is actually sent.


**However**, your screenshot shows _Example resoinse_. That's not a Try It Out response. That's an example generated during the extraction process (although I'm not sure why it encountered a 404 for a basic route).🤔

**Comment by vnhunter** [comment]
Thanks @shalvah for the response, I will take a look at my code and see what I did wrong.
