### ISSUE TITLE
authorization input is hidden 

### ISSUE THREAD

**Issue by ibrahem-kamal** [knuckleswtf/scribe#454]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
this is my auth config 

```php

	'auth'              => [
		/*
		 * Set this to true if any endpoints in your API use authentication.
		 */
		'enabled'     => true,
		
		/*
		 * Set this to true if your API should be authenticated by default. If so, you must also set `enabled` (above) to true.
		 * You can then use @unauthenticated or @authenticated on individual endpoints to change their status from the default.
		 */
		'default'     => true,
		
		/*
		 * Where is the auth value meant to be sent in a request?
		 * Options: query, body, basic, bearer, header (for custom header)
		 */
		'in'          => 'bearer',
		
		/*
		 * The name of the auth parameter (eg token, key, apiKey) or header (eg Authorization, Api-Key).
		 */
		'name'        => 'Authorization',
		
		/*
		 * The value of the parameter to be used by Scribe to authenticate response calls.
		 * This will NOT be included in the generated documentation.
		 * If this value is empty, Scribe will use a random value.
		 */
		'use_value'   => env('SCRIBE_AUTH_KEY'),
		
		/*
		 * Placeholder your users will see for the auth parameter in the example requests.
		 * Set this to null if you want Scribe to use a random value as placeholder instead.
		 */
		'placeholder' => '{YOUR_AUTH_KEY}',
		
		/*
		 * Any extra authentication-related info for your users. For instance, you can describe how to find or generate their auth credentials.
		 * Markdown and HTML are supported.
		 */
		'extra_info'  => 'You can retrieve your token by calling  <b>Generate Client token</b>.',
	],

```

the i have the tag "requires authorization but there is no input to add the token to , after inspecting the page 

i found out that the input is hidden

<img width="1619" alt="image" src="https://user-images.githubusercontent.com/38753243/159963689-1cac7fa4-7c25-43c6-85e8-ce91f922a5c2.png">

**Comment by shalvah** [comment]
Hmmm...that's odd. Seems like a one-off. Any JS errors in the console? What's the `data-authed` property on the `<form>` element?

**Comment by ibrahem-kamal** [comment]
thats the console 
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/38753243/160287730-957cfefc-e7a6-407e-8310-9ee4943791a2.png">
and the data-authed is 1 

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/38753243/160287790-6b14714b-61d6-41f6-bd35-c464ebc9a881.png">

**Comment by ibrahem-kamal** [comment]
i had no issue with version 3.13 but cant use it because of my laravel versions , current is 3.25

**Comment by shalvah** [comment]
Seems like that higherjs error might have crashed the JavaScript.

See if there's a solution to that here: https://github.com/knuckleswtf/scribe/issues/393

**Comment by ibrahem-kamal** [comment]
adding the docs url to the except in the debug bar config removed the js error , but the main issue remains 

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/38753243/160365053-11936f6a-925c-42bb-92cc-ac880f362c2e.png">

**Comment by ibrahem-kamal** [comment]
for some reason , it now shows the header input so am gonna close this issue
