### ISSUE TITLE
Any guide on how to integrate into automated CI/CD workflow to auto-update API documentation?

### ISSUE THREAD

**Issue by ajcastro** [knuckleswtf/scribe#457]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Also, versioning?

**Comment by deZbrown** [comment]
I'm not sure if this is the best way, but here is how I handle that.

Inside deployment workflow, I call bash script with a list of artisan commands that run on that container during deployment:

`    echo "Maintenance mode"
    php ${path}artisan down
    echo "Running the migrations.."
    php ${path}artisan migrate --force
    echo "Generating docs"
    php ${path}artisan scribe:generate --force
    echo "Publishing assets.."
    php ${path}artisan horizon:publish --ansi
    php ${path}artisan telescope:publish --ansi
    echo "Exiting maintenance mode"
    php ${path}artisan up

    exec php-fpm`

Hope this helps. Cheers.

**Comment by shalvah** [comment]
Also, there's a section in the docs that talks about CI/CD briefly.

https://scribe.knuckles.wtf/laravel/tasks/generating#running-on-cicd

Not sure what you mean by versioning, though.
