### ISSUE TITLE
Can I place docblocks outside of controller for better readability of the code?

### ISSUE THREAD

**Issue by mahdi-morovati** [knuckleswtf/scribe#458]
I want to put the documents somewhere outside the controller. For example, in swagger you can put documents in an interface and implement it. Does scribe have that capability?

**Comment by mahdi-morovati** [comment]
@shalvah 

hello, can you help me?

**Comment by shalvah** [comment]
Sorry, can't think of a way now. Your best bet is to create your own custom strategy; just extend one of those that uses doc blocks and tell it to fetch the doc blocks from elsewhere. The docs have more information ("Writing Plugins")

**Comment by vimkaf** [comment]
I tried using interfaces for this but no success.
