### ISSUE TITLE
The example request doesn't display correctly when type = laravel

### ISSUE THREAD

**Issue by HuyNguyen206** [knuckleswtf/scribe#460]
hi @shalvah 
When i use the type = laravel and access /docs endpoint, everything displays correctly except the example request
The example request is missing in the docs page but when I examine the source code in HTML, the example request actually still exists
I figured out there is an error related hljs.js library but not sure how to fix it
![image](https://user-images.githubusercontent.com/30259638/163401172-f42b1be0-4c00-48cd-ae3a-d72b1b7dbc07.png)

![image](https://user-images.githubusercontent.com/30259638/163400460-ab16a833-47e7-463f-8d9f-8407bb219690.png)

The issue doesn't occur when I switch to type = static
Please give me some advice on how to fix this error

Env:
"laravel/framework": "6.20.5"
"knuckleswtf/scribe": "3.26.0"

Thanks in advance

**Comment by shalvah** [comment]
Have you checked this issue? Some other hljs-related stuff there. https://github.com/knuckleswtf/scribe/issues/393

**Comment by HuyNguyen206** [comment]
Thanks @shalvah , let me check
