### ISSUE TITLE
Additional checks in form requests

### ISSUE THREAD

**Issue by WebPajooh** [knuckleswtf/scribe#461]
Hello.

Before returning the array, I get some stuff.
Look at this for example:
`$productData = $productService->get(request()->options['product_id']);`
And I have validation rules based on $productData.

The problem is that when I generate the docs, I got an error:
`✖ ErrorException in MyFormRequest.php at line 31: Trying to access array offset on value of type null.`
Why that happened? Because Scribe's request doesn't have an options field!

The question is that how can I make scribe ignoring this form request and only use my comments for generating docs?

Thank you for Scribe,
I love it!

**Comment by shalvah** [comment]
Disabling form requests? Remove the FormRequest strategy from your config file.

**Comment by WebPajooh** [comment]
@shalvah I don't want to disable it completely. I just need to disable it for a single method that I had mentioned before.

**Comment by shalvah** [comment]
I see. Unfortunately, there's no way to do that. It would be nice to be able to pass configuration to a strategy, but I haven't figured out a good API for that (you can suggest one).

In the meantime, you'll need to create your own strategy that extends the FormRequest strategy and add whatever logic you need to skip the method. Then replace the strategy in your config with this one.

**Comment by WebPajooh** [comment]
What about a docblock like `@ignoreFormRequest`? @shalvah

**Comment by shalvah** [comment]
Nope, that's out of the question. Otherwise, we might as well have an `ignore` annotation for every possible strategy.
