### ISSUE TITLE
i have problem for generate docs

### ISSUE THREAD

**Issue by zadrogg** [knuckleswtf/scribe#464]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

<img width="1550" alt="Снимок экрана 2022-04-26 в 16 33 42" src="https://user-images.githubusercontent.com/62801553/165311864-73438787-655b-4f3c-8369-a6d9c1d651dd.png">

anyone faced this? I don't understand the error
occurs when generating documentation

**Comment by shalvah** [comment]
This may be a bug in Scribe, possibly because you have an array of files. Can you provide more information, such as the endpoint and kind of parameters being documented when the error happened?

**Comment by zadrogg** [comment]
I'm sorry, I had an error in the syntax, when declaring the name of the parameter, I indicated "[]"

**Comment by shalvah** [comment]
So we can close this?

**Comment by zadrogg** [comment]
@shalvah yes or course, thanks ;)
