### ISSUE TITLE
Since fakerphp/faker 1.14: Accessing property "word" is deprecated, use "word()" instead.

### ISSUE THREAD

**Issue by Redtama** [knuckleswtf/scribe#467]
As a result of the following line: https://github.com/knuckleswtf/scribe/blob/31f534a88ef5c70f9f0c232335126d4ff9e0d71c/src/Extracting/ParamHelpers.php#L49

the following error is being logged:
```
Since fakerphp/faker 1.14: Accessing property "word" is deprecated, use "word()" instead. in /var/www/html/vendor/symfony/deprecation-contracts/function.php on line 25  
```

Use of the `$faker->word` property may be present elsewhere but this is the only place I'm aware of so far.

This is occurring with Laravel 9.

**Comment by tridcatij** [comment]
Same with 

```
Since fakerphp/faker 1.14: Accessing property "safeEmail" is deprecated, use "safeEmail()" instead.
```
