### ISSUE TITLE
Package not installing in Laravel

### ISSUE THREAD

**Issue by KellsWorks** [knuckleswtf/scribe#468]
composer require --dev knuckleswtf/scribe01

Info from https://repo.packagist.org: #StandWithUkraine

  [InvalidArgumentException]
  Could not find a matching version of package knuckleswtf/scribe01. Check the package spelling, your version constraint and t  
  hat the package is available in a stability which matches your minimum-stability (dev).

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

**Comment by shalvah** [comment]
Read the error message ffs. The name of the package is not scribe01.
