### ISSUE TITLE
Compatibility with spatie/laravel-data

### ISSUE THREAD

**Issue by bianchi** [knuckleswtf/scribe#469]
Scribe is compatbile with spatie/dto as mentioned here #241 . Would it be possible do implement the same compatibility with 
[https://github.com/spatie/laravel-data](url)? They look very similar.

**Comment by shalvah** [comment]
I can't "implement compatibility" with a package that doesn't have any relation or use in mine. You have to point out what makes them incompatible. (Regardless, I don't think I'd have the time to implement that, btw. A PR would be welcome.)
