### ISSUE TITLE
Docs not generating

### ISSUE THREAD

**Issue by JonathanPort** [knuckleswtf/scribe#47]
Hi, I've read all the docs, followed the steps and things appear to be working but when I run the generate command, nothing is generated. I see a list like this:

<img width="672" alt="Screenshot 2020-06-23 at 14 07 47" src="https://user-images.githubusercontent.com/16456310/85407273-ec0a3f00-b55a-11ea-85db-d55a67e820bd.png">

But nothing is generated. I've tried various settings and nothing changes. Any ideas? Please excuse me if I'm missing something obvious..

**Comment by shalvah** [comment]
This sounds similar to [this issue](https://github.com/knuckleswtf/scribe/issues/15). Are you documenting routes in your web.php?

**Comment by shalvah** [comment]
Those last two routes look like web routes. Try setting `match.prefixes` in your config to `['api/*']`.

**Comment by JonathanPort** [comment]
Hi, thanks for the quick reply! Yes the last two are web routes and adding ['api/*'] and doing `php artisan config:cache` after gave the following output:

<img width="662" alt="Screenshot 2020-06-23 at 16 03 02" src="https://user-images.githubusercontent.com/16456310/85420371-064c1900-b56b-11ea-8b87-cc4f2e63a7ad.png">

So that's working, how do I view in the browser? I've gone to https://website.test/docs but I get a 404. Does this package include the routes or do I need to manually add one? Sorry bit rusty with Laravel atm

**Comment by JonathanPort** [comment]
Sorry, changed the type to laravel and  cleared cache and it's working now. I am getting `View [scribe.index] not found.` but I can work it out from here. cheers!
