### ISSUE TITLE
Check for updates script not found config

### ISSUE THREAD

**Issue by polyskalov** [knuckleswtf/scribe#470]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. Deploy project with [Deployer](https://deployer.org/) (It uses zero-downtime by making symlinks to release directory, like /current → /releases/171/)
2. Then I ran `php artisan scribe:generate` by ssh to my server by Gitlab runner ssh
3. But I saw after success docs generation...
```bash
Checking for any pending upgrades to your config file...
Check failed with error:
✖ ErrorException in /home/domain.com/releases/171/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php at line 231: file_get_contents(config/scribe.php): Failed to open stream: No such file or directory
```

instead of success result

Maybe update script has some problem with resolving correct paths?

**My environment:**
 - PHP version (from `php -v`): 8.0.18
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): v9.9.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.26.0

**Comment by shalvah** [comment]
Hmm, I suspect perhaps you aren't running the command from your app directory? (It shouldn't crash, anyway, but just need to confirm.)
