### ISSUE TITLE
Generating Different Types of Documentation

### ISSUE THREAD

**Issue by mooseh** [knuckleswtf/scribe#471]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hi There 

I know this is more of a feature request but I have forked your repo and achieved what I need, and I know others need it,
currently your documentation doesn't support "multiple areas" such as admin docs and user docs.

I thought of a quick and easy way around this which is to generate multiple docs, in order to do this you will need a second config.

so I changed your GenerateDocumentation class slightly to accept a {--config=} option

and also in the bootstrap section I added this 
```     
        $this->docConfig = new DocumentationConfig(config('scribe'));
        if($this->option('config')){
            $config = config_path($this->option('config')).".php";
            if(!file_exists($config)){
                die("There is no suitable config found at {$config}\n");
            }
            $this->docConfig = new DocumentationConfig(config($this->option('config')));
        }
```

this allowed me the ability to make another config with static files and with a wider rule set for admins and then I just needed to add the admin routes and voila it works using the artisan command like so
php artisan scribe:generate --config=scribe_admins

maybe you can add this feature? I have seen other people asking for something like this and this is this is the quickest path to

**Comment by eonghk** [comment]
Vote for this. Maybe the config can be an array so it will be easy to support multiply configs?

**Comment by shalvah** [comment]
https://scribe.knuckles.wtf/laravel/generating#generating-multiple-docs
