### ISSUE TITLE
Database Transactions

### ISSUE THREAD

**Issue by travislykes** [knuckleswtf/scribe#474]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I have created a second database connection specifically for my scribe API documentation and I have set the value as below

`'database_connections_to_transact' => [
        'docs'
    ]`

For some strange reason, Scribe keeps using the default connection and persists all transactions to the database.
FYI, I have cleared all caches, rerun the docs generation, used a different env during docs generation et al.. But none seems to work, any help will be appreciated..

I even set the connection in the boot method for AppServiceProvider but didn't work either, a dump of the connection shows the database I want to use but after a response is requested via the docs, my default database is the one that is used.

`if (class_exists(\Knuckles\Scribe\Scribe::class)) {
            Scribe::beforeResponseCall(function () {
                DB::setDefaultConnection('docs');
               // echo DB::connection()->getDatabaseName();
            });
        }`

**Comment by travislykes** [comment]
Thanks for the reply, with regards to the .env file.. I did as suggested;
 I created the `.env.docs` file with the different Database credentials and generated the documents with the artisan command 

`php artisan scribe:generate --env docs` 

And with regards to what I stated earlier; when the docs are being generated it uses the second database connection but once you use the `try it out ` option in the docs; the default database is now called.

**Comment by shalvah** [comment]
Oh, did you mean "Try It Out"? That's a whole different functionality. Response calls are when Scribe is generating docs and hits your endpoints to try to get sample responses. Try It Out is you talking to your app, just that it uses your docs page as your API client. The requests you send from there are from you to your app. Scribd doesn't do anything there. If you want the database connection to be different, start your app with the right env configuration.

**Comment by travislykes** [comment]
Ok, thanks for the clarification.. was quite confused earlier.. it will be nice to add that to the docs :)
