### ISSUE TITLE
Scribe api documentation json validator request

### ISSUE THREAD

**Issue by michaelandrew123** [knuckleswtf/scribe#476]
Hi, I have problem with json validator request using @QueryParam.

Here is my command:
```php
/**
* Get shipment distribution
*
* @QueryParam customer_ids string[] required
*/
```

Result:
```json
{
"errors": {
"customer_ids": [
"The customer ids must be a valid JSON string."
]
}
}
```

**code:**
```php
public function getShipmentDistribution(Request $request,$po_num){

    $validator = \Validator::make(array_merge($request->all(),['po_num' => $po_num]), [
        'po_num' => 'required',
        'customer_ids' => 'required|json'
    ]);

    if ($validator->fails()) {
        return response([
          'errors' => $validator->messages()
        ],400);
    }
    $purchaseOrder =  PurchaseOrder::where('po_number', $po_num)->WhereIn('customer_id',json_decode($request->customer_ids))->first();
  ....
```

**Comment by leandrodiogenes** [comment]
Your validation is expecting a json and your customer_ids is an array

**Comment by shalvah** [comment]
1. Please always use triple backticks (```) when posting a code sample so it's easier to read.
2. Thank you @leandrodiogenes . `string[]` in your docblock means array of strings. `json` in your validation rules means a JSON string. If you didn't know the difference, that's probably a bug in your API. 🙂

**Comment by michaelandrew123** [comment]
Hi, I used string[] as a dummy example because I didnt find any solution and using param json from the docs to match the requirement in validator. Do you guys have solution using json?

**Comment by michaelandrew123** [comment]
Thanks for the advice appreciated it.

**Comment by shalvah** [comment]
Exactly. Thank you @leandrodiogenes

**Comment by michaelandrew123** [comment]
> Exactly. Thank you @leandrodiogenes

We probably, need to customize all the code including the frontend that accepts json if no other solutions.
