### ISSUE TITLE
Lumen error: Call to undefined function Knuckles\Scribe\Commands\public_path()

### ISSUE THREAD

**Issue by danielgestwa** [knuckleswtf/scribe#477]
**Stack:**
Lumen 8.0 (https://lumen.laravel.com/docs/8.x)
PHP 8.0
Scribe 3.29

**Reproduction:**
After proper installation and configuration I run "php artisan scribe:generate". 
Documentation generation works fine, but command line shows error: "Call to undefined function Knuckles\Scribe\Commands\public_path()"

![image](https://user-images.githubusercontent.com/16914661/172348031-b4f347e5-b427-4c7b-9e17-b6179252f39c.png)

**My solution:**
File "vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php", function "sayGoodbye". Change not existing Lumen function "public_path()" to "base_path('public')"

![image](https://user-images.githubusercontent.com/16914661/172348594-b0fb9746-e88a-4e93-bf49-d18d575201d1.png)

**Please add my solution or remove printing extended message at the end of generation in future versions.**

**Comment by shalvah** [comment]
Thanks, fixed now (3.30.0)
