### ISSUE TITLE
UnhandledMatchError Unhandled match case '...'

### ISSUE THREAD

**Issue by Pavel-Vinogradov** [knuckleswtf/scribe#478]
To simplify the creation of the Form Request, I use the function to calculate the request method POST GET PUT DELETE,when generating the API doc, it gives an error
UnhandledMatchError

Unhandled match case '...'

```
   public function rules(): array
     13▕     {
     14▕
  ➜ 15▕         return match ($this->method()) {
     16▕             "POST" => ['company_name' => 'string|max:255|required',
     17▕                 'company_full_name' => 'string',
     18▕                 'inn' => 'integer|required|unique:companies,inn',
     19▕                 'kpp' => 'integer|required|unique:companies,kpp',

```

**Comment by leandrodiogenes** [comment]
The problem seems to be on your API, not on scribe.

**Comment by leandrodiogenes** [comment]
Maybe you can try to debug and see what method is being pass

**Comment by shalvah** [comment]
Thanks, fixed now (3.30.0)

**Comment by shalvah** [comment]
Oops, closed wrong issue. Haven't even looked at this yet.

**Comment by shalvah** [comment]
Okay, looks like you're doing something unconventional with your API, which Scribe isn't really equipped to handle. Can't say more without further details.

**Comment by Pavel-Vinogradov** [comment]
![image](https://user-images.githubusercontent.com/65782910/173179418-a7ef0857-29a2-412b-9152-48089debd88e.png)

**Comment by shalvah** [comment]
This isn't going to work. You need to provide more details. You've said it's an UnhandledMatchError, but you didn't say what case it didn't match, and when this happened. Please provide sufficient information.

**Comment by Pavel-Vinogradov** [comment]
![image](https://user-images.githubusercontent.com/65782910/175924207-85b832d5-f3ca-4abc-bb5a-fbd62ab4ddc8.png)
