### ISSUE TITLE
Mongodb Transaction Error

### ISSUE THREAD

**Issue by barsengin** [knuckleswtf/scribe#48]
i m using mongodb in my project. So when ı generate `php artisan scribe:generate`, i get this error:
![mongodb_transaction](https://user-images.githubusercontent.com/33950394/85994307-49d9d380-ba00-11ea-99d6-74471e3be755.png)
How can i solve this error ? Is there any setting to disable mongodb connection? or to override `startDbTransaction()` that is trait method ?

**Comment by Smudge3806** [comment]
I got this issue too... Have had this issue for awhile with other libs as the MongoDB adaptor we use, [Jenssegers](https://github.com/jenssegers/laravel-mongodb) doesn't support transactions, or at any rate, hasn't implemented that part of the driver.

The cause for us, as far as I have seen is `Knuckles\Scribe\Extracting\DatabaseTransactionHelpers` which iterates over all database connections in the config and creates/rollbacks transactions in `startDbTransaction` and `endDbTransaction` respectively.

Suggest some sort of defensive checks to prevent this.

**Comment by shalvah** [comment]
We can wrap it in try/catch and ignore errors, but the problem is that any database changes from the response calls will actually be persisted. So, if you're not using a test db, tough luck. 🤔

**Comment by barsengin** [comment]
I could do these changes. My problem was fixed. I could not get a transaction error. Thanks for your supports.

**Comment by shalvah** [comment]
This should be fixed in 1.3.0. Give it a try.
