### ISSUE TITLE
PHP 8 Annotations

### ISSUE THREAD

**Issue by BertvanHoekelen** [knuckleswtf/scribe#485]
Hey! Thanks for the amazing package, always wished something like this existed. Because the docblocks don't have support for autocompletion in an IDE. I've created [this](https://github.com/BertvanHoekelen/scribe-annotations) package. Would you be interested in a PR to the core?

The package is also able to determine the model automatically based on the `@mixin` attribute on the JsonResource, so if the return type's are set correctly you don't have to add anything :)

#### Input
```php
<?php

use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Magwel\ScribeAnnotations\Attributes\ApiResource;
 
class UserController
{
    #[ApiResource(TestUser::class, resourceClass: TestUserApiResource::class, statusCode: 201, factoryStates: ['randomState'])]
    public function _invoke(): AnonymousResourceCollection
    {
        return TestUserApiResource::collection(
            collect([Utils::getModelFactory(TestUser::class)->make(['id' => 0])])
        );
    }
}
```

#### Ouptut
```php
[
    'status' => 201,
    'content' => json_encode([
        'data' => [
            [
                'id' => 1,
                'name' => 'Tested Again',
                'email' => 'a@b.com',
            ],
            [
                'id' => 2,
                'name' => 'Tested Again',
                'email' => 'a@b.com',
                'random-state' => true,
            ],
        ],
    ]),
];
```

#### Input
```php
/**
 * @mixin TestUser
 */
class TestUserApiResource extends JsonResource
{
    public function toArray($request): array
    {
        return [
            'id' => $this->id,
            'name' => $this->first_name . ' ' . $this->last_name,
            'email' => $this->email,
        ];
    }
}

class UserController
{
    public function withEloquentApiResourceAnnotation(): TestUserApiResource
    {
        return new TestUserApiResource(Utils::getModelFactory(TestUser::class)->make(['id' => 0]));
    }
}
```

#### Output
```php
[
    'status' => 200,
    'content' => json_encode([
        'data' => [
            'id' => 1,
            'name' => 'Tested Again',
            'email' => 'a@b.com',
        ],
    ]),
];
```

**Comment by shalvah** [comment]
Nice! Yeah, that looks useful enough to be in core.

From what I see, there are three separate features here:
1. Inferring from the return type and `@mixin`
2. Using the annotation.

We can incorporate (1) into the existing strategy, but (2) will need PHP 8 support, so I'd rather wait and put them all in v4. And now that you've brought it up, it would probably be better to add annotation equivalents for all tags, since they're better than parsing (and writing) text tags. And that will take a major refactor. I'll let you know when I have a v4 branch, then you can PR, and I'll refactor later.

**Comment by shalvah** [comment]
(Also noticed a lot of the code in your custom strategy is copied from the package's, which isn't good, as something internal may change between minor versions. That might be a sign of a leaky abstraction, so I'll look into if I can provide better extension points.)

**Comment by BertvanHoekelen** [comment]
Yeah I just started experimenting and copied a lot of stuff to test the implementation. Also wanted to get your opinion first before opening a PR. When I have some time I will try to create a PR for v3 to infer from return type and mixin. Should I just create a new response strategy e.g. `Strategies\Responses\UseReturnTypeAndMixin`? 

I think attribute tags won't break in a php 7.4 application as they are only read as comments. So we might not even have to create a v4. But we have to keep the php 8 strategies separate from the php 7.4 one's. Only problem might be the tests but we can create a custom group for that which only runs on the php 8 testsuite. Let me know your thoughts 😄

**Comment by shalvah** [comment]
I'm currently adding PHP Attributes in v4. Decided to focus on the attribute part. When that's done, you can then send in a PR to add support for inferring the model from the mixin tag.

**Comment by shalvah** [comment]
v4 has been released, which comes with PHP 8 attributes. Moved things around a bit, but it should be easier to follow.
