### ISSUE TITLE
Customize CSS in Documentation when 'type' => 'static' 

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#49]
Hi,

It is possible to change the css of the output documentation, using in scribe.php 'type' => 'static' ?
And if it is possible, what is the better way to do it ?

Best Regards...

**Comment by shalvah** [comment]
It's currently not possible, but support for themes is on the roadmap. See https://github.com/knuckleswtf/pastel/issues/3.
.
Right now, the best you can do is publish the views and use a bunch of <style> tags to add your own CSS..

**Comment by shalvah** [comment]
See the RFC that would help with this: #105 

With this, you could add custom CSS, probably in your Laravel config file.
