### ISSUE TITLE
(.scribe/endpoints.cache/00.yaml): Permission denied in Laravel sail.

### ISSUE THREAD

**Issue by antizhyk** [knuckleswtf/scribe#491]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hi all. Scribe in Laravel Sail project generates the endpoints.cache folder as root, although it creates the .scribe folder as user "sail". I need it to create everything as "sail" or at least as some other user, but not as root))

**Comment by shalvah** [comment]
How would we set that? Currently it does a basic [mkdir](https://github.com/knuckleswtf/scribe/search?q=mkdir&type=). Wouldn't that use the user you ran the command as?

**Comment by antizhyk** [comment]
But the thing is that in docker the container are run by root user and laravel sail works from docker and when I faced this problem I wondered if someone has already faced this problem (which is most likely) and found a way around it. Maybe there is a configuration in "scribe" where i can pass uid 1000 for example and folders will be created from a 1000th user.

**Comment by ManuDoni** [comment]
@antizhyk If you still have this issue, try to set this in your `.env` file:
```env
WWWUSER=1000
WWWGROUP=1000
```
Then rebuild your docker image.

**Comment by antizhyk** [comment]
Thank you very much for your help, as it turns out the thing is that in laravel sail commands have to be scribed in a container.
