### ISSUE TITLE
Ignoring rules

### ISSUE THREAD

**Issue by wrabit** [knuckleswtf/scribe#499]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I want to ignore some rules from the validation from being used as params. Is it possible? 

I could only find this [https://github.com/knuckleswtf/scribe/issues/298](url)

**Comment by leandrodiogenes** [comment]
Hi @wrabit, maybe @shalvah can help you with a definitive answer, but I don't think it's possible.
On the other hand, you can create a customStrategy to follow the behavior you need.
[https://scribe.knuckles.wtf/laravel/advanced/plugins#creating-a-strategy](url)

**Comment by wrabit** [comment]
So anything inside validation is forced in as a bodyParam? Here, "red_line_id" is the only param and it's an url param, but I am getting the urlParam and everything also as bodyParam:

This is my api controller:

```php
    public function __invoke($red_line_id, Request $request)
    {
        $segments = explode('-', $red_line_id);

        $charger_group_id = data_get($segments, '0');
        $channel = data_get($segments, '1');

        $validator = Validator::make([
            'red_line_id' => $red_line_id,
            'parts' => $segments,
            'charger_group_id_segment' => $charger_group_id,
            'channel_segment' => $channel,
        ], [
            'red_line_id' => 'required',
            'parts' => 'required|size:2',
            'charger_group_id_segment' => 'required|size:13',
            'channel_segment' => 'required|size:1',
        ], [
            'parts.size' => 'There are missing parts from the Red Line ID string. Format: [charger_group_id]-[channel]',
            'charger_group_id_param_data_source_id.required' => 'No device found for this Red Line ID',
            'channel_param_data_source_id.required' => 'No device found for this Red Line ID',
        ]);
```

<img width="677" alt="image" src="https://user-images.githubusercontent.com/5918271/179473939-e78d3b6a-44ad-4e87-a596-8242847c092d.png">

**Comment by wrabit** [comment]
Ok I got round it for now by:

```php
        $scribeIgnorer = "";

        $validator = Validator::make([
            'var' => $var,
        ], [
            $scribeIgnorer.'var' => 'required'
        ]
```

**Comment by wrabit** [comment]
The custom strategy only appended rules - not removed the old ones.

I have a feature that needs to be complete. It's labelled clear enough for now for other devs to know why it's there. It'll do.

**Comment by leandrodiogenes** [comment]
Instead of create a new custom strategy, try to override the current strategy.

**Comment by wrabit** [comment]
That would be "changing my validation layer"?

**Comment by leandrodiogenes** [comment]
I dont think so. You won't need to change the way you do your validations. The only change you will make will be made

**Comment by wrabit** [comment]
Is there a documented way of doing what you are proposing?

**Comment by leandrodiogenes** [comment]
I think not.

**Comment by shalvah** [comment]
Hah, that's a smart solution. But as @leandrodiogenes mentioned, we'd ideally not want you to change your application code for Scribe.

I'm still thinking of a good way to allow configuring things like this. Was this in a FormRequest or an inline validator?

**Comment by shalvah** [comment]
No, adding tags is an unscalable approach. If I added a tag for every possible behaviour change, we'd have at least 20+ tags now. A better option would be in the config file, but even then, it has to be placed somewhere where it makes sense.

I'm considering

``php
StrategyName::class => [
  // config options
],
```

but that's a major shift I have to commit to. Also, while it would allow for specific options to be passed, I'm trying to think of something that offers more extensibility, so you could configure something that doesn't have a config option without needing to write a custom strategy.
