### ISSUE TITLE
Customize language output of documentation. 

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#50]
By default the docs generated are english, can i change to other language ? example : French or Spanish ?

There is a way to achieve this ?

**Comment by shalvah** [comment]
No, right now, there isn't. Your best bet is replacing the relevant content in the generated markdown file and running `sctibe:generate --no-extraction`. This should be enough, as most of the textual documentation is written by yourself (config file, doc blocks).

**Comment by shalvah** [comment]
Closing because special support for this isn't likely to be on my roadmap any time soon.

**Comment by pirex360** [comment]
Thanks for the reply, i understand.
