### ISSUE TITLE
Upgrading from 1.2 to 3

### ISSUE THREAD

**Issue by skinnydesign** [knuckleswtf/scribe#501]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. composer update knuckleswtf/scribe
2. php artisan scribe:upgrade --dry-run
3. But I saw...
The following changes will be made to your config file:

   BadMethodCallException

  Method Knuckles\Scribe\Commands\Upgrade::newLine does not exist.

  at vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103
     99|      */
    100|     public function __call($method, $parameters)
    101|     {
    102|         if (! static::hasMacro($method)) {
  > 103|             throw new BadMethodCallException(sprintf(
    104|                 'Method %s::%s does not exist.', static::class, $method
    105|             ));
    106|         }
    107|

  • Bad Method Call: Did you mean Knuckles\Scribe\Commands\Upgrade::line() ?

**My environment:**
 - PHP version: 7.4.29 
 - Framework: Laravel
 - Laravel/Lumen version: v7.29.3 
 - Scribe version: 3.3.1

**Comment by shalvah** [comment]
The upgrader in v3 is designed to upgrade from v2. I suggest installing v2 and migrating to that, then installing v3 and migrating to that.

v2 migration guide is [here](https://scribe.readthedocs.io/en/latest/migrating-v2.html). I think you'll need to do all the config file changes and changes marked `Migration required`. Then follow the v3 migration guide.
