### ISSUE TITLE
Form Request - check unique with model value

### ISSUE THREAD

**Issue by malogajski** [knuckleswtf/scribe#503]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Ok, this rule works but the generation of docs will stop when came to `$this->model->field`:

`'email'          => [
                'required',
                'email',
                'unique:users,email,' . $this->user->id
            ],`

I guess this is solved on some way but I didn't find solution here. Thanks!

**Comment by shalvah** [comment]
> the generation of docs will stop

What does that mean? Is an error thrown?
