### ISSUE TITLE
mark group of routes as authenticated 

### ISSUE THREAD

**Issue by moathOSA** [knuckleswtf/scribe#504]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

how can i mark a group of routes as authenticated to avoid add 

 * @authenticated

above every  API method ?

```
/**
     * list all customers.
     *
     * @authenticated
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        return $this->success(Customer::all(), 'list all records', Response::HTTP_OK);
    }

```

**Comment by shalvah** [comment]
Did you really check the docs? Search for "authentication" and the first result takes you to [this](https://scribe.knuckles.wtf/laravel/documenting/metadata#indicating-authentication-status), where it points out your options.
