### ISSUE TITLE
even if i use @group all my endpoints listed under the default default_group

### ISSUE THREAD

**Issue by moathOSA** [knuckleswtf/scribe#506]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.
```
for Auth
/*
 * @group Auth management
 *
 * APIs for managing authentication
 */

for Customer
/*
 * @group Customer management
 *
 * @authenticated
 * 
 * APIs for managing customers
 * 
 */
```
even if i use @group all my endpoints listed under the default default_group

![groups](https://user-images.githubusercontent.com/60176683/183280463-d3d05405-6cc2-4133-b8ab-77a9d7784c7b.png)

**Comment by moathOSA** [comment]
i just want to clear that this is not a problem , but to make group works you have to add the @group tag above the endpoint not a above the class 
the @group for the class not working for me , only group tag above the endpoints worked for me 

can you check this please @shalvah

**Comment by leandrodiogenes** [comment]
Hi  @moathOSA, Where did you put those docblocks.

**Comment by moathOSA** [comment]
@leandrodiogenes 

at first i follow the tip in the documentation

```
tip

A better option is often to set @group on the controller instead. This will add all endpoints in that controller to the group, and you can add a group description below the group name
``` 

but it's not working at all 

then when i add the @group tag above the endpoints every thing works will , but you have to add the endpoint above every endpoint , cuz adding the tag above the controller doesn't work for me

**Comment by leandrodiogenes** [comment]
Can you share how your controller is?

**Comment by leandrodiogenes** [comment]
Maybe its because of how your doc block is.
instead of 
```php
/*
 * @group Customer management
 * @authenticated
 * APIs for managing customers
 */
```
try this

```php
/**
 * @group Customer management
 * @authenticated
 * APIs for managing customers
 */
```

**Comment by leandrodiogenes** [comment]
Your syntax is not doc bloc syntax, it's just an comment.

**Comment by shalvah** [comment]
Closing this. @moathOSA let me know if you still have an issue.
