### ISSUE TITLE
How to add a name for postman example that is generated by scribe

### ISSUE THREAD

**Issue by moathOSA** [knuckleswtf/scribe#507]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.
how to set the example file name for postman collection ?

![Screenshot 2022-08-07 at 11-15-46 Screenshot from 2022-08-07 11-12-34 png (PNG Image 3840 × 1080 pixels)](https://user-images.githubusercontent.com/60176683/183281842-5e22c318-d233-46a9-afd0-4abe459fd2bd.png)

**Comment by leandrodiogenes** [comment]
check @response tag on documentation.
[https://scribe.knuckles.wtf/laravel/documenting/responses#response](https://scribe.knuckles.wtf/laravel/documenting/responses#response)

**Comment by moathOSA** [comment]
@leandrodiogenes  nothing mentioned about postman collection examples

**Comment by leandrodiogenes** [comment]
The name of your postman collections comes from your .env APP_NAME.
You dont have your postman collection on your printscreen.
"My endpoints" is Group name (@group)
"Post register" is your route name

if you want to know about that last item. This is the name of the response example, not the name of your collection
![image](https://user-images.githubusercontent.com/2463299/183513056-03a38fe4-11e3-4bf0-935a-79fb2c9da55a.png)

**Comment by leandrodiogenes** [comment]
![image](https://user-images.githubusercontent.com/2463299/183513686-a2ac2b08-5641-440a-8101-7c652126ee81.png)

**Comment by moathOSA** [comment]
@leandrodiogenes  yes my problem is how to set the response example name in generated postman collection , sorry if my previous comment was ambiguous

**Comment by leandrodiogenes** [comment]
You have to specify your own custom response.
[https://scribe.knuckles.wtf/laravel/documenting/responses#response](https://scribe.knuckles.wtf/laravel/documenting/responses#response)

**Comment by leandrodiogenes** [comment]
@moathOSA No need to apologize, I probably got it wrong at first. 😆🤜🤛
