### ISSUE TITLE
[Feature request] Config item in scribe.php for CSS

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#51]
Hi,

If it's possible i suggest to create a variable into scribe.php for internal css for documentation. 
It can be :

```
$internalcss = <<< CSS
<style>
.params{
  font-weight:bold;
}
</style>
CSS;
```

This feature will create some freedom in css formating, that is missing.

Best Regards, keep up the good work.

**Comment by shalvah** [comment]
Hmmm. I'm reluctant to add any styling changes like this to the config, until Pastel supports such at least.

How about injecting it into the generated Markdown instead? You can put a `<style>` tag anywhere (or even create a  `prepend.md` containing that only, and it should be properly moved into the head by the browser.

**Comment by shalvah** [comment]
> Hmmm. I'm reluctant to add any styling changes like this to the config, until Pastel supports such at least.
> 
> How about injecting it into the generated Markdown instead? You can put a `<style>` tag anywhere (or even create a `prepend.md` containing that only, and it should be properly moved into the head by the browser.

I think this should work, but if you want a more elegant solution, we're having [a related discussion](https://github.com/knuckleswtf/pastel/issues/3#issuecomment-658575235) in Pastel. If we can get support for custom styles in there, we can easily expose that as an option here.

**Comment by shalvah** [comment]
See the RFC that would help with this: #105

**Comment by shalvah** [comment]
Scribe v3 (likely released next week) comes with a new theming system that eliminates the need for Pastel, so I'm closing this. You can create your own theme, and (though it's a bit of work), modify the default.

**Comment by shalvah** [comment]
🎉[v3 is out now](https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3), with the new theming system.
