### ISSUE TITLE
How to use No-example with formRequest bodyParameter or queryParameter ?

### ISSUE THREAD

**Issue by oskobri** [knuckleswtf/scribe#510]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

![image](https://user-images.githubusercontent.com/43296157/185414623-e2e5d200-fd20-4ed1-9ea2-f6aa6bc189b7.png)

If i set No-example instead of 1, it just write No-example in the query param

**Comment by leandrodiogenes** [comment]
Hi @oskobri 
check [448#](https://github.com/knuckleswtf/scribe/issues/448#issuecomment-1065965102)

**Comment by oskobri** [comment]
Nice, thanks !
