### ISSUE TITLE
Bearer token for each request to generate documentation

### ISSUE THREAD

**Issue by stevenoclock** [knuckleswtf/scribe#513]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hey !

I'm trying to add an Authorization header with a bearer token for each request to generate automatic responses in my documentation. I was thinking that the `beforeResponseCall()` hook could help me but it seems that it doesn't work (always 401 Unauthenticated as response) for my need. Is there a way to achieve that with Scribe? 👀

Have a good day !

**Comment by leandrodiogenes** [comment]
Hi, can you provide more details about your code?

**Comment by stevenoclock** [comment]
Hi @leandrodiogenes !

I just put this code in the boot() method of my AppServiceProvider. When I test the $token variable, the token to authenticate my request is ok :

```php
if (class_exists(Scribe::class)) {
    Scribe::beforeResponseCall(function (Request $request, ExtractedEndpointData $endpointData) {
        $token = Http::asForm()->post('very_private_url', [
            // credentials
        ])->json('access_token');
                
        $request->headers->add(["Authorization" => 'Bearer '. $token]);
    });
}
```

**Comment by shalvah** [comment]
Hmm, looks like something's buggy. Will check it out.

**Comment by shalvah** [comment]
I think this is the problem.

https://github.com/knuckleswtf/scribe/blob/28f4a2429e2561aab23ed6c9f15114f16feb25a1/src/Extracting/Strategies/Responses/ResponseCalls.php#L344-L360

You're setting the header correctly in Symfony's HeaderBag, but it also needs to be set as `$_SERVER['HTTP_AUTHORIZATION']`.

This should work (I think):

```php
$request->headers->add(["Authorization" => 'Bearer '. $token]);
$request->server->add(["HTTP_AUTHORIZATION" => 'Bearer '. $token]);
```

I'll update the docs on the hook to mention this.
