### ISSUE TITLE
'type' doesn't apply by bodyParameters()

### ISSUE THREAD

**Issue by LabSilo** [knuckleswtf/scribe#514]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
`bodyParameters()` method in the FormRequest:
```
    public function bodyParameters(): array
    {
        return [
            'parent_id' => [
                'description' => 'The parent id.',
                'type' => 'int',
                'example' => null,
            ],
        ];
    }
```

`rules()` function in the FormRequest:
```
     /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(): array
    {
        return [
            'parent_id' => 'nullable|exists:test_columns,id',
        ];
    }
```

I expect the documentation to have `parent_id` type as `int` but it's string. it just set to int if i set it in `rules` which i should not do that because id columns in laravel are `BIGINT` and integer cannot validate that in case of big integer IDs.

**Screenshots and stack traces:**
![image](https://user-images.githubusercontent.com/110684470/188305051-5f1e4ece-6f5b-49c8-9bbe-2c06c2d89152.png)

**My environment:**
 - PHP version (from `php -v`): 8.1.3
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 9.27.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.37.0

**My Scribe config (minus the comments):**
I guess only strategies are needed, here it is (are just the defaults):
```
'strategies' => [
        'metadata' => [
            Strategies\Metadata\GetFromDocBlocks::class,
        ],
        'urlParameters' => [
            Strategies\UrlParameters\GetFromLaravelAPI::class,
            Strategies\UrlParameters\GetFromLumenAPI::class,
            Strategies\UrlParameters\GetFromUrlParamTag::class,
        ],
        'queryParameters' => [
            Strategies\QueryParameters\GetFromFormRequest::class,
            Strategies\QueryParameters\GetFromInlineValidator::class,
            Strategies\QueryParameters\GetFromQueryParamTag::class,
        ],
        'headers' => [
            Strategies\Headers\GetFromRouteRules::class,
            Strategies\Headers\GetFromHeaderTag::class,
        ],
        'bodyParameters' => [
            Strategies\BodyParameters\GetFromFormRequest::class,
            Strategies\BodyParameters\GetFromInlineValidator::class,
            Strategies\BodyParameters\GetFromBodyParamTag::class,
        ],
        'responses' => [
            Strategies\Responses\UseTransformerTags::class,
            Strategies\Responses\UseApiResourceTags::class,
            Strategies\Responses\UseResponseTag::class,
            Strategies\Responses\UseResponseFileTag::class,
            Strategies\Responses\ResponseCalls::class,
        ],
        'responseFields' => [
            Strategies\ResponseFields\GetFromResponseFieldTag::class,
        ],
    ],
```

**Comment by leandrodiogenes** [comment]
Hi @LabSilo 
you have to specify the the int rule to set the parameter type.
```php
  public function rules(): array
    {
        return [
            'parent_id' => 'nullable|int|exists:test_columns,id',
        ];
    }
```

**Comment by LabSilo** [comment]
@leandrodiogenes Thanks, while i was researching to tell you FILTER_VALIDATE_INT is not suitable for BIGINT i found that PHP is not like C# and many other programming languages so PHP_INT_MAX will be 9223372036854775807 on 64 bit systems lel.
Yeah i came from .NET and there we have to use long and ulong for such big numbers even in 64 bit systems
