### ISSUE TITLE
php artisan scribe:generate doesn't generate updated documentation.

### ISSUE THREAD

**Issue by brainlet-ali** [knuckleswtf/scribe#52]
I'm using Lumen 7,

I've this on my login method,

  /**
     * Customer Info
     * Get current customer's info
     *
     *
     * @authenticated
     * @group Customer
     * @response {
     * "data": {
     * "id": 3,
     * "name": "Tina Luettgen",
     * "email": "pfeffer.jaren@example.net",
     * "mobile": "1-396-427-6971",
     * "email_verified_at": "2019-05-05 11:26:54",
     * "mobile_verified_at": "2019-05-05 11:26:54",
     * "avatar": "default.jpg",
     * "created_at": "2019-05-05 11:26:54",
     * "updated_at": "2019-05-05 11:26:54"
     * },
     * "status": 200
     * }
     */

But when try to run php artisan scribe:generate it just generate default documentation with annotation not taking any effect.

[Generated Docs](https://pasteboard.co/JfC3vGg.png)

**Comment by shalvah** [comment]
You should review your configuration settings. Is Scribe set up to pick up that route?

**Comment by brainlet-ali** [comment]
/*
             * Specify conditions to determine what routes will be parsed in this group.
             * A route must fulfill ALL conditions to pass.
             */
            'match' => [
                /*
                 * Match only routes whose domains match this pattern (use * as a wildcard to match any characters). Example: 'api.*'.
                 */
                'domains' => ['*'],

                /*
                 * Match only routes whose paths match this pattern (use * as a wildcard to match any characters). Example: 'users/*'.
                 */
                'prefixes' => ['*'],

                /*
                 * (Dingo router only) Match only routes registered under this version.
                 * Note that wildcards are not supported.
                 */
                'versions' => ['v1'],
            ],

All looks good, it pick all the routes just don't apply the annotations.

**Comment by shalvah** [comment]
Hmm. Are you sure your docblock is right next to your methods? No extra lines in between?

**Comment by brainlet-ali** [comment]
Tried both:
 
    /*** Customer Info
     * Get current customer's info
     *
     *
     * @authenticated
     * @group Customer
     * @response {
     * "data": {
     * "id": 3,
     * "name": "Tina Luettgen",
     * "email": "pfeffer.jaren@example.net",
     * "mobile": "1-396-427-6971",
     * "email_verified_at": "2019-05-05 11:26:54",
     * "mobile_verified_at": "2019-05-05 11:26:54",
     * "avatar": "default.jpg",
     * "created_at": "2019-05-05 11:26:54",
     * "updated_at": "2019-05-05 11:26:54"
     * },
     * "status": 200
     * }
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function login(Request $request)
    { ....


    /*** Customer Info
     * Get current customer's info
     *
     *
     * @authenticated
     * @group Customer
     * @response {
     * "data": {
     * "id": 3,
     * "name": "Tina Luettgen",
     * "email": "pfeffer.jaren@example.net",
     * "mobile": "1-396-427-6971",
     * "email_verified_at": "2019-05-05 11:26:54",
     * "mobile_verified_at": "2019-05-05 11:26:54",
     * "avatar": "default.jpg",
     * "created_at": "2019-05-05 11:26:54",
     * "updated_at": "2019-05-05 11:26:54"
     * },
     * "status": 200
     * }
     */
    public function login(Request $request)
    { ....

**Comment by shalvah** [comment]
Try moving the title line onto a new line. The first line of the doc block should just have `/**`.

Also, double check your config and make sure the DocBlock strategies are listed in the `strategies` section.

Lastly, add some `dump()` statements in some of those DocBlock strategies and see if they get executed.

**Comment by brainlet-ali** [comment]
Thanks for sticking around. It did work. Thanks

**Comment by shalvah** [comment]
What was the problem? Would be helpful to document it here in case someone else with a similar issue comes across this in future.

**Comment by brainlet-ali** [comment]
I Believe it's a caching issue, when I deleted the public/docs and resouces/docs and retry with same exact thing in the first comment. It works

Yesterday changing DOC BLOCKS had no effect on generated DOCS, just the default docs, no change whatever I did.

**Comment by parashagrawal75** [comment]
Having same issue. Does not update the docs.
