### ISSUE TITLE
Date and time of last update in sidebar

### ISSUE THREAD

**Issue by MaRmARk0** [knuckleswtf/scribe#520]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
My colleagues wanted to add also _time_ part into Last updated sidebar footer which is currently not achievable.

In default built-in theme in `sidebar.blade.php` there is
```
    <ul class="toc-footer" id="last-updated">
        <li>Last updated: {{ $metadata['last_updated'] }}</li>
    </ul>
```

That `last_updated` is being filled by `HtmlWriter.php` and is hard coded:
```
        return [
            'title' => $this->config->get('title') ?: config('app.name', '') . ' Documentation',
            'example_languages' => $this->config->get('example_languages'),
            'logo' => $this->config->get('logo') ?? false,
            'last_updated' => date("F j Y"),
            'auth' => $auth,
            'try_it_out' => $this->config->get('try_it_out'),
            'links' => array_merge($links, ['<a href="http://github.com/knuckleswtf/scribe">Documentation powered by Scribe ✍</a>']),
        ];
```
They'd like to have an opportunity to add custom data (git commit ID from which the docs were generated) and date as well as time (`Y-m-d H:i:s`) of last update. We do a deploy backend multiple times a day a frontend devs don't know which backend docs they currently see. 

**My environment:**
 - php v8.1.10
 - Laravel v9.30.1
 - nuckleswtf/scribe v4.0.0

**Comment by shalvah** [comment]
That sounds doable.

**Comment by shalvah** [comment]
Done in 4.1.0. https://scribe.knuckles.wtf/laravel/reference/config#last_updated
