### ISSUE TITLE
Empty sidebar in docs

### ISSUE THREAD

**Issue by wrabit** [knuckleswtf/scribe#521]
I'm getting this from a scribe:generate, the docs include the generated content in the scrollable area, but no links in sidebar to the sections (also checked html). Also in the console I am seeing errors, also below:

(replace things with xxx)
```
php artisan scribe:generate
ⓘ Processing route: [GET] api/v1/xxx/{data_source}
✔ Processed route: [GET] api/v1/xxx/{data_source}
ⓘ Processing route: [GET] api/v1/device/{red_line_id}
✔ Processed route: [GET] api/v1/device/{red_line_id}
ⓘ Processing route: [POST] api/v1/xxx/{data_source}
✔ Processed route: [POST] api/v1/xxx/{data_source}
ⓘ Processing route: [POST] api/v1/xxx/{red_line_id}
✔ Processed route: [POST] api/v1/xxx/{red_line_id}
ⓘ Processing route: [POST] api/v1/xxx
✔ Processed route: [POST] api/v1/xxx
ⓘ Extracting intro and auth Markdown files to: .scribe
✔ Extracted intro and auth Markdown files to: .scribe
ⓘ Writing Blade docs...
✔ Wrote Blade docs to: /Users/will/Code/xxx/resources/views/scribe/
✔ Wrote Laravel assets to: /Users/will/Code/xxx/public/vendor/scribe
ⓘ Generating Postman collection
✔ Wrote Postman collection to: storage/app/scribe/collection.json
ⓘ Generating OpenAPI specification
✔ Wrote OpenAPI specification to: storage/app/scribe/openapi.yaml
Checking for any pending upgrades to your config file...

✔ All done. Visit your docs at https://xxx.test/docs
```

Console on the /docs page:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/5918271/191478170-9e1e92cf-1f9c-4d8f-baf8-884bbc9716d0.png">

<img width="226" alt="image" src="https://user-images.githubusercontent.com/5918271/191478234-ddbb392e-d840-4683-abed-1952beccddc6.png">

**Comment by shalvah** [comment]
Have you tried updating to v4?

**Comment by wout101media** [comment]
I know this issue is closed but i'm having the same problem as well while generating docs.
All data i have is added. But menu is not generated.
Running scribe version 4.12. Getting the same errors as the screenshot poster above so could that be the cause?
Or do you maybe have any other ideas i could check @shalvah ?

**Comment by shalvah** [comment]
Check your devtools console. Are the JavaScript files properly loaded?

**Comment by wout101media** [comment]
> Check

Yeah everything was correctly loaded.
Still didnt find the cause of the bug happening. 
But gave up searching decided to delete everything scribe related and start anew. seems to work fine now
