### ISSUE TITLE
Is it possible to use a custom base URL for custom endpoints?

### ISSUE THREAD

**Issue by HaakonFlaaronning** [knuckleswtf/scribe#523]
When defining [custom endpoints](https://scribe.knuckles.wtf/laravel/documenting/custom-endpoints), is it possible to define a custom base URL for those endpoints? It automatically sets the base URL from the scribe config file, but it would be desirable to be able to set a custom base URL. I have a couple of endpoints that I want to include in the documentation that use a different base URL than most others.

**Comment by HaakonFlaaronning** [comment]
bump

**Comment by shalvah** [comment]
I mean, no it isn't, and I can't make any plans for that rn. But the EndpointData objects (both Extracted and Output) support a `custom` property where you can put whatever.

https://github.com/knuckleswtf/scribe/blob/0560f07cd6f4392b112df7a198f8dbb05b0b3688/camel/BaseDTO.php#L15

With that + customising the templates a bit, you could probably get a custom endpoint with a custom base URL to show.
