### ISSUE TITLE
Scribe does not make Postman folder for subgroups

### ISSUE THREAD

**Issue by HaakonFlaaronning** [knuckleswtf/scribe#524]
On default, the Postman collection generated by Scribe creates a new folder per group (@group tag), but does not create a new folder inside the group folder for each subgroup (@subgroup tag). Shouldn't new subgroup folders be created inside the group folder? Is there a way to make it so?

**Comment by shalvah** [comment]
Not so easy, bit doable, I believe. PRs welcome.

**Comment by shalvah** [comment]
Done in 4.1.0
