### ISSUE TITLE
using queryParam generate also bodyParam in docs

### ISSUE THREAD

**Issue by malogajski** [knuckleswtf/scribe#525]
Please check this example, with and without validation.
Laravel 8, php 8.0

`    /**
     * Index
     *
     * Display all users
     * @authenticated
     * @queryParam first_name string Last name. No-example
     * @queryParam last_name string First name. No-example
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index(Request $request)
    {
        $data = $request->all();

        $rules = [
            'first_name' => 'string|nullable',
            'last_name' => 'string|nullable',
        ];

        $this->validate($request, $rules);

        return response()->json($data);
    }`

This will generate both query and body parameters:
![image](https://user-images.githubusercontent.com/10074397/193239437-94b3150b-7717-485f-8a52-25dac67dc8b8.png)

But without "validation" it will works as expected and will generate only query parameters fields.

Any ideas or suggestions?

**Comment by shalvah** [comment]
Some options:
1. Do you want Scribe to generate from validation rules? If not, you can remove the strategy from your config file.
2. You can remove the `@queryParam` and add a `// Query parameters` comment above the validation rules.

See the docs for details. https://scribe.knuckles.wtf/laravel/documenting/query-body-parameters#using-validation-rules-for-query-parameters
