### ISSUE TITLE
BindingResolutionException: Target [Illuminate\Database\Eloquent\Model] is not instantiable while building

### ISSUE THREAD

**Issue by gabrielrbarbosa** [knuckleswtf/scribe#526]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

**Illuminate\Contracts\Container\BindingResolutionException in /var/www/httpdocs/v3/vendor/laravel/framework/src/Illuminate/Container/Container.php at line 884: Target [Illuminate\Database\Eloquent\Model] is not instantiable while building [App\Rules\Unique].**

AppServiceProvider.php
```
Scribe::instantiateFormRequestUsing(function (string $className, Route $route, \ReflectionFunctionAbstract $method) {
    return app()->makeWith(Unique::class, [1]);
});
```

Rules/Unique.php
```
use Illuminate\Database\Eloquent\Model;
class Unique implements Rule{
    public function __construct(Model $model) {
        $this->model =  $model;
    }
}
```

ExampleRequest.php
```
class ExampleRequest extends FormRequest {
    public function rules() {
        return [
            'email' => [
                'nullable',
                'email',
                new Unique(new User(), $this->clienteSistemaId)
            ],
        ];
    }
}
```

Unique rule can recieve multiple models as parameter, but using Illuminate\Database\Eloquent\Model as type hint throws these exceptions, is there any solution?

**Comment by leandrodiogenes** [comment]
Hi @gabrielrbarbosa.
I dont think this is something related to scribe.
I believe you are using unique rule incorrectly.

try this..
```php
class ExampleRequest extends FormRequest {
    public function rules() {
        return [
            'email' => [
                'nullable',
                'email',
               (new Unique(User::class))->ignore($this->clienteSistemaId)
            ],
        ];
    }
}

```
or 
```php
class ExampleRequest extends FormRequest {
    public function rules() {
        return [
            'email' => [
                'nullable',
                'email',
               \Illuminate\Validation\Rule::unique(User::class)->ignore($this->clienteSistemaId)]
            ],
        ];
    }
}

```

**Comment by shalvah** [comment]
@gabrielrbarbosa looking at your error message, I think this is your problem

```php
Scribe::instantiateFormRequestUsing(function (string $className, Route $route, \ReflectionFunctionAbstract $method) {
    return app()->makeWith(Unique::class, [1]); // ❌
});
```
I don't think you understand the point of `instantiateFormRequestUsing()`. `instantiateFormRequestUsing()` is meant to return an instance of a `FormRequest`. Instead, you're trying to create an instance of the `Unique` rule, which is failing because it needs a model. You can remove this whole `instantiateFormRequestUsing()`, and you should be good. I've also updated the docs to make the usage of `instantiateFormRequestUsing()` clearer.
