### ISSUE TITLE
Optional object bodyparam

### ISSUE THREAD

**Issue by anigroSIS** [knuckleswtf/scribe#528]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.
I have a optional object with more params and I want define one param as required if the optional parent is defined

**Comment by leandrodiogenes** [comment]
Hi @anigroSIS,
I dont think this is something related to scribe, but try this..

```php
    public function rules() {
        return [
            'products'       => ['array'],
            'products.name'  => ['required', 'string'],
            'products.price' => ['required', 'numeric'],
        ];
    }
```

**Comment by anigroSIS** [comment]
Hi Leandro,
my goal is to avoid show the optional object param "sorting" in example section. 
If I set the childs as required "sorting" object is reported in example section, also I set No-example.

This is my body specification by manual way:
     * @bodyParam filter object
     * @bodyParam filter.orderby sorting[] array di sorting. Example: [{"field": "field_1", "order": "asc"}]
     * 
     * @bodyParam sorting object No-example
     * @bodyParam sorting.field string field name No-example
     * @bodyParam sorting.order string sorting type [asc,desc] No-example

thks

**Comment by shalvah** [comment]
Hm, you're saying you want `sorting`'s fields to be required, but `sorting` itself to be optional? Hmm, setting `No-example` on `sorting` alone should work. I'll take a look at it. Can you share a screenshot of the generated example?

**Comment by shalvah** [comment]
Thanks for all your help with issues btw @leandrodiogenes . Much appreciated 👏
