### ISSUE TITLE
why app.js not use assetPathPrefix?

### ISSUE THREAD

**Issue by lengjunbin-trec** [knuckleswtf/scribe#534]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.
I checked the source code.and found different.
when load other js or css ,it used `$assetPathPrefix`.but app.js not used.
![image](https://user-images.githubusercontent.com/61955063/195504541-7db577d7-991c-4b56-838a-d4479b1bb419.png)

becasue I generate the api doc on my local.but whe ni push this into staging environment.becasue the api doc is generated on my local.so it still load my local app.js.

**Comment by lengjunbin-trec** [comment]
@shalvah

**Comment by shalvah** [comment]
1. You don't have to mention the maintainer whenever you create an issue. We're not your personal support team; we have our own lives and jobs. We'll look at your issue when we have time.
2. That line is not from this package. Look at the template file that's used. https://github.com/knuckleswtf/scribe/blob/master/resources/views/themes/default/index.blade.php We don't even use highlight.js, like in your screenshot, so I'm not sure where that's from. Looks like you either customized the templates or something else is modifying them.
