### ISSUE TITLE
Undefined variable $headingsBeforeEndpoints

### ISSUE THREAD

**Issue by N3OGeorgy** [knuckleswtf/scribe#536]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I recently updated my app from Laravel 7 to 9 and scribe from 3.3 to 4.1.
I don't have any templates, cleared the cache, removed the config file and published again.

When i try to generate the docs i get this error:

```
Writing Blade docs...

   Illuminate\View\ViewException 

  Undefined variable $headingsBeforeEndpoints (View: ...laravel/resources/views/vendor/scribe/themes/default/sidebar.blade.php) (View: .../laravel/resources/views/vendor/scribe/themes/default/sidebar.blade.php)
```

Same issue with ```$headingsAfterEndpoints```.

The only fix is publishing the default theme, putting @if(isset())@endif for both of the variables.
I'm unable to find the source of this problem.

THank you

**Comment by leandrodiogenes** [comment]
Make sure you are on the latest version of scribe.
There is no more $headingsBeforeEndpoints variable on sidebar.blade.php file.
That part was refactored on latest version.
https://github.com/knuckleswtf/scribe/blob/fca55860d8cab9306dd9c23ebf20f4bf4b644e84/resources/views/themes/default/sidebar.blade.php#L26-L30

https://github.com/knuckleswtf/scribe/commit/2ebf40b5e5be309bf5e685a0cd58bb70856b033d#diff-c6e9e5f7f8c676fb9262bed9ccc8bbfda39efd1132db2d21814f0b89887da357

**Comment by shalvah** [comment]
Thanks @leandrodiogenes . Indeed, that code was removed in v4, so you should double check @N3OGeorgy
