### ISSUE TITLE
How API resources in my custom api response layout

### ISSUE THREAD

**Issue by hooman-mirghasemi** [knuckleswtf/scribe#537]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

when use API resources it genereate response like this:

{
    "user": {
        "id": null,
        "first_name": null,
        "last_name": null,
        "username": null,
        "email": null,
        "mobile": null,
        "avatar": null,
        "roles": [],
        "active_advertisements_count": null,
        "status": null,
        "created_at": null,
        "activePlan": null
    },
}

and if i use @apiResourceAdditional test=aa
it will like this:
{
    "user": {
        "id": null,
        "first_name": null,
        "last_name": null,
        "username": null,
        "email": null,
        "mobile": null,
        "avatar": null,
        "roles": [],
        "active_advertisements_count": null,
        "status": null,
        "created_at": null,
        "activePlan": null
    },
    "test": "aa",
}

how can i generate response to wrap in data,like this
{
  "data"{
      "user": {
          "id": null,
          "first_name": null,
          "last_name": null,
          "username": null,
          "email": null,
          "mobile": null,
          "avatar": null,
          "roles": [],
          "active_advertisements_count": null,
          "status": null,
          "created_at": null,
          "activePlan": null
      },
   }
    "test": "aa",
}

**Comment by shalvah** [comment]
If you're asking about the `data` key, I think that's from Laravel. You should enable `data` wrapping in your resource.

https://laravel.com/docs/9.x/eloquent-resources#data-wrapping
