### ISSUE TITLE
Support laravel-json-api package

### ISSUE THREAD

**Issue by IAndreaGiuseppe** [knuckleswtf/scribe#538]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

We build our API with [laravel-json-api](https://github.com/laravel-json-api/laravel) package, is it supported by Scribe?

Thanks

**Comment by shalvah** [comment]
> is it supported by Scribe?

Hmm, I'm not sure what that entails...We don't have any special features for that package, but you could probably still use Scribe to document your API with it, as long as you have the main entry points of routes and controller classes/methods. And if you see a need/opportunity for a custom integration, you can suggest it.
