### ISSUE TITLE
Unable to customize the environment file

### ISSUE THREAD

**Issue by HaakonFlaaronning** [knuckleswtf/scribe#539]
I am unable to make Scribe read a custom .env.docs file when generating the docs through the command 
`php artisan scribe:generate --env docs`

Regardless of the **env** flag, Scribe only reads my .env file.

Do I have to se something in the Scribe config for the **env** flag to work? I am attempting to update the docs as a part of CI/CD using github actions.

**Comment by shalvah** [comment]
The env flag comes from Laravel. Laravel loads the specified env file before Scribe is even called. Either there's a bug in Laravel here (unlikely, but you can easily verify by dumping the loaded env), or you have incorrect expectations. What do you mean when you say the env isn't read? What places are you expecting to see the env values, and seeing something else?
