### ISSUE TITLE
Override default urlParamName and queryParamName with model binding

### ISSUE THREAD

**Issue by eduardodgarciac** [knuckleswtf/scribe#541]
Hi, I want to change the way parameters are named when using model binding.

Why? I have some old tables with wrong named columns so endpoints like `projects/{project}` end up like `projects/project_id_project` in the documentation, I just want to get `project_id` as parameter name.

I know I can get the result I expect by using {project_id} in the URL and setting Route::model(...) but the documentation is generated saying that the expected parameter is string

**Comment by shalvah** [comment]
How would you suggest being able to change that? At this point, route model binding is probably the most problematic part of docs generation for us. Maybe we should just provide a hook:

```php
Scribe::normalizeUrlUsing(function ($path, $endpoint) {
  return match ($path) {
    "projects/{project}" => "projects/{project_id}"
    default => null,
  };
});
```

But I'm wary of adding another hook.🤔

**Comment by eduardodgarciac** [comment]
Thinking of the simplest

Currently the behavior is to automatically add the primary key to the url parameter when model binding is used, maybe you can add a setting to disable it, if disabled, just concatenate id?. Also, when disabled, inferring the data type must still be done with the primary key.

Another useful option would be to be able to configure whether to force camelCase in the parameters, since when using model binding there may be cases where you use words like ProjectType. This case is generating {projectType_(primaryKey)}

Hmm, maybe some configuration options on how to deal with model binding and parameters.

Perhaps from these observations you have better suggestions.

**Comment by shalvah** [comment]
Unfortunately, there's no chance I'm adding any config options for this. We're approaching the stage of "too many settings", so only really important stuff get in.

Note that there are two separate things here:
- URL normalization: Laravel gives us `/projects/{project}`, and we convert it to `/projects/{project_id}` (or whatever) so it isn't confusing for non-Laravel users. This part is happened at the start of the extraction phase, when the EndpointData object is constructed.
- URL parameter extraction and inference: Then we extract the `project_id` from that URL and infer a type and description, if we can. This part happens during the `urlParameters` strategies.

Although it's some work, you can override the inference (for all endpoints) by disabling or using your custom strategy. Additionally, if you specify the parameter in your docblock with `@urlParam`, it'll override the inferred one (if the name is the same).

The normalization seems to be where your main problem is. I don't see a benefit for more configuration options, but it _should_ be customizable, so I think I'll go with the hook approach. Basically, you either use Scribe's default normalization, or override it with yours.

**Comment by shalvah** [comment]
In 4.2.0, you can now customise the normalization.

```php
Scribe::normalizeEndpointUrlUsing(function (string $url, Route $route, ReflectionFunctionAbstract $method, ReflectionClass $controller) {
  if ($url == 'things/{thing}') 
    return 'things/{the_id_of_the_thing}';

  if ($route->named('things.otherthings.destroy')) 
    return 'things/{thing-id}/otherthings/{other_thing-id}';
    
  return match ($route->name) {
    'people/{person}' => ...
  };
});
```
https://scribe.knuckles.wtf/laravel/hooks#normalizeendpointurlusing
