### ISSUE TITLE
Is there a way to add scripts in the Postman collection output

### ISSUE THREAD

**Issue by aledeg** [knuckleswtf/scribe#542]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I've checked the code in _PostmanCollectionWriter_ class and I couldn't find a place where the `event` array is added in the collection nor in the items.
Am I missing something?
If it's not possible as-is, is there a way I could achieve that? Maybe with some decorator.
If not, is it something that could be added in future release?

Thank you!

**Comment by shalvah** [comment]
I don't understand. Does the `postman.overrides` field not do what you need? https://scribe.knuckles.wtf/laravel/reference/config#postman

**Comment by aledeg** [comment]
Thank you for the pointer. I thought it was working only with values declared in the aforementioned class.
Now, I need to figure out how to not escape my slashed (`/`).

**Comment by aledeg** [comment]
As I've succeed configuring the prerequest script for the whole collection, I figured I share that here.

I've added the following in the `postman.overrides` configuration:
```php
'event' => [
    [
        'listen' => 'prerequest',
        'script' => [
            'type' => 'text/javascript',
            'exec' => file(config_path('js/prerequest.js'), FILE_IGNORE_NEW_LINES),
        ],
    ],
],
```

**Comment by aledeg** [comment]
Linked to #121

**Comment by shalvah** [comment]
Nice. Thanks for sharing.
