### ISSUE TITLE
Remove automatic URL parameter examples

### ISSUE THREAD

**Issue by HaakonFlaaronning** [knuckleswtf/scribe#543]
It could be nice to add the options for Scribe not to generate automatic examples for URL parmeters, without having to specify No-example in in the docblock. We end up with funky looking example requests. I changed it by creating a custom strategy for URL parameters and adding the following:

```
        # Replace random example placeholders placed automatically by Scribe 
        foreach ($endpointData->urlParameters as $urlParam) {
            $urlParam['example'] = ':' . $urlParam->name . ($urlParam->required ? '' : '?');
            $default[$urlParam->name] = $urlParam;
        }
```

**Comment by shalvah** [comment]
Unlikely that'll change, sorry. How about just specifying an example in the docblock? It's kind of the price you pay: describe your data, or Scribe will try to do so for you.
