### ISSUE TITLE
Abandoned Spatie package

### ISSUE THREAD

**Issue by SturmB** [knuckleswtf/scribe#546]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

While updating all the packages in our Laravel API app, this package is causing Composer to throw a warning:

```
Package spatie/data-transfer-object is abandoned, you should avoid using it. Use spatie/laravel-data instead.
```

Are there any plans to update Scribe to use `spatie/laravel-data` in the near future?

**Comment by shalvah** [comment]
No, there aren't. This package does everything we need at the moment. Switching to the new package would be a shit ton of work for zero added benefit.

That's how software works, (un)fortunately. People can deprecate software, but that doesn't mean it's bad or it doesn't work. It just means they're no longer interested in maintaining it, and that's okay. As long as they don't force you to stop using it. Imagine if I spent hours migrating to the new package, and in a few months they deprecate it for another one, and so on. It's a rat race that'll never end.

Sorry for the extra message in your logs, but luckily it's just a warning, so you can ignore it.

**Comment by repat** [comment]
@shalvah Would you accept a pull request to migrate this to `spatie/laravel-data`? For you it'd be the same "rat race that'll never end"... but somebody else does the work ;-)

**Comment by shalvah** [comment]
Sure, but the resulting DX shouldn't be worse. I haven't gone through this new package, but I recall disagreeing with some design decisions of a later version of the old one. Also, I feel like the new one is geared more towards use in Laravel apps (as opposed to libraries), but sure, give it a shot.
