### ISSUE TITLE
Scribe file upload not working with v2

### ISSUE THREAD

**Issue by JignasaSutariya** [knuckleswtf/scribe#547]
I'm using `knuckleswtf/scribe` with version `2.7.9`.
I've used `file` with `@bodyParam`. It allows to select the file in Scribe doc. But, not getting file after submitting the form, I'm not able to get the file. Am I missing anything while implementing?

**Comment by shalvah** [comment]
I'm sorry, 2.7.9 is a pretty old version, which I'm no longer supporting, so I can't help you there. You could try upgrading to a recent version. Either way, there's nothing I can do with this amount of information. You should try inspecting the request sent in your browser and received by your server.
