### ISSUE TITLE
Can't display the Bearer token field anymore

### ISSUE THREAD

**Issue by eneabb** [knuckleswtf/scribe#550]
I started using the 4.x version on a brand new project. 
However, it seems I cannot display the "bearer token" field anymore when trying an authenticated endpoint.

For instance, I'm using the 3.x version on another project and I see this when I try  an authenticated endpoint:
![Screenshot_20221108_150334](https://user-images.githubusercontent.com/114412105/200586114-6f7a2065-30a1-4349-9476-7f0e8e47ac82.png)

Now I see this:
![Screenshot_20221108_150433](https://user-images.githubusercontent.com/114412105/200586173-6066733a-acab-426b-92a5-dc75c54d86e4.png)

Are there any important new settings inside `config/scribe.php` I should have missed?
I basically copy/pasted the previous working configuration and I'm a bit confused

**Comment by shalvah** [comment]
No, nothing changed regarding that. Does it show in the example requests? Are you sure it isn't just a JS failure?

**Comment by shalvah** [comment]
I haven't been able to replicate this. Can you update and try now? Made some changes to how the Auth header (and headers in general) are displayed. There's also a new theme you can try out, `elements`.
