### ISSUE TITLE
Documenting Custom Rules

### ISSUE THREAD

**Issue by MissaelAnda** [knuckleswtf/scribe#551]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

It would be cool if custom rules could be documented with description and example.

This:
```php
/**
 * @description This rule validates something
 * @example "This:Is:An:Example"
 */
class CustomRule implements Rule
{
    //
}
```

Produces:
![imagen](https://user-images.githubusercontent.com/31199350/200691715-457e384c-40bd-43e5-b317-f5639bf55966.png)

**Comment by shalvah** [comment]
Good idea. PRs welcome.

I'd prefer a static `docs` method, though. It's simpler to implement and avoids us having to parse the annotation text, which can get tricky.
