### ISSUE TITLE
spatie/data-transfer-object abandoned warning

### ISSUE THREAD

**Issue by Purtl** [knuckleswtf/scribe#552]
Heyho,
today I got a warning about this package using the abandoned package `spatie/data-transfer-object`.

The full error-message:
`Package spatie/data-transfer-object is abandoned, you should avoid using it. Use spatie/laravel-data instead.`

Or do I have to change something?

Thanks

**Comment by shalvah** [comment]
Sucks, but https://github.com/knuckleswtf/scribe/issues/546#issuecomment-1302836669
