### ISSUE TITLE
#[ResponseFromApiResource] and Response Fields on Eloquent API resource toArray() method

### ISSUE THREAD

**Issue by jedlikowski** [knuckleswtf/scribe#553]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hi, it's me again :) I'm writing a documentation for our API and I'm using the attributes on my controller methods to provide info about the Eloquent resource returned. At first I was using `@apiResource` tags but wanted to move to attributes because some endpoints required them (multiple possible resources returned) and I wanted to keep the annotations consistent.

However, looks like when using `#[ResponseFromApiResource]` attribute it's not possible to specify the response fields on the Resource's `toArray()` method. I've tried adding both `@responseField` tag and `#[ResponseField]` attribute to provide some description of the response field, but neither way works to show the descriptions in the generated docs, but your documentation claims it's possible: https://scribe.knuckles.wtf/laravel/reference/annotations#responsefieldresponsefield. The descriptions worked when I used `@apiResource` tag in the docblock.

**Comment by shalvah** [comment]
Fixed in 4.2.2. However, you need to either use attributes in both places or tags in both places.
