### ISSUE TITLE
Authorization Header input not showing for try-it-out functionality

### ISSUE THREAD

**Issue by johnylemon89** [knuckleswtf/scribe#555]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
I cannot see that input as this func is broken.
![image](https://user-images.githubusercontent.com/86289323/201652817-b37615e0-3773-4914-8f5b-4a2da458bda7.png)

Config is absolutely valid  

**Problem:**

at first there is no single word in docs about `location` config option. But this option is used [here](https://github.com/knuckleswtf/scribe/blame/master/resources/views/themes/default/endpoint.blade.php#L97)

What more, even if I set that option in config (as I did) it still does not work. Why?
In [line 99](https://github.com/knuckleswtf/scribe/blame/master/resources/views/themes/default/endpoint.blade.php#L99) you assign `id` attribute to label instead of `data-endpoint`. That causes [this line](https://github.com/knuckleswtf/scribe/blob/master/resources/js/tryitout.js#L46) wont unhide rendered inputs

**Comment by shalvah** [comment]
Hm, I guess this must be the same issue as https://github.com/knuckleswtf/scribe/issues/550

`location` is an internal field; you don't need to bother with that. I see what you're saying about the label, but I haven't changed that line in a while, so not sure why it stopped working. 🤔

**Comment by johnylemon89** [comment]
@shalvah I see that code was changed 4 months ago and then 2 yr ago. But it does not work. 
Without 'location` field set in `config/scribe.php` the `<p>` node with try it out option does even not render so even if js selector was valid it won't inhide anything. I was looking for the problem for 2 days :/

**Comment by shalvah** [comment]
I haven't been able to replicate this. Also, can you try now? Made some changes to how the Auth header (and headers in general) are displayed. There's also a ew theme, `elements`.

**Comment by johnylemon89** [comment]
@shalvah  I found it working by changing some theme here:

**Comment by johnylemon89** [comment]
@shalvah  I found it working by changing theme file (`/resources/views/vendor/themes/default/endpoint.php`) in line 99 to something like that (I added `data` props to label).

```
@if($endpoint->metadata->authenticated && $metadata['auth']['location'] === 'header')
        <p>
            <label 
                id="auth-{{ $endpoint->endpointId() }}" 
                name="{{ $metadata['auth']['name'] }}"
                data-prefix="{{ $metadata['auth']['prefix'] }}"
                data-endpoint="{{ $endpoint->endpointId() }}"
                data-component="header"
                hidden
            >
                {{ $metadata['auth']['name'] }} header:
                <b><code>{{ $metadata['auth']['prefix'] }}</code></b>
                <input type="text"
                       name="{{ $metadata['auth']['name'] }}"
                       data-prefix="{{ $metadata['auth']['prefix'] }}"
                       data-endpoint="{{ $endpoint->endpointId() }}"
                       data-component="header">
            </label>
        </p>
    @endif
```

Earlier `label` tag looked like that:
```
<label id="auth-{{ $endpoint->endpointId() }}" hidden>
```

but js selector wanted data props on label (line 46 in `resources/js/tryitout.js`)
```
 document.querySelectorAll(`input[data-endpoint=${endpointId}],label[data-endpoint=${endpointId}]`)
```

Composer constraints: "knuckleswtf/scribe": "^4.2"
