### ISSUE TITLE
[Feature Request] Support uppercase and lowercase rule

### ISSUE THREAD

**Issue by ziming** [knuckleswtf/scribe#558]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

Laravel just added uppercase and lowercase validation rule today. It will be nice if this package can parse it and mention it in the auto generated documentation too, like it does for some of the other rules already

Thank you

**Comment by shalvah** [comment]
Hm, why did you close? It's a feature request that's on the table.
