### ISSUE TITLE
Generating documentation for a large number of routes

### ISSUE THREAD

**Issue by michaeldzjap** [knuckleswtf/scribe#560]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I'm trying to generate documentation for an API that currently exists of 177 routes and I'm running into memory issues due to large files Scribe generates during the documentation generation process. In my case I end up with a _00.yaml_ file of 344MB and an _index.blade.php_ file of 517MB.

Now obviously there are a couple of things I can do myself to reduce the issues. I can reduce the number of routes for which to generate the documentation and I could tinker with the memory limit setting in my php.ini. However, I most likely will need to document all my API routes at some point and it is quite likely that more will be added in the future. Hence, increasing my PHP memory limit is not the most optimal thing to do to fix these problems in a solid, permanent way.

To make a long story short; do you have any advice on how to handle generating documentation for an API with a large amount of routes? And do you perhaps have any future plans for dividing up all the generated documentation data into multiple YAML and blade templates instead of a single file that can basically grow to any size? Don't get me wrong, I think this is a great package where clearly a lot of effort has gone into. However, the memory issues with larger API's is kind of a concern for me from a practical perspective.

**Comment by shalvah** [comment]
First, regarding PHP memory limit: you don't need to adjust your ini file. The troubleshooting guide mentions that you can pass a command-line flag to adjust it.

Regarding file sizes, yes, those are unfortunate. But I think it's a mix of things you can do and things this package can do.

For one, I don't think there's much we can do to reduce the size of the YAML files or templates themselves. The YAML files are structured data; they contain the minimum amount of info to regenerate your docs. The templates are UI, but it's mostly essential stuff.

Also, if you have that many routes, I don't think splitting the YAML files themselves will do much for memory size. I think it might make it worse.

My first recommendation would be that you need the `laravel` type docs, but it seems you're already on that. That way, you can split the blade file and only render an endpoint or group when needed.

You can also try disabling things like "Try It Out", or the example requests. The generated output for those is usually between ⅓ - ⅔ of an endpoint.

You could try skipping the whole YAML output phase to save on that storage, if you don't edit the generated YAML files, and you're fine with extracting endpoints info afresh each time. There isn't an exposed way to do this right now, but it's probably not difficult to hack on it.


What this package could do is adjust the generation for Laravel type, to place each group or endpoint in a separate file. That isn't too difficult (technically), but it is a bit complex at first. 

Unfortunately, I can't commit to making any of these improvements for your use case at this time. You can send in a PR, and I'll review and merge it, but I can't make any promises for my own development time rn.

**Comment by shalvah** [comment]
Also, is memory the only problem? What is processing time like with 177 routes?

**Comment by michaeldzjap** [comment]
Thanks for your reply. Processing time for generating the documentation you mean? Not too bad actually. I investigated a bit more on my own and I discovered that some of the raw request body data is filled with a lot of data. For example: I have this rule in one of my form requests:

```php
public function rules()
{
    return [
        ...
        'description' => 'sometimes|nullable|string|max:16777215',
        ...
    ];
}
```

and when I look at the exported collection.json I see a random string associated with the "description" attribute that seems like it could be exactly 16777215 characters long. I have a few of those fields, so then no wonder that that packs on the MB's. Is there an easy way to override this behaviour?

**Comment by shalvah** [comment]
> I guess I can use bodyParameters with an example to override this behaviour. 

Yeah

>  a random string associated with the "description" attribute that seems like it could be exactly 16777215 characters long. 

Yeah, I noticed this issue. I've tried to bring it down in recent releases, but I'll try some more.

**Comment by shalvah** [comment]
Example generation should be smarter now (4.5.0).

**Comment by shalvah** [comment]
Closing this. Let me know how it went for you.

**Comment by michaeldzjap** [comment]
> Example generation should be smarter now (4.5.0).

I dialed back the number of routes for the documentation, but I think this helped massively. So should be good for now, thnx!
