### ISSUE TITLE
Using slug instead of ID for route parameter

### ISSUE THREAD

**Issue by mwllgr** [knuckleswtf/scribe#564]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hello,

I'm trying to generate docs for my project which uses slugs instead of IDs for route parameters.
Here's an example of a route:

```php
Route::get('status/{status}/software', [StatusController::class, 'showSoftware']);
```

I've overriden the parameter name in the model class using `getRouteKeyName()`:
```php
/**
 * Get the route key for the model.
 *
 * @return string
 */
public function getRouteKeyName()
{
    return 'slug';
}
```

Here comes the funny part: The URL seems to be correct in the generated documentation - however, inside the request, the route key is always being replaced with the ID or some other kind of numeric value instead of the slug.

See the following picture as an example: The curl example request uses (... seems to use?) `/status/allgemein/software` as the requested path, but the error response displays `/status/1/software` as the used path. (My 404 error handler uses `$request->getPathInfo()` to fetch the path).

![image](https://user-images.githubusercontent.com/25794895/203063899-f7dfe14f-0081-4819-81a3-5b5d42c85fb6.png)

This issue might be related to #275. Any ideas would be greatly appreciated.

**Comment by shalvah** [comment]
Version. If you won't describe your configuration, at the very least describe your version. I just wasted my time investigating a non-issue. I won't be investigating any more reports that do not state the version.

**Comment by mwllgr** [comment]
Hi @shalvah, your reply sounds a bit harsh. Sorry that I forgot to include the version.
The version I currently use is `4.6.0`. I pasted my whole configuration [here](https://p.kll.li/?c556a8530e002b38#2YbdqZm4TF54wDfubHSskggmveZ9DaHrdghhYpVLD8TV), as it would be a bit too long for Github.

Really hope that we can find a solution for this problem together. Also, what exactly do you mean when you write that you just "investigated a non-issue"?

Thanks! :)

**Comment by shalvah** [comment]
I've added ` scribe:config:diff` command which you can use to dump your config for issue reports in the future.

**Comment by shalvah** [comment]
Your issue should have been fixed now (4.7.1)

**Comment by shalvah** [comment]
Meanwhile, I notice from your config, you've got response calls enabled on all methods. How's that working for you? Do you feel confident enough in it rolling back any data changes? Are you running docs generation in a separate environment?

**Comment by shalvah** [comment]
Oh, and how did you get internationalization to work?

**Comment by mwllgr** [comment]
Thanks for the fix and the useful new command - it seems to work now.
For i18n I just exported the views and edited the several blade files - especially endpoint.blade.php.

For the other questions: I'm just figuring out how exactly I want to proceed, especially because I don't have a static Bearer token for generating the docs.

Right now I'm always generating a token in `beforeResponseCall()`:
```php
 $token = $user->createToken('docs');
```

Will report back here soon - for now: Thanks again for your help!

**Comment by shalvah** [comment]
> For i18n I just exported the views and edited the several blade files - especially endpoint.blade.php.

Okay, that works. But I would rather people didn't publish the views, as that makes package upgrades harder. Will look into providing internationalisation support out of the box.

**Comment by mwllgr** [comment]
Yeah, thought of that too but there aren't that many words/phrases to change so I didn't really mind having to change them in the future/after updates too. However, i18n support out of the box as you mentioned would be a great addition to this project.

**Comment by shalvah** [comment]
There's now internationalization support: `php artisan vendor:publish --tag=scribe-translations`

**Comment by mwllgr** [comment]
Amazing, thanks for the heads-up, @shalvah!
