### ISSUE TITLE
formRequests don't have a bodyParameter()

### ISSUE THREAD

**Issue by I2EJeffrey** [knuckleswtf/scribe#568]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

We've recently started to use laravel requests in our function so instead of just the normal "Request $request" we now have something like "userStoreRequest $request".

Though now trying to generate the scribe documentation we get the following error:
> No bodyParameters() method found in App\Http\Requests\User\UserUpdateRequest. Scribe will only be able to extract basic information from the rules() method.

i've tried adding it to the Request file according to the documentation by adding:
`#[BodyParam("body", "string", "The content of the post.")]`
and importing "BodyParam" by:
'use Knuckles\Scribe\Attributes\BodyParam;'

is there something i'm missing or something im doing wrong

**Comment by shalvah** [comment]
That's a warning, not an error. If you paid attention to the message, you'd see it says "`bodyParameters()` method", not "BodyParam attribute". See the docs: https://scribe.knuckles.wtf/laravel/documenting/query-body-parameters#validation-rules
