### ISSUE TITLE
Pass GET route parameters as query, not as body

### ISSUE THREAD

**Issue by mgefimov** [knuckleswtf/scribe#570]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I am adding a GET route to my API with parameters
2. I validate my parameters like this `$request->validate(['city_id' => 'required|integer|exists:cities,id'])`
3. Then in the docs, I see that the scribe wants to pass the examples as the body, not as query parameters.

**Expected**
in GET routes, by default, parameters must be passed as query

**Screenshot:**
<img width="1058" alt="Screen Shot 2022-11-26 at 00 44 30" src="https://user-images.githubusercontent.com/13413154/204041102-ff8cf366-beb8-4f4a-ab53-7aae88baf715.png">

**My environment:**
 - PHP version (from `php -v`):  8.1.12 
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): v9.41.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 4.6.0

**Additional info:**
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET

> Note: Sending body/payload in a GET request may cause some existing implementations to reject the request — while not prohibited by the specification, the semantics are undefined. It is better to just avoid sending payloads in GET requests.

**Comment by shalvah** [comment]
Did you search the docs? I mean, did you really try? You'd have saved us both time. https://scribe.knuckles.wtf/laravel/documenting/query-body-parameters#using-validation-rules-for-query-parameters

**Comment by mgefimov** [comment]
Thanks, but why is this not the default behavior

**Comment by shalvah** [comment]
Send in a PR, my man. I'm one man.
