### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by shalvah** [knuckleswtf/scribe#574]

**Comment by vpratfr** [comment]
I would be interested in a way to generate it in French too. If needed I can even make a PR to provide FR translation later on.

**Comment by guleswine** [comment]
I was disappointed to find that the authorization text is hardwired into this file and not even included in the localization packs vendor/knuckleswtf/scribe/src/Extracting/ApiDetails.php 😳

**Comment by vpratfr** [comment]
@guleswine do not hesitate to make a PR if you have time. On our side, we decided to document the API in English so this is not an issue anymore for us.

**Comment by guleswine** [comment]
> @guleswine do not hesitate to make a PR if you have time. On our side, we decided to document the API in English so this is not an issue anymore for us.

This is not even just a localization problem, I think this problem is more serious, because you cannot edit the text without changing the important project file

**Comment by vpratfr** [comment]
You can change those files too in your PR, no problem.

**Comment by guleswine** [comment]
> You can change those files too in your PR, no problem.

This is great, but don't forget the main thing when a person is looking for a tool for auto-generating documentation, he wants to save development time, not increase it.

first of all, I wanted to support this topic and point out the problem, code organization, storing text in classes is a dubious idea

**Comment by vpratfr** [comment]
I am not the maintainer of this project, but don't forget too that the main thing with **free** open-source libraries, is that it is not a product sold by @shalvah and that the community is also supposed to contribute (you already solve many hours by using it, even if not perfect).

**Comment by guleswine** [comment]
> I am not the maintainer of this project, but don't forget too that the main thing with **free** open-source libraries, is that it is not a product sold by @shalvah and that the community is also supposed to contribute (you already solve many hours by using it, even if not perfect).

I didn’t say that I use it, and I said that for a start I just wanted to support this topic, I understand perfectly well about PR myself, but for some reason you repeat the same thing... 
And in my next messages I just explained to you that this is a problem of organizing the code in this way, more seriously than you see it
and judging by this answer, it may not be advisable to make a PR in this project
https://github.com/knuckleswtf/scribe/issues/589#issuecomment-1477618675

**Comment by shalvah** [comment]
> P.S. judging by this answer, it may not be advisable to make a PR in this projec

Lol, wtf man. That's an excuse. You can literally click on the Pull Requests tab to see 20+ external PRs I've merged this year.

No idea how you picked an issue where I'm complaining about people bugging me about an unimportant issue with another package, and using that to justify not contributing. Did you even read that issue?🤨 FFS, this issue was created by _me_. Doesn't that mean I think it's important?

I respond to issues and PRs promptly when I can, so I really don't get you. If you have a problem, talk to me. Life happens. You have other shit you're doing, and so do I. I'll get to this when I can. If you want to help, ask how. Otherwise, you'll have to wait until I can find a solution. This whole thing just sounds ungrateful.

**Comment by shalvah** [comment]
> I just explained to you that this is a problem of organizing the code in this way, more seriously than you see it

True, it's a problem. But you need to remember that software development has to follow priorities. What's a serious problem to one person doesn't matter to another. No software is perfect. And over time, priorities will adjust and we will fix some problems (and probably add new ones). This package has evolved over the last few years to allow more end user flexibility while maintaining simplicity, and this will be another step in that.

**Comment by guleswine** [comment]
@shalvah  I understand you, no problem bro, just my first look at the project and a small dispute with another user😉

Your answer pleases, in that case, so, then a question for a potential PR, do you think it's right to put text pieces into laravel language packs? Because I see that you have taken out some parts of the text description in the config

**Comment by shalvah** [comment]
I obviously think it's a problem. That's why I created this issue. See also https://github.com/knuckleswtf/scribe/pull/639#issuecomment-1500872640 Progress happens little by little.

**Comment by shalvah** [comment]
Released in 4.19.0
