### ISSUE TITLE
Laravel Enum validation

### ISSUE THREAD

**Issue by hooman-mirghasemi** [knuckleswtf/scribe#579]
scribe can not auto generate suitable doc for request validation enum:

my validation:
'bannerDetail.type' => [
                'required',
                new Enum(BannerDetailType::class),
            ],

generated doc:

bannerDetail.type   string   
Example: quidem

And it force me to write @bodyParam manualy or using in valiadator.

**Comment by vpratfr** [comment]
Does it work with native PHP enums?
