### ISSUE TITLE
Markdown with HTML is not working right

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#58]
Hi there,

Creating documentation using html dont render in document generated, uses html like plain text.
Is there any configuration for support html ?

example :

```
/**
     * @group PHC Specialists
     * List All Specialists. 
     *  
     * List all specialists / {PT: Especialistas} in PHC. 
     * PHC Table: dr
     * <aside class="notice">We mean it; you really should.😕</aside>
*/
```

Renders :
`List all specialists / {PT: Especialistas} in PHC. PHC Table: dr <aside class="notice">We mean it; you really should.😕</aside>`

**Comment by shalvah** [comment]
Tried it just today, and it works: https://shalvah.me/TheCensorshipAPI/#add-a-word-to-the-list

Also, you should put code snippets on GitHub in code blocks (```). Was hard to understand you for a while.

**Comment by pirex360** [comment]
I dont understand why do not work with me....
I can put HMTL and works well in the 'intro_text' in scribe.php config dir.
But in the endpoint documentation... it just ignores, i cant put even a badge.

I use  "knuckleswtf/scribe": "^1.1" in composer.json

Ok, thanks for the tip about code.

**Comment by shalvah** [comment]
Have you tried updating to the latest version?

**Comment by pirex360** [comment]
Updated now 1.3.0 , "knuckleswtf/scribe": "^1.3.0",
...
but result is the same !

![Screenshot 2020-07-17 at 18 21 22](https://user-images.githubusercontent.com/17271768/87813970-d4249300-c85a-11ea-9599-cbe3f8066348.png)

**Comment by pirex360** [comment]
Hi there, 
Now some endpoints ignore text description.
It misses "List all Days from two dates by Specialities PHC. " in this example :

![Screenshot 2020-07-24 at 09 39 47](https://user-images.githubusercontent.com/17271768/88374581-d83c3d80-cd91-11ea-8c0c-09066ddaa106.png)

My result after php artisan scribe:generate

![Screenshot 2020-07-24 at 09 39 37](https://user-images.githubusercontent.com/17271768/88374622-ed18d100-cd91-11ea-98c6-20a423fdad19.png)

**Comment by shalvah** [comment]
Place your annotations (@group, @authenticated, etc) *after* your title and description (plus a blank line). It's not by design, but changing that breaks other things.

**Comment by pirex360** [comment]
:) Congratulations .... 

It fixes all, even the HTML is render perfect.

Thanks you, where do I find this rule/best practice in documentation ? if it's not there... it should be.

Once again, thanks.

**Comment by shalvah** [comment]
Added a note about it to the docs: https://scribe.readthedocs.io/en/latest/documenting/documenting-endpoint-metadata.html
