### ISSUE TITLE
Different User authentication for specific endpoints

### ISSUE THREAD

**Issue by alibori** [knuckleswtf/scribe#580]
Hi all!

I'm using Scribe to make the documentation for an API made with Laravel 9.

In this project there are two types of Users (simple users and companies) and some endpoints has applied a middleware to block users that aren't companies to use it.

I'm trying to use the `beforeResponseCall` hook to change the User token of the authorization header but without success.

Here are few project details:

- Laravel 9
- Laravel Sanctum for authentication
- Scribe configuration `'use_value' => ''`
- In AppServiceProvider.php:
```php
public function boot()
    {
        Schema::defaultStringLength(191);

        if (class_exists(\Knuckles\Scribe\Scribe::class)) {
            Scribe::beforeResponseCall(function (Request $request, ExtractedEndpointData $endpointData) {
                if ($endpointData->uri === 'api/companies' && $endpointData->httpMethods[0] === 'POST') {
                    $user = User::where('type', UserType::Company)->first();
                    $token = $user->createToken("API TOKEN")->plainTextToken;

                    $request->headers->set("Authorization", "Bearer " . $token);
                    // You also need to set the headers in $_SERVER
                    $request->server->set("HTTP_AUTHORIZATION", "Bearer " . $token);
                }
            });
        }
    }
```

Thanks in advance!

**Comment by shalvah** [comment]
> but without success.

What does this mean? Is the hook not called? Is the header not set? Have you tried dumping the raw request headers in your app (eg early in your authorisation middleware) to see what's set?

**Comment by alibori** [comment]
Hi again :)

I've been trying few things and hre is where I'm now:

- If the `$request->headers->set()` method is located inside the `if` block, the header isn't set.
- If I try this:
```php
Scribe::beforeResponseCall(function (Request $request, ExtractedEndpointData $endpointData) {
      if (($endpointData->uri === 'api/companies' && $endpointData->httpMethods[0] === 'POST')) {
          $user = User::where('type', UserType::Company)->first();
          $token = $user->createToken("API TOKEN")->plainTextToken;
      }

      $request->headers->set("Authorization", "Bearer " . $token);
      $request->server->set("HTTP_AUTHORIZATION", "Bearer " . $token);
  });
```
Works for the concrete endpoint but, of course, fails on the rest because `$token` is not set.
- But, if I try this way:
```php
Scribe::beforeResponseCall(function (Request $request, ExtractedEndpointData $endpointData) {
    $token = User::first()->createToken('API TOKEN')->plainTextToken;

    if (($endpointData->uri === 'api/companies' && $endpointData->httpMethods[0] === 'POST')) {
        $user = User::where('type', UserType::Company)->first();
        $token = $user->createToken("API TOKEN")->plainTextToken;
    }

    $request->headers->set("Authorization", "Bearer " . $token);
    $request->server->set("HTTP_AUTHORIZATION", "Bearer " . $token);
});
```
It doesn't works, is like even overwriting the `$token` inside the `if` block the logged user is the first one.

Any idea how to solve this?

Thanks a lot!

**Comment by alibori** [comment]
Hi!

The middleware doesn't receive an empty token, and even the token is generated each time it doesn't cause problems with other middlewares that I have applied.

I'm opened to try any suggestion :)

Thanks!

**Comment by shalvah** [comment]
Sorry, I'm out of ideas. This is crazy. You should go into Laravel's authentication middleware and dump the incoming request. I don't think there's anything Scribe is doing differently here.

**Comment by shalvah** [comment]
It might also be due to Scribe not setting some data that a request in your app might expect, but I can't tell. You can see [here](https://github.com/knuckleswtf/scribe/blob/ebadfcdcaf6eac2a36f7c080570c12a2b2fffbd6/src/Extracting/Strategies/Responses/ResponseCalls.php#L151-L160) that we try to set all needed data. You'll need to debug this some more.

**Comment by alibori** [comment]
Hi @shalvah !

Ok, I'll try to figure out what's happening and, if I find it, I'll update this issue.

Thanks for your time!

**Comment by shalvah** [comment]
Did you ever figure this out?

**Comment by alibori** [comment]
Hi @shalvah !

Sorry for my delay. I'd tried for a while and I cannot achieved it...

Thanks!

**Comment by ferdousanam** [comment]
I am also facing the same problem. Is there any solution regarding this?

**Comment by shalvah** [comment]
Maybe this is related to @ferdousanam's issue in #741 . Maybe you need to call `setUser` manually.🤔

**Comment by ferdousanam** [comment]
@shalvah
```php
Sanctum::actingAs($user, ['*']);
```
This method solved my problem. But I am confused why this happened using `token`.

Reference issue #741

**Comment by shalvah** [comment]
No idea, mate. I barely work with Laravel these days, and I've never used Sanctum, so I'm always at a loss when people ask things like this. I'm gonna close these two issues because I don't see myself being able to do anything here. I've added a `sanctum` label so future users can find these. Thanks for sharing your solution!
