### ISSUE TITLE
Add different header values for the same header in different output

### ISSUE THREAD

**Issue by aledeg** [knuckleswtf/scribe#583]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I'd like to have a header `XXX` (name irrelevant) to have the value `A` in the HTML output and the the value `B` in the Postman output.
I've added said header in the configuration file with the value `A`, which is perfect for the HTML output but not what I wanted in the Postman output.

Is there a way to modify the header value in the Postman collection without using the `afterGenerating` hook? I feel that it's my only option but it feels wrong to do that.

I've tried to use `postman.overrides` with wildcard but it does not work.

Thank you.

**Edit** I've checked #473 hoping to have some answers but there is none and I am not even sure the issue was related.

**Comment by shalvah** [comment]
I think `afterGenerating` is your only option, as you said. I can't see a clean way for Scribe to support this kind of scenario while making sense for other folks. You could also try creating your custom class to overwrite one of ours (eg a custom PostmanCollectionWriter).

**Comment by aledeg** [comment]
Thank you @shalvah. I'll try to find a way.
