### ISSUE TITLE
Package spatie/data-transfer-object is abandoned, you should avoid using it. Use spatie/laravel-data instead.

### ISSUE THREAD

**Issue by buglinjo** [knuckleswtf/scribe#588]
When I install the latest version of scribe I'm getting this deprecation warning `Package spatie/data-transfer-object is abandoned, you should avoid using it. Use spatie/laravel-data instead.`

Do you think it'll be replaced with the `spatie/laravel-data` soon?

**Comment by shalvah** [comment]
https://github.com/knuckleswtf/scribe/issues/546#issuecomment-1302836669
