### ISSUE TITLE
Documentation Formatting Issue

### ISSUE THREAD

**Issue by confused-Techie** [knuckleswtf/scribe#590]
Don't mean to be a drive by contributor, but was reading your docs while researching a random issue, and discovered some of your formatting isn't playing very nicely.

Within [scribe/docs/documenting/documenting-endpoint-query-parameters.md#L52](https://github.com/knuckleswtf/scribe/blob/v2/docs/documenting/documenting-endpoint-query-parameters.md?plain=1#L52)  You have a code block for the `tip` HTML element then a link within in.

This Link is being parsed as MarkDown when within the Code block, so outputs a little weird on your website.

![image](https://user-images.githubusercontent.com/26921489/208293058-5936b208-828a-440e-b40f-f908166b2525.png)

Not a big issue I know, was going to submit a PR changing it's current form of:

```
.. Tip:: You should avoid using query parameters that are arrays or objects, because [there isn't a standardised format for handling them](https://stackoverflow.com/a/9547490/7370522).
```

To 

```
.. Tip:: You should avoid using query parameters that are arrays or objects, because <pre>[there isn't a standardised format for handling them](https://stackoverflow.com/a/9547490/7370522)</pre>.
```

But since I don't have any way to quickly test your setup couldn't be confident that would help.

Otherwise just wanted to point this out, and if not a priority feel free to close.

Thanks for having awesome enough docs that they show up elsewhere 😊

**Comment by shalvah** [comment]
Thanks for being helpful, but you missed the banner at the top of that page that points out that's an extremely old, unsupported version. Current docs are at scribe.knuckles.wtf
