### ISSUE TITLE
Is there a way to access middleware on routes?

### ISSUE THREAD

**Issue by aledeg** [knuckleswtf/scribe#593]
!!IMPORTANT!!

READ BEFORE OPENING AN ISSUE:

- If you don't provide enough information in your issue for me to reproduce (such as version and any custom configuration), I will close it. I can't keep wasting my time investigating issues which no longer exist.
- Check the Troubleshooting Guide! https://scribe.knuckles.wtf/laravel/troubleshooting Some solutions to common problems are detailed there.

- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Okay, but DID YOU REALLY CHECK THE DOCS? Use the search bar on the docs page, and then come back and put an x in the box above only if you don't find answers. I know it's difficult when you don't know what you're looking for, but do your best.

-----

I've checked the documentation and the code. But unless I've missed something, I could not find a way to access a middleware nor its configuration when generating the documentation.

To add some context, I wrote a route middleware to handle deprecation. It generates 2 headers in the response to indicate when the route will be deprecated and if there is a replacement route.
I want to add those headers automatically in the documentation and also generate a visual warning in the route description.

Thank you.

PS: I am using the latest version.

**Comment by shalvah** [comment]
> unless I've missed something, I could not find a way to access a middleware nor its configuration when generating the documentation.

You've definitely missed something, lol. Scribe provides many extension points (custom strategies, hooks etc) that give you access to the route object. From there, accessing the middleware is between you and Laravel.

I don't have the energy to search the docs for you, but what you're looking for can be done with a custom strategy. They're very well documented, with examples and tooling that make it easy.

**Comment by aledeg** [comment]
Oh! I look into that. Sorry for your troubles. Thank you.
