### ISSUE TITLE
Bug in using an image 

### ISSUE THREAD

**Issue by tlinossier** [knuckleswtf/scribe#599]
hello 
I want to make the doc for a route who has to send an image

But no matter if I put the image in *img/logos/logo. png* or in *ressources/images/logo. png* I have the second screenshot exception

Did I use wrong? I don't see my mistake in the doc

Thx for all

**Screenshots and stack traces:**
![image](https://user-images.githubusercontent.com/90650481/210804896-1898325e-0412-4b61-9fa1-63d3216f0e7a.png)
![image](https://user-images.githubusercontent.com/90650481/210806562-013111dd-1845-41ac-b663-fa07b27645ce.png)

**My environment:**
 - PHP version 8.1.13 :  - Framework (Laravel):
 - Laravel versions : * v9.46.0
 - Scribe versions : * 4.10.1

**My Scribe config :
PHP Warning:  PHP Startup: gd: Unable to initialize module
Module compiled with module API=20190902
PHP    compiled with module API=20210902
These options need to match

Warning: PHP Startup: gd: Unable to initialize module
Module compiled with module API=20190902
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0
title => "Seela API Documentation"
base_url => "http://127.0.0.1:8000"
try_it_out.base_url => "http://127.0.0.1:8000"
auth.enabled => true
auth.default => true
auth.name => "Authorization"
auth.use_value => "agoodmail@compagny.com"
logo => "img/logos/logo.png"
last_updated => "Last updated: {date:j F Y}"

**Comment by shalvah** [comment]
This looks alright. Two questions:
1. Is the `img` directory in the root of your project?
2. Are you running Scribe from the root of your project?

**Comment by tlinossier** [comment]
yes im running Scribe from the root directory 
and for the path this is my bad it's the screenshot of my last attempt : 
the directory is in the public dir (/public/img/logo/logo.png)
but i tried these path : 
/resources/images/logo/logo.png
/public/img/logo/logo.png
/img/logo/logo.png
img/logo/logo.png
but this never work

**Comment by shalvah** [comment]
Did you try `public/img/logo/logo.png` (without the initial `/`)? That seems to be the correct path from the project root, which you should be passing to Scribe.

**Comment by tlinossier** [comment]
wow my bad thx for all this work now
