### ISSUE TITLE
Compatibility with the Laravel Actions package

### ISSUE THREAD

**Issue by vpratfr** [knuckleswtf/scribe#604]
We are using the Laravel Actions package (https://laravelactions.com/) in our application.

While Scribe properly discovers all the routes, it does not seem to pick-up any annotation we put in any of the places we have tried.

Basically, that helps avoiding to duplicate code or have boilerplate code when code could be used in multiple places (controller, job, command, etc.)

Route declaration is rather standard

```
Route::post('/auth/token')
    ->name("auth.token.store")
    ->uses(CreateProviderToken::class);
```

And the `CreateProviderToken` class is what serves as controller (but can also be turned easily in an artisan command):

```
class CreateProviderToken
{
    public function handle(string $apiKey): AccessToken
    {
        // [...] Logic to generate a token, e.g. with Sanctum
        return AccessToken::fromNewAccessToken($token);
    }

    //region Controller specific

    public function rules(): array
    {
        return [
            "api_key" => ["required", "string", Rule::exists('providers', 'api_key')],
        ];
    }

    public function asController(Request $request): JsonResponse
    {
        $token = $this->handle($request->string("api_key"));

        return response()->json($token);
    }

    //endregion
}
```

- `handle` method is what contains the logic to generate a token
- `asController` method is an entry point used when the action is called by a route
- `asCommand` method similarly would be the entry point when calling from Artisan

I have tried putting the following docblock both : before the `Route::post` declaration AND before the `asController` method, but it does not get read (title, content, tags are not in the generated docs)

I have also tried `artisan scribe:generate --force` (yaml have not been touched though).

How could I help Scribe to understand that I want to put my annotation on the asController method? I don't mind writing a plugin for that but I don't know where to start (I understood so far that plugins were more about adding tags, here my problem is to at least read the existing tags).

**Comment by shalvah** [comment]
Not familiar with the actions page. Do you know what method Scribe is checking? If Scribe is checking for __invoke(), you can probably add an empty method stub there until there's better support. You can go into the Extractor class and dump the endpointData object to see the controller and method being checked.

**Comment by vpratfr** [comment]
Hi,

It indeed wants to check the `__invoke` method.

Basically in that package, the `__invoke` method belongs to the base class and is the one responsible for dispatching to the proper specific method depending from where the action is called (asController, asCommand, etc.).

I think the best way to make that flexible would be to allow for some flexibility in the `Utils::getRouteClassAndMethodNames` method.

## Current code

```
        if ($uses !== null) {
            if (is_array($uses)) {
                return $uses;
            } elseif (is_string($uses)) {
                return explode('@', $uses);
            } elseif (static::isInvokableObject($uses)) {
                return [$uses, '__invoke'];
            }
        }
```

## Possibilities

### Adding a case specific to that package

We would check if the given class has a `asController` method (which is where the API documentation would end up really), and if it has that method, then use that one instead of `__invoke`.

Pro: this is an easy fix.
Con: this is specific to that package only, would need additional code to support other packages or if that package changes the method name.

### Allowing the end user to plug a strategy to pick the method

The `Utils::getRouteClassAndMethodNames` would check the config `scribe.route_to_class_method_strategy` to see if a custom strategy is provided.

That user strategy would receive the route as parameter and should return class + method from it.

Pro: you let the end user do the work to customize the logic for picking the proper class/method + it will work for any use case
Con: this requires a bit more changes : add a config value + contract for that strategy + call it from utils. Nothing hard though.

**Comment by vpratfr** [comment]
If you want to go with a special case for that particular package, the following code works:

```
        if ($uses !== null) {
            if (is_array($uses)) {
                return $uses;
            } elseif (is_string($uses)) {
                // Add support for the Laravel Actions package, docblock should be put on the asController method
                [$class, $method] = explode('@', $uses);
                if ($method === '__invoke' && method_exists($class, 'asController'))
                {
                    return [$class, 'asController'];
                }

                return [$class, $method];
            } elseif (static::isInvokableObject($uses)) {
                return [$uses, '__invoke'];
            }
        }
```

**Comment by shalvah** [comment]
Yep, let's go with this for now. Since I'd rather not add another config item, and I haven't come up with a good API for hooking into that yet, t's okay to have workarounds for some specific fairly popular packages.

**Comment by vpratfr** [comment]
Cool thanks. Let me know when published, I will test it for you on our project. 

You may want to add the same kind of special case in the `elseif (static::isInvokableObject($uses))` branch (but I don't know when that one is triggered. In our project, we always fall in the `(is_string($uses))` branch.

**Comment by shalvah** [comment]
Right...I can't promise any timeframe, so I'll recommend you submit a PR if it's important.

**Comment by vpratfr** [comment]
There you go. If anything, let me know in the PR

**Comment by eschricker** [comment]
We also use the Laravel Actions package. Instead of docblock we use attributes. The action class then looks like this:

```php 
#[Group('...')]
#[Subgroup(...')]
#[Endpoint('...')]
#[Response(status: 401, description: 'Unauthorized')]
class CreateProviderToken
{
    public function handle(string $apiKey): AccessToken
    {
        ...
    }

    public function rules(): array
    {
        return [
            ...
        ];
    }

    public function asController(Request $request): JsonResponse
    {
        ...
    }
}
```

We wrote our own strategy to extract definitions from the rules method. It works like a charm.

**Comment by vpratfr** [comment]
Thanks for the info. Now you can also write that as docblock on the
asController method, that works too.

Would you be able to share your strategy to get the rules?

**Comment by eschricker** [comment]
Here is an example for getting body parameters. 

```php
#[Attribute(Attribute::IS_REPEATABLE | Attribute::TARGET_CLASS)]
class BodyParamsFromRulesMethod
{
}

/**
 * @template T of GenericParam
 * @extends PhpAttributeStrategy<BodyParamsFromRulesMethod>
 */
class GetBodyParamFromRulesMethod extends GetParamsFromAttributeStrategy
{
    use ParsesValidationRules;

    protected static array $attributeNames = [BodyParamsFromRulesMethod::class];

    protected function extractFromAttributes(
        ExtractedEndpointData $endpointData,
        array $attributesOnMethod,
        array $attributesOnFormRequest = [],
        array $attributesOnController = []
    ): ?array {
        if (!empty($attributesOnController) && $endpointData->controller->hasMethod('rules')) {
            $className = $endpointData->controller->getName();
            $action = new $className;
            $rules = call_user_func_array([$action, 'rules'], []);

            $parametersFromAction = $this->getParametersFromValidationRules($rules);

            return $this->normaliseArrayAndObjectParameters($parametersFromAction);
        }

        return [];
    }
}
```

A strategy for query parameters just use another attribute.

**Comment by shalvah** [comment]
Nice! That's the goal with Scribe: making it easy to plug in your own pieces.

**Comment by rizaldywirawan** [comment]
> `getRouteClassAndMethodNames`

may I know why it's not using || instead of &&?

Because I get the method name called asController instead of __invoke.

![image](https://github.com/knuckleswtf/scribe/assets/31938164/cb8cf91d-bea1-411a-adf2-725390ec454b)

**Comment by shalvah** [comment]
@rizaldywirawan I don't understand (and I don't use the Laravel Actions package, so I can't help much here). If you think the code is wrong, please send in a test and a fix (also considering non-Laravel Actions use cases).

**Comment by rizaldywirawan** [comment]
@shalvah sorry for the late reply, I decided to follow this PR and it still works even tho I need some adjustment. Thank you for the great package!
