### ISSUE TITLE
required array marked as optional

### ISSUE THREAD

**Issue by markymarrow** [knuckleswtf/scribe#608]
**What happened?**
I have a custom FormRequest object containing the following:
```
public function rules()
{
    return [
        'events' => 'required|array',
        'events.*.name' => ['required', 'string', 'max:200', new UniqueEventName]
    ];
}
```

after running php artisan scribe:generate
the endpoint using the request shows
`events   object[]  optional`

**My environment:**
 - PHP version (from `php -v`): 8.1.14
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): v8.83.27
 - Scribe version (from `composer show knuckleswtf/scribe`): 4.13.0

**My Scribe config (from `php artisan scribe:config:diff`):**
try_it_out.enabled => false
auth.enabled => true
auth.default => true
postman.enabled => false
openapi.enabled => false
strategies.metadata => removed Knuckles\Scribe\Extracting\Strategies\Metadata\GetFromMetadataAttributes
strategies.urlParameters => removed Knuckles\Scribe\Extracting\Strategies\UrlParameters\GetFromUrlParamAttribute
strategies.queryParameters => removed Knuckles\Scribe\Extracting\Strategies\QueryParameters\GetFromQueryParamAttribute
strategies.headers => removed Knuckles\Scribe\Extracting\Strategies\Headers\GetFromHeaderAttribute
strategies.bodyParameters => removed Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromBodyParamAttribute
strategies.responses => removed Knuckles\Scribe\Extracting\Strategies\Responses\UseResponseAttributes
strategies.responseFields => removed Knuckles\Scribe\Extracting\Strategies\ResponseFields\GetFromResponseFieldAttribute

**Additional info:**
I think the issue is within Extracting/ParsesValidationRules:addMissingParentFields()
on the first run through the loop `$results['events']` is set as type array, required true
on the second run through there is the test
`if (empty($results[$normalisedParentPath]))` where `$normalisedParentPath = 'events.*'`
but then this variable has the last two characters trimmed from it and it overwrites `$results['events']` setting required = false

**Comment by shalvah** [comment]
This isn't a bug per se. It's what you get because you don't have a rule for `events.*`. An optional array can have required fields, so it's a judgement call by Scribe. Maybe the wrong call, but that's what it is.

**Comment by shalvah** [comment]
Right... Feel free to send a fix in.
