### ISSUE TITLE
Writing own writer for example generating swagger json/yaml file

### ISSUE THREAD

**Issue by pavankumarkatakam** [knuckleswtf/scribe#61]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.
I have seen that this package will generate postman collection by enabling in the config, but it will be usefull to give such a way users to create own writer and keep that class in the config (Like did for the strategies).

**Comment by pavankumarkatakam** [comment]
Is this question/issue ignored?

**Comment by shalvah** [comment]
Hi. That's something we can consider, but not anywhere on the roadmap for the near future. 😐
It's more likely that we'd add probably add Swagger generation to the package, but that's also not in the near future.

**Comment by shalvah** [comment]
I've added support for Swagger generation (v1.4.0). Closing this issue because of the reasons given above.
