### ISSUE TITLE
Undefined array key 1 on LARAVEL 10.0.0 - How to fix it ???

### ISSUE THREAD

**Issue by chegmarco1989** [knuckleswtf/scribe#617]
Hello.

**What happened?**
1. I ran `php artisan scribe:generate` .
2. And I saw the following error:

```
 ErrorException

  Undefined array key 1

  at vendor\knuckleswtf\scribe\src\Tools\Utils.php:108
    104▕         if ($uses !== null) {
    105▕             if (is_array($uses)) {
    106▕                 return $uses;
    107▕             } elseif (is_string($uses)) {
  ➜ 108▕                 [$class, $method] = explode('@', $uses);
    109▕
    110▕                 // Support for the Laravel Actions package, docblock should be put on the asController method
    111▕                 if ($method === '__invoke' && method_exists($class, 'asController'))
    112▕                 {

  1   vendor\knuckleswtf\scribe\src\Tools\Utils.php:108
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Undefined array key 1", "C:\laragon\www\PochiPay\vendor\knuckleswtf\scribe\src\Tools\Utils.php")

  2   vendor\knuckleswtf\scribe\src\GroupedEndpoints\GroupedEndpointsFromApp.php:106
      Knuckles\Scribe\Tools\Utils::getRouteClassAndMethodNames(Object(Illuminate\Routing\Route))
```

instead of...

**Screenshots and stack traces:**

![image](https://user-images.githubusercontent.com/51763985/219448487-29ae2364-f054-4c0f-949a-de879b120053.png)

**My environment:**
 - PHP version (from `php -v`): **PHP 8.2.1 (cli) (built: Jan  3 2023 23:31:58) (ZTS Visual C++ 2019 x64)**
 - Framework (Laravel/Lumen): **LARAVEL**
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): **LARAVEL version 10.0.0**
 - Scribe version (from `composer show knuckleswtf/scribe`): **4.15.0**

**My Scribe config (from `php artisan scribe:config:diff`):**

**Additional info:**

**Comment by shalvah** [comment]
Try running `php artisan route:clear`

**Comment by chegmarco1989** [comment]
Work now. Thanks
