### ISSUE TITLE
Try it out & beforeResponseCall() hook

### ISSUE THREAD

**Issue by gleb-sh** [knuckleswtf/scribe#618]
Hi all!

I'm trying to use hook "beforeResponseCall()" and see that it not called when i use "try it out" option in my generated docs.

As I see, hook "beforeResponseCall()" work only when I run generating command. And doesn't work from "try it out". Is it normal?

Framework: Laravel, php 8.0
Scribe version: 3.21 
Auth default disable.
Endpoint without auth annotation.
"Try it out" option is enable.

My purpose: set custom auth with cookies, which can be use automaticly from "try it out". Maybe are there other ways (without using hooks) ? (Set cookies in config doesnt work with "try it out" too)

p.s. yes, reading scribe documentation, googling and searching in scribe source code not helped me to get a complete answer.

Thanks in advance!

**Comment by shalvah** [comment]
Correct, the hook doesn't work with Try It Out. "Response calls" are only when generating. Same with the config cookies option.

First, verify if you really need this. The Try It Out API call [sets `credentials: 'same-origin'`](https://github.com/knuckleswtf/scribe/blob/1df972a3f73dd3b98e1dcf038597606ba9bdb01f/resources/js/tryitout.js#L123), which means, if you're logged in to your site, and it's on the same domain with your docs, your cookies should automatically be sent.

If you still need to set some other cookie, there's no easy way to directly do this for Try It Out. You can write some custom JavaScript and either: inject it into the output, for instance, with [the `afterGenerating` hook](https://scribe.knuckles.wtf/laravel/hooks#aftergenerating), or [overwrite the default Blade template](https://scribe.knuckles.wtf/laravel/advanced/theming#customising-all-templates).
