### ISSUE TITLE
Lumen publish views

### ISSUE THREAD

**Issue by stylianospanagakos** [knuckleswtf/scribe#62]
I've read the [documentation](https://scribe.readthedocs.io/en/latest/customization.html) regarding the customization of the `index.blade.php` and I can't find details on how to achieve a similar result in Lumen.

I tried to replicate the file structure but when I `generate` the docs, it defaults to the original version. Is there something I'm missing?

**Comment by stylianospanagakos** [comment]
For everyone else that might have the same problem, the solution lies in `ScribeServiceProvider.php` file:
```
 $this->publishes([
            __DIR__ . '/../resources/views' => $this->app->basePath('resources/views/vendor/scribe'),
        ], 'scribe-views');
```

Just create a `vendor/scribe` directory under `resources/views` and copy all the views content from the scribe package i.e. `scribe/resources/views/` and you should have a successful publication.

**Comment by shalvah** [comment]
Cool. Wanna make a PR to mention this in the docs?
