### ISSUE TITLE
Search highlighting broken

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#621]
Hi, I just updated from v2.x to v3.x.
I read all the docs, and the upgrade has been successful in some degree.

But when digging deeper... the highlighting does not work ... but the search is working, it only lacks the highlight aspect and the scrolling page doesn't trigger menu change on the sidebar.

Anything I missed on the upgrade? 
no errors in javascript, doc page loads fine... 
I did everything on the troubleshooting page, like clear cache, remove old docs folders, update packages, don't have debugbar... etc...

Thanks for your time.

**Comment by shalvah** [comment]
Note that the currently supported version is 4.x, so I can only provide limited answers here.

The scroll issue is a known one, not fixed yet. https://github.com/knuckleswtf/scribe/issues/422

As for highlighting, my suspicion would be that you have a JS problem. Probably the highlightjs library version is conflicting with some other library. You should check your dev tools console to see if there are any error messages. If there's nothing, I'd recommend just resetting and trying with a fresh setup

**Comment by shalvah** [comment]
Oh, I see you mention "no errors in javascript". Did you check that the JS and CSS assets load properly (in the Network tab)? That's would be my suspicion.

**Comment by shalvah** [comment]
Oh, wait, do you mean highlighting of search results? I thought you meant code examples syntax highlighting. If it's search results, I really can't say. There was a migration some time ago to a newer version of the search and table of contents that fixed some problems with the old setup. However, a casualty of that was the scroll thing, and maybe what you're mentioning as well. The scroll thing hasn't been fixed because it's a low priority, but tricky issue and no one has had time to look at it.

**Comment by pirex360** [comment]
Thanks for the reply, I will try to upgrade from v3 to v4 to check if some issues are fixed...

I see that the upgrade to v4 in the docs is straightforward and more smooth than v2 to v3.

**Comment by pirex360** [comment]
Ok, I just upgraded from v3 to v4.... everything went well, thank you for the smooth upgrade.
My only issue is the highlight of search results... no more the yellow background on the string, all javascript and CSS loaded ok.

![image](https://user-images.githubusercontent.com/17271768/220623475-9a7b0eea-4e42-44b5-86f4-64a7b790bb2e.png)

**Comment by shalvah** [comment]
Oh, yeah, highlight.js is only for syntax highlighting. The search is, I think, now handled by Jets: https://jets.js.org. It probably needs some configuration or custom JS in this package to highlight the search string.

**Comment by shalvah** [comment]
I think I'll close this. Yes, the search term is no longer highlighted, but I don't think that's a big problem, is it? I couldn't find any easy ways of achieving this with Jets, so I'll just call it a day.

**Comment by pirex360** [comment]
Sorry to re-open. I figure out that the search now only works for the endpoint names.

Before we could search in all the documentation document, now the search only works for the name of the endpoints or content in the sidebar.

**Comment by shalvah** [comment]
Oh, I never really used the search before, so I didn't notice. Is that a big problem, considering the user can still use the browser search (Ctrl-F)? It doesn't seem like a good usage of time trying to reimplement that.
