### ISSUE TITLE
Something changed thats breaking vendor files 4.14.0 -> 4.15.0

### ISSUE THREAD

**Issue by jackkitley** [knuckleswtf/scribe#627]
!!IMPORTANT!!

READ BEFORE OPENING AN ISSUE:

- If you don't provide enough information in your issue for me to reproduce (such as version and any custom configuration), I will close it. I can't keep wasting my time investigating issues which no longer exist.
- Check the Troubleshooting Guide! https://scribe.knuckles.wtf/laravel/troubleshooting Some solutions to common problems are detailed there.

Again, HAVE YOU CHECKED THE DOCS? Use the search bar on the docs page before rushing to open an issue. I know it's difficult when you don't know what you're looking for, but do your best. 

**What happened?**
1. I ran `php artisan scribe:generate` ...
2. And I saw...

I was on 4.14.0 and ran generate and was able to view my docs and console gave no errors. I upgraded to 4.15.0 and now it cannot read the files in vendor even though they are there. Wondering if asset reading changed? 

Package operations: 0 installs, 2 updates, 0 removals
  - Upgrading nunomaduro/collision (v6.4.0 => v7.0.5): Extracting archive
  - Upgrading knuckleswtf/scribe (4.14.0 => 4.15.0): Extracting archive

![Screenshot 2023-03-01 at 10 02 42](https://user-images.githubusercontent.com/3243014/222079588-bb6fb29c-0f0e-4594-b301-70ff5b57e813.png)

instead of...

![Screenshot 2023-03-01 at 09 09 01](https://user-images.githubusercontent.com/3243014/222068641-2a91f688-4519-4d30-b803-1f3a006b3db9.png)

Was giving no errors previously. Everything worked fine. I have back tracked versions and the step up from .15 to .16 is the issue.

**Screenshots and stack traces:**

**My environment:**
 - PHP version (from `php -v`):  8.2.0
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): v9.52.4 - Scribe version (from `composer show knuckleswtf/scribe`): 

**My Scribe config (from `php artisan scribe:config:diff`):**

base_url => "http://localhost"
type => "laravel"
try_it_out.base_url => "http://localhost"
try_it_out.use_csrf => true
auth.enabled => true
auth.default => true
auth.name => "token"
logo => "../images/oslogo.svg"

**Additional info:**

**Comment by shalvah** [comment]
Nothing related to that changed. See for yourself: https://github.com/knuckleswtf/scribe/compare/4.14.0...4.15.0

**Comment by jackkitley** [comment]
@shalvah thanks, ill look more into it.
im running a nginx container with proxy to php container. I think the nginx container doesnt have latest files.

**Comment by shalvah** [comment]
Okay. Also, you might as well upgrade to the latest version (4.16.0).

**Comment by jackkitley** [comment]
@shalvah yes, i was on latest everything and spotted it wasnt working anymore so i had to back track to see where the break was.
