### ISSUE TITLE
Documentation is not generated from invokable rules

### ISSUE THREAD

**Issue by aledeg** [knuckleswtf/scribe#629]
!!IMPORTANT!!

READ BEFORE OPENING AN ISSUE:

- If you don't provide enough information in your issue for me to reproduce (such as version and any custom configuration), I will close it. I can't keep wasting my time investigating issues which no longer exist.
- Check the Troubleshooting Guide! https://scribe.knuckles.wtf/laravel/troubleshooting Some solutions to common problems are detailed there.

Again, HAVE YOU CHECKED THE DOCS? Use the search bar on the docs page before rushing to open an issue. I know it's difficult when you don't know what you're looking for, but do your best. 

**What happened?**
1. I have a FormRequest using a custom invokable rule.
2. I have defined the `docs` method in the invokable rule with a description and an example.
3. I ran `php artisan scribe:generate --force`.
4. I can see the field extracted from the FormRequest but there is no mention of the documentation from the invokable rule.

**Screenshots and stack traces:**

**My environment:**
 - PHP version (from `php -v`): 8.1.11
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 9.43.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 4.16.0

**My Scribe config (from `php artisan scribe:config:diff`):**
```
title => "API"
try_it_out.enabled => false
auth.enabled => true
auth.name => "Authorization"
openapi.enabled => false
logo => "../media/logos/logo.light.png"
```
The irrelevant sections have been removed (ie: `postman.overrides`).
**Additional info:**

I've tried to debug the `Extracting\ParsesValidationRules::parseRule` method to find out what is going on. It turns out that when the rule is received in that method it is received as a `InvokableValidationRule` which implements `Rule`. This object does not have the `docs` method defined. But it has a `invokable` method which allows to retrieve the invokable rule with the `docs` method.

Knowing that, I can extract the invokable rule from the received rule and use it instead. And it works.
I've replaced
```php
        if ($rule instanceof Rule || $rule instanceof InvokableRule) {
```
by
```php
        if ($rule instanceof Rule) {
            if (method_exists($rule, 'invokable')) {
                $rule = $rule->invokable();
            }
```

With this change, I have access to the content of the docs method. It is displayed as intended both in the HTML documentation and the Postman collection.

**Comment by shalvah** [comment]
I'm confused. I can't find any information on this `invokable()` method? Is it a Laravel-supported thing?

**Comment by shalvah** [comment]
Never mind, I see what you mean. It's undocumented. Fixing!

**Comment by aledeg** [comment]
Thanks @shalvah 👍
