### ISSUE TITLE
Recommended way to ensure a sane ordering of Response examples?

### ISSUE THREAD

**Issue by mortenscheel** [knuckleswtf/scribe#632]
Basically my question boils down to this: If I have multiple `#[Response()]` examples defined, how do I ensure that the `200` response is listed first?

I find the ordering to be hard to predict, especially if some common `#[Response()]` are defined on the Controller and the controller methods have `#[ResponseFromApiResource()]`.

I suppose the most intuitive thing would be to have them ordered by status code, regardless of how or where they were defined. Then the success response would also automatically come first.

**Comment by shalvah** [comment]
Hmm, I'd have thought that was the case!

https://github.com/knuckleswtf/scribe/blob/ed7b0854c5f432a2c84200ec9ff4306170a14877/tests/Unit/ExtractorPluginSystemTest.php#L145

https://github.com/knuckleswtf/scribe/blob/ed7b0854c5f432a2c84200ec9ff4306170a14877/src/Extracting/Extractor.php#L168

**Comment by mortenscheel** [comment]
@shalvah is the response from `#[ResponseFromApiResource()]` included in that collection?

**Comment by shalvah** [comment]
Oh shit, I think this has already been fixed. https://github.com/knuckleswtf/scribe/pull/623

Just needs a release 😅 Will release today
