### ISSUE TITLE
Replace abandoned spatie/data-transfer-object

### ISSUE THREAD

**Issue by EnterpriseDNA** [knuckleswtf/scribe#635]
!!IMPORTANT!!

READ BEFORE OPENING AN ISSUE:

- If you don't provide enough information in your issue for me to reproduce (such as version and any custom configuration), I will close it. I can't keep wasting my time investigating issues which no longer exist.
- Check the Troubleshooting Guide! https://scribe.knuckles.wtf/laravel/troubleshooting Some solutions to common problems are detailed there.

- [ X ] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Okay, but DID YOU REALLY CHECK THE DOCS? Use the search bar on the docs page, and then come back and put an x in the box above only if you don't find answers. I know it's difficult when you don't know what you're looking for, but do your best.

Composer claims that spatie/data-transfer-object used by Scribe is abandoned. Are you planning to replace it for something new?
![image](https://user-images.githubusercontent.com/92759866/226530751-322a5773-e574-4a06-8a18-2e5ee5986993.png)

**Comment by shalvah** [comment]
https://github.com/knuckleswtf/scribe/issues/589

**Comment by shalvah** [comment]
Please search existing issues before opening a new one. It's literally pinned to the top of the issues page.
