### ISSUE TITLE
Warning about missing body parameters for parents of nested parameters.

### ISSUE THREAD

**Issue by bjhijmans** [knuckleswtf/scribe#643]
**What happened?**
1. I have the following (simplified) request in Laravel:

```php
class UpdateRequest extends FormRequest
{
...
    public function rules(): array
    {
        return [
            'things' => 'filled|array'
            'things.*' => 'in:1,2,3,4,5,6,7,8'
        ]
    }

    public function bodyParameters()
    {
        return [
            'things.*' => [
                'description' => 'bla',
                'example' => 1
            ]
        ]
    }
}
```

This generates the rule:

`things`   **string[]**  _optional_  
bla. Must be one of `1`, `2`, `3`, `4`, `5`, `6`, `7`, or `8`.

When I run `php artisan scribe:generate --v` I get the warning "⚒ No data found for parameter 'things' in your bodyParameters() method. Add an entry for 'things' so you can add a description and example."

However, when I add an entry for `things` with a description and example, they aren't added to the API docs. I think that behavior is correct, but it shouldn't give the warning to add something if it isn't going to use it.

The warning is given in https://github.com/knuckleswtf/scribe/blob/b0d2bbe20e641e7a6d9649481e454b1dc166b584/src/Extracting/ParsesValidationRules.php#L34. I think it would make sense to add a check to see if there are any keys that start with `$parameter . '.'`. Maybe something like:

```php
&& ! count(array_filter(array_keys($customParameterData), function ($key) use ($parameter) {
    return str_starts_with($key, $parameter . '.');
}))
```

Scribe version 4.17.

**Comment by shalvah** [comment]
Use 

```php
public function bodyParameters()
    {
        return [
            'things' => [
                'description' => 'bla',
                'example' => [1]
            ]
        ]
    }
```

Outside of the validation rules array, Scribe does not support that `.*` syntax.

**Comment by bjhijmans** [comment]
@shalvah 

When I do that, it doesn't add the description at all.

With my setup:

```php
    public function rules(): array
    {
        return [
            'things' => 'filled|array'
            'things.*' => 'in:1,2,3'
        ]
    }

    public function bodyParameters()
    {
        return [
            'things.*' => [
                'description' => 'bla',
                'example' => 1
            ]
        ]
    }
```

I get the following result, which is perfect:

![image](https://user-images.githubusercontent.com/59833909/229503397-fa4c59c7-cf1e-4ca8-9a1b-5c4b34fad23a.png)


If I follow your suggestion and change the bodyParameters to:

```php
    public function bodyParameters()
    {
        return [
            'things' => [
                'description' => 'bla',
                'example' => [1]
            ]
        ]
    }
```

The result is the following. Note that the description and example are missing.

![image](https://user-images.githubusercontent.com/59833909/229503963-5f8592cb-b5f2-4d51-a284-19a11732364a.png)

If I remove the `things.*` validation rule, it does render the description (but not the example).

![image](https://user-images.githubusercontent.com/59833909/229508409-d76f70a2-8102-41fb-9648-5f4b1dfaa071.png)


I used the default config to test this.

**Comment by shalvah** [comment]
Oh, I only just realised what you were pointing out. Fixed now.
