### ISSUE TITLE
Can request examples be manually defined?

### ISSUE THREAD

**Issue by deefour** [knuckleswtf/scribe#646]
### Scribe version

4.18.0

### Your question

Is there a way I can manually define request examples for inclusion in the OpenAPI.yaml file? [OpenAPI supports 1+ examples](https://swagger.io/docs/specification/adding-examples/).

I'd love to be able to do something like this.

```
@requestFile scenario="Example #1" storage/requests/example01.json
```

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by deefour** [comment]
I found I can get by with `openapi.overrides` in `config/scribe.php`, but would really like to see this implemented similar to `@responseFile`.

```
'openapi' => [
    'overrides' => [
        'paths./path/to/my/endpoint.post.requestBody.content.application/json.examples' => (request examples here)
    ]
]
```

I'd like to try a custom strategy, but body examples doesn't seem to fit any of the existing strategy groups properly.

**Comment by shalvah** [comment]
All endpoints and parameters have a [`$custom` property] (https://github.com/knuckleswtf/scribe/blob/4b806df88437bb4d5ace75d1d76ae7b23ece168d/camel/BaseDTO.php#L15), so you can write a custom strategy that reads examples from somewhere and saves them there.

The only missing part is a custom OpenAPISpecWriter that can read that. Currently there's no way to prove your own Writer, but I'm open to that. We can do something like we did with the route matcher.

**Comment by shalvah** [comment]
Hmm, I might be wrong.

https://github.com/knuckleswtf/scribe/blob/4b806df88437bb4d5ace75d1d76ae7b23ece168d/src/Writing/Writer.php#L147

Since we use the container to resolve the writer, that means you should be able to bind your implementation.
