### ISSUE TITLE
Laravel jsonapi

### ISSUE THREAD

**Issue by cruzvale33** [knuckleswtf/scribe#650]
### Scribe version

latest

### Your question

Hi, can you consider to add support to generate the api documentation for the laravel json api routes??

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
I'm sorry, I don't understand your question.

**Comment by niranjnn01** [comment]
@shalvah 

Scribe  does not automatically discover and document Related Resources Endpoints created implicitly by frameworks like **Laravel JSON:API**.

The routes in this case are registered programmatically by the underlying JSON:API routing component, not by an explicit controller method or route closure that Scribe is designed to analyze.

Current solution is to  manually documentation (via YAML files or dummy routes) for the missing Endpoint,

**Comment by shalvah** [comment]
Ahh, I don't have the bandwidth to add support for any new frameworks atm.
