### ISSUE TITLE
Generating local and push to production does not work 100% correctly

### ISSUE THREAD

**Issue by rabol** [knuckleswtf/scribe#651]
### Scribe version

4.19.0

### PHP version

8.1.18

### Framework and version

v10.9.0

### Scribe config

```ruby
type => "laravel"
laravel.docs_url => "/developer/docs"
try_it_out.enabled => false
try_it_out.base_url => "developer/"
auth.enabled => true
auth.default => true
auth.name => "token"
```

### What happened?

I'm following the recommend installation and have --dev, which I think is absolutely correct as I don't want to generate the doc on the production server.

I'm generating documentation for type Laravel on my local machine and push it to git->production.

2 problems:

First all the url's is pointing to my local server
second routes are missing

I can make a 'hack' to my web.php like this:

```
if (app()->environment('production')) {
    $prefix = config('scribe.laravel.docs_url', '/docs');
    $middleware = config('scribe.laravel.middleware', []);

    Route::middleware($middleware)
        ->group(function () use ($prefix) {
            Route::view($prefix, 'scribe.index')->name('scribe');

            Route::get("$prefix.postman", function () {
                return new JsonResponse(Storage::disk('local')->get('scribe/collection.json'), json: true);
            })->name('scribe.postman');

            Route::get("$prefix.openapi", function () {
                return response()->file(Storage::disk('local')->path('scribe/openapi.yaml'));
            })->name('scribe.openapi');
        });
}
```

and then include the 2 files in git, but it does not feel right.

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Do you still have this issue?

> First all the url's is pointing to my local server

Hmm, which URLs are you referring to? The ones displayed in examples? They are gotten from `config('scribe.base_url')` . If you didn't set that, it will fall back to `config('app.url')`, which is likely your local server. Perhaps that's what you're encountering?

> second routes are missing

Hmm, it seems the included routes for `laravel` type won't work if you installed with `--dev`. There's nothing we can do about that. I'll add that to the documentation. Thanks.
