### ISSUE TITLE
Generate document with `@apiResource` but without `@apiResourceModel`？

### ISSUE THREAD

**Issue by ccec1t91077** [knuckleswtf/scribe#652]
### Scribe version

4.19.0

### Your question

Hi, I have some functional api, and I'm trying to use the tag `@apiResource` to generate the document, but the command `scribe:generate` will got an exception and failed if I use the tag `@apiResource` but without any `@apiResourceModel`.

In my case, I've some response(api resoruce) it doesn't need to display any data, we are using exception and error code to check if the result failed, it means I don't have any model or collection need to pass into api resource.

The resource will seems like：
```php
// I added default empty resource from here.
class SuccessResponse extends BaseResource
{
    public function __construct($resource = [])
    {
        parent::__construct($resource);
    }

    public function toArray(Request $request): array
    {
        return [];
    }
}
```

This allow my controller simple like：
```php
public function __invoke(Request $request)
{
    /*
        Do something functional ...
    */

    return new SuccessResponse();
}
```

Although I can define it by `@response`, but I wonder if you think this is a reasonable idea, or there does have ways I didn't notice, please let me know. 😃

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Oof. it's not supported, so you'll have to do some other way (`@response`, `@responseFile`, custom annotation, ...). Or you can send in a PR.

**Comment by ccec1t91077** [comment]
I've send a [PR](https://github.com/knuckleswtf/scribe/pull/662) for this little feature, and I'll send another PR to update the document after merged, thanks.

**Comment by ccec1t91077** [comment]
Oops. Mistakenly clicked the close button.

**Comment by ccec1t91077** [comment]
Close since merge, update document later.
