### ISSUE TITLE
 Incorrect generation of URL parameters in OpenAPI YAML file

### ISSUE THREAD

**Issue by Romagod** [knuckleswtf/scribe#653]
### Scribe version

4.18

### PHP version

8.1

### Framework and version

10.0

### Scribe config

```php
title => "Internal API"
base_url => "xxx"
auth.enabled => true
auth.placeholder => "{token}"
strategies.queryParameters => removed Knuckles\Scribe\Extracting\Strategies\QueryParameters\GetFromFormRequest
strategies.bodyParameters => removed Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromFormRequest

```

### What happened?

I am using Scribe's attributes to describe URL parameters for the index action:
```php
     /**
     * List Example.
     */
    #[Scribe\UrlParam("year", "integer", "The year (min: 2000).", required: false, example: 2022)]
    #[Scribe\UrlParam("group", "string", "The display group.", required: false, example: "sync-zones,primary-systems,regions")]
    #[Scribe\UrlParam("sort_by", "string", "The sort option.", required: false, example: "id,name,updated_at,filled,unfilled")]
    #[Scribe\UrlParam("order", "string", "The order option.", required: false, example: "asc,desc")]
    #[Scribe\UrlParam("regions_ids", "integer[]", "The regions ids.", required: false, example: "1,3,5")]
    ...
    public function index(IndexRequest $request): JsonResponse
```
After generating the documentation, I check the generated YAML file and see that the parameters are placed at a higher level, affecting all actions, not just the index action as described in the attributes:
```yaml
  /api/model/example:
    get:
      summary: 'List example.'
      operationId: listExample
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {token}'
          schema:
            type: string
      responses:
        200:
          ...
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: year
        description: 'Optional parameter. The year (min: 2000).'
        required: true
        schema:
          type: integer
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: 2022
      - ...
```
I believe this is a bug, as it prevents me from correctly processing the YAML file for the frontend.

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by Romagod** [comment]
I've found a solution to move the URL parameters from the path level to the operation level in the generated OpenAPI specification. Here's how to modify the relevant methods:

1. In the generatePathsSpec method, remove the following block of code that adds URL parameters at the path level:
```php
if (count($endpoints[0]->urlParameters)) {
    ...
    $pathItem['parameters'] = $parameters; // @phpstan-ignore-line
}
```
2. Modify the generateEndpointParametersSpec method to add URL parameters at the operation level. Insert the code removed in the previous step before the code handling query parameters:
```php
protected function generateEndpointParametersSpec(OutputEndpointData $endpoint): array
{
    $parameters = [];

    // Add this block of code
    if (count($endpoint->urlParameters)) {
        ...
    }

    if (count($endpoint->queryParameters)) {
        ...
    }

    if (count($endpoint->headers)) {
        ...
    }

    return $parameters;
}
```
3. Remove the $parameters variable from the removed code since it's already defined at the beginning of the generateEndpointParametersSpec method. Replace it with the following code:
```php
if (count($endpoint->urlParameters)) {
    /**
     * @var string $name
     * @var Parameter $details
     */
    foreach ($endpoint->urlParameters as $name => $details) {
        ...
        $parameters[] = $parameterData;
    }
}
```
By making these changes, URL parameters will be added at the operation level instead of the path level. This should fix the issue with displaying parameters in the documentation.

**Comment by shalvah** [comment]
Closed your issues and PRs, as they are low quality (apparently AI-generated, with inaccurate details and incorrect solutions). If these are actual issues, please do try again with better work.

**Comment by tcox-enrollfirst** [comment]
#804

**Comment by tcox-enrollfirst** [comment]
New PR #804
