### ISSUE TITLE
Missing Translation after Update

### ISSUE THREAD

**Issue by BenWallmeyer** [knuckleswtf/scribe#657]
### Scribe version

4.19.0

### PHP version

8.1

### Framework and version

9.52.7

### Scribe config

```ruby
auth.enabled => true
auth.default => true
```

### What happened?

The Translation is broken after update in all my sites. Also local in dev.

This is shown as link and as Header

scribe::headers.introduction
scribe::base_url: http://localhost

or like this

sribe::endpoint.request    scribe::try_it_out.open   
POST api/login

I delete .scribe folder and public docs folder. Clear cache and generate new but the same.

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Laravel or Lumen?

**Comment by shalvah** [comment]
Also, what's the default locale setting of your app? My guess is that it's not `en`? In that case, you'll need to set it to `en` for the docs or add translation file for your locale.

**Comment by BenWallmeyer** [comment]
Laravel,

how to set docs to en? Before all was working

**Comment by BenWallmeyer** [comment]
my Locale is de i have already de.json in \resources\lang\vendor\scribe also en.json is there. If i change locale to en it works de not.  

I use this command to create php artisan vendor:publish --tag=scribe-translations copy en.js to de.js

**Comment by NoahNxT** [comment]
Downgrading to 4.18 solved the issue for me!

**Comment by JasperTey** [comment]
I also noticed this happening on my app, which isn't using any translations (so locale is `en` by default already). Downgrading to 4.18 didn't resolve anything for me though.

![image](https://user-images.githubusercontent.com/1280844/236553844-360dc870-46f4-4c1f-b148-146c10ec65c2.png)

Explicitly setting `Config::set('app.fallback_locale', 'en')` in AppServiceProvider doesn't do anything either.

**Comment by shalvah** [comment]
Yeah, that doesn't fix it. Some limitations of Laravel's translation system. I've tagged 4.19.1, which should fix it. Try updating and let me know.

**Comment by JasperTey** [comment]
> Yeah, that doesn't fix it. Some limitations of Laravel's translation system. I've tagged 4.19.1, which should fix it. Try updating and let me know.

Hmm, `4.19.1` didn't resolve it for me. Not sure if I'm missing something. I tried wiping out the .scribe directory, removing published lang file, re-publishing lang file.

Some of the strings continue to be left out from translation in the built files, e.g.,

![image](https://user-images.githubusercontent.com/1280844/236558368-1102fc89-0892-453c-b039-132daa7f7ae7.png)

I am running on Laravel 10, so not sure if the circumstances are different (compared to the OP of this issue running Laravel 9.x)

**Comment by shalvah** [comment]
That's so weird. And downgrading didn't fix it? Seems like something is cached somewhere.

**Comment by shalvah** [comment]
It seems there have been quite a few hidden changes to the Laravel translation system across 8 - 10. Will need to investigate this further. Though I wonder if your issue is something different.

**Comment by JasperTey** [comment]
In response to your comment about caching, I tried `artisan optimize:clear`, `artisan cache:clear`, `artisan view:clear` just to see - no luck there.

I will try to look at this in more detail later to see if I can offer anything else. I have yet to source-dive, so I'm only going at this at surface level.

**Comment by BenWallmeyer** [comment]
I tried also. No luck .

**Comment by shalvah** [comment]
Are you also on `en`, and downgrading didn't work?

**Comment by BenWallmeyer** [comment]
If i am on de it does not work. On en it works. Lang Files for de also not work

**Comment by shalvah** [comment]
Okay, there are definitely subtle breaking changes to the translation system for package devs across Laravel 8 - 10. I need you guys to provide detailed information, please. 
1. What Laravel version are you on?
2. What is your app locale/fallback locale?
3. Do you have any translation files in your app? (either in `lang` or `resources/lang`).
4. Did you publish the scribe-translations file? If so, where is it located? (In Laravel 10, it's in `lang/vendor/scribe`, in earlier versions, it's in `resources/lang`.)

**Comment by shalvah** [comment]
Please provide this info, guys. ☝️ It's very important, as Laravel has two translation systems (JSON-based and PHP-based) that look similar, but turn out to have some differences, including different file structures, and the places they can be loaded from (there are about two or three different places translation files can be loaded from, and they work differently).

**Comment by shalvah** [comment]
As it stands, I'm unable to replicate this on Laravel 10 with v4.19.1. There is some weirdness with the publishing and overriding of translations, but I don't get the `scribe::` text in the UI.

**Comment by BenWallmeyer** [comment]
1. Laravel 9.52.7
2. locale de / fallback en
3. ressource/lang/vendor/scribe/de.json
3.1 3. ressource/lang/vendor/scribe/en.json
and some more  in another folder in vendor
4. No
5. Yes in ressources/lang/vendor/scibe

**Comment by JasperTey** [comment]
Here's what I believe is the root cause, after some experimentation.

The default scribe lang file is published to: `resources/lang/vendor/scribe/en.json`

However, during `scribe:generate`, translations are being looked for in `resources/lang/en.json` instead of `resources/lang/vendor/scribe/en.json`.

**When manually copying `resources/lang/vendor/scribe/en.json` to `resources/lang/en.json`, everything works.**

Related: the documentation at https://scribe.knuckles.wtf/laravel/advanced/localization incorrectly states otherwise:

> You can publish Scribe's default translations using php artisan vendor:publish --tag=scribe-translations. This will create a lang/en.json (or resources/lang/en.json) file in your project.

Does this give you enough of a hint as to how to resolve it? I'm guessing the high level solution is to ensure that the path to the lang file is consistently prefixed with `vendor/scribe/`.

**Comment by shalvah** [comment]
What you're describing is Laravel 10 only. The publishing process works differently on 8-9 (which is what the docs on the site currently use).😕 Anyway, I can find a way around. What I'm curious about is: does everything work as normal when you don't publish any translations?

**Comment by JasperTey** [comment]
> 

No, does not work when I don't publish translations.

I forked the repo to poke around locally and get my head wrapped around everything. So what I am gathering is that JSON translation files are handled differently, and have to live in `resources/lang`, with no way of customizing the path or nesting in subfolders? Were you saying that this behaviour is L10 only?

**Comment by BenWallmeyer** [comment]
I Updated to 4.19.1  run composer update than generate new docs and all is working. Thx

**Comment by netpok** [comment]
This is related to a bug where adding translations are not taken into account if the are already loaded.

One possible source for this is using `bensampo/laravel-enum`
I made a bug report to both repositories:
https://github.com/laravel/framework/issues/47194
https://github.com/BenSampo/laravel-enum/issues/321

Until then if this is your problem adding this to a provider fixes it:
```php
use BenSampo\Enum\EnumServiceProvider;

// ...
    public function register(): void
    {
        $this->app->getProvider(EnumServiceProvider::class)?->booted(function () {
            if ($this->app->has('translator')) {
                $this->app->get('translator')->setLoaded([]);
            }
        });
    }
```

**Comment by shalvah** [comment]
For anyone having trouble with localizations, can you try the `localization` branch? See this PR for instructions: https://github.com/knuckleswtf/scribe/pull/673 It should work predictably now, across Laravel versions.
