### ISSUE TITLE
Doc generation build static class text on html(blade)

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#658]
### Scribe version

4.19

### PHP version

8.1

### Framework and version

laravel 9

### Scribe config

```ruby
`      'extra_info' => "..... some random text",`
```

### What happened?

I ran php artisan scribe:generate, and now in the final document file, classes are shown in HTML like text, I use blade-generated docs, and this is in the index.blade.php file :

```
<h1 id="authenticating-requests">Authenticating requests</h1>
<p>scribe::auth.instruction.bearer</p>
<p>scribe::auth.details</p>
<p>Some random text....</p>
```

Is there anything on the update process that I missed ? I always followed the guides from v1.0 to now v4.0!

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Sorry, same issue as https://github.com/knuckleswtf/scribe/issues/657, apparently. It's the new translations support, but apparently, it doesn't work if your locale is not `en`. Can you try adding `if class_exists(Scribe) Config::set('app.fallback_locale', 'en');` in your AppServiceProvider?

**Comment by shalvah** [comment]
Never mind, should be fixed in 4.19.1

**Comment by pirex360** [comment]
Thanks, it works...but it misses the JS file for the theme element

**Comment by shalvah** [comment]
What do you mean? What does it show?

**Comment by pirex360** [comment]
When I put in scribe.php , theme elements ... and then generate documentation... it misses the js file of the theme.
I tried to find the js file in your vendor path because in docs you say that for default and element theme, all files are published on document generation, for me the js file is not found anywhere.

Note: for the default theme, all work well.

**Comment by shalvah** [comment]
Yeah, I don't think the Elements theme has a JS file... It's JS is in the HTML page. I just need to remove the script tag that looks for the JS file.

**Comment by shalvah** [comment]
But apart from that, everything works, yes? How's the existence with the Elements theme?
