### ISSUE TITLE
Multi-word names not handled correctly when extracting route key from url param

### ISSUE THREAD

**Issue by Rasmus-Bertell** [knuckleswtf/scribe#669]
### Scribe version

4.19.1

### PHP version

8.2.6

### Framework

Laravel

### Framework version

10.11.0

### Scribe config

```ruby
type => "laravel"
```

### What happened?

After running `php artisan scribe:generate` the documentation has wrong url parameter for multi-word paths e.g. `/api/user-address/{user_address}`. Url parameter defaults to `id` but I'm having `uuid` returned from the method `getRouteKeyName()`. I tracked the issue down to `getRouteKeyFromModel(...)` function. It seems the `$paramName` is `user-address` while the array `$typeHintedEloquentModels` has a key named `userAddress` so it can't find it.

https://github.com/knuckleswtf/scribe/blob/3cd295f6b7d235f47350ab6b92c3e4571bca20f5/src/Extracting/Shared/UrlParamsNormalizer.php#L186-L194

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by Rasmus-Bertell** [comment]
Opened a PR #670, but it still needs a test case which I don't know how to write. It could also be improved with a more robust case changing function.

**Comment by Rasmus-Bertell** [comment]
And if I only would have searched a bit more I would have found `Str::camel(...)` earlier. Now all that is needed is the test case, if this is otherwise a sound solution.

**Comment by shalvah** [comment]
I see what you mean now.
