### ISSUE TITLE
[Feature] @bodyParamsFile, to generate Body Parameters documentation from json file

### ISSUE THREAD

**Issue by ajcastro** [knuckleswtf/scribe#67]
Would it be okay if I just link the original issue from mpociot/laravel-apidoc-generator?

https://github.com/mpociot/laravel-apidoc-generator/issues/767

**Comment by shalvah** [comment]
So what would be the contents of the file?

**Comment by fcolecumberri** [comment]
Lets asume we have this:

```php
<?php 
//...
class UserController extends Controller
{
    //...
    /**
    * @urlParam id required string user's id
    * @bodyParam name string
    * @bodyParam password string
    * @bodyParam age integer
    */
    public function update(Request $request, $id){
        //...
    }
    //...
}
```
It could be something like a php array at `storage/request/user.update.php`
```php
<?php
return [
    'urlParam' => [
        'id' => 'required string user\'s id'
    ],
    'bodyParam' => [
        'name' => 'string',
        'password' => 'string',
    ],
    'response' => [
        '200' => '{"id":4,"name":"Jessica Jones"}'
        '404' => '{}'
    ]
    //...
];

```

and the documentation block:
```php
<?php 
//...
class UserController extends Controller
{
    //...
    /**
    * @docFile storage/request/user.update.php
    * @bodyParam age integer
    */
    public function update(Request $request, $id){
        //...
    }
    //...
}
```

This way you could have the whole documentation outside the controller or only the parts you prefere to have outside

**Comment by shalvah** [comment]
Write a custom strategy for that. 🙃 It's actually pretty easy. You can work off any of the existing ones.

**Comment by shalvah** [comment]
So, yeah, won't be adding this any time soon because it's going to overly complicate things.
