### ISSUE TITLE
Package spatie/data-transfer-object is abandoned, you should avoid using it. Use spatie/laravel-data instead.

### ISSUE THREAD

**Issue by Djurdjijan** [knuckleswtf/scribe#675]
### Scribe version

4.20

### Your question

Hi, just to mention this :) 

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
See the pinned issue

![image](https://github.com/knuckleswtf/scribe/assets/14361073/7cd8d9f3-e542-4970-b12f-59c7334481a0)
