### ISSUE TITLE
Pagination response doesn't appear to work

### ISSUE THREAD

**Issue by laurenwilliams92** [knuckleswtf/scribe#678]
### Scribe version

4.19.0

### PHP version

8.2

### Framework

Laravel

### Framework version

10.8.0

### Scribe config

```ruby
type => "laravel"
try_it_out.enabled => false
auth.enabled => true
auth.default => true
auth.name => "Authorization"
auth.use_value => "{AUTHKEY}"
```

### What happened?

I have an endpoint that returns a resource collection with a paginated model

The response generated by scribe does not contain the paginated response, only that inside the 'data' array

![Screenshot 2023-06-01 at 11 46 44](https://github.com/knuckleswtf/scribe/assets/32837730/cfb886ce-6320-4de8-9405-df38352b440d)
![Screenshot 2023-06-01 at 11 49 03](https://github.com/knuckleswtf/scribe/assets/32837730/bd0e94a1-1b25-478e-b907-7fbddfd293a5)

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Fixed in 4.21.1
