### ISSUE TITLE
2nd config for different api set for mobile not working

### ISSUE THREAD

**Issue by jackkitley** [knuckleswtf/scribe#682]
### Scribe version

4.21.2

### PHP version

8.2.6

### Framework

Laravel

### Framework version

10.13.2

### Scribe config

```ruby
994d360921a2:/var/www/html$ php artisan scribe:config --config=mobile_scribe
Laravel Framework 10.13.2

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display help for the given command. When no command is given display help for the list command
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi|--no-ansi  Force (or disable --no-ansi) ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands for the "scribe:config" namespace:
  scribe:config:diff  Dump your changed config to the console. Use this when posting bug reports
```

### What happened?

php artisan scribe:config --config=mobile_scribe

I created another config to generate another doc to separate my routes for mobile.

It doesnt generate the routes for `laravel`. 404 not found.

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by jackkitley** [comment]
Issue is that the route generated is not dynamic to the config set.

`$prefix = config('scribe_mobile.laravel.docs_url', '/docs');
$middleware = config('scribe_mobile.laravel.middleware', []);

Route::middleware($middleware)
    ->group(function () use ($prefix) {
        Route::view($prefix, 'scribe.index')->name('scribe');

        Route::get("$prefix.postman", function () {
            return new JsonResponse(Storage::disk('local')->get('scribe/collection.json'), json: true);
        })->name('scribe_mobile.postman');

        Route::get("$prefix.openapi", function () {
            return response()->file(Storage::disk('local')->path('scribe/openapi.yaml'));
        })->name('scribe_mobile.openapi');
    });
`

**Comment by shalvah** [comment]
It's stated in the docs:


![Screenshot_20230609-164939~2](https://github.com/knuckleswtf/scribe/assets/14361073/f3a63cdb-769a-4565-b761-5b115bfa048c)

Maybe I should move it to the beginning of the section so it's more obvious?

**Comment by jackkitley** [comment]
Thanks.

Because I looked in vendor and saw config this was my immediate thought to
create another configuration and it would automatically work.

I'll give this a try.

**Comment by jackkitley** [comment]
@shalvah I tried what was described in docs and i tried this way in routes before the other issues and i get the following:

If i set both to false in config then all works.

![Screenshot 2023-06-09 at 20 48 21](https://github.com/knuckleswtf/scribe/assets/3243014/764b6c46-1e52-4022-b377-2cc53ecc2459)

**Comment by jackkitley** [comment]
Had to add two more routes to get openapi and postman.

`Route::view('/mobile/docs', 'scribe_mobile.index')->name('scribe-mobile');
Route::get("scribe_mobile.postman", function () {
    return new JsonResponse(Storage::disk('local')->get('scribe_mobile/collection.json'), json: true);
})->name('scribe_mobile.postman');
Route::get("scribe_mobile.openapi", function () {
    return response()->file(Storage::disk('local')->path('scribe_mobile/openapi.yaml'));
})->name('scribe_mobile.openapi');`
