### ISSUE TITLE
 View [partials.example-requests.go] not found.

### ISSUE THREAD

**Issue by adityadees** [knuckleswtf/scribe#684]
### Scribe version

^4.21

### PHP version

8.1.20

### Framework

Laravel

### Framework version

10.10

### Scribe config

```ruby
auth.enabled => true
```

### What happened?

Run  ` php artisan scribe:generate`

```
✔ Processed route: [POST] api/xxxxx
ⓘ Extracting intro and auth Markdown files to: .scribe
✔ Extracted intro and auth Markdown files to: .scribe
ⓘ Writing HTML docs...

 Illuminate\View\ViewException 

  View [partials.example-requests.go] not found. (View: /var/www/html/vendor/knuckleswtf/scribe/resources/views/themes/default/endpoint.blade.php) (View: /var/www/html/vendor/knuckleswtf/scribe/resources/views/themes/default/endpoint.blade.php) (View: /var/www/html/vendor/knuckleswtf/scribe/resources/views/themes/default/endpoint.blade.php)

  at vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137
```

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

<img width="1680" alt="image" src="https://github.com/knuckleswtf/scribe/assets/37553901/740a7aac-f0ad-4715-8cc1-97d296e10726">

**Comment by shalvah** [comment]
There's no `go` example included in the package. You need to create your own Go template. See the docs on adding a custom example request.
