### ISSUE TITLE
How write a two auth service in config

### ISSUE THREAD

**Issue by ztejack** [knuckleswtf/scribe#690]
### Scribe version

4.19.1

### Your question

im using bearer and my custom api-key in header, im write into array and atuh->in parameter cannot convert array into string

### Docs

- [x] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Oof, Scribe doesn't currently support multiple auth. And it's unlikely I'll be able to support that anytime soon, so I'll close this for now. I think you can still get this to work with something along these lines:
- use only the bearer in the `auth` section
- in the `extra_info`, you can then talk about the other token (or use the [Translations feature](https://scribe.knuckles.wtf/laravel/advanced/localization) to customize the auth text completely
- add your custom `header` in the `routes-> apply` section
