### ISSUE TITLE
@response fails with queryparameters.

### ISSUE THREAD

**Issue by ptrcksc** [knuckleswtf/scribe#7]
The response documentation is rendered as null when you have a null value in your example response.
{
“test” : null
}

It also seems that URL’s as values are not correctly interpreted. It looks to be failing on slashes and question marks.

**Comment by shalvah** [comment]
Please include more comprehensive examples. What was the full content of your doc block?

**Comment by ptrcksc** [comment]
I have no checked the code itself, but still will cause an endpoint to not show up in the docs at all:

     * @response
     * {
     *     "data": {
     *         "test" : "http://google.com?page=1"
     *     }
     * }
Haven't checked your package itself, just have been using it. I think it's the equal sign, "http://google.com?page" does get documented.

//adjusted title, can't reproduce the null value issue for some reason.

**Comment by shalvah** [comment]
Thanks, this has been fixed now.

**Comment by ptrcksc** [comment]
Cheers!
