### ISSUE TITLE
API Token from use_value is included in generated Postman collection

### ISSUE THREAD

**Issue by Grldk** [knuckleswtf/scribe#701]
### Scribe version

4.22.0

### PHP version

8.1.18

### Framework

Laravel

### Framework version

10.15.0

### Scribe config

```ruby
routes.apply.response_calls.methods => ['GET','POST']
routes.apply.response_calls.config.app.env => 'testing'
auth.enabled => true
auth.default => true
auth.name => "Authorization"
auth.use_value => "actual_api_token"
examples.models_source => removed factoryCreate
```

### What happened?

Just started using this package, like it so far, so thanks very much for your work!

Ran into the following, not sure if this is something I did wrong, but from reading the docs and the config file I think this shouldnt happen:

I've started to get this to work on one of our API endpoints, which is a POST endpoint. I've added some `@bodyParam` docs in the Request class, added the following to the AppServiceProvider:
```php
        if (class_exists(Scribe::class)) {
            Scribe::bootstrap(function (GenerateDocumentation $command) {
                App::setLocale('en');
            });

            Scribe::instantiateFormRequestUsing(function (string $form_request_class_name) {
                if ($form_request_class_name === {{className}}::class) {
                    return request()->createFrom(request(), new {{className}}(resolve({{dependency}}::class)));
                }
            });
        }
```
This has resulted in a Postman collection json file which includes the following:
```json
    "auth": {
        "type": "bearer",
        "bearer": [
            {
                "key": "Authorization",
                "value": "actual_api_token",
                "type": "string"
            }
        ]
    }
```
Although the config explicitly says the following:
```
        /*
         * The value of the parameter to be used by Scribe to authenticate response calls.
         * This will NOT be included in the generated documentation.
         * If this value is empty, Scribe will use a random value.
         */
```
So I was not expecting to see the actual api token in put in the config to show up in the Postman collection. Is this a bug, or did I misunderstand something?

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Oof, definitely a bug, probably copy and paste, as we don't do that for other auth method, only bearer tokens.

https://github.com/knuckleswtf/scribe/blob/fbb687e0348c882f67bc8f90385631e1bdb75cd9/src/Writing/PostmanCollectionWriter.php#L83
