### ISSUE TITLE
Generate response model of swagger using scribe

### ISSUE THREAD

**Issue by bhattaxay** [knuckleswtf/scribe#703]
### Scribe version

4.22

### Your question

Hi there,

I want to generate swagger response model as shown in below image:

![image](https://github.com/knuckleswtf/scribe/assets/16645901/2fd65123-7a80-4acd-b5f9-78807d868ff7)

Is it possible to generate response model as above image? Basically it will be useful for integrate in mobile app easily. Let me know if it is possible. 

The scribe is not providing any option to add this object in response model. It will just take response from my api resource.

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Sorry, Scribe is mostly focused on human-readable documentation. If you need a detailed OpenAPI spec with full response models and types, you may need to look elsewhere.
