### ISSUE TITLE
GetFromDocBlocks - not generating

### ISSUE THREAD

**Issue by Dimrak** [knuckleswtf/scribe#71]
Hi,

The documentation generation works without issues on localhost env.
The problem is while running in prod server scribe:generate.

It goes through all the routes and all the strategies. The first strategy is GetFromDocBlocks.
This strategy is not working and not generating any information written in the DocBlock.
As the prod server (nginx) is not able to read the docBlock of each function, every route goes to the "MISC" default group.

We have tried removing the files and generating those again.
Provided different combination of file permissions.
Removing cache.

Php : 7.4.7
Laravel - 6.0.4
Scribe - Latest

Thank in advance.

**Comment by Dimrak** [comment]
Hi,

We found the problem and fixed by changing this on php config;

opcache.save_comments=1
opcache.load_comments=1

Closing issue

**Comment by shalvah** [comment]
Ah, interesting. Thanks for reporting your solution.

**Comment by jayenne** [comment]
We also had this issue too and found the solution independantly so adding this note to help it show in searches..
ignoring docblock, params ignored in docblock
