### ISSUE TITLE
@hideFromAPIDocumentation does not work

### ISSUE THREAD

**Issue by rabol** [knuckleswtf/scribe#716]
### Scribe version

4.23.0

### PHP version

8.2.9

### Framework

Laravel

### Framework version

10.20

### Scribe config

```ruby
type => "laravel"
laravel.docs_url => "/developer/docs"
try_it_out.enabled => false
try_it_out.base_url => "developer/"
auth.enabled => true
auth.default => true
auth.name => "token"
logo => "/img/logo.png"
```

### What happened?

@hideFromAPIDocumentation does not hide the endpoint.

```

/** @hideFromAPIDocumentation */
Route::middleware(['auth.basic'])->prefix('postmark')->as('postmark.')->group(function () {
    /** @hideFromAPIDocumentation */
    Route::post('/', [PostmarkWebhookController::class, 'handle'])->name('handle');
});

```

the above is in the final doc

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
It should be on the controller method or class definition.
