### ISSUE TITLE
Docs not found after deploy of Laravel 10.X project with Vapor

### ISSUE THREAD

**Issue by pierluiginovatag** [knuckleswtf/scribe#719]
### Scribe version

version 4.22.0

### Your question

I generate the doc on my W11 pc, and locally the /docs directory works fine.
Then I push to the git repo that is linked to a laravel/vapo project
Accessing the aws server (generated by vapor) accessing the /docs directory result in a 404 not found
Then i tried to generate locally the docs, running "php artisan scribe:generate" using vapor command console, but I get this error: Unable to delete file located at: /var/task/.scribe/endpoints/00.yaml.

Is there any way to have scribe docs in vapor/laravel env ?

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
I haven't used Vapor, so my knowledge here is limited, but I think you'll need to configure your setup to serve static pages from your public/docs directory. Alternatively, I think you can change the `type` in your Scribe config to `laravel`. This will route the docs through your Laravel app, so you shouldn't need to configure any static file serving.
