### ISSUE TITLE
Create two document pages, it is possible ?

### ISSUE THREAD

**Issue by pirex360** [knuckleswtf/scribe#72]
Is possible to create two versions of the xxx.xx/docs , with different endpoints ?

Having : 
yyyy.xxx/docs -> main documentation
yyyy.xxx/something -> secondary documentation for some endpoints that i want to exclude from main documentation.

I dont want to duplicate my project, to a different URL a customize the secondary documentation, if it's possible to have like a child documentation ou some sort of duplication with control of endpoints.

Thanks.

**Comment by shalvah** [comment]
Not directly, no. I considered this earlier but decided against it as most people don't need it and it would add complexity for them.

You can achieve this with a bit of scripting. For instance, you could have two separate config files for the two docs you want, say scribe.api1.php and scribe.api2.php. In each file, you configure the docs as needed. You'll need to change the value of `routes` so it only captures the endpoints you want. Then tinker with the output settings as needed (example `static.output_path`) so each file points to a different output path. 

Then when you're ready, rename each file in turn to scribe.php and run the command. You can have a script that does this. Note that the source files will be generated to the same location (`resources/docs`), so if you want to retain the originals, you can have a step in your script that moves the first one's source files to a different location before generating for the second.

(It's a little more involved if using `laravel` type, but you get the idea.)

**Comment by shalvah** [comment]
You can now do this! https://scribe.knuckles.wtf/laravel/generating#generating-multiple-docs

**Comment by shalvah** [comment]
Oof, you could just have used the search bar to search for it. 🙄
https://scribe.knuckles.wtf/laravel/tasks/generating#generating-multiple-docs

**Comment by junaid-A-khan** [comment]
> Or you could just have used the search bar to search for it. 🙄 https://scribe.knuckles.wtf/laravel/tasks/generating#generating-multiple-docs

Sorry, my bad. 😔
Thank you 🙏🙏🙏
