### ISSUE TITLE
Postman collection body mode "formdata"

### ISSUE THREAD

**Issue by thewhaleiam** [knuckleswtf/scribe#730]
### Scribe version

4.22

### Your question

With regards to the collection file generated for postman, I can see that the body elements are generated with the mode of "raw", is there a way to configure this so that it uses "formdata" and generates json accordingly?

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
You want form-data type, but JSON body? Isn't that a contradiction?

**Comment by thewhaleiam** [comment]
So, no I meant that that on the import file I would like to have body json to be 

`"body": {
							"mode": "formdata",
							"formdata": [
								{
									"key": "email",
									"value": "<string>",
									"type": "text"
								},
								{
									"key": "password",
									"value": "<string>",
									"type": "text"
								}
							]
						},`

rather than
 `"body": {
                            "mode": "raw",
                            "raw": "{\"email\":\"user@email.com\",\"password\":\"password12\"}"
                        },`

I was wondering if there was a setting that would allow this to happen?

**Comment by shalvah** [comment]
See https://github.com/knuckleswtf/scribe/blob/6a9d51b3a215a89e8b8af47f796ffaa10993c171/src/Writing/PostmanCollectionWriter.php#L171-L175. It sets these based on your content-type header.

**Comment by thewhaleiam** [comment]
When I add the attributes it prevents the form being posted as it now fails validation?

`    #[Header("Content-Type", "multipart/form-data")]`

**Comment by shalvah** [comment]
Huh?
