### ISSUE TITLE
php artisan scribe:generate doesn't work with bodyParams 

### ISSUE THREAD

**Issue by sabrio** [knuckleswtf/scribe#74]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. I set my configuration to:
```
'bodyParams' => [
                        'email' => 'test@test.com',
                        'password' => 'testcom',
                    ],
```
2. Then I ran `php artisan scribe:generate` ...
3. But I saw output of my bodyParams: 
```array:2 [
  "email" => "test@test.com"
  "password" => "testcom"
]
```

instead of the default message after generating the docs

**Comment by shalvah** [comment]
When reporting bugs, please respect the bug template. This looks like a stray `dd()`, but I can't find any such in the codebase. I'll need some details of your setup.

**Comment by sabrio** [comment]
My mistake in the endpoint it self, sorry for disturbing.
