### ISSUE TITLE
Replacement for https://www.jsdelivr.com/

### ISSUE THREAD

**Issue by Saifallak** [knuckleswtf/scribe#744]
### Scribe version

4.25.0

### PHP version

8.2

### Framework

Laravel

### Framework version

10.0

### Scribe config

```ruby
------ SAME AS DEFAULT CONFIG ------
```

### What happened?

https://www.jsdelivr.com is blocked in my country, so i need to replace it to https://cdnjs.com

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by Saifallak** [comment]
> Oof, that's tough. I'd like to change it, but I don't want to potentially break things for other users. I recommend rewriting the URL yourself. Search the docs for "afterGenerating". You can use this hook to read the generated HTML file and replace the CDN with whatever you prefer.

Okay gonna try, but would be awesome if this can be changed from config file maybe?

**Comment by shalvah** [comment]
> would be awesome if this can be changed from config file maybe?

It would be helpful for you, but the config file is used by all users. Adding an option every time someone has a specific use case would quickly lead to bloat.
