### ISSUE TITLE
can we have an ignore_hidden override pls?

### ISSUE THREAD

**Issue by mooseh** [knuckleswtf/scribe#746]
### Scribe version

4.22.0

### Your question

so a while back you added config support which is super helpful for those who need 2 sets of documentation
this works great but I was wondering if we could add a 'ignore_hidden' to the config like so

```

    /*
     * The base URL displayed in the docs. If this is empty, Scribe will use the value of config('app.url').
     */
    'base_url' => null,

    /**
     * overide hidden items
     */

    'ignore_hidden' => true,
```

and then add the following lines in GroupedEndpointsFromApp

```
            if ($this->isRouteHiddenFromDocumentation($routeControllerAndMethod) && $this->docConfig->get('ignore_hidden') !== false) {
                c::warn('Skipping route: ' . c::getRouteRepresentation($route) . ': @hideFromAPIDocumentation was specified.');
                continue;
            }
```

this is so we can have an ALL documentation and then filtered documentations

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
> this is so we can have an ALL documentation and then filtered documentations

I don't get it. Can you elaborate, possibly with an example?

**Comment by mooseh** [comment]
so its a little tricky to explain but i have 2 configs, 1 for users and 1 for admins
the admin routes for the documentation are gated so only admins can reach the /admin/docs path

I need the config/scribe_admin.php config file to have an override for the @hideFromAPIDocumentation
such as ignore_hidden flag in the config.php
so that admins get all the routes even if they are hidden.

maybe i am taking the wrong approach but I feel like this is a quick and helpful solution to my problem

**Comment by shalvah** [comment]
Closing this, as there's no plan to add this. This is what the `routes` -> `match` rules in the config file are for. In one config file, you can have `'exclude' => 'GET /some_endpoint'` to exclude it from that doc.
