### ISSUE TITLE
HTML shows one thing an YAML shows another

### ISSUE THREAD

**Issue by rabol** [knuckleswtf/scribe#757]
### Scribe version

4.25

### PHP version

8.2.12

### Framework

Laravel

### Framework version

10.30.1

### Scribe config

```ruby
type => "laravel"
laravel.docs_url => "/developer/docs"
try_it_out.enabled => false
try_it_out.use_csrf => true
auth.enabled => true
auth.default => true
logo => "/img/logo.png"
```

### What happened?

the yaml file has this enty

``` '/api/documents/{id}/show':``` which is incorrect

it comes from this:

```
/**
     * Get document
     *
     * @urlParam document string required Document id Example: 9909c553-31bf-494b-bde8-41b6eda60400
     */
    public function show(Request $request, string $document)
    {
```

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by rabol** [comment]
actually the

**Comment by rabol** [comment]
I belive the issue is in the

class UrlParamsNormalizer, method normalizeParameterNamesInRouteUri as it will turn what ever you have into {id}

which would okay if you don't have any @urlParm or no #[UrlParm] specified for your methof

**Comment by shalvah** [comment]
I think you want 
https://scribe.knuckles.wtf/laravel/hooks#normalizeendpointurlusing
