### ISSUE TITLE
Enum values not getting written to HTML

### ISSUE THREAD

**Issue by RobinJespersen** [knuckleswtf/scribe#758]
### Scribe version

4.24.0

### PHP version

8.2.9

### Framework

Laravel

### Framework version

v10.25.2

### Scribe config

```ruby
static.output_path => "public/scribe"
postman.enabled => false
openapi.enabled => false
```

### What happened?

1. Validation rule is parsed correctly.
2. Field is correctly described in .scribe/endpointy/0*.yaml file. (With enumValues)
3. Generated documentation does not show the "Must be one of:" part. 

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
(Apparently) closed by https://github.com/knuckleswtf/scribe/pull/759
