### ISSUE TITLE
Ability to set a standard response that wraps the actual data being returned

### ISSUE THREAD

**Issue by abodnar** [knuckleswtf/scribe#769]
### Scribe version

4.26.0

### Your question

I'm working on a project where we have a standard structured object that wraps the data that is being returned to the frontend. 

Example:
```json
{
    "success": "boolean of whether it was a success or not",
    "payload": {
       "object/paginated data/etc"
    },
    "message": "Some sort of informational message if needed"
}
```

As I've been implementing Scribe and reading the docs, it seems like the best solution would be to extend each of the Response Attribute objects to wrap the data being returned and set the appropriate values for the keys. After reading   https://github.com/knuckleswtf/scribe/issues/738, this made it seem like that was the right path as well.

Am I missing some other way to do this? I've considered that maybe could just leverage the API Resource data wrapping that Laravel supports(https://laravel.com/docs/10.x/eloquent-resources#wrapping-nested-resources), but not fully seeing if that would result in what I want.

Thanks.

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by abodnar** [comment]
Just to follow up, this is the Attribute I created:

```php
<?php

namespace App\Docs\Responses;

use Attribute;
use Knuckles\Scribe\Attributes\Response;

#[Attribute(Attribute::IS_REPEATABLE | Attribute::TARGET_FUNCTION | Attribute::TARGET_METHOD | Attribute::TARGET_CLASS)]
class TCResponse extends Response
{
    public function __construct(
        public string|array|null $content = null,
        public int $status = 200,
        public ?bool $success = true,
        public ?string $message = '',
        public ?string $description = '',
    ) {
        parent::__construct($content, $status, $this->description);
    }

    public function toArray(): array
    {
        $baseResponse = parent::toArray();

        $payload = [
            'success' => $this->success,
            'payload' => $baseResponse['content'],
            'message' => $this->message,
        ];

        return [
            'status' => $baseResponse['status'],
            'content' => $payload,
            'description' => $baseResponse['description'],
        ];
    }
}
```

When I set it up on my controller:

```php
    #[Unauthenticated]
    #[Endpoint('Refresh Auth Tokens', 'Refreshes the access token and refresh tokens for the logged in user')]
    #[Group('Authentication')]
    #[BodyParam('token', 'string', 'The refresh token', required: true)]
    #[TCResponse([
        'access_token' => '{NEW_ACCESS_TOKEN}',
        'refresh_token' => '{NEW_REFRESH_TOKEN}',
    ])]
    #[TCResponse(['message' => 'The refresh token is invalid.'], 400, false, 'refresh_failed', 'An invalid or expired refresh token was sent')]
```

I got the following error when I ran the generate command:

```
ⓘ Processing route: [POST] api/v1/auth/refresh

   UnhandledMatchError 

  Unhandled match case '...'

  at vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/UseResponseAttributes.php:41
     37▕     {
     38▕         $responses = [];
     39▕         foreach ([...$attributesOnController, ...$attributesOnFormRequest, ...$attributesOnMethod] as $attributeInstance) {
     40▕             /* @phpstan-ignore-next-line */
  ➜  41▕             $responses[] = match (get_class($attributeInstance)) {
     42▕                 Response::class => $attributeInstance->toArray(),
     43▕                 ResponseFromFile::class => $attributeInstance->toArray(),
     44▕                 ResponseFromApiResource::class => $this->getApiResourceResponse($attributeInstance),
     45▕                 ResponseFromTransformer::class => $this->getTransformerResponse($attributeInstance),
```

**Comment by shalvah** [comment]
Ah, thanks for the report. A custom attribute should indeed work, although probably you can do that with a regular API resource too (I haven't used them much, but I think that's what they're for).

Can you try again with `dev-master`? I've pushed an update that should make custom attributes work.

**Comment by abodnar** [comment]
Yeah. This change did indeed work with the response object I set up. I haven't been able to get a chance(holidays and all) to try with the other response objects as parent classes, but I don't see why there'd be a problem with them working.

I agree that this should be doable with a the regular API Resource object, but I've been having a hard time wrapping my head around it and getting it set up so it's manageable for the different resources.
