### ISSUE TITLE
upgrade symfony/var-exporter to support v7.0.1 please

### ISSUE THREAD

**Issue by teoprayoga** [knuckleswtf/scribe#772]
### Scribe version

4.26.0

### PHP version

8.2.13

### Framework

Laravel

### Framework version

10.35.0

### Scribe config

```ruby
unable install scribe:4.26.0 on laravel 10.35.0, upgrade symfony/var-exporter to support v7.0.1 please
```

### What happened?

unable install scribe:4.26.0 on laravel 10.35.0, upgrade symfony/var-exporter to support v7.0.1 please

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Try now (4.27.0)

**Comment by skrypnik-dzencode** [comment]
> Try now (4.27.0)

Awesome, tnx!
