### ISSUE TITLE
"Try it out" ignores port

### ISSUE THREAD

**Issue by tebbbb** [knuckleswtf/scribe#782]
### Scribe version

4.29.0

### PHP version

8.3

### Framework

Laravel

### Framework version

10.39.0

### Scribe config

```ruby
base_url => "http://localhost:81/"
type => "laravel"
auth.enabled => true
```

### What happened?

My installation is running on port 81. On the right side, where the Example requests are, its correctly shown, but when i click on the "Try it out" button and then "Send Request", its sending requests to http://localhost instead of http://localhost:81/

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
I think you missed this. https://github.com/knuckleswtf/scribe/blob/695c2a99a70f8c6c1b0dd3bf34d0d70af5ca44fc/config/scribe.php#L86

Either set `try_it_out.base_url` to the value you want, or make sure your app URL is set correctly when generating.

**Comment by tebbbb** [comment]
Hi,

my app.url is set correctly, but the whole application runs in a docker container so the port gets redirected from 80 internally to 81 exposed. In the base_url i have set it to localhost:81 which works, but only on the right side with the example requests. Not with the try it out function. It should use the same (base) url for both parts

**Comment by shalvah** [comment]
> It should use the same (base) url for both parts

No, dude. You're not paying attention. The docs mention it, and I mentioned it again in my comment. There are two separate base_url settings.

**Comment by shalvah** [comment]
See https://scribe.knuckles.wtf/laravel/reference/config#try_it_out
