### ISSUE TITLE
Couldn't get example model for ...Models\UserTerm via factoryCreate.

### ISSUE THREAD

**Issue by yormy** [knuckleswtf/scribe#784]
### Scribe version

4.29

### PHP version

8.1

### Framework

Laravel

### Framework version

10

### Scribe config

```ruby
When I generate docs it mentions 't get example model for ...Models\UserTerm via factoryCreate.`` in yellow as a warning. However the resulted static docs do contain the generated model data.

Any ideas?
```

### What happened?

..

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by ceejayoz** [comment]
In `php artisan tinker`, do `Models\UserTerm::factory()->create()`. Do you get an error when doing so?

**Comment by shalvah** [comment]
I think it's just an emitted warning. If you have your `examples.models_source` config looking like this, for instance: `['factoryCreate', 'factoryMake', 'databaseFirst']`, Scribe will try the next strategy if the previous one fails; that's probably why it still "works". If that's fine with you, then there's no problem.
