### ISSUE TITLE
Specific type

### ISSUE THREAD

**Issue by bernardarhia** [knuckleswtf/scribe#787]
### Scribe version

2.0.2

### Your question

So is there a way to explicitly specify the type for a body param?
Example: @bodyParam  **string:male|female** required User's Gender.
It'll come in very handy if something like that was added.

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
`Enum: `

https://scribe.knuckles.wtf/laravel/reference/annotations#bodyparambodyparam

However, I don't think that's supported in V2.
