### ISSUE TITLE
Type declaration in methods not supported

### ISSUE THREAD

**Issue by ErnestStaug** [knuckleswtf/scribe#8]
At the moment when generating documentation I am getting errors because of type declarations in my method options
![image](https://user-images.githubusercontent.com/17262977/81847095-c94c3a00-955b-11ea-93bf-32a6f541f286.png)

![image](https://user-images.githubusercontent.com/17262977/81846836-62c71c00-955b-11ea-85fe-ce15739beb1b.png)

**Comment by shalvah** [comment]
Run it again in verbose mode for a full stack trace.

**Comment by shalvah** [comment]
@ErnestStaug ? Also, have you tried this on 1.0.0-beta3?

**Comment by shalvah** [comment]
@ErnestStaug let me know if you still have this issue.
