### ISSUE TITLE
cannot install scribe

### ISSUE THREAD

**Issue by Laurino108** [knuckleswtf/scribe#801]
### Scribe version

newest

### PHP version

8.2

### Framework

Laravel

### Framework version

latest

### Scribe config

```ruby
N/A
```

### What happened?

I cannot install scribe.

Following Error is shown up:

knuckleswtf/scribe[4.14.0, ..., 4.29.0] require nikic/php-parser ^4.10 -> found nikic/php-parser[v4.10.0, ..., v4.18.0] but the package is fixed to v5.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command

### Docs

- [x] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by Laurino108** [comment]
I have seen that there was a commit #795 in this regard, but this "updated" version cannot be used. Since no new release has been "created" since then

**Comment by shalvah** [comment]
Busy with school and work nowadays, but I've tagged a new release.
