### ISSUE TITLE
Example Request buggy in Elements Theme

### ISSUE THREAD

**Issue by Laurino108** [knuckleswtf/scribe#810]
### Scribe version

4.30.1

### PHP version

8.2

### Framework

Laravel

### Framework version

latest

### Scribe config

```ruby
I don't think we need it, but please let us know if we do
```

### What happened?

The example request in the elements theme is truncated if the body is too long and only partially appears after the example response. An example can be seen in the image 

![image](https://github.com/knuckleswtf/scribe/assets/72888948/1bd35abe-87d7-44c8-8817-25efad78d1d6)

A fix would be very helpful in that regard, I think it's just a style problem here. 

Sometimes the two texts also collide with each other

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Sorry about that! Unfortunately, I can't promise any timeline for when this will be fixed, as I'm quite busy. However, if you'd like to use the `elements` theme, you can try switching type to `external_laravel`. This uses the CSS + JavaScript directly from the Elements website, so there shouldn't be any rendering issues from our side. The only difference is that the doc is fetched and rendered client-side based on your OpenAPI spec.

**Comment by Laurino108** [comment]
Alright, thanks for the fast reply, I will try this. 👌🏼
