### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by Majed6** [knuckleswtf/scribe#82]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. I ran `composer require --dev knuckleswtf/scribe ` .
2. But I saw...

```
knuckleswtf/scribe 1.4.1 requires knuckleswtf/pastel ^1.3.3 
knuckleswtf/pastel 1.3.3 requires illuminate/view ^6.0|^7.0|^8.0 
```

instead of...

Installing the package.

**Screenshots and stack traces:**
N/A

**My environment:**
 - PHP version (from `php -v`):  7.4
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show lumen/framework`): 5.8
 - Scribe version (from `composer show knuckleswtf/scribe`): 

**My Scribe config (minus the comments):**
N/A
**Additional info:**
N/A

**Comment by Majed6** [comment]
Hi,

First of all, thank you all for your efforts on scribe. I really like the package. Would it be possible to support  laravel 5.8 ? I would love to use the package on my projects but I can't due to the knuckleswtf/pastel dependency requiring a minimum of laravel 6.

**Comment by shalvah** [comment]
Sorry, man. That's a no. That would be extra maintenance burden for me. Your best bets:
1. Upgrade to L6. Laravel Shift can help automate this.
2. Fork the packages (Pastel, Scribe) and modify so they work with your Laravel version.
3. Use the older version of this package (mpociot/laravel-apidoc-generator). It's no longer maintained and lacks several features, but you might be able to make do.

**Comment by shalvah** [comment]
Hey @Majed6 I noticed the problem was actually from Pastel https://github.com/knuckleswtf/pastel/. Took a look at the deps and realised it didn't need to be 6.xminimum, so I've lowered it to 5.8. Give it a try now. I think Scribe should work.
