### ISSUE TITLE
Generating Scribe views from an openapi.yml file

### ISSUE THREAD

**Issue by medeirosinacio** [knuckleswtf/scribe#823]
### Scribe version

4.31.0

### Your question

Hello, I'm currently exploring Scribe and I'm quite impressed with the tools it offers. However, my Laravel application already has a comprehensive openapi 3.0 specification file with mappings for all routes and written examples.

I've searched, but haven't found a solution. Is there a way to generate Scribe views directly from the openapi.yml file?

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Unfortunately, no. Scribe isn't the tool for that. There are many tools out there which render OpenAPI to HTML (eg [scalar](https://github.com/scalar/scalar?tab=readme-ov-file), [elements](https://github.com/stoplightio/elements) and [rapidoc](https://github.com/rapi-doc/RapiDoc))
