### ISSUE TITLE
I have a single api endpoint that can be used to multiple thing. How can I add multiple example request.

### ISSUE THREAD

**Issue by aekanshpartani** [knuckleswtf/scribe#83]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.
I have a single function in controller and based on the api body content I trigger different things.
I want to document all of them separately. Any option from which I can achieve the same?

**Comment by shalvah** [comment]
There's no clean way to do that, I'm afraid. Your best bet is probably to manually override the generated markdown.

**Comment by shalvah** [comment]
Another option is overriding the Blade templates directly. Then you could add logic there to render multiple example requests for certain endpoints.

Summary: that use case isn't directly supported by Scribe ATM and probably won't be for a while, but Scribe is pretty hackable. With some fiddling, you can come up with something. Hope that helps.

**Comment by shalvah** [comment]
Taken note of this, though, and I'll let you know if we add anything for this scenario. 

How about having a `@markdown` annotation that points to a file that contains any extra markdown you want for the endpoint?

**Comment by aekanshpartani** [comment]
@shalvah Thanks for suggestions. Yeah it would be great feature to have something like this. As it is normal to have a single API when you are talking about messaging scenario but there can be multiple formats as in Text, Image, Video, etc. So it would help if we can display multiple example requests and body params accordingly for the endpoint.
Thanks again.
