### ISSUE TITLE
How to write multiple examples in response body?

### ISSUE THREAD

**Issue by Hao1995** [knuckleswtf/scribe#837]
### Scribe version

4.35.0

### Your question

I want to add multiple examples to the response bodies. It is mentioned by [swagger doc](https://swagger.io/docs/specification/adding-examples/#:~:text=Multiple%20examples%20in%20response%20bodies:).

```
responses:
  '200':
    description: A user object.
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/User'   # Reference to an object
        examples:
          Jessica:
            value:
              id: 10
              name: Jessica Smith
          Ron:
            value:
              id: 20
              name: Ron Stewart
``` 

Does it work on scribe?

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Hey, yes Scribe supports multiple response samples using the "scenario" field. Check out https://scribe.knuckles.wtf/laravel/documenting/responses
But I'm not sure it's exactly handled correctly in OpenAPI, since OpenAPI doesn't let you add descriptions for examples.

**Comment by Dinushasilva** [comment]
@shalvah @Hao1995 This is introduced in https://github.com/knuckleswtf/scribe/pull/855

**Comment by Hao1995** [comment]
> @shalvah @Hao1995 This is introduced in https://github.com/knuckleswtf/scribe/pull/855

Thanks your PR!!

**Comment by shalvah** [comment]
Unfortunately, that PR seems to be abandoned.
