### ISSUE TITLE
API Guide

### ISSUE THREAD

**Issue by wcostaprijo** [knuckleswtf/scribe#839]
### Scribe version

4.35

### Your question

Is it possible to create an API Guide using this library with Laravel?

[ x ] Laravel 11.x
[ x ] Scribe 4.35

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
What do you mean by an API guide?

**Comment by wcostaprijo** [comment]
An API Guide provides a comprehensive and contextual overview of the API, including detailed descriptions of concepts, step-by-step guides, usage examples, best practices, and perhaps even tutorials. This documentation is typically more focused on helping developers understand how to use the API in their own projects, providing guidance and insights on how to make the most of the API's features.

![Captura de tela de 2024-05-01 11-36-49](https://github.com/knuckleswtf/scribe/assets/54078100/b0329d9c-57db-4cf6-8109-0f006a5a4caa)

**Comment by AryaSvitkona** [comment]
@wcostaprijo You mean something like that?
https://adidas.gitbook.io/api-guidelines (see for others: https://apistylebook.com/design/guidelines/)

Well I would rather use Gitbook for that and use Scribe to generate the technical documentation :)
