### ISSUE TITLE
Always ask to remove external.html_attributes.* on scribe:generate for no reason

### ISSUE THREAD

**Issue by max13fr** [knuckleswtf/scribe#845]
### Scribe version

4.35

### PHP version

8.2.18

### Framework

Laravel

### Framework version

11.5.0

### Scribe config

```ruby
type => "external_laravel"
theme => "elements"
external.html_attributes.apiDescriptionUrl => "/docs.openapi"
external.html_attributes.basePath => "/docs"
external.html_attributes.layout => "responsive"
external.html_attributes.router => "hash"
external.html_attributes.tryItCredentialsPolicy => "same-origin"
auth.enabled => true
auth.default => true
auth.name => "Authorization"
examples.faker_seed => 666
```

### What happened?

Hello,

To use Elements, I need to set external.html_attributes, mainly to fix a current issue with laravel mode (#813) but also for some customization.

I followed the scribe documentation (https://scribe.knuckles.wtf/laravel/reference/config#external), but everytime I run `php artisan scribe:generate`, the update process ask me to remove html_attributes, it's really annoying.

I'm on new fresh install of Scribe & laravel, so need to run any update part.
Am I missing something ?

Thanks in advance,
Best regards, Max

```
✔ Wrote Laravel assets to: public/vendor/scribe/
Checking for any pending upgrades to your config file...

You're using an updated version of Scribe, which added new items to the config file.
Here are the changes:
- `external.html_attributes.apiDescriptionUrl` will be removed.
- `external.html_attributes.basePath` will be removed.
- `external.html_attributes.layout` will be removed.
- `external.html_attributes.router` will be removed.
- `external.html_attributes.tryItCredentialsPolicy` will be removed.

 Let's help you update your config file. Accept changes? (yes/no) [no]:
```

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Oh, that's an oversight. FIxing in a bit. Thanks for the repot.

**Comment by max13fr** [comment]
Thanks !
