### ISSUE TITLE
getting 401 Unauthorized in each routes where i set the middleware

### ISSUE THREAD

**Issue by codeArtisanry** [knuckleswtf/scribe#848]
### Scribe version

4.35

### Your question

Can somebody help me out? 
When I remove my middleware i can see the data and api's 
but when i add middleware it got me with 401 unauthorized

i'm using `sanctum:auth`

Below are the ways which i already tried

- 'middleware' => ['auth:*'],

- 'middleware' => ['*', 'auth:sanctum', 'auth:promoter_app', 'client:promoter_scope', 'auth:store_manager_app', 'client:store_manager_scope', 'client:e_commerce_scope', 'auth:warehouse_manager_app', 'client:warehouse_manager_scope', 'auth:admin_app', 'client:admin_scope', 'auth:cashier_app', 'client:cashier_scope', 'auth:member_app', 'client:member_scope', 'auth:api'],

- 'middleware' => ['*'],

Thanks for your help and support

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by codeArtisanry** [comment]
Also please do let me know if there's any way to bypass the middleware by writing up any rules in comments above method

**Comment by shalvah** [comment]
Hey, sorry, I missed this. Unfortunately, I don't have an answer for you, as I've never worked with Sanctum. A few folks have had issues and some have had solutions. If you still have trouble, try searching for "Sanctum" in the issues.
