### ISSUE TITLE
Extract Just openApi & Postman collection

### ISSUE THREAD

**Issue by tomsjac** [knuckleswtf/scribe#85]
Hello,

I would like to know, if it was planned to be able to extract only the openApi and/or postman collection files without the HTML version ?

to use another html viewer a bit more mordern

thx

**Comment by shalvah** [comment]
No, it's not possible. It's a simple thing to delete the HTML files after generation, though.

What HTML viewer do you plan on using?

**Comment by tomsjac** [comment]
Ok, I suspected the answer, 
but would it be possible to include it as an cmd option? a day

html viewer is https://github.com/Redocly/redoc | https://rebilly.github.io/ReDoc/

**Comment by shalvah** [comment]
> would it be possible to include it as an cmd option? a day

Currently? I doubt I'll do this. It's an easy config option, but I want to keep config options few. The main use case of this package is generating the HTML docs page, not the OpenAPI spec.

(I should mention that the OpenAPI schema has limitations which don't let it properly support some API features that Laravel/Scribe supports, so Scribe just tries to do it's best. Similarly, OpenAPI sports some things that Scribe doesn't cater for (example: authentication with OAuth), but you can add those yourself without too much trouble.)
