### ISSUE TITLE
scalar theme doesnt properly generate example and child attributes

### ISSUE THREAD

**Issue by masterbater** [knuckleswtf/scribe#852]
### Scribe version

4.35

### Your question

https://github.com/scalar/scalar/discussions/1642

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Looks like an issue with Scalar's interpretation of OpenAPI specs.

**Comment by masterbater** [comment]
I think it did properly generate the properties of array but scalar could have used the default example instead of generating per field

properties:
                readings:
                  type: array
                  description: ''
                  example:
                    - []
                  items:
                    type: object
                    properties:
                      serial:
                        type: string
                        description: ''
                        example: eos
                      manual:
                        type: boolean
                        description: ''
                        example: true
                      timezone:
                        type: string
                        description: ''
                        example: America/Costa_Rica
                      source:
                        type: string
                        description: ''
                        example: ipsa
                      value:
                        type: array
                        description: ''
                        example:
                          - 12942970.0
                        items:
                          type: number
                      device:
                        type: string
                        description: ''
                        example: modi
                      readingType:
                        type: string
                        description: ''
                        example: vero
                      date:
                        type: string
                        description: 'Must be a valid date in the format <code>Y-m-d\TH:i:sP</code>.'
                        example: '2024-05-14T06:11:08+00:00'
                    required:
                      - serial
                      - manual
                      - timezone
                      - source
                      - value
                      - device
                      - readingType
                      - date
