### ISSUE TITLE
404 Not Found on Production

### ISSUE THREAD

**Issue by muhammad-sadeeq** [knuckleswtf/scribe#860]
### Scribe version

4.37.0

### PHP version

8.2

### Framework

Laravel

### Framework version

10.0

### Scribe config

```ruby
type => "laravel"
auth.enabled => true
auth.default => true
```

### What happened?

After following the docs and generating docs using php artisan scribe:generate, the docs can be accessed by visiting /docs url on local machine. But it gives 404 not found error on visiting the /docs url on production server. The production server has all those generated files by scribe that are also present on local.

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by codespearhead** [comment]
Are you deploying it behind a reverse proxy?

**Comment by shamil8124** [comment]
if you installed scribe as a dev dependency, then the laravel routing does not work in prod. 

move it to the "require" key in composer.json vs the "require-dev" key. 

should solve it.

**Comment by shalvah** [comment]
This ^^^. Alternatively, you need to set up your own routing.

**Comment by shalvah** [comment]
I should probably add an explainer in the docs for this, but you can see an example of routing here: https://scribe.knuckles.wtf/laravel/tasks/generating#generating-multiple-docs

**Comment by shalvah** [comment]
Lol, it's actually already in the docs: https://scribe.knuckles.wtf/laravel/reference/config#laravel
![image](https://github.com/knuckleswtf/scribe/assets/14361073/a95c0b71-c7c8-4aa2-9f9b-ed1a288fa371)

**Comment by alexchirolde** [comment]
Hello, after upgrading to Laravel 11, PHP 8.2, and " knuckles wtf/scribe": "5.2," my previously declared route for docs is not working.

`Route::view('api-docs', 'scribe.index')->name('api-docs');`

It returns a white page and when inspecting the HTML is unrelated to the actual file at `scribe/index.blade.php.`

This setup used to work before the upgrade.

There are no errors when executing the generate command.

It is not working on my local environment, production, or dev. It just stopped working

Any advice??

Thxs
