### ISSUE TITLE
The package is ending with a Check Failed Error

### ISSUE THREAD

**Issue by SayedAkhtar** [knuckleswtf/scribe#865]
### Scribe version

4.37.0

### PHP version

8.2

### Framework

Laravel

### Framework version

10.48.16 

### Scribe config

```ruby
title => "Clicks & Pay API routes"
base_url => "https://sellerondc.in"
auth.in => "header"
auth.name.0 => "X-Api-Key"
auth.name.1 => "X-Api-Salt"
auth.placeholder.0 => "{YOUR_API_KEY}"
auth.placeholder.1 => "{YOUR_API_SALT}"
```

### What happened?

I am attaching a complete stack trace :

php artisan scribe:generate --verbose
ⓘ Processing route: [POST] api/v1/encrypt
✔ Processed route: [POST] api/v1/encrypt
ⓘ Processing route: [POST] api/v1/create-payment
⚠ No bodyParameters() method found in App\Http\Requests\PaymentRequest. Scribe will only be able to extract basic information from the rules() method.
✔ Processed route: [POST] api/v1/create-payment
ⓘ Processing route: [POST] api/v1/get-status
✔ Processed route: [POST] api/v1/get-status
ⓘ Processing route: [POST] api/v1/payout/encrypt
✔ Processed route: [POST] api/v1/payout/encrypt
ⓘ Processing route: [POST] api/v1/payout/request-payout
⚠ No bodyParameters() method found in App\Http\Requests\CreatePayoutRequest. Scribe will only be able to extract basic information from the rules() method.
✔ Processed route: [POST] api/v1/payout/request-payout
ⓘ Processing route: [GET] api/v1/payout/check-balance
✔ Processed route: [GET] api/v1/payout/check-balance
ⓘ Extracting intro and auth Markdown files to: .scribe
✔ Extracted intro and auth Markdown files to: .scribe
ⓘ Writing HTML docs...
✔ Wrote HTML docs and assets to: public/docs/
ⓘ Generating Postman collection
✔ Wrote Postman collection to: public/docs/collection.json
ⓘ Generating OpenAPI specification
✔ Wrote OpenAPI specification to: public/docs/openapi.yaml
Checking for any pending upgrades to your config file...
Check failed with error:

   ErrorException 

  Attempt to read property "value" on null

  at vendor/shalvah/upgrader/src/Upgrader.php:162
    158▕         // Loop over the old config
    159▕         // TODO handle cases of mixed assoc- and list array
    160▕         foreach ($userCurrentConfig as $arrayItem) {
    161▕             // @phpstan-ignore-next-line Not yet sure how to handle mixed
  ➜ 162▕             $key = $arrayItem->key->value;
    163▕             $value = $arrayItem->value;
    164▕ 
    165▕             $fullKey = $this->getFullKey($key, $rootKey);
    166▕ 

  1   vendor/shalvah/upgrader/src/Upgrader.php:162
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Attempt to read property "value" on null", "/Users/apple/Desktop/zethic/clicks_and_pay/vendor/shalvah/upgrader/src/Upgrader.php")

  2   vendor/shalvah/upgrader/src/Upgrader.php:191
      Shalvah\Upgrader\Upgrader::fetchRemovedAndMovedItems([], "auth.name")

  3   vendor/shalvah/upgrader/src/Upgrader.php:191
      Shalvah\Upgrader\Upgrader::fetchRemovedAndMovedItems("auth")

  4   vendor/shalvah/upgrader/src/Upgrader.php:86
      Shalvah\Upgrader\Upgrader::fetchRemovedAndMovedItems()

  5   vendor/shalvah/upgrader/src/Upgrader.php:61
      Shalvah\Upgrader\Upgrader::fetchChanges()

  6   vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php:183
      Shalvah\Upgrader\Upgrader::dryRun()

  7   vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php:69
      Knuckles\Scribe\Commands\GenerateDocumentation::upgradeConfigFileIfNeeded()

  8   vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
      Knuckles\Scribe\Commands\GenerateDocumentation::handle(Object(Knuckles\Scribe\Matching\RouteMatcher), Object(Knuckles\Scribe\GroupedEndpoints\GroupedEndpointsFactory))

  9   vendor/laravel/framework/src/Illuminate/Container/Util.php:41
      Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

  10  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
      Illuminate\Container\Util::unwrapIfClosure(Object(Closure))

  11  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:35
      Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))

  12  vendor/laravel/framework/src/Illuminate/Container/Container.php:662
      Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])

  13  vendor/laravel/framework/src/Illuminate/Console/Command.php:211
      Illuminate\Container\Container::call()

  14  vendor/symfony/console/Command/Command.php:326
      Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))

  15  vendor/laravel/framework/src/Illuminate/Console/Command.php:180
      Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))

  16  vendor/symfony/console/Application.php:1096
      Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

  17  vendor/symfony/console/Application.php:324
      Symfony\Component\Console\Application::doRunCommand(Object(Knuckles\Scribe\Commands\GenerateDocumentation), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

  18  vendor/symfony/console/Application.php:175
      Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

  19  vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:201
      Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

  20  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Note that this isn't a fatal error, just a warning. But it points out the mistake in your config. You have invalid config.

```
auth.name.0 => "X-Api-Key"
auth.name.1 => "X-Api-Salt"
auth.placeholder.0 => "{YOUR_API_KEY}"
auth.placeholder.1 => "{YOUR_API_SALT}"
```

`auth.name` and `auth.placeholder` are not arrays. They take a single string value.
