### ISSUE TITLE
Badges don't work with element theme

### ISSUE THREAD

**Issue by basarito** [knuckleswtf/scribe#866]
### Scribe version

4.37.0

### PHP version

8.3.6

### Framework

Laravel

### Framework version

10.48.14

### Scribe config

```ruby
'type' => 'static',
'theme' => 'elements'
```

### What happened?

I am trying to add a badge as described here: https://scribe.knuckles.wtf/laravel/reference/html#badges but it doesn't render when using `element` theme. It works when using `default` theme.

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
What does it render as?

**Comment by basarito** [comment]
@shalvah it doesn't render any style at all, just the html element. So if we add `<small class="badge">Badge</small>` as described in the docs, we'd only get the small text displayed. If you inspect the element, the `badge` class is there, but no associated style is applied.

It just looks like this:
<img width="260" alt="image" src="https://github.com/user-attachments/assets/38cb5488-7b32-4b3d-bdba-f52559d6e603">

**Comment by dvlpr91** [comment]
![image](https://github.com/user-attachments/assets/e919af5c-8a72-4c29-9d9d-0410b3d03f45)

However, if you define the CSS, it will be solved.

**Comment by shalvah** [comment]
Yeah, sorry. You have to understand that I'm not a frontend guy, and the limited time I have will be spent on maintenance and improvements in generation, not presentation.
