### ISSUE TITLE
Theme Dark Mode Support

### ISSUE THREAD

**Issue by thomasfw** [knuckleswtf/scribe#869]
### Scribe version

4.37.1

### Your question

It would be nice to have a dark theme available. Dark mode for the elements theme could be activated by adding the `<html data-theme="dark">` attribute (see [Dark Mode Option [Design] #1439](https://github.com/stoplightio/elements/issues/1439#issuecomment-1766406108)).

Currently, its only possible to enable this by publishing the package's blade templates and modifying `resources/views/scribe/themes/elements/index.blade.php`, which I'd like to avoid.

For now, i've got around this by adding a hacky middleware to modify scribe's html before it's rendered, as there are only a few tweaks required to enable dark mode. I've included it below in case anyone finds it useful. It can be enabled by registering as middleware in scribe's config (under `laravel.middleware`). 

Looking ahead though, would it be feasible to add a dark mode toggle UI? Or maybe just add a separate `elements-dark` theme?

```php
<?php // app/Http/Middleware/ScribeDarkModeSupport.php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Intercept the scribe HTML response to add dark mode and other customisations.
 * https://github.com/knuckleswtf/scribe/issues/869
 */
class ScribeDarkModeSupport
{
    /** The scribe theme to target */
    protected string $targetScribeTheme = 'elements';

    /** Enforce dark mode */
    protected bool $useDarkMode = true;

    /** https://highlightjs.org/examples */
    protected string $hljsTheme = 'github-dark';

    /**
     * Handle an incoming request.
     *
     * @param  \Closure(\Illuminate\Http\Request): (\Symfony\Component\HttpFoundation\Response)  $next
     */
    public function handle(Request $request, Closure $next): Response
    {
        $response = $next($request);
        if ('scribe' != $request->route()->getName() || $this->targetScribeTheme != config('scribe.theme')) {
            return $response;
        }

        $html = $response->getContent();

        if ($this->hljsTheme) {
            $html = str_replace('/styles/docco.min.css', '/styles/'.str_replace('-min', '', $this->hljsTheme).'.min.css', $html);
        }

        // See: https://github.com/stoplightio/elements/issues/1439#issuecomment-1766406108
        if ($this->useDarkMode) {
            $html = str_replace('<html', '<html data-theme="dark"', $html);
        }

        $inject_css = '';
        if ($this->useDarkMode) {
            // Background colour fix:
            $inject_css .= '.sl-elements > div:not(#sidebar) { background: transparent; }';
            $inject_css .= 'body { background: #141c28; }';
            // Select input fix:
            $inject_css .= 'select { background: transparent; }';
        }
        $html = str_replace('</head>', '<style>'.$inject_css.'</style></head>', $html);

        $response->setContent($html);
        return $response;
    }
}
```

Register the middleware:

```php
<?php // config/scribe.php

return [
    'type' => 'laravel',
    'laravel' => [
        'middleware' => [
            \App\Http\Middleware\ScribeDarkModeSupport::class,
        ],
    ],
],
```

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Yeah, there's likely a zero chance of my adding that, as I don't mess with the UI anymore. Btw, I recommend people use the `external_static` or `external_laravel` doc types, as that allows you to use the UI directly from the Elements site (or yours), rather than my naive attempts to replicate it.
https://scribe.knuckles.wtf/laravel/reference/config#theme
