### ISSUE TITLE
@urlParam is not respecting the example given

### ISSUE THREAD

**Issue by TheRed002** [knuckleswtf/scribe#87]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
I've been trying to auto-generate responses for my documentation by providing examples to each parameter that correlates to actual values in the database. Currently, I was working on the "show" method of a simple CRUD controller. As I was using UUID as my primary key, so I provided an example UUID value that does exist in the database. But scribe is not taking that value or any other value but 1. 

**Screenshots and stack traces:**
***Output***
![image](https://user-images.githubusercontent.com/1557123/92066538-91dbf480-edbb-11ea-8f53-b5ff5706c019.png)

***Controller method***
```
    /**
     * Get data of a user
     * @urlParam id required The id of the user. Example: 90f2540f-fb80-4e92-a786-3954dba53e0b
     * 
     */

    public function show($id)
    {

        $item = $this->repository->get($id);
        return  successResponse(new UserResource($item));
    }
```
**My environment:**
 - PHP version (from `php -v`): 
 - Laravel
 -  v7.27.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 1.4.1

**Additional info:**

**Comment by shalvah** [comment]
It looks like you're using Laravel's auto created routes (`resource()`, maybe?), because I can see your path is /user/{user}. But you're using `id` in your code and annotations. Try using the same parameter name.

**Comment by shalvah** [comment]
Gonna go ahead and assume that was the problem...
