### ISSUE TITLE
Create schema in components

### ISSUE THREAD

**Issue by laudaikinhdi** [knuckleswtf/scribe#876]
### Scribe version

v4.37.1

### Your question

Can I create components in OpenApi?
Docs: https://swagger.io/docs/specification/components/

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Hmmm... No you can't. In theory, it could be possible to add support for this, but it would be pretty tricky, as it would require Scribe to make some decisions as to what represents what. Unlikely.
