### ISSUE TITLE
Why do we url-encode  query params when creating a postman collection?

### ISSUE THREAD

**Issue by iamafasha** [knuckleswtf/scribe#877]
### Scribe version

4.33.0

### Your question

So I am using laravel purity in a project and sometimes I need to generate a collection with endpints like this.

```
GET /api/posts?filters[title][$contains]=Purity
```

But then when I try to document my project like this 
```
...
* @queryParam filters[title][$contains] string.
...
```

I end up with URL-encoded query params in Postman i.e

```
filters%5Btitle%5D%5B%24contains%5D
```

Is there a special reason why we URL-encode them?

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Yeah, I think it breaks something when you don't. Sorry, I can't remember the details, but you could try to dig through the Git history.
