### ISSUE TITLE
parse exists rules

### ISSUE THREAD

**Issue by lotfimostafa** [knuckleswtf/scribe#882]
### Scribe version

4.37.1

### Your question

Hey,

I noticed that the **exists** rule isn't currently handled in the parseRule switch case within the ParsesValidationRules trait. This rule seems like it **could be added easily**.

Is there a particular reason why it hasn’t been included?

Thanks!

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Dunno, PR welcome!
