### ISSUE TITLE
Separate source code from documentation

### ISSUE THREAD

**Issue by roke22** [knuckleswtf/scribe#885]
### Scribe version

4.3

### Your question

Hello,
We want to separate the source code from the documentation, would it be possible to put all the source code in a src folder and then all the documentation in the doc folder?
Some controllers are very long with the documentation and the idea is to have all this divided so as not to have files of 1000 lines.
We know that response can be put outside but can be done for all documentation.
For example:

MyController.php
```php
/*
 * @doc doc/MyControllerDocumentation.php
 * /
 public function myEndpoint()
``` 

So all the documentation is in MyControllerDocumentation.php

Thank you.

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
I...don't have a solution for you right now, sorry. It's just not on the roadmap. I'd encourage you to build a wrapper yourself? Scribe is pretty extensible, so it should be possible to do what you need. You can always make PRs or ask questions if you need more flexibility. Gonna close this now, sorry.
