### ISSUE TITLE
generate php docs array of object

### ISSUE THREAD

**Issue by mbehzad-bhz** [knuckleswtf/scribe#889]
### Scribe version

^4.37

### PHP version

^8.2

### Framework

Laravel

### Framework version

^11.9

### Scribe config

```ruby
<?php

use Knuckles\Scribe\Extracting\Strategies;

return [
    'title' => 'API Documentation',
    'description' => 'Supplier Panel.',
    'base_url' => null,
    'routes' => [
        [
            'match' => [
                'prefixes' => ['api/supplier_panel/*'],
                'domains' => ['*'],
                'versions' => ['v1'],
            ],
            'include' => [],
            'exclude' => [

            ],
        ],
    ],
    'type' => 'static',
    'theme' => 'default',
    'static' => [
        'output_path' => 'public/docs/supplier',
    ],
    'laravel' => [
        'add_routes' => true,
        'docs_url' => '/docs/admin',
        'assets_directory' => null,
        'middleware' => [],
    ],
    'try_it_out' => [
        'enabled' => true,
        'base_url' => null,
        'use_csrf' => false,
        'csrf_url' => '/sanctum/csrf-cookie',
    ],
    'auth' => [
        'enabled' => true,
        'default' => false,
        'in' => 'bearer',
        'name' => 'key',
        'use_value' => env('SCRIBE_AUTH_KEY'),
        'placeholder' => '{YOUR_AUTH_KEY}',
        'extra_info' => 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.',
    ],
    'intro_text' => <<<INTRO
This documentation aims to provide all the information you need to work with our API.

<aside>As you scroll, you'll see code examples for working with the API in different programming languages in the dark area to the right (or as part of the content on mobile).
You can switch the language used with the tabs at the top right (or from the nav menu at the top left on mobile).</aside>
INTRO,
    'example_languages' => ['bash', 'javascript'],
    'postman' => ['enabled' => true, 'overrides' => []],
    'openapi' => ['enabled' => true, 'overrides' => []],
    'groups' => ['default' => 'Endpoints', 'order' => []],
    'logo' => false,
    'last_updated' => 'Last updated: {date:F j, Y}',
    'examples' => ['faker_seed' => null, 'models_source' => ['factoryCreate', 'factoryMake', 'databaseFirst']],
    'strategies' => [
        'metadata' => [Strategies\Metadata\GetFromDocBlocks::class, Strategies\Metadata\GetFromMetadataAttributes::class],
        'urlParameters' => [Strategies\UrlParameters\GetFromLaravelAPI::class, Strategies\UrlParameters\GetFromUrlParamAttribute::class, Strategies\UrlParameters\GetFromUrlParamTag::class],
        'queryParameters' => [Strategies\QueryParameters\GetFromFormRequest::class, Strategies\QueryParameters\GetFromInlineValidator::class, Strategies\QueryParameters\GetFromQueryParamAttribute::class, Strategies\QueryParameters\GetFromQueryParamTag::class],
        'headers' => [Strategies\Headers\GetFromHeaderAttribute::class, Strategies\Headers\GetFromHeaderTag::class, ['override', ['Content-Type' => 'application/json', 'Accept' => 'application/json']]],
        'bodyParameters' => [Strategies\BodyParameters\GetFromFormRequest::class, Strategies\BodyParameters\GetFromInlineValidator::class, Strategies\BodyParameters\GetFromBodyParamAttribute::class, Strategies\BodyParameters\GetFromBodyParamTag::class],
        'responses' => [Strategies\Responses\UseResponseAttributes::class, Strategies\Responses\UseTransformerTags::class, Strategies\Responses\UseApiResourceTags::class, Strategies\Responses\UseResponseTag::class, Strategies\Responses\UseResponseFileTag::class, [Strategies\Responses\ResponseCalls::class, ['only' => ['GET *']]]],
        'responseFields' => [Strategies\ResponseFields\GetFromResponseFieldAttribute::class, Strategies\ResponseFields\GetFromResponseFieldTag::class],
    ],
//    'database_connections_to_transact' => [config('database.default')],
    'database_connections_to_transact' => [],
    'fractal' => ['serializer' => null],
    'routeMatcher' => \Knuckles\Scribe\Matching\RouteMatcher::class,
    'external' => ['html_attributes' => []],
];
```

### What happened?

this is my php doc for endpoint that has request socialMedias with type and link in every object of array :
`/**
     * Send Supplier Request - Step 1
     *
     * This endpoint allows a supplier user to submit the first step of a request to create or update a supplier profile. It includes supplier details such as name, brand name, description, social media links, and files (thumb and brand logo).
     *
     * @bodyParam name string required The supplier's name. Example: My Supplier
     * @bodyParam brandName string required The brand's name. Example: My Brand
     * @bodyParam description string required A brief description of the supplier. Example: Leading supplier of organic products.
     * @bodyParam text string required Detailed information about the supplier. Example: We specialize in organic and eco-friendly products.
     * @bodyParam thumb file required A thumbnail image of the supplier.
     * @bodyParam brandLogo file required The brand's logo.
     * @bodyParam socialMedias array required A list of social media links for the supplier. Each item in the array should contain a `link` and `type`.
     * @bodyParam socialMedias[].link string required A valid social media URL. Example: https://instagram.com/mybrand
     * @bodyParam socialMedias[].type string required The type of social media (must be one of the allowed types). Example: INSTAGRAM
     *
     * Example request:
     * [
     *   {
     *     "type": "INSTAGRAM",
     *     "link": "https://instagram.com/mybrand"
     *   },
     *   {
     *     "type": "FACEBOOK",
     *     "link": "https://facebook.com/mybrand"
     *   }
     * ]
     *
     * @response 200 {
     *   "data": {
     *     "token": "abcdef123456"
     *   },
     *   "message": "Store operation successful."
     * }
     */`
     and this is my screen shot of swagger :
     
![image](https://github.com/user-attachments/assets/dbbff319-eee9-438e-bf59-6474ea563f24)

and curl is :
curl -X 'POST' \
  'https://example.com/api/supplier_request/sendRequest' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'name=My Supplier' \
  -F 'brandName=My Brand' \
  -F 'description=Leading supplier of organic products.' \
  -F 'text=We specialize in organic and eco-friendly products.' \
  -F 'thumb=@3.jpeg;type=image/jpeg' \
  -F 'brandLogo=@3.jpeg;type=image/jpeg' \
  -F 'socialMedias=string'
  
  it should be somthing like this :
  curl -X 'POST' \
  'https://example.com/api/supplier_panel/supplier_request/sendRequest' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'name=My Supplier' \
  -F 'brandName=My Brand' \
  -F 'description=Leading supplier of organic products.' \
  -F 'text=We specialize in organic and eco-friendly products.' \
  -F 'thumb=@3.jpeg;type=image/jpeg' \
  -F 'brandLogo=@3.jpeg;type=image/jpeg' \
  -F 'socialMedias[0][type]=INSTAGRAM' \
  -F 'socialMedias[0][link]=https://instagram.com/mybrand' \
  -F 'socialMedias[1][type]=FACEBOOK' \
  -F 'socialMedias[1][link]=https://facebook.com/mybrand'
     
  would anyone be so kind as to respond to my question, please?

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Try using `@bodyParam socialMedias object[]` instead of `@bodyParam socialMedias array`.

See the examples in the docs. https://scribe.knuckles.wtf/laravel/documenting/query-body-parameters#arrays-of-objects

**Comment by mbehzad-bhz** [comment]
my updated code is :
`/**
     * Send a request to store supplier data.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @bodyParam name string required The supplier's name. Example: Acme Corp
     * @bodyParam brandName string required The supplier's brand name. Example: Acme
     * @bodyParam description string required A description of the supplier, max 900 characters. Example: Leading provider of industrial tools.
     * @bodyParam text string required The supplier's text content. Example: We provide top quality industrial tools.
     * @bodyParam thumb file required A thumbnail image of the supplier.
     * @bodyParam brandLogo file required A logo image of the supplier's brand.
     * @bodyParam socialMedias object[] List of social media links. Example: [{"link": "https://twitter.com/acme" , "type": "twitter"}]
     * @bodyParam socialMedias[].link string The URL of a social media account, max 900 characters. Example: https://twitter.com/acme
     * @bodyParam socialMedias[].type string The type of social media, must be a valid type. Example: twitter
     *
     * @response 200 {
     *   "token": "12bde6b0-68fc-44f5-bd30-2877e5c46b13",
     *   "message": "Store successful"
     * }
     *
     * @response 422 {
     *   "errors": [
     *      "The name field is required.",
     *      "The brandName field is required."
     *   ]
     * }
     *
     * @response 500 {
     *   "error": "Internal Server Error"
     * }
     */`
     got error :
     `   Illuminate\View\ViewException 

  Object of class stdClass could not be converted to string (View: /home/tenetup-coreccconcept/htdocs/coreccconcept.tenetup.com/vendor/knuckleswtf/scribe/resources/views/partials/example-requests/bash.md.blade.php) (View: /home/tenetup-coreccconcept/htdocs/coreccconcept.tenetup.com/vendor/knuckleswtf/scribe/resources/views/themes/default/endpoint.blade.php) (View: /home/tenetup-coreccconcept/htdocs/coreccconcept.tenetup.com/vendor/knuckleswtf/scribe/resources/views/themes/default/endpoint.blade.php) (View: /home/tenetup-coreccconcept/htdocs/coreccconcept.tenetup.com/vendor/knuckleswtf/scribe/resources/views/themes/default/endpoint.blade.php)

  at storage/framework/views/5900fb6d077d8febac4c0ce79edd567a.php:16
     12▕ <?php endif; ?>
     13▕ <?php if($endpoint->hasFiles() || (isset($endpoint->headers['Content-Type']) && $endpoint->headers['Content-Type'] == 'multipart/form-data' && count($endpoint->cleanBodyParameters))): ?>
     14▕ <?php $__currentLoopData = $endpoint->cleanBodyParameters; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $parameter => $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
     15▕ <?php $__currentLoopData = u::getParameterNamesAndValuesForFormData($parameter, $value); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $actualValue): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
  ➜  16▕     --form "<?php echo "$key=".$actualValue; ?>"<?php if(!($loop->parent->last) || count($endpoint->fileParameters)): ?>\
     17▕ <?php endif; ?>
     18▕ <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
     19▕ <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
     20▕ <?php $__currentLoopData = $endpoint->fileParameters; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $parameter => $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>

      +1 vendor frames 

  2   storage/framework/views/5900fb6d077d8febac4c0ce79edd567a.php:16
      Illuminate\View\ViewException::("Object of class stdClass could not be converted to string (View: /home/tenetup-coreccconcept/htdocs/coreccconcept.tenetup.com/vendor/knuckleswtf/scribe/resources/views/partials/example-requests/bash.md.blade.php) (View: /home/tenetup-coreccconcept/htdocs/coreccconcept.tenetup.com/vendor/knuckleswtf/scribe/resources/views/themes/default/endpoint.blade.php) (View: /home/tenetup-coreccconcept/htdocs/coreccconcept.tenetup.com/vendor/knuckleswtf/scribe/resources/views/themes/default/endpoint.blade.php)")
      +1 vendor frames 

  4   storage/framework/views/5900fb6d077d8febac4c0ce79edd567a.php:16
      Illuminate\View\ViewException::("Object of class stdClass could not be converted to string (View: /home/tenetup-coreccconcept/htdocs/coreccconcept.tenetup.com/vendor/knuckleswtf/scribe/resources/views/partials/example-requests/bash.md.blade.php) (View: /home/tenetup-coreccconcept/htdocs/coreccconcept.tenetup.com/vendor/knuckleswtf/scribe/resources/views/themes/default/endpoint.blade.php)")
`

**Comment by mbehzad-bhz** [comment]
@shalvah i just change the library code and its fixed now , the below files its changed:

- vendor/knuckleswtf/scribe/resources/views/partials/example-requests/javascript.md.blade.php

`
@php
    use Knuckles\Scribe\Tools\WritingUtils as u;
    /** @var  Knuckles\Camel\Output\OutputEndpointData $endpoint */
@endphp
```bash
curl --request {{$endpoint->httpMethods[0]}} \
    {{$endpoint->httpMethods[0] == 'GET' ? '--get ' : ''}}"{!! rtrim($baseUrl, '/') !!}/{{ ltrim($endpoint->boundUri, '/') }}@if(count($endpoint->cleanQueryParameters))?{!! u::printQueryParamsAsString($endpoint->cleanQueryParameters) !!}@endif"@if(count($endpoint->headers)) \
@foreach($endpoint->headers as $header => $value)
    --header "{{$header}}: {{ addslashes($value) }}"@if(! ($loop->last) || ($loop->last && count($endpoint->bodyParameters))) \
@endif
@endforeach
@endif
@if($endpoint->hasFiles() || (isset($endpoint->headers['Content-Type']) && $endpoint->headers['Content-Type'] == 'multipart/form-data' && count($endpoint->cleanBodyParameters)))
@foreach($endpoint->cleanBodyParameters as $parameter => $value)
@foreach(u::getParameterNamesAndValuesForFormData($parameter, $value) as $key => $actualValue)
    --form "{!! "$key=".(is_object($actualValue) ? json_encode($actualValue) : $actualValue) !!}"@if(!($loop->parent->last) || count($endpoint->fileParameters))\
@endif
@endforeach
@endforeach
@foreach($endpoint->fileParameters as $parameter => $value)
@foreach(u::getParameterNamesAndValuesForFormData($parameter, $value) as $key => $file)
    --form "{!! "$key=@".$file->path() !!}" @if(!($loop->parent->last))\
@endif
@endforeach
@endforeach
@elseif(count($endpoint->cleanBodyParameters))
@if ($endpoint->headers['Content-Type'] == 'application/x-www-form-urlencoded')
    --data "{!! http_build_query($endpoint->cleanBodyParameters, '', '&') !!}"
@else
    --data "{!! addslashes(json_encode($endpoint->cleanBodyParameters, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) !!}"
@endif
@endif

```

`

- vendor/knuckleswtf/scribe/resources/views/partials/example-requests/bash.md.blade.php
`
@php
    use Knuckles\Scribe\Tools\WritingUtils as u;
    /** @var  Knuckles\Camel\Output\OutputEndpointData $endpoint */
@endphp
```javascript
const url = new URL(
    "{!! rtrim($baseUrl, '/') !!}/{{ ltrim($endpoint->boundUri, '/') }}"
);
@if(count($endpoint->cleanQueryParameters))

const params = {!! u::printQueryParamsAsKeyValue($endpoint->cleanQueryParameters, "\"", ":", 4, "{}") !!};
Object.keys(params)
    .forEach(key => url.searchParams.append(key, params[key]));
@endif

@if(!empty($endpoint->headers))
const headers = {
@foreach($endpoint->headers as $header => $value)
    "{{$header}}": "{{$value}}",
@endforeach
@empty($endpoint->headers['Accept'])
    "Accept": "application/json",
@endempty
};
@endif

@if($endpoint->hasFiles() || (isset($endpoint->headers['Content-Type']) && $endpoint->headers['Content-Type'] == 'multipart/form-data' && count($endpoint->cleanBodyParameters)))
const body = new FormData();
@foreach($endpoint->cleanBodyParameters as $parameter => $value)
@foreach( u::getParameterNamesAndValuesForFormData($parameter, $value) as $key => $actualValue)
    body.append('{!! $key !!}', '{!! is_object($actualValue) || is_array($actualValue) ? json_encode($actualValue) : addslashes($actualValue) !!}');
@endforeach
@endforeach
@foreach($endpoint->fileParameters as $parameter => $value)
@foreach( u::getParameterNamesAndValuesForFormData($parameter, $value) as $key => $file)
body.append('{!! $key !!}', document.querySelector('input[name="{!! $key !!}"]').files[0]);
@endforeach
@endforeach
@elseif(count($endpoint->cleanBodyParameters))
@if ($endpoint->headers['Content-Type'] == 'application/x-www-form-urlencoded')
let body = "{!! http_build_query($endpoint->cleanBodyParameters, '', '&') !!}";
@else
let body = {!! json_encode($endpoint->cleanBodyParameters, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) !!};
@endif
@endif

fetch(url, {
    method: "{{$endpoint->httpMethods[0]}}",
@if(count($endpoint->headers))
    headers,
@endif
@if($endpoint->hasFiles() || (isset($endpoint->headers['Content-Type']) && $endpoint->headers['Content-Type'] == 'multipart/form-data' && count($endpoint->cleanBodyParameters)))
    body,
@elseif(count($endpoint->cleanBodyParameters))
@if ($endpoint->headers['Content-Type'] == 'application/x-www-form-urlencoded')
    body,
@else
    body: JSON.stringify(body),
@endif
@endif
}).then(response => response.json());
```

`
`the changes is only about $actualValue 
@foreach( u::getParameterNamesAndValuesForFormData($parameter, $value) as $key => $actualValue)
    body.append('{!! $key !!}', '{!! is_object($actualValue) || is_array($actualValue) ? json_encode($actualValue) : addslashes($actualValue) !!}');
@endforeach`
and 
`--form "{!! "$key=".(is_object($actualValue) ? json_encode($actualValue) : $actualValue) !!}"@if(!($loop->parent->last) || count($endpoint->fileParameters))\`

**Comment by shalvah** [comment]
hey, to format your multiline code snippets correctly in Markdown use 3x backticks (```). So do:

&#96;&#96;&#96;
this is 
multiple lines
&#96;&#96;&#96;

and you'll get:

```
this is 
multiple lines
```

Don't do

&#96;this is
multiple lines&#96;

because you'll get:

`this is
multiple lines`

which makes it harder to read your code
