### ISSUE TITLE
How to override config for all strategies (eg: set locale)

### ISSUE THREAD

**Issue by max13fr** [knuckleswtf/scribe#898]
### Scribe version

4.37.2

### Your question

Hello,

I have `APP_LOCALE=fr` set in .env file.
When I generate my scribe documentation, I have validations rules from FormRequest in french and I would like to get them in english.

I didn't find any solution (in config, doc & issues) to override config parameters (here app.locale) globally to all strategies. Did I missed something ?

I tried to replicate the Strategies\Responses\ResponseCalls specific case on Strategies\BodyParameters\GetFromFormRequest but without success : 

```php
    'strategies' => [
        'bodyParameters' => [
            [
                Strategies\BodyParameters\GetFromFormRequest::class,
                [
                    // try to set locale to english for scribe generation (mainly for validations rules)
                    'config' => [
                        'app.locale' => 'en',
                        'app.fallback_locale' => 'fr',
                    ],
                ],
            ],
            Strategies\BodyParameters\GetFromInlineValidator::class,
            Strategies\BodyParameters\GetFromBodyParamAttribute::class,
            Strategies\BodyParameters\GetFromBodyParamTag::class,
        ],
```

Thanks in advance and for this awesome tool.

Best regards, Max

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
Hmmm, are you certain the locale isn't being used? Tried the .env.docs file?
https://scribe.knuckles.wtf/laravel/tasks/generating#customising-the-environment

**Comment by max13fr** [comment]
Hello,

Ah thanks I didn't find that.
The only downside of this solution is that we can sometimes forget to select the correct env file when running the command.

An option in the config file that allow to override config variables globally in config/scribe.php would be awesome.

Best regards,
Max

**Comment by shalvah** [comment]
You can also use Scribe::bootstrap() for that. https://scribe.knuckles.wtf/laravel/hooks

Additions to the config file are reserved for very important features that can't be done any way else. Might be a nice feature here, but maybe in future.
