### ISSUE TITLE
How to make it work with Oracle DB

### ISSUE THREAD

**Issue by tsndp** [knuckleswtf/scribe#91]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

With DB_CONNECTION=oracle; Doc generate function is not working, just freezing, no logs in laravel. When i remove connection string in DB then its wokring.

I have added 
    'continue_without_database_transactions' => [
        \Yajra\Oci8\Oci8Connection::class
    ],
also tried         \Yajra\Oci8\Oci8Connection\OracleConnector::class

auth.enable = false

Can someone please help me with this.

**Comment by shalvah** [comment]
This will take some more debugging. Do you need to use the response calls feature? Because if not, you can comment out the ResponseCalls class in your config and try again. Let me know if that works, so we can narrow down the problem.

**Comment by tsndp** [comment]
Thanks it worked after commenting ResponseCalls (I maynot need it as of now). Im trying to populate documentation with oracle database, all the other settings are almost default. I doubt oracle transaction are not working exaclty as mysql.

**Comment by shalvah** [comment]
My guess is that the Oracle driver's beginTransaction() method never ends. You can debug it further by adding some logging around there (see https://github.com/knuckleswtf/scribe/blob/master/src/Extracting/DatabaseTransactionHelpers.php#L22).

**Comment by danilopolani** [comment]
Note: I'm using Laravel8 and I was having problems with database transactions (but I'm using MySQL driver, Idk why it happens) and to completely disable DB interactions I had to comment also:

- `\Knuckles\Scribe\Extracting\Strategies\Responses\UseTransformerTags::class`
- `\Knuckles\Scribe\Extracting\Strategies\Responses\UseApiResourceTags::class`
- `\Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls::class` (as previously mentioned)

**Comment by shalvah** [comment]
I recommend you guys try out the latest version. Shouldn't be experiencing those same problems.

Can't speak for the Oracle DB issue though. I doubt I'll be able to fix that.
