### ISSUE TITLE
HIde or exclude PATCH method

### ISSUE THREAD

**Issue by sisparkdev** [knuckleswtf/scribe#910]
### Scribe version

4.36

### Your question

there is a option to hide patch method in docs for laravel route::resource?

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by amabilee** [comment]
If you need to keep using `Route::resource` and just want to hide the `PATCH` method in Scribe documentation, you can customize the Scribe configuration in your `config/scribe.php` configuration file.

**Comment by sisparkdev** [comment]
What's the section where I can customize method to hide?

**Comment by amabilee** [comment]
You can write something like this:
```
'routes' => [
    'exclude' => [ 
        'api/*/patch', 
    ],
 ],
```

**Comment by shalvah** [comment]
You can try something like this:

```php
'routes' => [
    'exclude' => [ 
        'PATCH /api/your-endpoint', 
    ],
 ],
```

But I can't guarantee that it won't exclude the PUT version as well. It's really not Scribe's concern; we're just using what Laravel reports to us. Using `Route::resource` or similar means that both PUT and PATCH are supported. You can adjust your route definition to declare only the ones you want.
