### ISSUE TITLE
docs rules for rule : "confirmed" in password rules

### ISSUE THREAD

**Issue by Nguemoue** [knuckleswtf/scribe#914]
### Scribe version

4.2

### Your question

when using rules confirmed in password field name `password` scribe not automatically append a `field_confirmation`  

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
The `confirmed` rule isn't supported - list of supported rules is [here](https://scribe.knuckles.wtf/laravel/documenting/query-body-parameters#supported-validation-rules). You can send in a PR if you want support, but I don't think I'll accept it, as password confirmation is usually not an API thing.

**Comment by J5Dev** [comment]
I know this is closed, but wanted to add a solution for those who may land here given this is the top search result, and the topic has come up a few times now... the reason we have this in our API (for reference), is tobe able to offer a user to update their password 'in-app', and as such want it confirmed, however we also use the confirmed validation rule for numerous other fields across our site to ensure valid input of critical fields, and while we do validate them in our local app, its good practice to secure your app at all points as we all know ;)

This solution is written using a form request but should be easy enough to translate to inline validation as well, and works by not using the 'confirmed' helper rule, and manually setting up the '_confirmation' field manually, and having it use the 'same' rule against the field it needs to match.

PasswordUpdateFormRequest.php
```php
public function rules(): array
{
    return [
        'password' => [
            'required',
            'min:' . config('auth.password_length_min'),
        ],
        'password_confirmation' => [
            'required',
            'same:password',
        ],
    ];
}

public function bodyParameters(): array
{
    return [
        'password' => [
            'description' => 'The new password',
            'example' => 'Htg48!dU6Gba.45',
        ],
        'password_confirmation' => [
            'description' => 'The new password again, to confirm correct entry',
            'example' => 'Htg48!dU6Gba.45',
        ],
    ];
}
```

**Comment by KeironLowe** [comment]
To add to this, it absolutely should be validated on the API, it's best practice not to leave validation to the client.
