### ISSUE TITLE
Is it possible to add @operationId prop for each methods

### ISSUE THREAD

**Issue by mandado** [knuckleswtf/scribe#919]
### Scribe version

4.38.0

### Your question

Is it possible to add an **operationId attribute** to define the value of operation without updating the summary?

Another idea might be to add it as a named parameter on the **Endpoint attribute**.

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by BUBLET** [comment]
Yeah u can totally add an ```operationId``` without messing with the ```summary```. Just use the ```OperationId``` named parameter in the ``Endpoint``` attribute. Check it out:

```
using Scribe.Attributes;

public class MyController : ControllerBase
{
    [Endpoint("GET", "/api/myendpoint", OperationId = "GetCustomOperationId")]
    public IActionResult MyAction()
    {
        // Your action logic here
        return Ok();
    }
}
```

**Comment by shalvah** [comment]
Someone has asked this before...my answer's still the same: https://github.com/knuckleswtf/scribe/issues/540
