### ISSUE TITLE
Laravel 8.x compatibility

### ISSUE THREAD

**Issue by shalvah** [knuckleswtf/scribe#92]
Laravel 8 is getting released tomorrow, and the package hasn't been updated or tested specifically for that. I'm quite busy these days, so it might take a while to get to it. I'd appreciate any good PR sent in. Don't forget to update dependencies properly (composer.json and composer.dingo.json) and the CI config.

**Comment by Jurager** [comment]
Added request, seems all to be working flawlessly #93

**Comment by 3robi-vollebregt** [comment]
werk niet

**Comment by sunil-vr-k** [comment]
how to get this package to work with laravel 8? i get composer error

`Problem 1
    - Installation request for knuckleswtf/scribe ^1.6 -> satisfiable by knuckleswtf/scribe[1.6.0].
    - Conclusion: remove laravel/framework v8.1.0
    - Conclusion: don't install laravel/framework v8.1.0
    - knuckleswtf/scribe 1.6.0 requires illuminate/routing ^5.8|^6.0|^7.0 -> satisfiable by illuminate/routing[5.8.x-dev`

**Comment by shalvah** [comment]
I'm guessing the latest release (1.6.0) works on Laravel 8 now...
