### ISSUE TITLE
OpenAPI link within docs shows empty object

### ISSUE THREAD

**Issue by robtesch** [knuckleswtf/scribe#95]
Hey @shalvah , sorry for not following the template. I know exactly what the issue is here.

In the generated docs, we get a link: ``View OpenAPI (Swagger) Spec``.

If we click that, we get taken to ``\Knuckles\Scribe\Http\Controller::openapi``

Then there is an attempt to respond in the same way as the postman json collection, by json decoding a yaml file, and then re-encoding it as a json response.

This leads to an empty json object as a response, when in fact the underlying ``openapi.yaml`` file does exist and is populated properly.

A couple of solutions here:

1) We use Symfony's Yaml component to first convert the yaml to php array, then give the response as json, like so:

```
use Symfony\Component\Yaml\Yaml;

class Controller
{
...
public function openapi()
    {
        return response()->json(
            Yaml::parse(
                Storage::disk('local')
                       ->get('scribe/openapi.yaml')
            )
        );
    }
}
```

2) We convert this endpoint into a file download endpoint instead of a json endpoint, like so:

```
    public function openapi()
    {
        return response()->download(storage_path('app/scribe/openapi.yaml'), 'openapi.yaml', ['Content-Type' => 'application/x-yaml']);
    }
```

3) For consistency we convert both postman and openapi endpoints to file download types.

I am happy to submit a PR if you have a preferred approach.

Kind regards,

Rob

**Comment by shalvah** [comment]
Whoops. We should not be JSONing that file, just returning the file contents. I personally don't like forcing downloads because sometimes I just want to inspect a file's contents in my browser. So yeah, just read the file and output with the correct June type.

**Comment by robtesch** [comment]
@shalvah thanks for looking into it. Let me know if you want me to do a PR. I messed around a little with doing a plain YAML response (non-download) but I wasn't really getting the right looking result. Likely I was doing something wrong as I don't really work with YAML too often (and have never used it in the context of a laravel response) but I'm sure I could get something to work if you like.

**Comment by shalvah** [comment]
Sure, send in a PR.

It shouldn't be tough. It's in a file, so basically you read the contents of the file and send it as the response. I think Laravel should even have a helper that makes that easier.

**Comment by robtesch** [comment]
Thanks, I'll give it a go and submit ASAP.
