### ISSUE TITLE
Feature Request: Sort endpoints within groups alphabetically (by title)

### ISSUE THREAD

**Issue by robtesch** [knuckleswtf/scribe#99]
Hi @shalvah , this is a low importance feature request, but it would potentially help organise things.

In my case I use the grouping feature, but I actually have a bunch of sub-groups. For example:

Group: **Entities**
SubGroups: _Teams, Groups, Users_

Group: **Tools**
SubGroups: _Alerts, Settings, Profile_

etc etc.

I currently manage this by starting the tiles of each endpoint with the "SubGroup" name. So for example: _Teams_ - Add, _Teams_ - Delete, _Teams_ - Edit.

While most of these end up being sorted correctly, some end up being all over the place, making it hard for end users to reason about the API.

Is this something you would be interested in doing at some point? I would be happy to try and dive into the code and do this if it's something you are interested in or see value in.

Thanks again for this awesome library.

Kind regards,

Rob

**Comment by shalvah** [comment]
Hmm. This is complex. Right now, they're sorted in the order in which they were delivered by Laravel's router, which is probably the order in which they were registered. I'm working on something for v2 that should allow you sort as you wish. In the meantime, I think you can change the order by changing the order of route registration.

**Comment by robtesch** [comment]
Thanks @shalvah I will play around with how I have the routes registered and see what I can do to improve things from my side.

**Comment by shalvah** [comment]
See the RFC that would help with this: #105

**Comment by shalvah** [comment]
This is done in v3. You'll be able to sort endpoints as you wish.

How it works: Scribe generates an intermediate YAML file that you can modify, and your changes will be preserved as much as possible.

**Comment by shalvah** [comment]
🎉[v3 is out now](https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3)! You can sort endpoints as you wish.

**Comment by robtesch** [comment]
Thanks, I will check this out asap.
